<?php
namespace Modules\RestaurantNew\Services;
use Illuminate\Support\Facades\DB;
use Modules\RestaurantNew\Entities\{DiscountUsage,GoodsReceipt,Order,OrderAdjustment,StockMovement,Wastage};
class AdvancedReportService
{
    public function __construct(private TenantScopeService $scope){}
    private function range(array $f):array{return [$f['from']??now()->startOfMonth()->toDateString(),$f['to']??now()->toDateString(),(int)($f['location_id']??0)?:null];}
    private function scoped($q,?int $location,string $column='location_id'){if($location)$q->where($column,$location);$this->scope->applyLocationScope($q,$column);return $q;}
    public function hourly(array $f){[$from,$to,$location]=$this->range($f);$q=Order::withoutGlobalScopes()->selectRaw('DATE(created_at) business_date, HOUR(created_at) sales_hour, COUNT(*) order_count, SUM(total_amount) amount')->where('business_id',$this->scope->businessId())->where('payment_status','paid')->whereBetween('created_at',[$from.' 00:00:00',$to.' 23:59:59']);return $this->scoped($q,$location)->groupByRaw('DATE(created_at), HOUR(created_at)')->orderBy('business_date')->orderBy('sales_hour');}
    public function waiter(array $f){[$from,$to,$location]=$this->range($f);$q=Order::withoutGlobalScopes()->selectRaw('waiter_id, COUNT(*) order_count, SUM(total_amount) amount, AVG(total_amount) average_bill')->where('business_id',$this->scope->businessId())->where('payment_status','paid')->whereBetween('created_at',[$from.' 00:00:00',$to.' 23:59:59']);return $this->scoped($q,$location)->groupBy('waiter_id')->orderByDesc('amount');}
    public function discounts(array $f){[$from,$to,$location]=$this->range($f);$q=DiscountUsage::withoutGlobalScopes()->select('restnew_discount_usages.*')->join('restnew_orders','restnew_orders.id','=','restnew_discount_usages.order_id')->where('restnew_discount_usages.business_id',$this->scope->businessId())->whereBetween('restnew_discount_usages.created_at',[$from.' 00:00:00',$to.' 23:59:59']);if($location)$q->where('restnew_orders.location_id',$location);$this->scope->applyLocationScope($q,'restnew_orders.location_id');return $q->latest('restnew_discount_usages.id');}
    public function voids(array $f){[$from,$to,$location]=$this->range($f);$q=OrderAdjustment::withoutGlobalScopes()->select('restnew_order_adjustments.*')->join('restnew_orders','restnew_orders.id','=','restnew_order_adjustments.order_id')->where('restnew_order_adjustments.business_id',$this->scope->businessId())->whereIn('adjustment_type',['void_item','cancel_order','refund'])->whereBetween('restnew_order_adjustments.created_at',[$from.' 00:00:00',$to.' 23:59:59']);if($location)$q->where('restnew_orders.location_id',$location);$this->scope->applyLocationScope($q,'restnew_orders.location_id');return $q->latest('restnew_order_adjustments.id');}
    public function stockUsage(array $f){[$from,$to,$location]=$this->range($f);$q=StockMovement::withoutGlobalScopes()->selectRaw('ingredient_id, movement_type, SUM(quantity) quantity, SUM(value) value')->where('business_id',$this->scope->businessId())->whereBetween('created_at',[$from.' 00:00:00',$to.' 23:59:59']);return $this->scoped($q,$location)->groupBy('ingredient_id','movement_type')->orderBy('ingredient_id');}
    public function purchases(array $f){[$from,$to,$location]=$this->range($f);$q=GoodsReceipt::withoutGlobalScopes()->where('business_id',$this->scope->businessId())->where('status','posted')->whereBetween('received_date',[$from,$to]);return $this->scoped($q,$location)->latest('received_date');}
    public function wastage(array $f){[$from,$to,$location]=$this->range($f);$q=Wastage::withoutGlobalScopes()->with('lines')->where('business_id',$this->scope->businessId())->whereBetween('wastage_date',[$from,$to]);return $this->scoped($q,$location)->latest('wastage_date');}
    public function profitability(array $f){[$from,$to,$location]=$this->range($f);$sql='restnew_order_items.item_code, restnew_order_items.item_name, SUM(restnew_order_items.quantity) qty, SUM(restnew_order_items.line_total) sales, SUM(restnew_order_items.quantity * restnew_menu_items.cost_price) estimated_cost, SUM(restnew_order_items.line_total - (restnew_order_items.quantity * restnew_menu_items.cost_price)) gross_profit';$q=DB::table('restnew_order_items')->selectRaw($sql)->join('restnew_orders','restnew_orders.id','=','restnew_order_items.order_id')->leftJoin('restnew_menu_items','restnew_menu_items.id','=','restnew_order_items.menu_item_id')->where('restnew_order_items.business_id',$this->scope->businessId())->where('restnew_orders.payment_status','paid')->whereNotIn('restnew_order_items.status',['voided','cancelled'])->whereBetween('restnew_orders.created_at',[$from.' 00:00:00',$to.' 23:59:59']);if($location)$q->where('restnew_orders.location_id',$location);$this->scope->applyLocationScope($q,'restnew_orders.location_id');return $q->groupBy('restnew_order_items.item_code','restnew_order_items.item_name')->orderByDesc('gross_profit');}
}
