@extends('layouts.app')
@section('title', 'Preventive Maintenance Scheduler')
@section('content')
<section class="content-header hm-page-header"><h1><i class="fa fa-calendar-check-o"></i> Preventive Maintenance Scheduler <small>Asset and room maintenance plans, tasks and cost control</small></h1></section>
<section class="content hm-pos-scope">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please check:</strong> {{ $errors->first() }}</div>@endif
<div class="row hm-kpi-row">
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Active Plans</div><div class="hm-kpi-value">{{ $pm['plan_count'] }}</div><div class="hm-kpi-sub">Recurring schedules</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Due Tasks</div><div class="hm-kpi-value">{{ $pm['due_count'] }}</div><div class="hm-kpi-sub">Today or earlier</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Overdue</div><div class="hm-kpi-value">{{ $pm['overdue_count'] }}</div><div class="hm-kpi-sub">Needs attention</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Cost</div><div class="hm-kpi-value">{{ number_format($pm['maintenance_cost'],2) }}</div><div class="hm-kpi-sub">Completed work</div></div></div>
</div>
<div class="row">
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Create Plan</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.preventive-maintenance.plan') }}">@csrf
  <div class="form-group"><label>Plan No / Name</label><input name="plan_no" class="form-control" placeholder="Auto if blank"><input name="plan_name" class="form-control" style="margin-top:6px" required placeholder="Plan name"></div>
  <div class="form-group"><label>Asset / Room</label><div class="row"><div class="col-xs-6"><select name="asset_id" class="form-control"><option value="">No asset</option>@foreach($pm['assets'] as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code ?? $asset->id }} - {{ $asset->asset_name ?? '' }}</option>@endforeach</select></div><div class="col-xs-6"><select name="room_id" class="form-control"><option value="">No room</option>@foreach($pm['rooms'] as $room)<option value="{{ $room->id }}">{{ $room->room_no ?? $room->id }}</option>@endforeach</select></div></div></div>
  <div class="form-group"><label>Department / Priority</label><div class="row"><div class="col-xs-6"><input name="department" class="form-control" placeholder="Department"></div><div class="col-xs-6"><select name="priority" class="form-control"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div></div></div>
  <div class="form-group"><label>Frequency</label><div class="row"><div class="col-xs-5"><input type="number" name="frequency_value" min="1" value="1" class="form-control"></div><div class="col-xs-7"><select name="frequency_type" class="form-control" required><option value="daily">Day(s)</option><option value="weekly">Week(s)</option><option value="monthly" selected>Month(s)</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></div></div></div>
  <div class="form-group"><label>Start / Next Due</label><div class="row"><div class="col-xs-6"><input type="date" name="start_date" class="form-control" required></div><div class="col-xs-6"><input type="date" name="next_due_date" class="form-control"></div></div></div>
  <div class="form-group"><label>Estimated Cost</label><input type="number" step="0.01" name="estimated_cost" class="form-control" placeholder="Estimated cost"></div>
  <div class="form-group"><label>Instructions</label><textarea name="instructions" class="form-control" rows="2"></textarea></div>
  <div class="text-right"><button class="btn hm-btn-add"><i class="fa fa-save"></i> Save Plan</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Checklist Item</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.preventive-maintenance.checklist') }}">@csrf
  <div class="form-group"><label>Plan</label><select name="plan_id" class="form-control" required><option value="">Select plan</option>@foreach($pm['plans'] as $plan)<option value="{{ $plan->id }}">{{ $plan->plan_no }} - {{ $plan->plan_name }}</option>@endforeach</select></div>
  <div class="form-group"><label>Check Item</label><input name="check_item" class="form-control" required placeholder="Example: Check A/C filter"></div>
  <div class="form-group"><label>Required Result / Order</label><div class="row"><div class="col-xs-8"><input name="required_result" class="form-control" placeholder="Expected result"></div><div class="col-xs-4"><input type="number" name="sort_order" class="form-control" value="0"></div></div></div>
  <div class="checkbox"><label><input type="checkbox" name="is_required" value="1" checked> Required</label></div>
  <div class="text-right"><button class="btn hm-btn-excel"><i class="fa fa-list"></i> Add Checklist</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Generate Task</h3></div><div class="box-body"><form method="POST" action="#" onsubmit="this.action='{{ url('hotel-management/preventive-maintenance/plan') }}/'+this.plan_id.value+'/task';">@csrf
  <div class="form-group"><label>Plan</label><select name="plan_id" class="form-control" required><option value="">Select plan</option>@foreach($pm['plans'] as $plan)<option value="{{ $plan->id }}">{{ $plan->plan_no }} - {{ $plan->plan_name }}</option>@endforeach</select></div>
  <div class="form-group"><label>Task Title</label><input name="task_title" class="form-control" placeholder="Default plan name if blank"></div>
  <div class="form-group"><label>Due Date / Technician</label><div class="row"><div class="col-xs-6"><input type="date" name="due_date" class="form-control"></div><div class="col-xs-6"><input name="assigned_to" class="form-control" placeholder="Technician"></div></div></div>
  <div class="form-group"><label>Priority / Cost</label><div class="row"><div class="col-xs-6"><select name="priority" class="form-control"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><div class="col-xs-6"><input type="number" step="0.01" name="estimated_cost" class="form-control" placeholder="Cost"></div></div></div>
  <div class="text-right"><button class="btn hm-btn-pdf"><i class="fa fa-wrench"></i> Generate</button></div>
 </form></div></div></div>
</div>
<div class="box hm-card"><div class="box-header with-border"><div class="hm-toolbar"><input class="form-control hm-search-input" style="max-width:260px" placeholder="Search maintenance..."><button class="btn hm-btn-csv">CSV</button><button class="btn hm-btn-excel">Excel</button><button class="btn hm-btn-pdf">PDF</button><button class="btn hm-btn-print">Print</button><button class="btn hm-btn-col">Column Visibility</button></div><h3 class="box-title">Preventive Maintenance Tasks</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>No</th><th>Plan</th><th>Asset</th><th>Room</th><th>Task</th><th>Due</th><th>Assigned</th><th>Priority</th><th>Status</th><th>Cost</th><th>Update</th></tr></thead><tbody>@forelse($pm['tasks'] as $task)<tr><td>{{ $task->task_no }}</td><td>{{ $task->plan_id }}</td><td>{{ $task->asset_id }}</td><td>{{ $task->room_id }}</td><td>{{ $task->task_title }}</td><td>{{ $task->due_date }}</td><td>{{ $task->assigned_to }}</td><td><span class="hm-badge {{ $task->priority }}">{{ ucfirst($task->priority) }}</span></td><td><span class="hm-badge {{ $task->status }}">{{ ucfirst(str_replace('_',' ',$task->status)) }}</span></td><td>{{ number_format($task->actual_cost ?? $task->estimated_cost ?? 0,2) }}</td><td><form method="POST" action="{{ route('hotel-management.preventive-maintenance.status',$task->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="assigned">Assigned</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="deferred">Deferred</option><option value="cancelled">Cancelled</option></select><input name="assigned_to" class="form-control input-sm" style="width:90px" placeholder="Tech"><input type="date" name="completed_date" class="form-control input-sm"><input type="number" step="0.01" name="actual_cost" class="form-control input-sm" style="width:90px" placeholder="Cost"><label class="checkbox-inline"><input type="checkbox" name="checklist_verified" value="1"> Checklist</label><button class="btn btn-xs hm-btn-add">Save</button></form></td></tr>@empty<tr><td colspan="11" class="text-center text-muted">No preventive maintenance tasks generated yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Maintenance Plans</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>No</th><th>Name</th><th>Asset</th><th>Room</th><th>Frequency</th><th>Start</th><th>Last Completed</th><th>Next Due</th><th>Priority</th><th>Status</th><th>Cost</th></tr></thead><tbody>@forelse($pm['plans'] as $plan)<tr><td>{{ $plan->plan_no }}</td><td>{{ $plan->plan_name }}</td><td>{{ $plan->asset_id }}</td><td>{{ $plan->room_id }}</td><td>{{ $plan->frequency_value }} {{ ucfirst($plan->frequency_type) }}</td><td>{{ $plan->start_date }}</td><td>{{ $plan->last_completed_date }}</td><td>{{ $plan->next_due_date }}</td><td><span class="hm-badge {{ $plan->priority }}">{{ ucfirst($plan->priority) }}</span></td><td><span class="hm-badge {{ $plan->status }}">{{ ucfirst($plan->status) }}</span></td><td>{{ number_format($plan->estimated_cost ?? 0,2) }}</td></tr>@empty<tr><td colspan="11" class="text-center text-muted">No preventive maintenance plans yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Checklist Library</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>Plan</th><th>Order</th><th>Check Item</th><th>Required Result</th><th>Required</th></tr></thead><tbody>@forelse($pm['checklists'] as $c)<tr><td>{{ $c->plan_id }}</td><td>{{ $c->sort_order }}</td><td>{{ $c->check_item }}</td><td>{{ $c->required_result }}</td><td>{{ !empty($c->is_required) ? 'Yes' : 'No' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No checklist items yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Control Notes</h3></div><div class="box-body"><ul class="hm-note-list">@foreach($pm['notes'] as $note)<li>{{ $note }}</li>@endforeach</ul></div></div>
</section>
@endsection
