<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AccountGroupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('account_groups')->delete();
        
        \DB::table('account_groups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'business_id' => 1,
                'name' => 'Raw Material Account',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 1,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:27:31',
                'updated_at' => '2020-06-19 08:27:31',
            ),
            1 => 
            array (
                'id' => 2,
                'business_id' => 1,
                'name' => 'Finished Goods Account',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 2,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:27:54',
                'updated_at' => '2020-06-19 08:27:54',
            ),
            2 => 
            array (
                'id' => 3,
                'business_id' => 1,
                'name' => 'Other Stocks',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 3,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:28:09',
                'updated_at' => '2020-06-19 08:28:09',
            ),
            3 => 
            array (
                'id' => 4,
                'business_id' => 1,
                'name' => 'Bank Account',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 4,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:28:27',
                'updated_at' => '2020-06-19 08:28:27',
            ),
            4 => 
            array (
                'id' => 5,
                'business_id' => 1,
                'name' => 'Cash Account',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 5,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:28:44',
                'updated_at' => '2020-06-19 08:28:44',
            ),
            5 => 
            array (
                'id' => 6,
                'business_id' => 1,
            'name' => 'Cheques in Hand (Customer\'s)',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 6,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:29:01',
                'updated_at' => '2020-06-19 08:29:01',
            ),
            6 => 
            array (
                'id' => 7,
                'business_id' => 1,
                'name' => 'Card',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 7,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:31:50',
                'updated_at' => '2020-06-19 08:31:50',
            ),
            7 => 
            array (
                'id' => 8,
                'business_id' => 1,
                'name' => 'COGS Account Group',
                'account_type_id' => 4,
                'note' => NULL,
                'default_account_group_id' => 8,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2020-06-19 08:32:06',
                'updated_at' => '2020-06-26 12:34:20',
            ),
            8 => 
            array (
                'id' => 9,
                'business_id' => 1,
                'name' => 'Company Cards',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 11,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2023-03-01 09:37:43',
                'updated_at' => '2023-03-01 09:37:43',
            ),
            9 => 
            array (
                'id' => 10,
                'business_id' => 1,
                'name' => 'Goods in Transit',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 12,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2023-06-28 07:17:32',
                'updated_at' => '2023-06-28 07:17:32',
            ),
            10 => 
            array (
                'id' => 11,
                'business_id' => 1,
                'name' => 'Owners Drawings',
                'account_type_id' => 5,
                'note' => NULL,
                'default_account_group_id' => 13,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2023-11-26 14:28:35',
                'updated_at' => '2023-11-26 14:28:35',
            ),
            11 => 
            array (
                'id' => 12,
                'business_id' => 1,
                'name' => 'Sales Income Group',
                'account_type_id' => 3,
                'note' => 'na',
                'default_account_group_id' => 9,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2024-02-13 02:56:55',
                'updated_at' => '2024-02-13 02:56:55',
            ),
            12 => 
            array (
                'id' => 13,
                'business_id' => 1,
                'name' => 'Direct Expense',
                'account_type_id' => 4,
                'note' => NULL,
                'default_account_group_id' => 10,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-13 02:56:55',
                'updated_at' => '2024-02-13 02:56:55',
            ),
            13 => 
            array (
                'id' => 14,
                'business_id' => 1,
                'name' => 'CPC',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 11,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-13 02:56:56',
            ),
            14 => 
            array (
                'id' => 15,
                'business_id' => 1,
                'name' => 'Credit Sales',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 13,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-13 02:56:56',
            ),
            15 => 
            array (
                'id' => 16,
                'business_id' => 1,
                'name' => 'Loans Given',
                'account_type_id' => 6,
                'note' => NULL,
                'default_account_group_id' => 14,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-28 12:48:08',
            ),
            16 => 
            array (
                'id' => 17,
                'business_id' => 1,
                'name' => 'Loan Taken',
                'account_type_id' => 9,
                'note' => NULL,
                'default_account_group_id' => 15,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-26 15:16:15',
            ),
            17 => 
            array (
                'id' => 18,
                'business_id' => 1,
                'name' => 'Own Cards',
                'account_type_id' => 5,
                'note' => NULL,
                'default_account_group_id' => 21,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-13 02:56:56',
            ),
            18 => 
            array (
                'id' => 19,
                'business_id' => 1,
                'name' => 'Indirect Expense',
                'account_type_id' => 4,
                'note' => NULL,
                'default_account_group_id' => 22,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-13 02:56:56',
                'updated_at' => '2024-02-13 02:56:56',
            ),
            19 => 
            array (
                'id' => 58,
                'business_id' => 4,
                'name' => 'Raw Material Account',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 1,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            20 => 
            array (
                'id' => 59,
                'business_id' => 4,
                'name' => 'Finished Goods Account',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 2,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            21 => 
            array (
                'id' => 60,
                'business_id' => 4,
                'name' => 'Other Stocks',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 3,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            22 => 
            array (
                'id' => 61,
                'business_id' => 4,
                'name' => 'Bank Account',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 4,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            23 => 
            array (
                'id' => 62,
                'business_id' => 4,
                'name' => 'Cash Account',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 5,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            24 => 
            array (
                'id' => 63,
                'business_id' => 4,
            'name' => 'Cheques in Hand (Customer\'s)',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 6,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            25 => 
            array (
                'id' => 64,
                'business_id' => 4,
                'name' => 'Card',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 7,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            26 => 
            array (
                'id' => 65,
                'business_id' => 4,
                'name' => 'COGS Account Group',
                'account_type_id' => 31,
                'note' => NULL,
                'default_account_group_id' => 8,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            27 => 
            array (
                'id' => 66,
                'business_id' => 4,
                'name' => 'Sales Income Group',
                'account_type_id' => 30,
                'note' => 'na',
                'default_account_group_id' => 9,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            28 => 
            array (
                'id' => 67,
                'business_id' => 4,
                'name' => 'Direct Expense',
                'account_type_id' => 31,
                'note' => NULL,
                'default_account_group_id' => 10,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            29 => 
            array (
                'id' => 68,
                'business_id' => 4,
                'name' => 'CPC',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 11,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            30 => 
            array (
                'id' => 69,
                'business_id' => 4,
                'name' => 'Goods in Transit',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 12,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            31 => 
            array (
                'id' => 70,
                'business_id' => 4,
                'name' => 'Credit Sales',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 13,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            32 => 
            array (
                'id' => 71,
                'business_id' => 4,
                'name' => 'Loans Given',
                'account_type_id' => 33,
                'note' => NULL,
                'default_account_group_id' => 14,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-28 12:48:08',
            ),
            33 => 
            array (
                'id' => 72,
                'business_id' => 4,
                'name' => 'Loan Taken',
                'account_type_id' => 36,
                'note' => NULL,
                'default_account_group_id' => 15,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            34 => 
            array (
                'id' => 73,
                'business_id' => 4,
                'name' => 'Owners Drawings',
                'account_type_id' => 32,
                'note' => NULL,
                'default_account_group_id' => 18,
                'reg_cheque' => 'Y',
                'show_status' => 1,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-27 04:13:02',
            ),
            35 => 
            array (
                'id' => 74,
                'business_id' => 4,
                'name' => 'Owners Drawings',
                'account_type_id' => NULL,
                'note' => NULL,
                'default_account_group_id' => 19,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            36 => 
            array (
                'id' => 75,
                'business_id' => 4,
                'name' => 'Own Cards',
                'account_type_id' => 32,
                'note' => NULL,
                'default_account_group_id' => 21,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
            37 => 
            array (
                'id' => 76,
                'business_id' => 4,
                'name' => 'Indirect Expense',
                'account_type_id' => 31,
                'note' => NULL,
                'default_account_group_id' => 22,
                'reg_cheque' => 'Y',
                'show_status' => 0,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2024-02-26 15:20:51',
            ),
        ));
        
        
    }
}