<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArticlesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('articles')->delete();
        
        \DB::table('articles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 30,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 07:46:35',
                'updated_at' => '2024-12-06 07:46:35',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 08:11:48',
                'updated_at' => '2024-12-06 08:11:48',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 9,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 09:59:52',
                'updated_at' => '2024-12-06 09:59:52',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 9,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 10:09:55',
                'updated_at' => '2024-12-06 10:09:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 10:17:19',
                'updated_at' => '2024-12-06 10:17:19',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'title' => 'Add New Supplier',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 10:25:46',
                'updated_at' => '2024-12-06 10:29:49',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'title' => 'Add New Purchase',
                'content' => NULL,
                'published' => 1,
                'category_id' => 4,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-06 10:36:26',
                'updated_at' => '2024-12-06 10:39:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 08:01:02',
                'updated_at' => '2024-12-09 08:01:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'title' => 'Cheque Deposit',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 08:03:47',
                'updated_at' => '2024-12-26 07:04:22',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 08:07:46',
                'updated_at' => '2024-12-09 08:07:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'title' => 'Card Deposit',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 08:10:19',
                'updated_at' => '2024-12-09 08:11:15',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'title' => 'How to Create New Account',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 08:29:54',
                'updated_at' => '2024-12-26 07:08:53',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'title' => 'Add Credit Limit',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 09:23:04',
                'updated_at' => '2024-12-26 07:11:12',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 09:25:33',
                'updated_at' => '2024-12-09 09:25:33',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'title' => 'Refund Deposit',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 09:35:58',
                'updated_at' => '2024-12-26 07:12:31',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'title' => 'Cheque Return',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 09:55:39',
                'updated_at' => '2024-12-26 07:13:52',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'title' => 'Customer Balance - Customer Ledger',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 09:58:24',
                'updated_at' => '2024-12-09 10:06:30',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 10:21:38',
                'updated_at' => '2024-12-09 10:21:38',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'title' => 'Pumper Dashboard All Steps',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 10:52:47',
                'updated_at' => '2024-12-26 07:17:36',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'title' => 'Add Journal',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 12:34:00',
                'updated_at' => '2024-12-26 07:20:02',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'title' => 'Checking Product Stocks',
                'content' => NULL,
                'published' => 1,
                'category_id' => 9,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-09 12:39:16',
                'updated_at' => '2024-12-26 07:20:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-10 08:26:52',
                'updated_at' => '2024-12-10 08:26:52',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'title' => 'Add New Fleet & Check List Fleet',
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-10 10:10:05',
                'updated_at' => '2024-12-26 07:22:41',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-10 10:19:41',
                'updated_at' => '2024-12-10 10:19:41',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'title' => 'Check List Trip Operations',
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-10 10:23:25',
                'updated_at' => '2024-12-10 11:29:18',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 04:31:58',
                'updated_at' => '2024-12-11 04:31:58',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 06:02:42',
                'updated_at' => '2024-12-11 06:02:42',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 06:06:40',
                'updated_at' => '2024-12-11 06:06:40',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 06:11:30',
                'updated_at' => '2024-12-11 06:11:30',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 06:18:50',
                'updated_at' => '2024-12-11 06:18:50',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 15,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 08:01:45',
                'updated_at' => '2024-12-11 08:01:45',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 08:13:23',
                'updated_at' => '2024-12-11 08:13:23',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'title' => 'Add Partner',
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 08:19:14',
                'updated_at' => '2024-12-11 09:40:58',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 09:47:47',
                'updated_at' => '2024-12-11 09:47:47',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'title' => 'Add Shipment SW',
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 10:04:18',
                'updated_at' => '2024-12-26 07:37:33',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-11 11:09:45',
                'updated_at' => '2024-12-11 11:09:45',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'title' => 'Shipping Module Settings',
                'content' => NULL,
                'published' => 1,
                'category_id' => 38,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-13 08:47:43',
                'updated_at' => '2024-12-13 09:14:26',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'title' => 'How to get Backup',
                'content' => NULL,
                'published' => 1,
                'category_id' => 36,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-13 13:51:02',
                'updated_at' => '2024-12-26 07:50:29',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'title' => 'Customer Payment',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 05:24:03',
                'updated_at' => '2024-12-26 07:51:45',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'title' => 'How to get Customer Statement',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 08:01:18',
                'updated_at' => '2024-12-14 08:36:21',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 1,
                'title' => 'Day End Settlement',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 08:40:54',
                'updated_at' => '2024-12-26 07:53:36',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 09:21:03',
                'updated_at' => '2024-12-14 09:21:03',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 09:47:49',
                'updated_at' => '2024-12-14 09:47:49',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-14 16:56:26',
                'updated_at' => '2024-12-14 16:56:26',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 30,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 04:13:21',
                'updated_at' => '2024-12-15 04:13:21',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 05:44:35',
                'updated_at' => '2024-12-15 05:44:35',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'title' => 'Price Change Effect for Profit & Loss',
                'content' => NULL,
                'published' => 1,
                'category_id' => 8,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 05:56:52',
                'updated_at' => '2024-12-15 05:58:30',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'title' => 'Add Supplier Map Products',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 06:28:53',
                'updated_at' => '2024-12-15 06:36:39',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'title' => 'Add Stock Adjustment',
                'content' => NULL,
                'published' => 1,
                'category_id' => 29,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 07:24:33',
                'updated_at' => '2024-12-15 07:55:56',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'title' => 'Store Transfer Steps',
                'content' => NULL,
                'published' => 1,
                'category_id' => 28,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 10:17:30',
                'updated_at' => '2024-12-15 10:21:44',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'title' => 'Supplier Payment',
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 10:27:22',
                'updated_at' => '2024-12-15 10:49:42',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 1,
            'title' => 'Guide for Postpaid bills (Purchase Order)',
                'content' => NULL,
                'published' => 1,
                'category_id' => 4,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 10:52:15',
                'updated_at' => '2024-12-15 11:01:41',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'title' => 'VAT Settings',
                'content' => NULL,
                'published' => 1,
                'category_id' => 10,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 11:04:10',
                'updated_at' => '2024-12-15 11:08:39',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 4,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 11:23:21',
                'updated_at' => '2024-12-15 11:23:21',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 1,
                'title' => 'VAT for Expenses',
                'content' => NULL,
                'published' => 1,
                'category_id' => 30,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 11:39:48',
                'updated_at' => '2024-12-15 11:41:10',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'title' => 'Add Expenses with VAT Invoice',
                'content' => NULL,
                'published' => 1,
                'category_id' => 30,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-15 12:59:09',
                'updated_at' => '2024-12-15 14:01:26',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 39,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-24 10:19:13',
                'updated_at' => '2024-12-24 10:19:13',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'title' => 'List Suggestions & Add New Suggestions',
                'content' => NULL,
                'published' => 1,
                'category_id' => 39,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-24 10:22:19',
                'updated_at' => '2024-12-24 10:29:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 39,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-24 10:34:33',
                'updated_at' => '2024-12-24 10:34:33',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 39,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-24 10:35:49',
                'updated_at' => '2024-12-24 10:35:49',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:19:10',
                'updated_at' => '2024-12-26 06:55:46',
                'deleted_at' => '2024-12-26 06:55:46',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:20:11',
                'updated_at' => '2024-12-26 06:20:11',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:22:07',
                'updated_at' => '2024-12-26 06:22:07',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 1,
                'title' => 'Pumper Dashboard Add Payments',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:23:24',
                'updated_at' => '2024-12-26 06:23:42',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:24:36',
                'updated_at' => '2024-12-26 06:24:36',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:25:38',
                'updated_at' => '2024-12-26 06:25:38',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 1,
                'title' => 'Pumper Dashboard Close Shift',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:26:38',
                'updated_at' => '2024-12-26 07:54:31',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 1,
            'title' => 'Settlement (Pumper Dashbaord)',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:28:09',
                'updated_at' => '2024-12-26 06:28:20',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 1,
                'title' => 'Pumper Dashboard Enter Meters with payments',
                'content' => NULL,
                'published' => 1,
                'category_id' => 6,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:31:56',
                'updated_at' => '2024-12-26 06:32:07',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 30,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:39:49',
                'updated_at' => '2024-12-26 06:53:38',
                'deleted_at' => '2024-12-26 06:53:38',
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 7,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:41:45',
                'updated_at' => '2024-12-26 06:41:45',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 1,
                'title' => 'Add New Product',
                'content' => NULL,
                'published' => 1,
                'category_id' => 9,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:43:47',
                'updated_at' => '2024-12-26 06:43:56',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 1,
                'title' => NULL,
                'content' => NULL,
                'published' => 1,
                'category_id' => 9,
                'updated_by' => 1,
                'featured' => 0,
                'rate_total' => 0,
                'rate_helpful' => 0,
                'created_at' => '2024-12-26 06:47:11',
                'updated_at' => '2024-12-26 06:47:11',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}