<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('brands')->delete();
        
        \DB::table('brands')->insert(array (
            0 => 
            array (
                'id' => 1,
                'business_id' => 4,
                'name' => 'FAK',
                'description' => 'FAK',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:16:25',
                'updated_at' => '2024-02-27 08:16:25',
            ),
            1 => 
            array (
                'id' => 2,
                'business_id' => 4,
                'name' => 'NSK',
                'description' => 'NSK',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:16:39',
                'updated_at' => '2024-02-27 08:16:39',
            ),
            2 => 
            array (
                'id' => 3,
                'business_id' => 4,
                'name' => 'FRO',
                'description' => 'FRO',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:17:07',
                'updated_at' => '2024-02-27 08:17:07',
            ),
            3 => 
            array (
                'id' => 4,
                'business_id' => 4,
                'name' => 'NACHI',
                'description' => 'NACHI',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:17:29',
                'updated_at' => '2024-02-27 08:17:29',
            ),
            4 => 
            array (
                'id' => 5,
                'business_id' => 4,
                'name' => 'AOKMAN DRIVE',
                'description' => 'AOKMAN DRIVE',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:17:53',
                'updated_at' => '2024-02-27 08:17:53',
            ),
            5 => 
            array (
                'id' => 6,
                'business_id' => 4,
                'name' => 'KG',
                'description' => 'KG',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:18:35',
                'updated_at' => '2024-02-27 08:18:35',
            ),
            6 => 
            array (
                'id' => 7,
                'business_id' => 4,
                'name' => 'Mercedes',
                'description' => 'Mercedes',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 08:18:50',
                'updated_at' => '2024-02-27 08:18:50',
            ),
            7 => 
            array (
                'id' => 8,
                'business_id' => 4,
                'name' => 'SERVO',
                'description' => 'LUBE CANS',
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 1,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-03-14 04:52:53',
                'updated_at' => '2024-03-14 04:52:53',
            ),
            8 => 
            array (
                'id' => 9,
                'business_id' => 4,
                'name' => 'KOYO',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-03-29 06:46:00',
                'updated_at' => '2024-03-29 06:46:00',
            ),
            9 => 
            array (
                'id' => 10,
                'business_id' => 4,
                'name' => 'STR',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 38,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-18 06:30:04',
                'updated_at' => '2024-04-18 06:30:04',
            ),
            10 => 
            array (
                'id' => 11,
                'business_id' => 4,
                'name' => 'TOTACHI',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-09-27 11:39:15',
                'updated_at' => '2024-09-27 11:39:15',
            ),
            11 => 
            array (
                'id' => 12,
                'business_id' => 4,
                'name' => 'VISTA',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-10-15 14:00:28',
                'updated_at' => '2024-10-15 14:00:28',
            ),
            12 => 
            array (
                'id' => 13,
                'business_id' => 4,
                'name' => 'RHM',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-10-25 04:04:11',
                'updated_at' => '2024-10-25 04:04:11',
            ),
            13 => 
            array (
                'id' => 14,
                'business_id' => 4,
                'name' => 'FBJ',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-10-25 04:07:34',
                'updated_at' => '2024-10-25 04:07:34',
            ),
            14 => 
            array (
                'id' => 15,
                'business_id' => 4,
                'name' => 'JVN',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-10-25 04:34:50',
                'updated_at' => '2024-10-25 04:34:50',
            ),
            15 => 
            array (
                'id' => 16,
                'business_id' => 4,
                'name' => 'LIQUI MOLY',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-10-29 11:34:00',
                'updated_at' => '2024-10-29 11:34:00',
            ),
            16 => 
            array (
                'id' => 17,
                'business_id' => 4,
                'name' => 'VIC',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-12-06 05:18:38',
                'updated_at' => '2024-12-06 05:18:38',
            ),
            17 => 
            array (
                'id' => 18,
                'business_id' => 4,
                'name' => 'SAKURA',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-12-06 05:57:42',
                'updated_at' => '2024-12-06 05:57:42',
            ),
            18 => 
            array (
                'id' => 19,
                'business_id' => 4,
                'name' => 'GTOP',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-12-23 11:39:23',
                'updated_at' => '2024-12-23 11:39:23',
            ),
            19 => 
            array (
                'id' => 20,
                'business_id' => 4,
                'name' => 'ABB',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-01-22 07:00:08',
                'updated_at' => '2025-01-22 07:00:08',
            ),
            20 => 
            array (
                'id' => 21,
                'business_id' => 4,
                'name' => 'IJK',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-02-19 18:45:51',
                'updated_at' => '2025-02-19 18:45:51',
            ),
            21 => 
            array (
                'id' => 22,
                'business_id' => 4,
                'name' => 'KOYO',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-03-05 06:53:45',
                'updated_at' => '2025-03-05 06:53:45',
            ),
            22 => 
            array (
                'id' => 23,
                'business_id' => 4,
                'name' => 'FYH',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-03-05 06:55:35',
                'updated_at' => '2025-03-05 06:55:35',
            ),
            23 => 
            array (
                'id' => 24,
                'business_id' => 4,
                'name' => 'NTN',
                'description' => NULL,
                'type' => NULL,
                'model' => NULL,
                'serial_nos' => NULL,
                'is_auto_repair' => 0,
                'created_by' => 7,
                'use_for_repair' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-03-24 07:01:42',
                'updated_at' => '2025-03-24 07:01:42',
            ),
        ));
        
        
    }
}