<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BusinessTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('business')->delete();
        
        \DB::table('business')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'SYZYGY',
                'company_number' => NULL,
                'currency_id' => 111,
                'is_manged_stock_enable' => 1,
                'business_categories' => 'null',
                'show_for_customers' => 1,
                'day_end' => 0,
                'day_end_enable' => 0,
                'start_date' => '2019-12-01',
                'tax_number_1' => '1000928728-7000',
                'tax_label_1' => 'VAT',
                'tax_number_2' => NULL,
                'tax_label_2' => NULL,
                'default_sales_tax' => NULL,
                'default_profit_percent' => 25.0,
                'owner_id' => 1,
                'time_zone' => 'Asia/Colombo',
                'fy_start_month' => 1,
                'accounting_method' => 'fifo',
                'default_sales_discount' => '0.00',
                'sell_price_tax' => 'includes',
                'logo' => NULL,
                'sku_prefix' => NULL,
                'enable_product_expiry' => 0,
                'expiry_type' => 'add_expiry',
                'on_product_expiry' => 'keep_selling',
                'stop_selling_before' => 0,
                'sale_import_date' => NULL,
                'purchase_import_date' => NULL,
                'enable_tooltip' => 1,
                'purchase_in_diff_currency' => 0,
                'purchase_currency_id' => NULL,
                'p_exchange_rate' => '1.000',
                'transaction_edit_days' => 30,
                'stock_expiry_alert_days' => 30,
                'keyboard_shortcuts' => '{"pos":{"express_checkout":"shift+e","pay_n_ckeckout":"shift+p","draft":"shift+d","cancel":"shift+c","recent_product_quantity":"f2","edit_discount":"shift+i","edit_order_tax":"shift+t","add_payment_row":"shift+r","finalize_payment":"shift+f","add_new_product":"f4"}}',
                'pos_settings' => '{"tc_sale_and_pos_text":"&lt;br&gt;","show_credit_sale_button":"1","duplicate_invoice_prefix":0,"disable_duplicate_invoice":0,"disable_pay_checkout":0,"disable_draft":0,"disable_express_checkout":0,"hide_product_suggestion":0,"hide_recent_trans":0,"disable_discount":0,"disable_order_tax":0,"is_pos_subtotal_editable":0}',
                'manufacturing_settings' => NULL,
                'enable_brand' => 1,
                'enable_category' => 1,
                'enable_sub_category' => 1,
                'enable_price_tax' => 1,
                'enable_purchase_status' => 1,
                'enable_lot_number' => 0,
                'default_unit' => NULL,
                'enable_sub_units' => 0,
                'enable_racks' => 1,
                'enable_row' => 0,
                'enable_position' => 0,
                'show_avai_qty_in_qr_catalogue' => 0,
                'show_in_catalogue_page' => 0,
                'enable_editing_product_from_purchase' => 1,
                'sales_cmsn_agnt' => 'cmsn_agnt',
                'item_addition_method' => 1,
                'enable_inline_tax' => 1,
                'currency_symbol_placement' => 'before',
                'enabled_modules' => '["purchase","add_sale","pos_sale","stock_transfer","stock_adjustment","expenses","account","banking_module","tables","modifiers","booking","kitchen","subscription","type_of_service","tables","modifiers","service_staff","kitchen","booking"]',
                'date_format' => 'd-m-Y',
                'time_format' => '24',
                'ref_no_prefixes' => '{"purchase":"PO","purchase_return":null,"stock_transfer":"ST","stock_adjustment":"SA","sell_return":"CN","expense":"EP","contacts":"CO","purchase_payment":"PP","sell_payment":"SP","expense_payment":null,"business_location":"BL","username":null,"subscription":null,"customer":null,"supplier":null,"settlement":null,"excess_commission":null,"shortage_recover":null,"security_deposit":null,"refund_security_deposit":null,"employee_no":null}',
                'theme_color' => NULL,
                'created_by' => NULL,
                'crm_settings' => NULL,
                'enable_rp' => 0,
                'enable_free_qty' => 0,
                'popup_load_save_data' => 0,
                'rp_name' => NULL,
                'amount_for_unit_rp' => '1.0000',
                'min_order_total_for_rp' => '1.0000',
                'max_rp_per_order' => NULL,
                'redeem_amount_per_unit_rp' => '1.0000',
                'min_order_total_for_redeem' => '1.0000',
                'min_redeem_point' => NULL,
                'max_redeem_point' => NULL,
                'rp_expiry_period' => NULL,
                'rp_expiry_type' => 'year',
                'email_settings' => '{"mail_driver":"smtp","mail_host":null,"mail_port":null,"mail_username":null,"mail_password":"7777","mail_encryption":null,"mail_from_address":null,"mail_from_name":null}',
                'sms_settings' => '{"url":null,"send_to_param_name":"to","msg_param_name":"text","request_method":"post","param_1":null,"param_val_1":null,"param_2":null,"param_val_2":null,"param_3":null,"param_val_3":null,"param_4":null,"param_val_4":null,"param_5":null,"param_val_5":null,"param_6":null,"param_val_6":null,"param_7":null,"param_val_7":null,"param_8":null,"param_val_8":null,"param_9":null,"param_val_9":null,"param_10":null,"param_val_10":null}',
                'custom_labels' => '{"payments":{"custom_pay_1":null,"custom_pay_2":null,"custom_pay_3":null},"custom_field":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null}}',
                'common_settings' => '{"enable_product_warranty":"1","default_datatable_page_entries":"25"}',
                'enable_line_discount' => 0,
                'currency_precision' => '3',
                'reg_no' => NULL,
                'quantity_precision' => '3',
                'search_product_settings' => '{"enable_code":"1","enable_rack_number":"1","enable_qty":"1","enable_product_cost":"1","enable_product_supplier":"1"}',
                'default_store' => NULL,
                'is_active' => 1,
                'is_patient' => 0,
                'is_hospital' => 0,
                'is_pharmacy' => 0,
                'is_laboratory' => 0,
                'patient_details_id' => NULL,
                'background_showing_type' => NULL,
                'background_image' => NULL,
                'created_at' => '2019-12-30 12:22:03',
                'updated_at' => '2024-02-27 04:14:36',
                'ref_no_starting_number' => '{"purchase":null,"purchase_return":null,"stock_transfer":null,"stock_adjustment":null,"sell_return":null,"expense":null,"contacts":null,"purchase_payment":null,"sell_payment":null,"expense_payment":null,"business_location":null,"username":null,"subscription":null,"customer":null,"supplier":null,"settlement":null,"excess_commission":null,"shortage_recover":null,"security_deposit":null,"refund_security_deposit":null,"employee_no":null}',
                'repair_settings' => NULL,
                'auto_repair_settings' => '',
                'visitor_qr_data' => NULL,
                'contact_fields' => NULL,
                'trial_used' => 0,
                'customer_interest_deduct_option' => 0,
                'customer_interest_deduct' => 0,
                'service_addition_method' => 0,
                'duplicate_orders_allowed' => 0,
                'essentials_settings' => NULL,
                'asset_settings' => '',
                'font_size' => 0,
                'font_family' => '',
                'hms_settings' => NULL,
                'weighing_scale_setting' => '',
                'sms_non_delivery' => 0,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => '130',
                'company_number' => 'RA-8',
                'currency_id' => 111,
                'is_manged_stock_enable' => 1,
                'business_categories' => 'null',
                'show_for_customers' => 0,
                'day_end' => 0,
                'day_end_enable' => 0,
                'start_date' => '2024-02-25',
                'tax_number_1' => '100928728-7000',
                'tax_label_1' => 'TAX',
                'tax_number_2' => NULL,
                'tax_label_2' => NULL,
                'default_sales_tax' => NULL,
                'default_profit_percent' => 25.0,
                'owner_id' => 7,
                'time_zone' => 'Asia/Colombo',
                'fy_start_month' => 1,
                'accounting_method' => 'fifo',
                'default_sales_discount' => '0.00',
                'sell_price_tax' => 'includes',
                'logo' => NULL,
                'sku_prefix' => NULL,
                'enable_product_expiry' => 0,
                'expiry_type' => 'add_expiry',
                'on_product_expiry' => 'keep_selling',
                'stop_selling_before' => 0,
                'sale_import_date' => NULL,
                'purchase_import_date' => NULL,
                'enable_tooltip' => 1,
                'purchase_in_diff_currency' => 0,
                'purchase_currency_id' => NULL,
                'p_exchange_rate' => '1.000',
                'transaction_edit_days' => 2000,
                'stock_expiry_alert_days' => 30,
                'keyboard_shortcuts' => '{"pos":{"express_checkout":"shift+e","pay_n_ckeckout":"shift+p","draft":"shift+d","cancel":"shift+c","recent_product_quantity":"f2","edit_discount":"shift+i","edit_order_tax":"shift+t","add_payment_row":"shift+r","finalize_payment":"shift+f","add_new_product":"f4"}}',
                'pos_settings' => '{"allow_overselling":"1","tc_sale_and_pos_text":"&lt;br&gt;","enable_transaction_date":"1","show_credit_sale_button":"1","hide_purchase_price":"1","cash_denominations":null,"enable_cash_denomination_on":"pos_screen","duplicate_invoice_prefix":0,"enable_prefix_duplicate_invoice":0,"price_later":0,"disable_duplicate_invoice":0,"disable_pay_checkout":0,"disable_draft":0,"disable_express_checkout":0,"hide_product_suggestion":0,"hide_recent_trans":0,"disable_discount":0,"disable_order_tax":0,"is_pos_subtotal_editable":0,"enable_line_discount":0}',
                'manufacturing_settings' => NULL,
                'enable_brand' => 1,
                'enable_category' => 1,
                'enable_sub_category' => 1,
                'enable_price_tax' => 1,
                'enable_purchase_status' => 1,
                'enable_lot_number' => 0,
                'default_unit' => NULL,
                'enable_sub_units' => 0,
                'enable_racks' => 1,
                'enable_row' => 1,
                'enable_position' => 1,
                'show_avai_qty_in_qr_catalogue' => 1,
                'show_in_catalogue_page' => 0,
                'enable_editing_product_from_purchase' => 1,
                'sales_cmsn_agnt' => NULL,
                'item_addition_method' => 1,
                'enable_inline_tax' => 1,
                'currency_symbol_placement' => 'before',
                'enabled_modules' => NULL,
                'date_format' => 'm/d/Y',
                'time_format' => '24',
                'ref_no_prefixes' => '{"supplier_add_purchase":null,"supplier_list_purchase":null,"customer_list_purchase":null,"customer_payment":null,"customer_bulk_payment":null,"customer_list_statement":null,"customer_vat_statement":null,"purchase":"PO","purchase_return":null,"stock_transfer":"ST","stock_adjustment":"SA","sell_return":"CN","expense":"EP","contacts":"CO","purchase_payment":"PP","sell_payment":"SP","expense_payment":null,"business_location":"BL","username":null,"subscription":null,"customer":"CU","supplier":"SU","settlement":"ST","excess_commission":null,"shortage_recover":null,"security_deposit":null,"refund_security_deposit":null,"employee_no":null,"route_no":null,"quotation_no":"5","settlement_customer_payment":"SW-CP","settlement_expense":"SW-EXP","settlement_sw":"SET-SW"}',
                'theme_color' => NULL,
                'created_by' => NULL,
                'crm_settings' => NULL,
                'enable_rp' => 0,
                'enable_free_qty' => 0,
                'popup_load_save_data' => 0,
                'rp_name' => NULL,
                'amount_for_unit_rp' => '1.0000',
                'min_order_total_for_rp' => '1.0000',
                'max_rp_per_order' => NULL,
                'redeem_amount_per_unit_rp' => '1.0000',
                'min_order_total_for_redeem' => '1.0000',
                'min_redeem_point' => NULL,
                'max_redeem_point' => NULL,
                'rp_expiry_period' => NULL,
                'rp_expiry_type' => 'year',
                'email_settings' => '{"mail_driver":"smtp","mail_host":null,"mail_port":null,"mail_username":null,"mail_password":null,"mail_encryption":null,"mail_from_address":null,"mail_from_name":null}',
                'sms_settings' => NULL,
                'custom_labels' => '{"payments":{"custom_pay_1":null,"custom_pay_2":null,"custom_pay_3":null},"custom_field":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null}}',
                'common_settings' => '{"default_credit_limit":null,"default_datatable_page_entries":"25","captch_site_key":null}',
                'enable_line_discount' => 0,
                'currency_precision' => '2',
                'reg_no' => NULL,
                'quantity_precision' => '2',
                'search_product_settings' => '{"enable_code":"1","enable_rack_number":"1","enable_qty":"1","enable_product_cost":"1","enable_product_supplier":"1"}',
                'default_store' => 3,
                'is_active' => 1,
                'is_patient' => 0,
                'is_hospital' => 0,
                'is_pharmacy' => 0,
                'is_laboratory' => 0,
                'patient_details_id' => NULL,
                'background_showing_type' => NULL,
                'background_image' => NULL,
                'created_at' => '2024-02-26 15:20:51',
                'updated_at' => '2025-05-28 11:51:13',
                'ref_no_starting_number' => '{"supplier_add_purchase":null,"supplier_list_purchase":null,"customer_list_purchase":null,"customer_payment":null,"customer_bulk_payment":null,"customer_list_statement":null,"customer_vat_statement":null,"purchase":"1","purchase_return":null,"stock_transfer":"1","stock_adjustment":"1","sell_return":"1","expense":"1","contacts":"1","purchase_payment":"1","sell_payment":"1","expense_payment":null,"business_location":"1","username":null,"subscription":null,"customer":"1","supplier":"1","settlement":"1","excess_commission":null,"shortage_recover":null,"security_deposit":null,"refund_security_deposit":null,"employee_no":null,"route_no":null,"quotation_no":null,"settlement_customer_payment":"1","settlement_expense":"1","settlement_sw":"1"}',
                'repair_settings' => NULL,
                'auto_repair_settings' => '{"repair_tc_condition":null,"job_sheet_prefix":"JOB\\/","problem_reported_by_customer":null,"product_condition":null,"product_configuration":null,"job_sheet_custom_field_1":null,"job_sheet_custom_field_2":null,"job_sheet_custom_field_3":null,"job_sheet_custom_field_4":null,"job_sheet_custom_field_5":null,"default_repair_checklist":"Mechanical|Electrical|paint","default_status":"1"}',
                'visitor_qr_data' => NULL,
                'contact_fields' => '{"location":"0","need_to_send_sms":"1","credit_notification_type":"1","vat_no":"1","customer_customer_group":"1","customer_credit_limit":"1","add_more_mobile":"1","customer_mobile":"1","customer_landline":"1","assigned_to":"1","customer_address":"1","address_line_2":"1","customer_city":"1","customer_state":"1","customer_country":"1","customer_landmark":"1","customer_tax_number":"1","customer_pay_term":"1","customer_password":"1","customer_confirm_password":"1","customer_email":"1","customer_alternate_contact_number":"1","sub_customer":"1","vehicle_no":"1","address_line_3":"1","passport_nic_no":"1","passport_nic_image":"1","signature":"1"}',
                'trial_used' => 1,
                'customer_interest_deduct_option' => 1,
                'customer_interest_deduct' => 0,
                'service_addition_method' => 0,
                'duplicate_orders_allowed' => 0,
                'essentials_settings' => NULL,
                'asset_settings' => '',
                'font_size' => 0,
                'font_family' => '',
                'hms_settings' => NULL,
                'weighing_scale_setting' => '',
                'sms_non_delivery' => 0,
            ),
        ));
        
        
    }
}