<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DefaultAccountsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('default_accounts')->delete();
        
        \DB::table('default_accounts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'business_id' => 1,
                'name' => 'Cash',
                'account_number' => '101',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 5,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:34:50',
                'updated_at' => '2020-06-19 08:34:50',
            ),
            1 => 
            array (
                'id' => 2,
                'business_id' => 1,
                'name' => 'Petty Cash',
                'account_number' => '102',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 5,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:36:39',
                'updated_at' => '2020-06-19 08:36:39',
            ),
            2 => 
            array (
                'id' => 3,
                'business_id' => 1,
                'name' => 'Cheques in Hand',
                'account_number' => '103',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 6,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:37:44',
                'updated_at' => '2020-06-19 08:37:44',
            ),
            3 => 
            array (
                'id' => 4,
                'business_id' => 1,
                'name' => 'Accounts Receivable',
                'account_number' => '104',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 13,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:46:08',
                'updated_at' => '2023-08-30 11:27:33',
            ),
            4 => 
            array (
                'id' => 5,
                'business_id' => 1,
                'name' => 'Company Deposits',
                'account_number' => '105',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:46:42',
                'updated_at' => '2020-06-19 08:46:42',
            ),
            5 => 
            array (
                'id' => 6,
                'business_id' => 1,
                'name' => 'Raw Material Account',
                'account_number' => '106',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 1,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:47:24',
                'updated_at' => '2020-06-19 08:47:24',
            ),
            6 => 
            array (
                'id' => 7,
                'business_id' => 1,
                'name' => 'Finished Goods Account',
                'account_number' => '107',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 2,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:48:09',
                'updated_at' => '2020-09-18 07:25:20',
            ),
            7 => 
            array (
                'id' => 8,
                'business_id' => 1,
                'name' => 'Stock Account',
                'account_number' => '108',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 3,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:48:39',
                'updated_at' => '2020-06-19 08:48:39',
            ),
            8 => 
            array (
                'id' => 9,
                'business_id' => 1,
            'name' => 'Cards (Credit Debit)  Account',
                'account_number' => '120',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 7,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:50:46',
                'updated_at' => '2020-06-19 08:50:46',
            ),
            9 => 
            array (
                'id' => 10,
                'business_id' => 1,
                'name' => 'Fixed Assets',
                'account_number' => '150',
                'account_type_id' => 7,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:53:17',
                'updated_at' => '2020-06-19 08:53:17',
            ),
            10 => 
            array (
                'id' => 11,
                'business_id' => 1,
                'name' => 'Accounts Payable',
                'account_number' => '201',
                'account_type_id' => 8,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:53:56',
                'updated_at' => '2020-06-19 08:53:56',
            ),
            11 => 
            array (
                'id' => 12,
                'business_id' => 1,
                'name' => 'Wages Payable',
                'account_number' => '202',
                'account_type_id' => 8,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:54:26',
                'updated_at' => '2020-06-19 08:54:26',
            ),
            12 => 
            array (
                'id' => 13,
                'business_id' => 1,
                'name' => 'Taxes Payable',
                'account_number' => '203',
                'account_type_id' => 8,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:54:56',
                'updated_at' => '2020-06-19 08:54:56',
            ),
            13 => 
            array (
                'id' => 14,
                'business_id' => 1,
                'name' => 'Customer Deposits',
                'account_number' => '204',
                'account_type_id' => 8,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:55:27',
                'updated_at' => '2020-06-19 08:55:27',
            ),
            14 => 
            array (
                'id' => 15,
                'business_id' => 1,
                'name' => 'Sales Income',
                'account_number' => '301',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:56:12',
                'updated_at' => '2020-09-18 07:25:46',
            ),
            15 => 
            array (
                'id' => 16,
                'business_id' => 1,
                'name' => 'Cost of Goods Sold',
                'account_number' => '401',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 08:56:51',
                'updated_at' => '2020-09-18 07:24:55',
            ),
            16 => 
            array (
                'id' => 17,
                'business_id' => 1,
                'name' => 'Bank Fees & Charges',
                'account_number' => '402',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 4,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:16:58',
                'updated_at' => '2024-02-28 12:47:50',
            ),
            17 => 
            array (
                'id' => 18,
                'business_id' => 1,
                'name' => 'Rent Expense',
                'account_number' => '403',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:17:25',
                'updated_at' => '2020-06-19 10:17:25',
            ),
            18 => 
            array (
                'id' => 19,
                'business_id' => 1,
                'name' => 'Salaries & Wages Expenses',
                'account_number' => '404',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:18:01',
                'updated_at' => '2020-06-19 10:18:01',
            ),
            19 => 
            array (
                'id' => 20,
                'business_id' => 1,
                'name' => 'Water Expenses',
                'account_number' => '405',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:18:52',
                'updated_at' => '2020-06-19 10:18:52',
            ),
            20 => 
            array (
                'id' => 21,
                'business_id' => 1,
                'name' => 'Electricity Expenses',
                'account_number' => '406',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:19:17',
                'updated_at' => '2020-06-19 10:19:17',
            ),
            21 => 
            array (
                'id' => 22,
                'business_id' => 1,
                'name' => 'Owners Contribution',
                'account_number' => '600',
                'account_type_id' => 5,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:20:01',
                'updated_at' => '2020-06-19 10:20:01',
            ),
            22 => 
            array (
                'id' => 23,
                'business_id' => 1,
                'name' => 'Retained Earnings',
                'account_number' => '601',
                'account_type_id' => 5,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-06-19 10:20:30',
                'updated_at' => '2020-06-19 10:20:30',
            ),
            23 => 
            array (
                'id' => 24,
                'business_id' => 1,
                'name' => 'Sales Income - Gas',
                'account_number' => '301-1',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:38:34',
                'updated_at' => '2020-07-01 06:52:56',
            ),
            24 => 
            array (
                'id' => 25,
                'business_id' => 1,
                'name' => 'Sales Income - Kerosene Oil',
                'account_number' => '301-2',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:39:17',
                'updated_at' => '2020-07-01 06:53:18',
            ),
            25 => 
            array (
                'id' => 26,
                'business_id' => 1,
                'name' => 'Sales Income - Other Sales',
                'account_number' => '301-3',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:39:58',
                'updated_at' => '2020-07-01 06:53:48',
            ),
            26 => 
            array (
                'id' => 27,
                'business_id' => 1,
                'name' => 'Sales Income - Petrol 92',
                'account_number' => '301-4',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:41:29',
                'updated_at' => '2020-07-01 06:54:30',
            ),
            27 => 
            array (
                'id' => 28,
                'business_id' => 1,
                'name' => 'Sales Income - Petrol 95',
                'account_number' => '301-4',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:41:53',
                'updated_at' => '2020-07-01 06:54:46',
            ),
            28 => 
            array (
                'id' => 29,
                'business_id' => 1,
                'name' => 'Sales Income - LAD',
                'account_number' => '301-6',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:42:18',
                'updated_at' => '2020-07-01 06:54:59',
            ),
            29 => 
            array (
                'id' => 30,
                'business_id' => 1,
                'name' => 'Sales Income - Super Diesel',
                'account_number' => '301-7',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:42:56',
                'updated_at' => '2020-07-01 06:55:11',
            ),
            30 => 
            array (
                'id' => 31,
                'business_id' => 1,
                'name' => 'Sales Income - Lubricants',
                'account_number' => '301-8',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:43:56',
                'updated_at' => '2020-07-01 06:54:18',
            ),
            31 => 
            array (
                'id' => 32,
                'business_id' => 1,
                'name' => 'COGS - Gas',
                'account_number' => '401-1',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:56:07',
                'updated_at' => '2020-09-18 07:24:45',
            ),
            32 => 
            array (
                'id' => 33,
                'business_id' => 1,
                'name' => 'COGS  - Kerosene Oil',
                'account_number' => '401-2',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:56:31',
                'updated_at' => '2020-09-18 07:23:21',
            ),
            33 => 
            array (
                'id' => 34,
                'business_id' => 1,
                'name' => 'COGS  - Other Sales',
                'account_number' => '401-3',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:57:11',
                'updated_at' => '2020-09-18 07:24:02',
            ),
            34 => 
            array (
                'id' => 35,
                'business_id' => 1,
                'name' => 'COGS  - Petrol 92',
                'account_number' => '401-4',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:57:50',
                'updated_at' => '2020-09-18 07:24:13',
            ),
            35 => 
            array (
                'id' => 36,
                'business_id' => 1,
                'name' => 'COGS  - Petrol 95',
                'account_number' => '401-5',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:58:14',
                'updated_at' => '2020-09-18 07:24:23',
            ),
            36 => 
            array (
                'id' => 37,
                'business_id' => 1,
                'name' => 'COGS  - LAD',
                'account_number' => '401-6',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:58:40',
                'updated_at' => '2020-09-18 07:23:31',
            ),
            37 => 
            array (
                'id' => 38,
                'business_id' => 1,
                'name' => 'COGS  - Super Diesel',
                'account_number' => '401-7',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:59:14',
                'updated_at' => '2020-09-18 07:24:34',
            ),
            38 => 
            array (
                'id' => 39,
                'business_id' => 1,
                'name' => 'COGS  - Lubricants',
                'account_number' => '401-8',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => 8,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-01 06:59:38',
                'updated_at' => '2020-09-18 07:23:52',
            ),
            39 => 
            array (
                'id' => 40,
                'business_id' => 1,
                'name' => 'Sales income - Bowser',
                'account_number' => '301 - 8',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => 9,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-09-18 07:37:57',
                'updated_at' => '2020-09-18 07:40:23',
            ),
            40 => 
            array (
                'id' => 42,
                'business_id' => 1,
                'name' => 'Expenses',
                'account_number' => '400',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-10-06 03:12:39',
                'updated_at' => '2020-10-06 03:12:39',
            ),
            41 => 
            array (
                'id' => 43,
                'business_id' => 1,
                'name' => 'Cheque Return Income',
                'account_number' => '399',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-10-18 12:56:12',
                'updated_at' => '2020-10-18 12:56:12',
            ),
            42 => 
            array (
                'id' => 44,
                'business_id' => 1,
                'name' => 'Opening Balance Equity Account',
                'account_number' => 'E1',
                'account_type_id' => 5,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2021-02-28 16:02:57',
                'updated_at' => '2021-02-28 16:02:57',
            ),
            43 => 
            array (
                'id' => 46,
                'business_id' => 1,
                'name' => 'Advance Account – Sale of Land Blocks',
                'account_number' => '900',
                'account_type_id' => 3,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2023-04-19 04:47:22',
                'updated_at' => '2023-04-19 04:47:22',
            ),
            44 => 
            array (
                'id' => 47,
                'business_id' => 1,
                'name' => 'Goods in Transit',
                'account_number' => '44',
                'account_type_id' => 6,
                'note' => NULL,
                'asset_type' => 12,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2023-05-17 05:58:44',
                'updated_at' => '2023-05-17 05:58:44',
            ),
            45 => 
            array (
                'id' => 48,
                'business_id' => 1,
                'name' => 'Sales Discount',
                'account_number' => 'SD100',
                'account_type_id' => 4,
                'note' => NULL,
                'asset_type' => NULL,
                'created_by' => 1,
                'is_closed' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-01-25 02:57:32',
                'updated_at' => '2024-01-25 02:57:32',
            ),
        ));
        
        
    }
}