<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocManagementUploadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('doc_management_uploads')->delete();
        
        \DB::table('doc_management_uploads')->insert(array (
            0 => 
            array (
                'doc_no' => 1,
                'originator' => 'Ermias',
                'document_type' => 'Sales',
                'purpose' => 'Approved ',
                'note' => 'Nice',
                'referred_to' => 'Janaka,Upul',
                'image' => 'Finance',
                'status' => 'Referred Back',
                'created_at' => '2024-02-06 19:20:17',
                'updated_at' => '2024-02-06 19:20:17',
            ),
            1 => 
            array (
                'doc_no' => 2,
                'originator' => 'Ermias',
                'document_type' => 'Purchase Related',
                'purpose' => 'Approved ',
                'note' => 'Nice good',
                'referred_to' => 'Prabath,Janaka,Dhanushka,Upul',
                'image' => 'c:\\conn\\ermias.png',
                'status' => 'Referred Back',
                'created_at' => '2024-02-06 19:23:01',
                'updated_at' => '2024-02-06 19:23:01',
            ),
            2 => 
            array (
                'doc_no' => 3,
                'originator' => 'Ermias',
                'document_type' => 'Sales Tpe',
                'purpose' => 'Approved ',
                'note' => 'sdfsd',
                'referred_to' => 'Prabath',
                'image' => 'c:\\conn\\ermias.png',
                'status' => 'Approved',
                'created_at' => '2024-02-06 19:26:57',
                'updated_at' => '2024-02-06 19:26:57',
            ),
            3 => 
            array (
                'doc_no' => 4,
                'originator' => 'makda',
                'document_type' => 'Sales Return Related',
                'purpose' => 'Check again and send me',
                'note' => 'dfsdf',
                'referred_to' => 'Prabath',
                'image' => 'c:\\conn\\ermias.png',
                'status' => 'Referred Back',
                'created_at' => '2024-02-06 19:29:13',
                'updated_at' => '2024-02-06 19:29:13',
            ),
            4 => 
            array (
                'doc_no' => 5,
                'originator' => 'fsd',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 'xxx',
                'referred_to' => 'Services',
                'image' => 'c:\\conn\\ermias.png',
                'status' => '',
                'created_at' => '2024-02-03 08:30:19',
                'updated_at' => '2024-02-03 08:30:19',
            ),
            5 => 
            array (
                'doc_no' => 6,
                'originator' => '4',
                'document_type' => 'Purchase Related',
                'purpose' => 'For approval',
                'note' => 'xxx',
                'referred_to' => 'Gas',
                'image' => 'c:\\conn\\ermias.png',
                'status' => '',
                'created_at' => '2024-02-03 16:11:58',
                'updated_at' => '2024-02-03 16:11:58',
            ),
            6 => 
            array (
                'doc_no' => 7,
                'originator' => 'makda',
                'document_type' => 'Sales Return Related',
                'purpose' => 'For approval',
                'note' => 'xxx',
                'referred_to' => 'Gas',
                'image' => 'c:\\conn\\ermias.png',
                'status' => '',
                'created_at' => '2024-02-03 19:38:44',
                'updated_at' => '2024-02-03 19:38:44',
            ),
            7 => 
            array (
                'doc_no' => 8,
                'originator' => 'makda',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 'xxx',
                'referred_to' => 'Other Sales',
                'image' => 'c:\\conn\\ermias.png',
                'status' => '',
                'created_at' => '2024-02-03 19:42:14',
                'updated_at' => '2024-02-03 19:42:14',
            ),
            8 => 
            array (
                'doc_no' => 9,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '2',
                'image' => 'images/YBZf2BwGosVftLZYb2ot8590c0GUGi0y1AcT4Y2b.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:25:33',
                'updated_at' => '2024-02-04 09:25:33',
            ),
            9 => 
            array (
                'doc_no' => 10,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '4',
                'image' => 'images/JdOTzylL2AIpl0xKCrn7O4lXBSNrA4ydKgiN3HhM.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:26:24',
                'updated_at' => '2024-02-04 09:26:24',
            ),
            10 => 
            array (
                'doc_no' => 11,
                'originator' => 'yasin',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '4',
                'image' => 'images/kCFkVaEpxW0VrW7i9QYNQXo0BXA0z5EPj1WHbSFZ.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:41:20',
                'updated_at' => '2024-02-04 09:41:20',
            ),
            11 => 
            array (
                'doc_no' => 12,
                'originator' => 'yasin',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '4',
                'image' => 'images/KRKqW8SaBa61AsH2KaHjn1XWO22CE0wyMYMmOek2.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:47:05',
                'updated_at' => '2024-02-04 09:47:05',
            ),
            12 => 
            array (
                'doc_no' => 13,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '3',
                'image' => 'images/fYe8jbJ0OMF6AbVdXuqdbsmeCkRIxhAowcP5NngE.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:50:48',
                'updated_at' => '2024-02-04 09:50:48',
            ),
            13 => 
            array (
                'doc_no' => 14,
                'originator' => 'yasin',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '3',
                'image' => 'images/5rMhXs2M6aepFSRq4LE8EhA3fCREvtVQIvwKVWIT.jp',
                'status' => '',
                'created_at' => '2024-02-04 09:53:15',
                'updated_at' => '2024-02-04 09:53:15',
            ),
            14 => 
            array (
                'doc_no' => 15,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '4',
                'image' => 'images/6cHlvszoWdDIhR0Bbpsomsm0AoVRW89PWDGzAaiD.jp',
                'status' => '',
                'created_at' => '2024-02-04 10:05:29',
                'updated_at' => '2024-02-04 10:05:29',
            ),
            15 => 
            array (
                'doc_no' => 16,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '3',
                'image' => 'images/kQEF7JinzvGy2if9ybSGCsnJHvB3tg1lDWbiQP23.jp',
                'status' => '',
                'created_at' => '2024-02-04 10:08:16',
                'updated_at' => '2024-02-04 10:08:16',
            ),
            16 => 
            array (
                'doc_no' => 17,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '2',
                'image' => 'images/oIU8XkAMf7MvY4CuPTCL7iQRyeDvUtiapjiV3O6o.jp',
                'status' => '',
                'created_at' => '2024-02-04 10:10:07',
                'updated_at' => '2024-02-04 10:10:07',
            ),
            17 => 
            array (
                'doc_no' => 18,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '3',
                'image' => 'images/IkVBZM7tZ9IYAEOrwb8rDoDelmhpCMO2LBBTCRJ3.jp',
                'status' => '',
                'created_at' => '2024-02-04 10:21:39',
                'updated_at' => '2024-02-04 10:21:39',
            ),
            18 => 
            array (
                'doc_no' => 19,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'xxx',
                'referred_to' => '3',
                'image' => 'images/dFbYCE7DCkSkkIYUTHRQGitDUJ44p6Z9sE9K1AVs.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 10:42:32',
                'updated_at' => '2024-02-04 10:42:32',
            ),
            19 => 
            array (
                'doc_no' => 20,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'dsfsdf',
                'referred_to' => '2',
                'image' => 'images/dZ9B6yfUrjjn3ku0BqGNbloGX9xVzOX49Fi5d0Jq.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 10:46:33',
                'updated_at' => '2024-02-04 10:46:33',
            ),
            20 => 
            array (
                'doc_no' => 21,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'fsdfasdf',
                'referred_to' => '3',
                'image' => 'images/TSsocdgHmkXxdTXpQcWBVBgStNwFZOknErdbsAri.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 10:52:18',
                'updated_at' => '2024-02-04 10:52:18',
            ),
            21 => 
            array (
                'doc_no' => 22,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'fasd fsdfasdf',
                'referred_to' => '3',
                'image' => 'images/k7RpOspl85aqPR2o4wX5a3oUq0nxRqLMFpumqnfA.jp',
                'status' => 'Approved',
                'created_at' => '2024-02-04 10:52:49',
                'updated_at' => '2024-02-04 10:52:49',
            ),
            22 => 
            array (
                'doc_no' => 23,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'fsdfs',
                'referred_to' => '2',
                'image' => 'images/FG7LL3VIa694CBwqlN2hJJlCDz98FdlS3JBbrONA.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 10:54:13',
                'updated_at' => '2024-02-04 10:54:13',
            ),
            23 => 
            array (
                'doc_no' => 24,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'sdagsdg',
                'referred_to' => '4',
                'image' => 'images/f3Rl8mKYJOEzwhjlgUORtwA0C6WvwGmc4VXrS9V9.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 10:57:29',
                'updated_at' => '2024-02-04 10:57:29',
            ),
            24 => 
            array (
                'doc_no' => 25,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'fsdf',
                'referred_to' => '3',
                'image' => 'images/FgDqfdphaVwrhQeQvmxJoPrQk3BXewiwlVTm4uBq.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 11:53:38',
                'updated_at' => '2024-02-04 11:53:38',
            ),
            25 => 
            array (
                'doc_no' => 26,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'fsdf',
                'referred_to' => '3',
                'image' => 'images/aWJIW5Ho6aJV7fYE2D3MSy85bWDUpQNo7Nj6FuGk.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 11:54:14',
                'updated_at' => '2024-02-04 11:54:14',
            ),
            26 => 
            array (
                'doc_no' => 27,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'werwe',
                'referred_to' => '2',
                'image' => 'images/shRbmltD33HhIxs1NAIXvhYZ40XX9PjbmE5I0ZWz.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 11:55:49',
                'updated_at' => '2024-02-04 11:55:49',
            ),
            27 => 
            array (
                'doc_no' => 28,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'erer',
                'referred_to' => '3',
                'image' => 'images/6OcXfjiTAKx14Jns6vHlBlsFp2611aimkUKJbR8b.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 12:19:11',
                'updated_at' => '2024-02-04 12:19:11',
            ),
            28 => 
            array (
                'doc_no' => 29,
                'originator' => 'yasin',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'bbbb',
                'referred_to' => '2',
                'image' => 'images/qfDvy7CA3PFXP107lQEOWIYpEcVLy3LNc3fDqDxo.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 12:43:20',
                'updated_at' => '2024-02-04 12:43:20',
            ),
            29 => 
            array (
                'doc_no' => 30,
                'originator' => 'srwer',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'dsad',
                'referred_to' => '|2|4',
                'image' => 'images/S2iewMo1VnOWuf8IYiTxqLkWuO7NbzueflhYMTpC.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 13:54:12',
                'updated_at' => '2024-02-04 13:54:12',
            ),
            30 => 
            array (
                'doc_no' => 31,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'tt',
                'referred_to' => '|2|5',
                'image' => 'images/J3PPPfxb1XndEg1IQxsD4b5hXpkTXXv8Eb82Uqje.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 15:43:05',
                'updated_at' => '2024-02-04 15:43:05',
            ),
            31 => 
            array (
                'doc_no' => 32,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'tt',
                'referred_to' => '|2|5',
                'image' => 'images/RNcv4dSBf1iUp7yeOOTyGTomIPlrWCIwyKuMjAQf.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 15:44:11',
                'updated_at' => '2024-02-04 15:44:11',
            ),
            32 => 
            array (
                'doc_no' => 33,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'tt',
                'referred_to' => '|2|5',
                'image' => 'images/Dt7XbIPs9GabNnaTTjwWxxJUfaiT1C0693Floczw.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 15:44:54',
                'updated_at' => '2024-02-04 15:44:54',
            ),
            33 => 
            array (
                'doc_no' => 34,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'dds',
                'referred_to' => '|2|3|4',
                'image' => 'images/YsGxzkMH5QdQv7y5K5j0ckxlKjpC2Rmo7KLi5THM.jp',
                'status' => 'Approved',
                'created_at' => '2024-02-04 16:34:50',
                'updated_at' => '2024-02-04 16:34:50',
            ),
            34 => 
            array (
                'doc_no' => 35,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'erf',
                'referred_to' => '|4|5',
                'image' => 'images/s4iNgemegvAeE2CrLRUSPBk34QvmcGydvWgE7aON.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 16:39:48',
                'updated_at' => '2024-02-04 16:39:48',
            ),
            35 => 
            array (
                'doc_no' => 36,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'ddd',
                'referred_to' => '|4',
                'image' => 'images/3ZBFvhkDfT551DRErBCnOAhM9mchwn1oNLuTBawt.jp',
                'status' => 'Completed',
                'created_at' => '2024-02-04 16:40:11',
                'updated_at' => '2024-02-04 16:40:11',
            ),
            36 => 
            array (
                'doc_no' => 37,
                'originator' => 'srwer',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'DDD',
                'referred_to' => '|4|5',
                'image' => 'images/tyqIsjKDYW7wgwovsH9dJ1gVi1ZAcryRRS2a7zTu.jp',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-04 16:52:31',
                'updated_at' => '2024-02-04 16:52:31',
            ),
            37 => 
            array (
                'doc_no' => 38,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'f',
                'referred_to' => '||3',
                'image' => 'images/YSt0LcziKur8eRIj5kOT4R5kZNJD88F4wX5E9xPW.jpg',
                'status' => 'Completed',
                'created_at' => '2024-02-04 17:08:54',
                'updated_at' => '2024-02-04 17:08:54',
            ),
            38 => 
            array (
                'doc_no' => 39,
                'originator' => 'yasin',
                'document_type' => '2',
                'purpose' => '1',
                'note' => 'f',
                'referred_to' => '|2',
                'image' => 'images/obMIYtf29W2tdVwfuKUflSlDFMlj1d51TBfPI1kp.jpg',
                'status' => 'Completed',
                'created_at' => '2024-02-04 17:12:41',
                'updated_at' => '2024-02-04 17:12:41',
            ),
            39 => 
            array (
                'doc_no' => 40,
                'originator' => '3',
                'document_type' => '3',
                'purpose' => '1',
                'note' => 'tert',
                'referred_to' => '|3|5',
                'image' => 'images/4jtqRNa9JQ6WAXtbYXFJm0NBcisH3wo1d5m7oR26.jpg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 17:04:36',
                'updated_at' => '2024-02-05 17:04:36',
            ),
            40 => 
            array (
                'doc_no' => 41,
                'originator' => '3',
                'document_type' => '3',
                'purpose' => '2',
                'note' => 'fsd',
                'referred_to' => '|3|4',
                'image' => 'images/fv8ZlVtOUu8EixAGs7DZoLd62LdLqW1lBxtEnhHH.jpg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 17:09:14',
                'updated_at' => '2024-02-05 17:09:14',
            ),
            41 => 
            array (
                'doc_no' => 42,
                'originator' => '3',
                'document_type' => '1',
                'purpose' => '2',
                'note' => 'fsd',
                'referred_to' => '||4|6',
                'image' => 'images/DqF80qtKfiFKeK6O3JLXqw7rzq5OWCsyHASet0QF.jpg',
                'status' => 'Completed',
                'created_at' => '2024-02-05 17:09:43',
                'updated_at' => '2024-02-05 17:09:43',
            ),
            42 => 
            array (
                'doc_no' => 43,
                'originator' => '3',
                'document_type' => 'Sales Return Related',
                'purpose' => 'For approval',
                'note' => 'f',
                'referred_to' => '|Services|Other Sales',
                'image' => 'images/AkRY7MSCJ1Qth51OcXWuXiKQkTJ2w0pfC1GxyaQb.jpg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 17:50:16',
                'updated_at' => '2024-02-05 17:50:16',
            ),
            43 => 
            array (
                'doc_no' => 44,
                'originator' => '5',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 'ede',
                'referred_to' => '|Gas|Other Sales|Fuel|Sub-Gas',
                'image' => 'images/hHapJGLQKayM9jJDyBe3nCewqoE8cOpVWev1yEdu.jpg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 17:51:19',
                'updated_at' => '2024-02-05 17:51:19',
            ),
            44 => 
            array (
                'doc_no' => 45,
                'originator' => '67',
                'document_type' => 'Sales Tpe',
                'purpose' => 'Deligation',
                'note' => 'rr',
                'referred_to' => '|Janaka|OJkQjxRX|CO-0001-2',
                'image' => 'images/FKPManlys0BnlJ6qbN9Pdy7NDHhXW9dZAWV2Hbuw.jpg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 18:19:00',
                'updated_at' => '2024-02-05 18:19:00',
            ),
            45 => 
            array (
                'doc_no' => 46,
                'originator' => '555',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 'eden',
                'referred_to' => '|Udesh|Dhanushka',
                'image' => 'public/images/65c11a025d241.jpeg',
                'status' => 'Approved',
                'created_at' => '2024-02-05 18:25:22',
                'updated_at' => '2024-02-05 18:25:22',
            ),
            46 => 
            array (
                'doc_no' => 47,
                'originator' => '555',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 'eden',
                'referred_to' => '|Udesh|Dhanushka',
                'image' => 'public/images/65c11a032fe51.jpeg',
                'status' => 'Approved',
                'created_at' => '2024-02-05 18:25:23',
                'updated_at' => '2024-02-05 18:25:23',
            ),
            47 => 
            array (
                'doc_no' => 48,
                'originator' => '3',
                'document_type' => 'Sales Return Related',
                'purpose' => 'Deligation',
                'note' => 'r',
                'referred_to' => '|Janaka',
                'image' => 'public_html/images/65c11b2b13bd5.jpeg',
                'status' => 'Completed',
                'created_at' => '2024-02-05 18:30:19',
                'updated_at' => '2024-02-05 18:30:19',
            ),
            48 => 
            array (
                'doc_no' => 49,
                'originator' => '44',
                'document_type' => 'Sales Tpe',
                'purpose' => 'Deligation',
                'note' => 'rr',
                'referred_to' => '|Prabath',
                'image' => 'public_html/images/65c11d27385ec.jpeg',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 18:38:47',
                'updated_at' => '2024-02-05 18:38:47',
            ),
            49 => 
            array (
                'doc_no' => 50,
                'originator' => '44',
                'document_type' => 'Purchase Related',
                'purpose' => 'Deligation',
                'note' => '44',
                'referred_to' => '|Janaka',
                'image' => 'public_html/images/65c121198d44b.JPG',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 18:55:37',
                'updated_at' => '2024-02-05 18:55:37',
            ),
            50 => 
            array (
                'doc_no' => 51,
                'originator' => '44',
                'document_type' => 'Purchase Related',
                'purpose' => 'Deligation',
                'note' => '44',
                'referred_to' => '|Janaka',
                'image' => 'public_html/65c12163b2fa6.JPG',
                'status' => 'Forwarded with',
                'created_at' => '2024-02-05 18:56:51',
                'updated_at' => '2024-02-05 18:56:51',
            ),
            51 => 
            array (
                'doc_no' => 52,
                'originator' => '23',
                'document_type' => 'Sales Return Related',
                'purpose' => 'Deligation',
                'note' => '32',
                'referred_to' => '|Udesh',
                'image' => 'public_html/65c121854c2df.JPG',
                'status' => 'Approved',
                'created_at' => '2024-02-05 18:57:25',
                'updated_at' => '2024-02-05 18:57:25',
            ),
            52 => 
            array (
                'doc_no' => 53,
                'originator' => 'yasin',
                'document_type' => 'Purchase Related',
                'purpose' => 'For approval',
                'note' => 'This is the agreement document',
                'referred_to' => 'Prabath',
                'image' => '/public_html/Modules/DocManagement/Resources/assets/images/65c3b215ec004.jpg',
                'status' => 'Pending',
                'created_at' => '2024-02-07 17:52:22',
                'updated_at' => '2024-02-07 17:38:46',
            ),
            53 => 
            array (
                'doc_no' => 54,
                'originator' => '3',
                'document_type' => 'Sales Tpe',
                'purpose' => 'For approval',
                'note' => 't',
                'referred_to' => 'Janaka',
                'image' => '/public_html/public/uploads/img/1707326873_fasika.jpg',
                'status' => 'Pending',
                'created_at' => '2024-02-07 18:42:39',
                'updated_at' => '2024-02-07 17:58:46',
            ),
        ));
        
        
    }
}