<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ExpenseCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('expense_categories')->delete();
        
        \DB::table('expense_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'M H A UDAYAKUMARA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-1',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:21:53',
                'updated_at' => '2024-02-27 04:21:53',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'T V A A KUMARATHUNGA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-2',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:41:05',
                'created_at' => '2024-02-27 04:22:04',
                'updated_at' => '2025-03-26 07:41:05',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'R D KAHINGALA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-3',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:22:13',
                'updated_at' => '2024-02-27 04:22:13',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'W A R DILAN - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-4',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:40:26',
                'created_at' => '2024-02-27 04:22:22',
                'updated_at' => '2025-03-26 07:40:26',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'K R S RANATHUNGA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-5',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:22:32',
                'updated_at' => '2024-02-27 04:22:32',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'M M A D KUMARA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-6',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:24:27',
                'updated_at' => '2024-02-27 04:24:27',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'W A A OSHAN - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-7',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:40:49',
                'created_at' => '2024-02-27 04:24:36',
                'updated_at' => '2025-03-26 07:40:49',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'M P NANDASENA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-8',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:24:46',
                'updated_at' => '2024-02-27 04:24:46',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'S K K S PERERA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-9',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:24:55',
                'updated_at' => '2024-02-27 04:24:55',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'O S A PARERA - Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-10',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:25:07',
                'updated_at' => '2024-02-27 04:25:07',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'M H A UDAYAKUMARA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-11',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:25:21',
                'updated_at' => '2024-02-27 04:25:21',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'T V A A KUMARATHUNGA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-12',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:41:01',
                'created_at' => '2024-02-27 04:25:31',
                'updated_at' => '2025-03-26 07:41:01',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'R D KAHINGALA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-13',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:25:39',
                'updated_at' => '2024-02-27 04:25:39',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'W A R DILAN - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-14',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:40:31',
                'created_at' => '2024-02-27 04:25:49',
                'updated_at' => '2025-03-26 07:40:31',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'K R S RANATHUNGA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-15',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:25:59',
                'updated_at' => '2024-02-27 04:25:59',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'M M A D KUMARA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-16',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:26:10',
                'updated_at' => '2024-02-27 04:26:10',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'W A A OSHAN - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-17',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2025-03-26 07:40:54',
                'created_at' => '2024-02-27 04:26:20',
                'updated_at' => '2025-03-26 07:40:54',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'M P NANDASENA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-18',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:26:29',
                'updated_at' => '2024-02-27 04:26:29',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'S K K S PERERA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-19',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:26:38',
                'updated_at' => '2024-02-27 04:26:38',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'O S A PARERA - Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-20',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:26:46',
                'updated_at' => '2024-02-27 04:26:46',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Bank Charges',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-21',
                'expense_account' => 153,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:28:33',
                'updated_at' => '2024-02-27 04:28:33',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Loan Interest',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-22',
                'expense_account' => 153,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:28:51',
                'updated_at' => '2024-02-27 04:28:51',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Pump Repair & Maintenances',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-23',
                'expense_account' => 195,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:29:31',
                'updated_at' => '2024-02-27 04:29:31',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'EPF',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-24',
                'expense_account' => 196,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:30:42',
                'updated_at' => '2024-02-27 04:32:36',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ETF',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-25',
                'expense_account' => 197,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:30:55',
                'updated_at' => '2024-02-27 04:30:55',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Water Bill',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-26',
                'expense_account' => 156,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:31:07',
                'updated_at' => '2024-02-27 04:31:07',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Electricity Bill',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-27',
                'expense_account' => 157,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:31:17',
                'updated_at' => '2024-02-27 04:31:17',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Bowser TIP',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-28',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:31:29',
                'updated_at' => '2024-02-27 04:31:29',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Transport Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-29',
                'expense_account' => 198,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:31:51',
                'updated_at' => '2024-02-27 04:31:51',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Meals & Tea',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-30',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:32:04',
                'updated_at' => '2024-02-27 04:32:04',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Owner Vehicle Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-31',
                'expense_account' => 199,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 04:34:50',
                'updated_at' => '2024-02-27 04:34:50',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Cleaning Service',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-32',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-28 10:43:43',
                'updated_at' => '2024-02-28 10:43:43',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Welfare Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-33',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-28 12:21:46',
                'updated_at' => '2024-06-14 10:00:43',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Boarding Rent',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-34',
                'expense_account' => 154,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-29 14:56:26',
                'updated_at' => '2024-03-08 09:54:45',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Rate & Tax',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-35',
                'expense_account' => 218,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 09:15:54',
                'updated_at' => '2024-03-08 09:15:54',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Stationary & Postage',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-36',
                'expense_account' => 219,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 09:26:36',
                'updated_at' => '2024-03-08 09:26:36',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Maintenance Charge For Software System',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-37',
                'expense_account' => 220,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 09:37:59',
                'updated_at' => '2024-03-08 09:37:59',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Mobitel Bill',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-38',
                'expense_account' => 221,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 09:42:25',
                'updated_at' => '2024-03-08 09:42:25',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Dialog Bill',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-39',
                'expense_account' => 222,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 09:50:08',
                'updated_at' => '2024-03-08 09:53:44',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Security Service Charges',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-40',
                'expense_account' => 223,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 10:03:05',
                'updated_at' => '2024-03-08 10:03:05',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Petty Cash Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-41',
                'expense_account' => 224,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 10:13:27',
                'updated_at' => '2024-03-08 10:13:27',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Staff & Labour Salary & Wages',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-42',
                'expense_account' => 155,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-20 05:55:08',
                'updated_at' => '2024-03-20 05:55:08',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Staff & Labour Salary Advance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-43',
                'expense_account' => 226,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-20 05:55:30',
                'updated_at' => '2024-03-20 05:55:30',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Sri Lanka Telecom PLC',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-44',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-20 06:07:34',
                'updated_at' => '2024-03-20 06:07:34',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Audit Fee',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-45',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-28 07:54:21',
                'updated_at' => '2024-03-28 07:54:21',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Repair & Maintanance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-46',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-03-28 08:06:39',
                'updated_at' => '2024-11-29 08:28:31',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Printer Service',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-47',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-04-06 04:53:12',
                'updated_at' => '2024-04-06 04:53:12',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'O D Interest',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-48',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-04-06 08:10:38',
                'updated_at' => '2024-04-06 08:10:38',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'CCTV Camera System',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-49',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-04-06 08:27:54',
                'updated_at' => '2024-04-06 08:27:54',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Staff & Labour Festival Bonus',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-50',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 05:32:30',
                'updated_at' => '2024-05-06 05:33:30',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Partner\'s Drowing Account-M C Perera',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-51',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 05:51:19',
                'updated_at' => '2024-05-06 05:51:19',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Advertising Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-52',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 05:59:28',
                'updated_at' => '2024-05-06 05:59:28',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Measurement Unit & Services',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-53',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:01:44',
                'updated_at' => '2024-05-06 06:01:44',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Ceylinco General Insurance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-54',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:06:13',
                'updated_at' => '2024-05-06 06:06:13',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Monthly Service Charges-Comm Bank',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-55',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:17:37',
                'updated_at' => '2024-05-06 06:17:37',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Annual Fee-Comm Bank',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-56',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:18:34',
                'updated_at' => '2024-05-06 06:19:36',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Fee on Excess-Comm Bank',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-57',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:19:17',
                'updated_at' => '2024-05-06 06:19:17',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Comm Bank Loan-15,000,000/=',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-58',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:32:05',
                'updated_at' => '2024-05-06 06:32:05',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Comm Bank Sola Loan-5,000,000/=',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-59',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:33:14',
                'updated_at' => '2024-06-14 10:42:09',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Comm Bank Leasing',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-60',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-06 06:33:55',
                'updated_at' => '2024-05-06 06:33:55',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Director Salary',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-61',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-07 05:28:06',
                'updated_at' => '2024-05-07 05:28:06',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Building Expenses & Maintenance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-62',
                'expense_account' => 233,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 04:08:08',
                'updated_at' => '2024-05-14 04:08:08',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Solar Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-63',
                'expense_account' => 232,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 04:08:40',
                'updated_at' => '2024-05-14 04:08:40',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Bowser Expenses Fuel & Maintenance',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-64',
                'expense_account' => 231,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 04:09:17',
                'updated_at' => '2024-05-14 04:09:17',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Other Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-65',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-22 06:00:42',
                'updated_at' => '2024-05-22 06:00:42',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Donation',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-66',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-05-22 06:15:43',
                'updated_at' => '2024-05-22 06:15:43',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Sri Lanka Insurance Corparation Ltd',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-67',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-14 10:11:50',
                'updated_at' => '2024-06-19 07:01:33',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Staff & Labour Loan',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-68',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => '2024-07-04 06:49:51',
                'created_at' => '2024-07-04 06:36:59',
                'updated_at' => '2024-07-04 06:49:51',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            68 => 
            array (
                'id' => 69,
            'name' => 'Shermans Logistics(Pvt)Ltd',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-68',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-07-08 08:48:51',
                'updated_at' => '2024-07-08 08:48:51',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Stationery Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-69',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-08-21 12:13:41',
                'updated_at' => '2024-08-21 12:13:41',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Business Promotion',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-70',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-20 12:26:13',
                'updated_at' => '2024-09-20 12:26:13',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Fuel Expenses',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-71',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-12-27 11:05:49',
                'updated_at' => '2024-12-27 11:05:49',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'IOC Delay Payment Interest',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-72',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-23 11:34:20',
                'updated_at' => '2025-01-23 11:34:20',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Staff & Labour Commision',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-73',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-31 09:22:16',
                'updated_at' => '2025-01-31 09:22:16',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Office Equipments',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-74',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-28 09:16:18',
                'updated_at' => '2025-02-28 09:16:18',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Environment License Fees',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-75',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-26 07:33:26',
                'updated_at' => '2025-03-26 07:40:13',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Valuation fees',
                'business_id' => 4,
                'default_expense_category_id' => NULL,
                'code' => 'EXP-76',
                'expense_account' => 177,
                'is_sub_category' => 0,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-26 07:39:26',
                'updated_at' => '2025-03-26 07:39:26',
                'payee_id' => 5,
                'is_employee' => 0,
                'employee_id' => NULL,
                'vat_claimed' => 0,
            ),
        ));
        
        
    }
}