<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HelpguideCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('helpguide_categories')->delete();
        
        \DB::table('helpguide_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Default Category',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-05 01:20:35',
                'updated_at' => '2024-11-30 04:06:07',
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'Purchase Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:06:50',
                'updated_at' => '2024-11-30 04:06:50',
            ),
            2 => 
            array (
                'id' => 5,
                'name' => 'Settlement',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2024-11-30 04:07:41',
                'created_at' => '2024-11-30 04:07:16',
                'updated_at' => '2024-11-30 04:07:41',
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'Petro Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:07:48',
                'updated_at' => '2024-11-30 04:07:48',
            ),
            4 => 
            array (
                'id' => 7,
                'name' => 'Contact Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:08:07',
                'updated_at' => '2024-11-30 04:08:07',
            ),
            5 => 
            array (
                'id' => 8,
                'name' => 'Accounting Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:08:28',
                'updated_at' => '2024-11-30 04:08:28',
            ),
            6 => 
            array (
                'id' => 9,
                'name' => 'Product Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:08:45',
                'updated_at' => '2024-11-30 04:08:45',
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'VAT Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:09:16',
                'updated_at' => '2024-11-30 04:09:16',
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'Post Dated Cheques Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2024-11-30 05:08:11',
                'created_at' => '2024-11-30 04:09:33',
                'updated_at' => '2024-11-30 05:08:11',
            ),
            9 => 
            array (
                'id' => 12,
                'name' => 'SMS Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:09:52',
                'updated_at' => '2024-11-30 04:09:52',
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'Reports',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:10:13',
                'updated_at' => '2024-11-30 04:18:09',
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'Add on Modules',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:10:27',
                'updated_at' => '2024-11-30 04:10:27',
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'Fleet Management',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:14:42',
                'updated_at' => '2024-11-30 04:21:52',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'My Voice',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:15:42',
                'updated_at' => '2024-11-30 04:22:16',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'Logistic Services',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:15:56',
                'updated_at' => '2024-11-30 04:17:20',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'Airline Ticketing',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:16:29',
                'updated_at' => '2024-11-30 04:16:55',
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'Land Sales',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:16:43',
                'updated_at' => '2024-11-30 04:16:43',
            ),
            17 => 
            array (
                'id' => 20,
                'name' => 'HRM Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:19:00',
                'updated_at' => '2024-11-30 04:19:00',
            ),
            18 => 
            array (
                'id' => 21,
                'name' => 'Leads Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:19:34',
                'updated_at' => '2024-11-30 04:19:34',
            ),
            19 => 
            array (
                'id' => 22,
                'name' => 'Task Management',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:19:50',
                'updated_at' => '2024-11-30 04:19:50',
            ),
            20 => 
            array (
                'id' => 23,
                'name' => 'MPCS Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:20:11',
                'updated_at' => '2024-11-30 04:20:11',
            ),
            21 => 
            array (
                'id' => 24,
                'name' => 'Price Change Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:20:28',
                'updated_at' => '2024-11-30 04:20:28',
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'Bakery System',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:20:39',
                'updated_at' => '2024-11-30 04:20:39',
            ),
            23 => 
            array (
                'id' => 26,
                'name' => 'Sales Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:22:42',
                'updated_at' => '2024-11-30 04:22:42',
            ),
            24 => 
            array (
                'id' => 27,
                'name' => 'Stock Taking Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:23:03',
                'updated_at' => '2024-11-30 04:23:03',
            ),
            25 => 
            array (
                'id' => 28,
                'name' => 'Stock Transfers',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:23:44',
                'updated_at' => '2024-11-30 04:23:44',
            ),
            26 => 
            array (
                'id' => 29,
                'name' => 'Stock Adjustments',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:23:55',
                'updated_at' => '2024-11-30 04:23:55',
            ),
            27 => 
            array (
                'id' => 30,
                'name' => 'Expenses',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:24:39',
                'updated_at' => '2024-11-30 04:24:39',
            ),
            28 => 
            array (
                'id' => 31,
                'name' => 'My Health',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:28:11',
                'updated_at' => '2024-11-30 04:28:11',
            ),
            29 => 
            array (
                'id' => 32,
                'name' => 'Sugar Reading',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => 31,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:28:40',
                'updated_at' => '2024-11-30 04:28:40',
            ),
            30 => 
            array (
                'id' => 33,
                'name' => 'Medications',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => 31,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:29:11',
                'updated_at' => '2024-11-30 04:29:11',
            ),
            31 => 
            array (
                'id' => 34,
                'name' => 'Restaurant System',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:49:29',
                'updated_at' => '2024-11-30 04:49:29',
            ),
            32 => 
            array (
                'id' => 35,
            'name' => 'PD (Post Dated) Cheque Management Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:50:03',
                'updated_at' => '2024-11-30 05:08:34',
            ),
            33 => 
            array (
                'id' => 36,
                'name' => 'Backup Module',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:50:24',
                'updated_at' => '2024-11-30 04:50:24',
            ),
            34 => 
            array (
                'id' => 37,
                'name' => 'Cheque Writing System',
                'thumbnail' => NULL,
                'category_order' => 0,
                'active' => 1,
                'has_ticket' => 1,
                'is_featured' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-11-30 04:51:05',
                'updated_at' => '2024-11-30 04:51:05',
            ),
        ));
        
        
    }
}