<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LoansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('loans')->delete();
        
        \DB::table('loans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_by_id' => 3,
                'contact_type' => 'customer',
                'contact_id' => 5,
                'group_id' => NULL,
                'location_id' => 3,
                'loan_application_id' => NULL,
                'currency_id' => 111,
                'loan_product_id' => 1,
                'variation_id' => 1,
                'loan_transaction_processing_strategy_id' => 1,
                'loan_purpose_id' => 1,
                'loan_officer_id' => 5,
                'linked_savings_id' => NULL,
                'loan_disbursement_channel_id' => NULL,
                'submitted_on_date' => '2023-06-02',
                'submitted_by_user_id' => 3,
                'approved_on_date' => NULL,
                'approved_by_user_id' => NULL,
                'approved_notes' => NULL,
                'expected_disbursement_date' => '2023-06-02',
                'expected_first_payment_date' => '2023-07-02',
                'first_payment_date' => NULL,
                'expected_maturity_date' => NULL,
                'disbursed_on_date' => NULL,
                'disbursed_by_user_id' => NULL,
                'disbursed_notes' => NULL,
                'rejected_on_date' => NULL,
                'rejected_by_user_id' => NULL,
                'rejected_notes' => NULL,
                'written_off_on_date' => NULL,
                'written_off_by_user_id' => NULL,
                'written_off_notes' => NULL,
                'closed_on_date' => NULL,
                'closed_by_user_id' => NULL,
                'closed_notes' => NULL,
                'rescheduled_on_date' => NULL,
                'rescheduled_by_user_id' => NULL,
                'rescheduled_notes' => NULL,
                'withdrawn_on_date' => NULL,
                'withdrawn_by_user_id' => NULL,
                'withdrawn_notes' => NULL,
                'external_id' => '2023/0001',
                'account_number' => NULL,
                'principal' => '0.000000',
                'applied_amount' => '10000.0000',
                'top_up_amount' => NULL,
                'approved_amount' => NULL,
                'interest_rate' => '10.000000',
                'decimals' => NULL,
                'instalment_multiple_of' => 1,
                'loan_term' => 12,
                'repayment_frequency' => 1,
                'repayment_frequency_type' => 'months',
                'interest_rate_type' => 'month',
                'enable_balloon_payments' => 0,
                'allow_schedule_adjustments' => 0,
                'grace_on_principal_paid' => 0,
                'grace_on_interest_paid' => 0,
                'grace_on_interest_charged' => 0,
                'allow_custom_grace_period' => 0,
                'allow_topup' => 0,
                'interest_methodology' => 'flat',
                'interest_recalculation' => 0,
                'amortization_method' => 'equal_installments',
                'interest_calculation_period_type' => NULL,
                'days_in_year' => 'actual',
                'days_in_month' => 'actual',
                'include_in_loan_cycle' => 0,
                'lock_guarantee_funds' => 0,
                'auto_allocate_overpayments' => 0,
                'allow_additional_charges' => 0,
                'auto_disburse' => 0,
                'status' => 'submitted',
                'is_signed' => 0,
                'disbursement_charges' => NULL,
                'principal_disbursed_derived' => '0.000000',
                'principal_repaid_derived' => '0.000000',
                'principal_written_off_derived' => '0.000000',
                'principal_outstanding_derived' => '0.000000',
                'interest_disbursed_derived' => '0.000000',
                'interest_repaid_derived' => '0.000000',
                'interest_written_off_derived' => '0.000000',
                'interest_waived_derived' => '0.000000',
                'interest_outstanding_derived' => '0.000000',
                'fees_disbursed_derived' => '0.000000',
                'fees_repaid_derived' => '0.000000',
                'fees_written_off_derived' => '0.000000',
                'fees_waived_derived' => '0.000000',
                'fees_outstanding_derived' => '0.000000',
                'penalties_disbursed_derived' => '0.000000',
                'penalties_repaid_derived' => '0.000000',
                'penalties_written_off_derived' => '0.000000',
                'penalties_waived_derived' => '0.000000',
                'penalties_outstanding_derived' => '0.000000',
                'total_disbursed_derived' => '0.000000',
                'total_repaid_derived' => '0.000000',
                'total_written_off_derived' => '0.000000',
                'total_waived_derived' => '0.000000',
                'total_outstanding_derived' => '0.000000',
                'accounting_rule' => 'cash',
                'fund_source_chart_of_account_id' => 0,
                'loan_portfolio_chart_of_account_id' => 0,
                'suspended_income_chart_of_account_id' => 0,
                'interest_receivable_chart_of_account_id' => NULL,
                'fees_receivable_chart_of_account_id' => NULL,
                'penalties_receivable_chart_of_account_id' => NULL,
                'transfer_in_suspense_chart_of_account_id' => 0,
                'income_from_interest_chart_of_account_id' => 101,
                'income_from_penalties_chart_of_account_id' => 101,
                'income_from_fees_chart_of_account_id' => 101,
                'income_from_recovery_chart_of_account_id' => 101,
                'losses_written_off_chart_of_account_id' => 102,
                'interest_written_off_chart_of_account_id' => 102,
                'overpayments_chart_of_account_id' => 0,
                'created_at' => '2023-06-02 15:32:24',
                'updated_at' => '2023-06-02 15:32:24',
            ),
            1 => 
            array (
                'id' => 2,
                'created_by_id' => 3,
                'contact_type' => 'customer',
                'contact_id' => 5,
                'group_id' => NULL,
                'location_id' => 3,
                'loan_application_id' => NULL,
                'currency_id' => 111,
                'loan_product_id' => 6,
                'variation_id' => 1,
                'loan_transaction_processing_strategy_id' => 1,
                'loan_purpose_id' => 1,
                'loan_officer_id' => 3,
                'linked_savings_id' => NULL,
                'loan_disbursement_channel_id' => NULL,
                'submitted_on_date' => '2023-06-03',
                'submitted_by_user_id' => 3,
                'approved_on_date' => '2023-06-03',
                'approved_by_user_id' => 3,
                'approved_notes' => 'Approved by Daniel',
                'expected_disbursement_date' => '2023-06-03',
                'expected_first_payment_date' => '2023-06-03',
                'first_payment_date' => '2023-06-04',
                'expected_maturity_date' => '2024-06-04',
                'disbursed_on_date' => '2023-06-03',
                'disbursed_by_user_id' => 3,
                'disbursed_notes' => NULL,
                'rejected_on_date' => NULL,
                'rejected_by_user_id' => NULL,
                'rejected_notes' => NULL,
                'written_off_on_date' => NULL,
                'written_off_by_user_id' => NULL,
                'written_off_notes' => NULL,
                'closed_on_date' => NULL,
                'closed_by_user_id' => NULL,
                'closed_notes' => NULL,
                'rescheduled_on_date' => NULL,
                'rescheduled_by_user_id' => NULL,
                'rescheduled_notes' => NULL,
                'withdrawn_on_date' => NULL,
                'withdrawn_by_user_id' => NULL,
                'withdrawn_notes' => NULL,
                'external_id' => '2023/0002',
                'account_number' => NULL,
                'principal' => '100000.000000',
                'applied_amount' => '100000.0000',
                'top_up_amount' => NULL,
                'approved_amount' => '100000.000000',
                'interest_rate' => '9.000000',
                'decimals' => NULL,
                'instalment_multiple_of' => 1,
                'loan_term' => 12,
                'repayment_frequency' => 1,
                'repayment_frequency_type' => 'months',
                'interest_rate_type' => 'year',
                'enable_balloon_payments' => 0,
                'allow_schedule_adjustments' => 0,
                'grace_on_principal_paid' => 0,
                'grace_on_interest_paid' => 0,
                'grace_on_interest_charged' => 0,
                'allow_custom_grace_period' => 0,
                'allow_topup' => 0,
                'interest_methodology' => 'flat',
                'interest_recalculation' => 0,
                'amortization_method' => 'equal_installments',
                'interest_calculation_period_type' => NULL,
                'days_in_year' => 'actual',
                'days_in_month' => 'actual',
                'include_in_loan_cycle' => 0,
                'lock_guarantee_funds' => 0,
                'auto_allocate_overpayments' => 0,
                'allow_additional_charges' => 0,
                'auto_disburse' => 0,
                'status' => 'active',
                'is_signed' => 0,
                'disbursement_charges' => '0.000000',
                'principal_disbursed_derived' => '100000.000000',
                'principal_repaid_derived' => '0.000000',
                'principal_written_off_derived' => '0.000000',
                'principal_outstanding_derived' => '0.000000',
                'interest_disbursed_derived' => '9000.000000',
                'interest_repaid_derived' => '0.000000',
                'interest_written_off_derived' => '0.000000',
                'interest_waived_derived' => '0.000000',
                'interest_outstanding_derived' => '0.000000',
                'fees_disbursed_derived' => '0.000000',
                'fees_repaid_derived' => '0.000000',
                'fees_written_off_derived' => '0.000000',
                'fees_waived_derived' => '0.000000',
                'fees_outstanding_derived' => '0.000000',
                'penalties_disbursed_derived' => '0.000000',
                'penalties_repaid_derived' => '0.000000',
                'penalties_written_off_derived' => '0.000000',
                'penalties_waived_derived' => '0.000000',
                'penalties_outstanding_derived' => '0.000000',
                'total_disbursed_derived' => '0.000000',
                'total_repaid_derived' => '0.000000',
                'total_written_off_derived' => '0.000000',
                'total_waived_derived' => '0.000000',
                'total_outstanding_derived' => '0.000000',
                'accounting_rule' => 'cash',
                'fund_source_chart_of_account_id' => 0,
                'loan_portfolio_chart_of_account_id' => 0,
                'suspended_income_chart_of_account_id' => 0,
                'interest_receivable_chart_of_account_id' => NULL,
                'fees_receivable_chart_of_account_id' => NULL,
                'penalties_receivable_chart_of_account_id' => NULL,
                'transfer_in_suspense_chart_of_account_id' => 0,
                'income_from_interest_chart_of_account_id' => 101,
                'income_from_penalties_chart_of_account_id' => 101,
                'income_from_fees_chart_of_account_id' => 101,
                'income_from_recovery_chart_of_account_id' => 101,
                'losses_written_off_chart_of_account_id' => 102,
                'interest_written_off_chart_of_account_id' => 102,
                'overpayments_chart_of_account_id' => 0,
                'created_at' => '2023-06-03 08:25:54',
                'updated_at' => '2023-06-06 02:35:53',
            ),
        ));
        
        
    }
}