<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PumpsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pumps')->delete();
        
        \DB::table('pumps')->insert(array (
            0 => 
            array (
                'id' => 1,
                'business_id' => 4,
                'pump_name' => 'P3',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P3',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '1372500.0000',
                'last_meter_reading' => '1372590.000',
                'temp_meter_reading' => '1871968.470',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 1,
                'fuel_tank_id' => 1,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:20:38',
                'updated_at' => '2025-05-29 14:06:55',
            ),
            1 => 
            array (
                'id' => 2,
                'business_id' => 4,
                'pump_name' => 'P5',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P5',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '3733355.0000',
                'last_meter_reading' => '3733385.000',
                'temp_meter_reading' => '2989336.340',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 1,
                'fuel_tank_id' => 1,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:21:02',
                'updated_at' => '2025-05-23 11:26:51',
            ),
            2 => 
            array (
                'id' => 3,
                'business_id' => 4,
                'pump_name' => 'P7',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P7',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '6315317.2000',
                'last_meter_reading' => '6315400.200',
                'temp_meter_reading' => '4944949.010',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 1,
                'fuel_tank_id' => 1,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:23:47',
                'updated_at' => '2025-05-05 08:02:31',
            ),
            3 => 
            array (
                'id' => 4,
                'business_id' => 4,
                'pump_name' => 'P9',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P9',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '4082666.0200',
                'last_meter_reading' => '4082766.020',
                'temp_meter_reading' => '3525512.510',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 4,
                'fuel_tank_id' => 2,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:24:45',
                'updated_at' => '2025-05-04 17:29:48',
            ),
            4 => 
            array (
                'id' => 5,
                'business_id' => 4,
                'pump_name' => 'P10',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P10',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '614810.5300',
                'last_meter_reading' => '614910.530',
                'temp_meter_reading' => '4214779.080',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 4,
                'fuel_tank_id' => 2,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:25:07',
                'updated_at' => '2025-05-03 05:28:30',
            ),
            5 => 
            array (
                'id' => 6,
                'business_id' => 4,
                'pump_name' => 'P13',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P13',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '408995.2100',
                'last_meter_reading' => '410832.580',
                'temp_meter_reading' => '4049416.500',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 4,
                'fuel_tank_id' => 2,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:25:28',
                'updated_at' => '2025-04-09 08:37:48',
            ),
            6 => 
            array (
                'id' => 7,
                'business_id' => 4,
                'pump_name' => 'P8',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P8',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '3142074.0500',
                'last_meter_reading' => '3143347.270',
                'temp_meter_reading' => '2649806.890',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 5,
                'fuel_tank_id' => 3,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:26:14',
                'updated_at' => '2025-04-09 08:37:06',
            ),
            7 => 
            array (
                'id' => 8,
                'business_id' => 4,
                'pump_name' => 'P12',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P12',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '9323.5500',
                'last_meter_reading' => '9549.930',
                'temp_meter_reading' => '395591.090',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 5,
                'fuel_tank_id' => 3,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:26:36',
                'updated_at' => '2025-04-09 08:37:38',
            ),
            8 => 
            array (
                'id' => 9,
                'business_id' => 4,
                'pump_name' => 'P2',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P2',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '267008.8700',
                'last_meter_reading' => '267667.100',
                'temp_meter_reading' => '451159.090',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 2,
                'fuel_tank_id' => 4,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:27:35',
                'updated_at' => '2025-04-09 07:36:20',
            ),
            9 => 
            array (
                'id' => 10,
                'business_id' => 4,
                'pump_name' => 'P4',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P4',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '589327.3100',
                'last_meter_reading' => '589543.340',
                'temp_meter_reading' => '514107.020',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 2,
                'fuel_tank_id' => 4,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:27:57',
                'updated_at' => '2025-04-09 08:24:43',
            ),
            10 => 
            array (
                'id' => 11,
                'business_id' => 4,
                'pump_name' => 'P6',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P6',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '2052370.3100',
                'last_meter_reading' => '2052697.100',
                'temp_meter_reading' => '1864589.630',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 2,
                'fuel_tank_id' => 4,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:28:22',
                'updated_at' => '2025-04-09 08:27:54',
            ),
            11 => 
            array (
                'id' => 12,
                'business_id' => 4,
                'pump_name' => 'P11',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P11',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '66853.4200',
                'last_meter_reading' => '66882.100',
                'temp_meter_reading' => '1414031.030',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 6,
                'fuel_tank_id' => 5,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:28:57',
                'updated_at' => '2025-04-09 08:45:40',
            ),
            12 => 
            array (
                'id' => 13,
                'business_id' => 4,
                'pump_name' => 'P1',
                'location_id' => 2,
                'fuel_type' => '',
                'installation_date' => '2024-02-25',
                'pump_no' => 'P1',
                'image_link' => '',
                'storage_tank' => NULL,
                'starting_meter' => '2268582.0000',
                'last_meter_reading' => '2269064.000',
                'temp_meter_reading' => '2133104.000',
                'pod_starting_meter' => NULL,
                'pod_last_meter' => NULL,
                'product_id' => 3,
                'fuel_tank_id' => 6,
                'qty' => '',
                'checkk' => 1,
                'testing' => '1',
                'transaction_date' => '2024-02-25',
                'bulk_sale_meter' => 0,
                'created_at' => '2024-02-27 03:29:44',
                'updated_at' => '2025-04-09 07:35:45',
            ),
        ));
        
        
    }
}