<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PumpOperatorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pump_operators')->delete();
        
        \DB::table('pump_operators')->insert(array (
            0 => 
            array (
                'id' => 1,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'M HASITHA UDAYAKUMARA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '517580.79',
                'excess_amount' => '-41062.70',
                'settlement_no' => 'ST3879',
                'active' => 1,
                'created_at' => '2024-02-27 03:06:42',
                'updated_at' => '2025-05-05 08:00:46',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'T V A AJITH KUMARATHUNGA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '643266.79',
                'excess_amount' => '-103464.77',
                'settlement_no' => 'ST3873',
                'active' => 1,
                'created_at' => '2024-02-27 03:07:23',
                'updated_at' => '2025-04-09 08:24:09',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'RANJITH KAHINGALA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '53492.87',
                'excess_amount' => '-35451.78',
                'settlement_no' => 'ST3882',
                'active' => 1,
                'created_at' => '2024-02-27 03:08:05',
                'updated_at' => '2025-05-13 09:04:56',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'W A RUSITH DILAN',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '6591.12',
                'excess_amount' => '-3830.78',
                'settlement_no' => 'ST3881',
                'active' => 1,
                'created_at' => '2024-02-27 03:08:35',
                'updated_at' => '2025-05-05 08:19:33',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'KRISHAN RANATHUNGA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '3991.93',
                'excess_amount' => '-2921.01',
                'settlement_no' => 'ST125',
                'active' => 1,
                'created_at' => '2024-02-27 03:09:16',
                'updated_at' => '2024-10-09 10:49:41',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'M M AMILA DASANTHA KUMARA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '1254368.06',
                'excess_amount' => '-47075.81',
                'settlement_no' => 'ST3877',
                'active' => 1,
                'created_at' => '2024-02-27 03:09:46',
                'updated_at' => '2025-04-09 08:55:05',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'W A AVIDU OSHAN',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '123040.25',
                'excess_amount' => '-91043.43',
                'settlement_no' => 'ST3867',
                'active' => 1,
                'created_at' => '2024-02-27 03:10:21',
                'updated_at' => '2025-04-08 11:14:44',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'M P NANDASENA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '134155.11',
                'excess_amount' => '-77193.05',
                'settlement_no' => 'ST3874',
                'active' => 1,
                'created_at' => '2024-02-27 03:10:53',
                'updated_at' => '2025-04-09 08:27:23',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'S K K SAMPATH PERERA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '80945.14',
                'excess_amount' => '-53893.71',
                'settlement_no' => 'ST3878',
                'active' => 1,
                'created_at' => '2024-02-27 03:11:29',
                'updated_at' => '2025-05-05 07:58:59',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'SUDESH ARUNA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '555.66',
                'excess_amount' => '0.00',
                'settlement_no' => 'ST6',
                'active' => 0,
                'created_at' => '2024-02-27 03:12:03',
                'updated_at' => '2024-09-09 06:43:26',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'OFFICE SALE',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-02-25',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '5491.00',
                'excess_amount' => '-4096.00',
                'settlement_no' => 'ST3866',
                'active' => 1,
                'created_at' => '2024-02-28 11:33:37',
                'updated_at' => '2025-04-08 11:12:23',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'CHAMINDA DARMASIRI',
                'cnic' => '0',
                'address' => 'C/373 THANAKOLAWATHTHA HAKBELLAWAKA',
                'dob' => '2024-03-04',
                'landline' => '0',
                'mobile' => '0773454785',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '11043.64',
                'excess_amount' => '-80.06',
                'settlement_no' => 'ST2862',
                'active' => 1,
                'created_at' => '2024-03-04 11:33:21',
                'updated_at' => '2024-12-27 10:43:21',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'SAMANTHA',
                'cnic' => '0',
                'address' => '0',
                'dob' => '2024-03-12',
                'landline' => '0',
                'mobile' => '0',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '444366.78',
                'excess_amount' => '0.00',
                'settlement_no' => 'ST95',
                'active' => 0,
                'created_at' => '2024-03-12 13:24:06',
                'updated_at' => '2024-09-09 06:43:26',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'K A SANGEETH CHINTHAKA',
                'cnic' => '198105900050',
                'address' => '84/3 C SAWMYA SANDALLA ARAKAWILA HANDA PANAGODA',
                'dob' => '2028-01-02',
                'landline' => '0',
                'mobile' => '0711133342',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '59456.57',
                'excess_amount' => '-68245.27',
                'settlement_no' => 'ST3875',
                'active' => 1,
                'created_at' => '2024-04-06 10:51:51',
                'updated_at' => '2025-04-09 08:30:51',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'K G PRABATH SURANGA',
                'cnic' => '0',
                'address' => '275/6  KORATUWA POHAMMULLA GODAWA KAMBURU PITIYA',
                'dob' => '1981-10-12',
                'landline' => '0',
                'mobile' => '0742427766',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '40183.75',
                'excess_amount' => '-29422.04',
                'settlement_no' => 'ST1561',
                'active' => 1,
                'created_at' => '2024-04-24 06:23:32',
                'updated_at' => '2024-09-09 06:43:26',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'Other Income',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-05-15',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '0.00',
                'excess_amount' => '0.00',
                'settlement_no' => NULL,
                'active' => 1,
                'created_at' => '2024-05-15 08:21:58',
                'updated_at' => '2024-09-09 06:43:26',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'D K G PIYAL WEERASENA',
                'cnic' => '1',
                'address' => '1',
                'dob' => '2024-07-08',
                'landline' => '1',
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '14361.48',
                'excess_amount' => '-5315.10',
                'settlement_no' => 'ST2077',
                'active' => 1,
                'created_at' => '2024-07-08 05:31:06',
                'updated_at' => '2024-11-18 17:37:54',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'R M PREDEEP',
                'cnic' => '0',
                'address' => '0',
                'dob' => '2024-08-13',
                'landline' => '0',
                'mobile' => '0',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'percentage',
                'commission_ap' => '0.00',
                'short_amount' => '0.00',
                'excess_amount' => '-22.44',
                'settlement_no' => 'ST1544',
                'active' => 1,
                'created_at' => '2024-08-13 06:28:25',
                'updated_at' => '2024-09-09 06:43:26',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'Ruwanpura Sankha Chamara',
                'cnic' => '870074654V',
                'address' => '456, High Level Road',
                'dob' => '1987-01-07',
                'landline' => '074248540',
                'mobile' => '0763483719',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '5140.78',
                'excess_amount' => '-10058.24',
                'settlement_no' => 'ST3166',
                'active' => 1,
                'created_at' => '2024-09-09 06:43:26',
                'updated_at' => '2025-01-27 10:54:07',
                'dashboard_settings' => NULL,
                'is_default' => 1,
                'can_fullscreen' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'JAGATH KUMARA',
                'cnic' => '683130982V',
                'address' => 'Wataraka, Padukka',
                'dob' => '0001-12-01',
                'landline' => NULL,
                'mobile' => '1',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '6127.29',
                'excess_amount' => '-21.14',
                'settlement_no' => 'ST2041',
                'active' => 1,
                'created_at' => '2024-10-08 09:46:54',
                'updated_at' => '2024-11-18 17:28:23',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'ROSHAN KUMARA',
                'cnic' => '791030374V',
                'address' => '176/1A, PAMUNUGAMA. ALUBOMULLA',
                'dob' => '0001-11-01',
                'landline' => NULL,
                'mobile' => '0757440417',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'percentage',
                'commission_ap' => '0.00',
                'short_amount' => '27092.03',
                'excess_amount' => '-30137.13',
                'settlement_no' => 'ST3864',
                'active' => 1,
                'created_at' => '2024-10-11 12:18:21',
                'updated_at' => '2025-04-08 11:09:20',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'KAPILA KUMARA',
                'cnic' => '950732849V',
                'address' => 'Pinnaketiya, Urubokka.',
                'dob' => '0001-03-01',
                'landline' => NULL,
                'mobile' => '0717488593',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'none',
                'commission_ap' => '0.00',
                'short_amount' => '124349.47',
                'excess_amount' => '-98765.94',
                'settlement_no' => 'ST3860',
                'active' => 1,
                'created_at' => '2024-11-04 12:08:06',
                'updated_at' => '2025-04-08 11:04:11',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'business_id' => 4,
                'location_id' => 2,
                'pump_id' => 0,
                'name' => 'W.M.A. KUMARA WICKRAMASINGHE',
                'cnic' => '691880168V',
                'address' => 'RANDIWELA, MAWANELLA.',
                'dob' => '1969-06-07',
                'landline' => NULL,
                'mobile' => '0777672851',
                'assigned_pump_id' => 0,
                'status' => 1,
                'commission_type' => 'percentage',
                'commission_ap' => '0.00',
                'short_amount' => '7634.62',
                'excess_amount' => '-3395.64',
                'settlement_no' => 'ST3858',
                'active' => 1,
                'created_at' => '2025-01-23 08:51:29',
                'updated_at' => '2025-04-08 10:58:46',
                'dashboard_settings' => NULL,
                'is_default' => 0,
                'can_fullscreen' => 1,
            ),
        ));
        
        
    }
}