<?php
return [
    ['name'=>'egg.dashboard.view','group'=>'Dashboard','label'=>'View dashboard'],
    ['name'=>'egg.flocks.view','group'=>'Flocks','label'=>'View flocks'],
    ['name'=>'egg.flocks.create','group'=>'Flocks','label'=>'Create flocks'],
    ['name'=>'egg.production.view','group'=>'Production','label'=>'View production'],
    ['name'=>'egg.production.create','group'=>'Production','label'=>'Add production'],
    ['name'=>'egg.grading.view','group'=>'Grading','label'=>'View grading'],
    ['name'=>'egg.grading.create','group'=>'Grading','label'=>'Post grading'],
    ['name'=>'egg.stock.view','group'=>'Stock','label'=>'View stock'],
    ['name'=>'egg.sales.view','group'=>'Sales','label'=>'View sales'],
    ['name'=>'egg.sales.create','group'=>'Sales','label'=>'Create sales'],
    ['name'=>'egg.purchases.view','group'=>'Purchases','label'=>'View purchases'],
    ['name'=>'egg.purchases.create','group'=>'Purchases','label'=>'Create purchases'],
    ['name'=>'egg.transfers.view','group'=>'Transfers','label'=>'View transfers'],
    ['name'=>'egg.transfers.create','group'=>'Transfers','label'=>'Create transfers'],
    ['name'=>'egg.adjustments.view','group'=>'Adjustments','label'=>'View adjustments'],
    ['name'=>'egg.adjustments.create','group'=>'Adjustments','label'=>'Create adjustments'],
    ['name'=>'egg.settings.view','group'=>'Settings','label'=>'View settings'],
    ['name'=>'egg.settings.manage','group'=>'Settings','label'=>'Manage settings'],
    ['name'=>'egg.integrations.view','group'=>'Integrations','label'=>'View integration outbox'],
    ['name'=>'egg.share','group'=>'Sharing','label'=>'Share/print/send reports'],
    ['name'=>'egg.reports.production','group'=>'Reports','label'=>'Production report'],
    ['name'=>'egg.reports.stock','group'=>'Reports','label'=>'Stock report'],
    ['name'=>'egg.reports.sales','group'=>'Reports','label'=>'Sales report'],
    ['name'=>'egg.reports.purchases','group'=>'Reports','label'=>'Purchase report'],
    ['name'=>'egg.reports.movements','group'=>'Reports','label'=>'Movement report'],
    ['name'=>'egg.reports.wastage','group'=>'Reports','label'=>'Wastage report'],
    ['name'=>'egg.reports.audit','group'=>'Reports','label'=>'Audit report'],
    ['name'=>'egg.product-mappings.view','group'=>'Products New Integration','label'=>'View product mappings'],
    ['name'=>'egg.product-mappings.manage','group'=>'Products New Integration','label'=>'Manage product mappings'],
];
