-- Simple Audit tenant uninstall. Review before running in production.
SET FOREIGN_KEY_CHECKS=0;
DROP TRIGGER IF EXISTS `sau_vld_ai`;
DROP TRIGGER IF EXISTS `sau_vld_au`;
DROP TRIGGER IF EXISTS `sau_vld_ad`;
DROP TRIGGER IF EXISTS `sau_transactions_ai`;
DROP TRIGGER IF EXISTS `sau_transactions_au`;
DROP TRIGGER IF EXISTS `sau_transactions_ad`;
DROP TRIGGER IF EXISTS `sau_purchase_lines_ai`;
DROP TRIGGER IF EXISTS `sau_purchase_lines_au`;
DROP TRIGGER IF EXISTS `sau_purchase_lines_ad`;
DROP TRIGGER IF EXISTS `sau_stock_adjustment_lines_ai`;
DROP TRIGGER IF EXISTS `sau_stock_adjustment_lines_au`;
DROP TRIGGER IF EXISTS `sau_stock_adjustment_lines_ad`;
DROP TRIGGER IF EXISTS `sau_transaction_payments_ai`;
DROP TRIGGER IF EXISTS `sau_transaction_payments_au`;
DROP TRIGGER IF EXISTS `sau_transaction_payments_ad`;
DROP TRIGGER IF EXISTS `sau_account_transactions_ai`;
DROP TRIGGER IF EXISTS `sau_account_transactions_au`;
DROP TRIGGER IF EXISTS `sau_account_transactions_ad`;
DROP TRIGGER IF EXISTS `sau_contact_ledgers_ai`;
DROP TRIGGER IF EXISTS `sau_contact_ledgers_au`;
DROP TRIGGER IF EXISTS `sau_contact_ledgers_ad`;
DROP TABLE IF EXISTS `sau_activity_logs`;
DROP TABLE IF EXISTS `sau_report_shares`;
DROP TABLE IF EXISTS `sau_stock_snapshots`;
DROP TABLE IF EXISTS `sau_change_events`;
DROP TABLE IF EXISTS `sau_settings`;
SET FOREIGN_KEY_CHECKS=1;
