<?php
namespace Modules\ProductsNew\Services\InventoryIntelligence;
use Modules\ProductsNew\Entities\StockIntelligenceSnapshot;
use Modules\ProductsNew\Utilities\ProductsNewTenantGuard;
class StockIntelligenceService
{
    public function summary(array $filters=[]): array { $businessId=ProductsNewTenantGuard::businessId($filters['business_id']??null); $base=StockIntelligenceSnapshot::where('business_id',$businessId); return ['dead_stock'=>(clone $base)->where('movement_status','dead')->count(),'slow_moving'=>(clone $base)->where('movement_status','slow')->count(),'fast_moving'=>(clone $base)->where('movement_status','fast')->count(),'negative_stock'=>(clone $base)->where('current_stock','<',0)->count(),'high_risk'=>(clone $base)->where('risk_level','high')->count()]; }
    public function snapshots(array $filters=[]) { $businessId=ProductsNewTenantGuard::businessId($filters['business_id']??null); return StockIntelligenceSnapshot::where('business_id',$businessId)->latest('snapshot_date')->paginate($filters['per_page']??25); }
    public function recordSnapshot(array $data): StockIntelligenceSnapshot { $businessId=ProductsNewTenantGuard::businessId($data['business_id']??null); $current=(float)($data['current_stock']??0); $age=(int)($data['stock_age_days']??0); $status=$current<=0?'zero_or_negative':($age>180?'dead':($age>90?'slow':'normal')); $risk=$current<0||$age>180?'high':($age>90?'medium':'low'); return StockIntelligenceSnapshot::create(['business_id'=>$businessId,'location_id'=>$data['location_id']??null,'product_id'=>$data['product_id'],'variation_id'=>$data['variation_id']??null,'snapshot_date'=>$data['snapshot_date']??now()->toDateString(),'current_stock'=>$current,'available_stock'=>$data['available_stock']??$current,'reserved_stock'=>$data['reserved_stock']??0,'on_order_qty'=>$data['on_order_qty']??0,'in_transit_qty'=>$data['in_transit_qty']??0,'stock_age_days'=>$age,'last_sale_at'=>$data['last_sale_at']??null,'last_purchase_at'=>$data['last_purchase_at']??null,'movement_status'=>$data['movement_status']??$status,'recommended_action'=>$data['recommended_action']??($status==='dead'?'clearance':'monitor'),'risk_level'=>$data['risk_level']??$risk,'payload'=>$data['payload']??null,'created_by'=>auth()->id()]); }
}
