@extends('pumperdashboardnew::layouts.admin')
@section('title',$labels[$report] ?? 'Reports')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Pumper Dashboard Reports</div><h1>{{ $labels[$report] ?? 'Reports' }}</h1><p>All rows are read from PONE-owned tables and may be filtered by business, location, operator and period.</p></div><div class="pone-actions">@can('pumper_dashboard_new.reports.print')<button class="pone-btn pone-btn-primary" data-print>Print</button>@endcan @can('pumper_dashboard_new.reports.export')<a class="pone-btn pone-btn-success" href="{{ route('pumper-dashboard-new.admin.reports.export',['report'=>$report]+request()->query()) }}">CSV Export</a>@endcan</div></div>
<div class="pone-admin-nav pone-no-print">@foreach($availableReports as $key=>$label)<a id="pone-report-{{ $key }}-tab" class="{{ $report===$key?'is-active':'' }}" href="{{ route('pumper-dashboard-new.admin.reports.index',$key) }}">{{ $label }}</a>@endforeach</div>
<div class="pone-panel pone-no-print"><div class="pone-panel-body"><form method="get" action="{{ route('pumper-dashboard-new.admin.reports.index',$report) }}"><div class="pone-form-grid">
<div class="pone-field pone-col-2"><label>From</label><input name="from" type="date" value="{{ $filters['from']??'' }}"></div><div class="pone-field pone-col-2"><label>To</label><input name="to" type="date" value="{{ $filters['to']??'' }}"></div>
<div class="pone-field pone-col-2"><label>Location</label><select name="location_id" data-search-select><option value="">All Locations</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((int)($filters['location_id']??0)===(int)$location->id)>{{ $location->name }}</option>@endforeach</select></div>
<div class="pone-field pone-col-2"><label>PD Operator</label><select name="operator_profile_id" data-search-select><option value="">All Operators</option>@foreach($operators as $operator)<option value="{{ $operator->id }}" @selected((int)($filters['operator_profile_id']??0)===(int)$operator->id)>{{ $operator->display_name }}</option>@endforeach</select></div>
@if($report==='payments')<div class="pone-field pone-col-2"><label>Payment Type</label><select name="payment_type"><option value="">All Types</option>@foreach(['cash','card','cheque','credit','other','shortage','excess'] as $type)<option value="{{ $type }}" @selected(($filters['payment_type']??'')===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div>@endif
@if($report==='print-logs')<div class="pone-field pone-col-2"><label>Printable Type</label><select name="printable_type"><option value="">All Types</option>@foreach(['payment','credit_sale','other_sale','unload_stock','daily_collection','shift'] as $type)<option value="{{ $type }}" @selected(($filters['printable_type']??'')===$type)>{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select></div>@endif
@if($report==='audit')<div class="pone-field pone-col-2"><label>Action Contains</label><input name="action" value="{{ $filters['action']??'' }}"></div>@endif
@if(in_array($report,['shifts','payments','other-sales','unloads','day-entries','collections','ledger','shortages','commissions'],true))<div class="pone-field pone-col-2"><label>Status</label><input name="status" value="{{ $filters['status']??'' }}" placeholder="All"></div>@endif
<div class="pone-field pone-col-1"><label>Limit</label><select name="limit">@foreach([100,250,500,1000,2000] as $limit)<option value="{{ $limit }}" @selected((int)($filters['limit']??500)===$limit)>{{ $limit }}</option>@endforeach</select></div><div class="pone-field pone-col-1" style="align-self:end"><button class="pone-btn pone-btn-primary pone-btn-block">Apply</button></div><div class="pone-field pone-col-1" style="align-self:end"><a class="pone-btn pone-btn-light pone-btn-block" href="{{ route('pumper-dashboard-new.admin.reports.index',$report) }}">Reset</a></div>
</div></form></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>{{ $labels[$report] ?? 'Report' }}</h2><span class="pone-badge pone-badge-open">{{ $rows->count() }} records</span></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0">
@switch($report)
@case('shifts')
<table class="pone-table"><thead><tr><th>Shift</th><th>Operator</th><th>Location</th><th>Opened</th><th>Closed</th><th class="pone-text-right">Meter Sales</th><th class="pone-text-right">Other Sales</th><th class="pone-text-right">Expected</th><th class="pone-text-right">Payments</th><th class="pone-text-right">Shortage</th><th class="pone-text-right">Excess</th><th>Status</th><th>Sync</th></tr></thead><tbody>@forelse($rows as $row)<tr><td><a href="{{ route('pumper-dashboard-new.admin.shifts.show',$row) }}"><strong>{{ $row->shift_number }}</strong></a></td><td>{{ $row->operatorProfile->display_name ?? ('Operator '.$row->pd_operator_id) }}</td><td>{{ $row->location_id ?: '-' }}</td><td>{{ optional($row->opened_at)->format('Y-m-d H:i') }}</td><td>{{ optional($row->closed_at)->format('Y-m-d H:i') ?: '-' }}</td><td class="pone-text-right">{{ number_format((float)$row->meter_sales_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->other_sales_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->expected_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->payments_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->shortage_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->excess_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td></tr>@empty<tr><td colspan="13" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('payments')
<table class="pone-table"><thead><tr><th>Payment No.</th><th>Shift</th><th>Date/Time</th><th>Type</th><th>Customer</th><th>Reference</th><th>Slip / Order</th><th class="pone-text-right">Amount</th><th>Status</th><th>Sync</th><th>Edited</th><th>Prints</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->payment_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ optional($row->transaction_at)->format('Y-m-d H:i') }}</td><td>{{ ucfirst($row->payment_type) }}</td><td>{{ $row->customer_id ?: '-' }}</td><td>{{ $row->reference_no ?: '-' }}</td><td>{{ $row->slip_no ?: ($row->creditSale->order_number ?? '-') }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td><td>{{ $row->edited_at ? optional($row->edited_at)->format('Y-m-d H:i') : '-' }}</td><td>{{ $row->printed_count }}</td></tr>@empty<tr><td colspan="12" class="pone-empty">No records.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="7" class="pone-text-right">Total</th><th class="pone-text-right">{{ number_format((float)$rows->where('status','confirmed')->sum('amount'),4) }}</th><th colspan="4"></th></tr></tfoot></table>
@break
@case('meters')
<table class="pone-table"><thead><tr><th>Shift</th><th>Pump ID</th><th>Product ID</th><th>Closed</th><th class="pone-text-right">Opening</th><th class="pone-text-right">Closing</th><th class="pone-text-right">Testing</th><th class="pone-text-right">Sold Qty</th><th class="pone-text-right">Unit Price</th><th class="pone-text-right">Amount</th><th>Sync</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->pump_id }}</td><td>{{ $row->product_id ?: '-' }}</td><td>{{ optional($row->closed_at)->format('Y-m-d H:i') }}</td><td class="pone-text-right">{{ number_format((float)$row->opening_meter,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->closing_meter,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->testing_quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->sold_quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->unit_price,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td></tr>@empty<tr><td colspan="11" class="pone-empty">No records.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="7" class="pone-text-right">Totals</th><th class="pone-text-right">{{ number_format((float)$rows->sum('sold_quantity'),3) }}</th><th></th><th class="pone-text-right">{{ number_format((float)$rows->sum('amount'),4) }}</th><th></th></tr></tfoot></table>
@break
@case('other-sales')
<table class="pone-table"><thead><tr><th>Sale No.</th><th>Shift</th><th>Date/Time</th><th>Payment</th><th>Customer</th><th>Lines</th><th class="pone-text-right">Gross</th><th class="pone-text-right">Discount</th><th class="pone-text-right">Net</th><th>Status</th><th>Sync</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->sale_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ optional($row->sale_at)->format('Y-m-d H:i') }}</td><td>{{ ucfirst($row->payment_method) }}</td><td>{{ $row->customer_id ?: '-' }}</td><td>{{ $row->lines->count() }}</td><td class="pone-text-right">{{ number_format((float)$row->gross_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->discount_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->net_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td></tr>@empty<tr><td colspan="11" class="pone-empty">No records.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="8" class="pone-text-right">Total</th><th class="pone-text-right">{{ number_format((float)$rows->where('status','confirmed')->sum('net_amount'),4) }}</th><th colspan="2"></th></tr></tfoot></table>
@break
@case('unloads')
<table class="pone-table"><thead><tr><th>Receipt No.</th><th>Shift</th><th>Date/Time</th><th>Supplier</th><th>Bill No.</th><th>Lines</th><th class="pone-text-right">Quantity</th><th class="pone-text-right">Amount</th><th>Status</th><th>Sync</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->receipt_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ optional($row->unloaded_at)->format('Y-m-d H:i') }}</td><td>{{ $row->supplier_id ?: '-' }}</td><td>{{ $row->bill_number ?: '-' }}</td><td>{{ $row->lines->count() }}</td><td class="pone-text-right">{{ number_format((float)$row->total_quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->total_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td></tr>@empty<tr><td colspan="10" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('day-entries')
<table class="pone-table"><thead><tr><th>Date/Time</th><th>Shift</th><th>Type</th><th>Pump</th><th>Reference</th><th>Settlement</th><th class="pone-text-right">Quantity</th><th class="pone-text-right">Amount</th><th>Note</th><th>Status</th><th>Sync</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ optional($row->entry_at)->format('Y-m-d H:i') }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ ucfirst($row->entry_type) }}</td><td>{{ $row->assignment->pump_id ?? '-' }}</td><td>{{ $row->reference_no ?: '-' }}</td><td>{{ $row->settlement_no ?: '-' }}</td><td class="pone-text-right">{{ number_format((float)$row->quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td class="pone-wrap">{{ $row->note ?: '-' }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td><span class="pone-badge pone-badge-{{ $row->integration_status }}">{{ $row->integration_status }}</span></td></tr>@empty<tr><td colspan="11" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('collections')
<table class="pone-table"><thead><tr><th>Collection No.</th><th>Shift</th><th>Operator</th><th>Date/Time</th><th class="pone-text-right">Expected</th><th class="pone-text-right">Cash</th><th class="pone-text-right">Card</th><th class="pone-text-right">Cheque</th><th class="pone-text-right">Credit</th><th class="pone-text-right">Other</th><th class="pone-text-right">Declared</th><th class="pone-text-right">Difference</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->collection_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->operator_profile_id }}</td><td>{{ optional($row->collection_at)->format('Y-m-d H:i') }}</td><td class="pone-text-right">{{ number_format((float)$row->expected_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->cash_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->card_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->cheque_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->credit_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->other_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->declared_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->difference_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td></tr>@empty<tr><td colspan="13" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('ledger')
<table class="pone-table"><thead><tr><th>Date/Time</th><th>Operator</th><th>Shift</th><th>Reference</th><th>Description</th><th>Source</th><th class="pone-text-right">Debit</th><th class="pone-text-right">Credit</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ optional($row->entry_at)->format('Y-m-d H:i') }}</td><td>{{ $row->operatorProfile->display_name ?? $row->operator_profile_id }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->reference_no ?: '-' }}</td><td class="pone-wrap">{{ $row->description }}</td><td>{{ str_replace('_',' ',ucfirst($row->source_type)) }}</td><td class="pone-text-right">{{ number_format((float)$row->debit,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->credit,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td></tr>@empty<tr><td colspan="9" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('shortages')
<table class="pone-table"><thead><tr><th>Recovery No.</th><th>Operator</th><th>Shift</th><th>Date</th><th>Method</th><th>Reference</th><th class="pone-text-right">Amount</th><th>Note</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->recovery_number }}</td><td>{{ $row->operatorProfile->display_name ?? $row->operator_profile_id }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ optional($row->recovery_date)->format('Y-m-d') }}</td><td>{{ ucfirst($row->payment_method) }}</td><td>{{ $row->reference_no ?: '-' }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td class="pone-wrap">{{ $row->note ?: '-' }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td></tr>@empty<tr><td colspan="9" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('commissions')
<table class="pone-table"><thead><tr><th>Commission No.</th><th>Operator</th><th>Shift</th><th>Date</th><th>Type</th><th class="pone-text-right">Base Excess</th><th class="pone-text-right">Rate</th><th class="pone-text-right">Commission</th><th>Note</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->commission_number }}</td><td>{{ $row->operatorProfile->display_name ?? $row->operator_profile_id }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ optional($row->commission_date)->format('Y-m-d') }}</td><td>{{ ucfirst($row->commission_type) }}</td><td class="pone-text-right">{{ number_format((float)$row->base_excess_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->commission_rate,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->commission_amount,4) }}</td><td class="pone-wrap">{{ $row->note ?: '-' }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td></tr>@empty<tr><td colspan="10" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('print-logs')
<table class="pone-table"><thead><tr><th>Printed At</th><th>Type</th><th>Record</th><th>Template</th><th>Paper</th><th>Copy</th><th>Shift</th><th>Operator</th><th>User</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ optional($row->printed_at)->format('Y-m-d H:i:s') }}</td><td>{{ ucwords(str_replace('_',' ',$row->printable_type)) }}</td><td>{{ $row->printable_id }}</td><td>{{ $row->template_name }}</td><td>{{ $row->paper_size }}</td><td><span class="pone-badge pone-badge-{{ $row->copy_type }}">{{ $row->copy_type }}</span></td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->operator_profile_id ?: '-' }}</td><td>{{ $row->printed_by ?: '-' }}</td></tr>@empty<tr><td colspan="9" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@case('audit')
<table class="pone-table"><thead><tr><th>Date/Time</th><th>Action</th><th>Entity</th><th>Entity ID</th><th>Business</th><th>Location</th><th>Operator</th><th>User</th><th>IP</th><th>Before</th><th>After</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ optional($row->created_at)->format('Y-m-d H:i:s') }}</td><td><strong>{{ $row->action }}</strong></td><td>{{ $row->entity_type }}</td><td>{{ $row->entity_id ?: '-' }}</td><td>{{ $row->business_id }}</td><td>{{ $row->location_id ?: '-' }}</td><td>{{ $row->operator_profile_id ?: '-' }}</td><td>{{ $row->user_id ?: '-' }}</td><td>{{ $row->ip_address ?: '-' }}</td><td class="pone-wrap"><code>{{ json_encode($row->before_data,JSON_UNESCAPED_SLASHES) }}</code></td><td class="pone-wrap"><code>{{ json_encode($row->after_data,JSON_UNESCAPED_SLASHES) }}</code></td></tr>@empty<tr><td colspan="11" class="pone-empty">No records.</td></tr>@endforelse</tbody></table>
@break
@default
<div class="pone-empty">Unsupported report.</div>
@endswitch
</div></div></div>
@endsection
