@extends('stocktakingnew::layouts.app')
@section('stk_title','Stock Taking Settings')
@section('stk_subtitle','Numbering, decimals, approval rules, inventory posting and communication gateways.')
@section('stk_content')
<form method="post" action="{{ route('stock-taking-new.settings.update') }}" class="stk-form">@csrf @method('PUT')<div class="stk-form-grid"><section class="stk-card stk-card-accent blue"><div class="stk-card-header"><div><h3><span class="stk-square-icon"><i class="fa fa-sliders"></i></span> General Rules</h3></div></div><div class="stk-card-body stk-fields"><div><label>Number Prefix</label><input name="number_prefix" value="{{ old('number_prefix',$values['number_prefix']) }}" class="form-control"></div><div><label>Default Count Mode</label><select name="default_count_mode" class="form-control"><option value="blind" @selected($values['default_count_mode']==='blind')>Blind</option><option value="open" @selected($values['default_count_mode']==='open')>Open</option></select></div><div><label>Quantity Decimals</label><input type="number" name="quantity_decimals" value="{{ $values['quantity_decimals'] }}" class="form-control"></div><div><label>Amount Decimals</label><input type="number" name="amount_decimals" value="{{ $values['amount_decimals'] }}" class="form-control"></div><div><label>Share Link Expiry Hours</label><input type="number" name="share_link_expiry_hours" value="{{ $values['share_link_expiry_hours'] }}" class="form-control"></div><label class="stk-switch-row"><input type="checkbox" name="require_approval" value="1" @checked(filter_var($values['require_approval'],FILTER_VALIDATE_BOOLEAN))><span>Require approval before posting</span></label><label class="stk-switch-row"><input type="checkbox" name="require_recount_for_variance" value="1" @checked(filter_var($values['require_recount_for_variance'],FILTER_VALIDATE_BOOLEAN))><span>Require recount for variance</span></label><label class="stk-switch-row"><input type="checkbox" name="post_to_shared_inventory" value="1" @checked(filter_var($values['post_to_shared_inventory'],FILTER_VALIDATE_BOOLEAN))><span>Update shared location/store stock when posted</span></label></div></section>
<section class="stk-card stk-card-accent green"><div class="stk-card-header"><div><h3><span class="stk-square-icon green"><i class="fa fa-comment"></i></span> SMS Gateway</h3></div></div><div class="stk-card-body stk-fields"><div class="wide"><label>Endpoint URL</label><input name="sms_endpoint" value="{{ $values['sms_endpoint'] }}" class="form-control" placeholder="https://gateway.example/send"></div><div class="wide"><label>Bearer Token</label><input type="password" name="sms_token" value="" class="form-control" placeholder="Leave blank to keep the saved token"></div><div><label>Sender ID</label><input name="sms_sender_id" value="{{ $values['sms_sender_id'] }}" class="form-control"></div><div class="wide stk-hint">Without an endpoint, the module creates a device SMS link for manual sending.</div></div></section>
<section class="stk-card stk-card-accent purple"><div class="stk-card-header"><div><h3><span class="stk-square-icon purple"><i class="fa fa-whatsapp"></i></span> WhatsApp Gateway</h3></div></div><div class="stk-card-body stk-fields"><div class="wide"><label>Endpoint URL</label><input name="whatsapp_endpoint" value="{{ $values['whatsapp_endpoint'] }}" class="form-control"></div><div><label>Phone Number ID</label><input name="whatsapp_phone_number_id" value="{{ $values['whatsapp_phone_number_id'] }}" class="form-control"></div><div class="wide"><label>Bearer Token</label><input type="password" name="whatsapp_token" value="" class="form-control" placeholder="Leave blank to keep the saved token"></div><div class="wide stk-hint">Without API settings, the module generates a WhatsApp Web/mobile send link.</div></div></section>
<section class="stk-card stk-card-accent orange"><div class="stk-card-header"><div><h3><span class="stk-square-icon orange"><i class="fa fa-envelope"></i></span> Email</h3></div></div><div class="stk-card-body"><p>Email uses the application's configured Laravel mail transport. Configure SMTP in the main environment settings.</p><div class="stk-hint"><i class="fa fa-lock"></i> Gateway tokens are encrypted in the tenant database.</div></div></section></div><div class="stk-sticky-actions"><button class="stk-btn stk-btn-primary"><i class="fa fa-save"></i> Save Settings</button></div></form>
@endsection
