@extends('pumperdashboardnew::layouts.operator')
@section('title','Pump Assignment History')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Pump Audit Trail</div><h1>{{ $pump->pump_name ?? $pump->pump_no ?? ('Pump '.$assignment->pump_id) }}</h1><p>Every assignment, confirmation and meter event recorded by Pumper Dashboard-New.</p></div><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.pumps.index') }}">Back</a></div>
<div class="pone-grid pone-grid-4" style="margin-bottom:16px">
<div class="pone-stat"><div class="pone-stat-label">Opening Meter</div><div class="pone-stat-value">{{ number_format((float)$assignment->opening_meter,3) }}</div></div>
<div class="pone-stat"><div class="pone-stat-label">Current Meter</div><div class="pone-stat-value">{{ number_format((float)$assignment->current_meter,3) }}</div></div>
<div class="pone-stat"><div class="pone-stat-label">Closing Meter</div><div class="pone-stat-value">{{ $assignment->closing_meter===null?'-':number_format((float)$assignment->closing_meter,3) }}</div></div>
<div class="pone-stat"><div class="pone-stat-label">Sold Quantity</div><div class="pone-stat-value">{{ number_format((float)$assignment->sold_quantity,3) }}</div><div class="pone-stat-note">Testing {{ number_format((float)$assignment->testing_quantity,3) }}</div></div>
</div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Assignment Events</h2><span class="pone-badge pone-badge-{{ $assignment->status }}">{{ $assignment->status }}</span></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>Date/Time</th><th>Event</th><th class="pone-text-right">Meter</th><th class="pone-text-right">Testing</th><th>Note</th></tr></thead><tbody>@forelse($assignment->events as $event)<tr><td>{{ optional($event->occurred_at)->format('Y-m-d H:i:s') }}</td><td><span class="pone-badge pone-badge-{{ $event->event_type }}">{{ str_replace('_',' ',$event->event_type) }}</span></td><td class="pone-text-right">{{ $event->meter_value===null?'-':number_format((float)$event->meter_value,3) }}</td><td class="pone-text-right">{{ $event->testing_quantity===null?'-':number_format((float)$event->testing_quantity,3) }}</td><td class="pone-wrap">{{ $event->note ?: '-' }}</td></tr>@empty<tr><td colspan="5" class="pone-empty">No events recorded.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Meter Readings</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>Date/Time</th><th>Type</th><th class="pone-text-right">Meter</th><th class="pone-text-right">Testing</th><th class="pone-text-right">Price</th></tr></thead><tbody>@forelse($assignment->readings as $reading)<tr><td>{{ optional($reading->recorded_at)->format('Y-m-d H:i:s') }}</td><td>{{ ucfirst($reading->reading_type) }}</td><td class="pone-text-right">{{ number_format((float)$reading->meter_value,3) }}</td><td class="pone-text-right">{{ number_format((float)$reading->testing_quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$reading->unit_price,4) }}</td></tr>@empty<tr><td colspan="5" class="pone-empty">No readings recorded.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
