<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        $this->settings(); $this->masters(); $this->items(); $this->inventory();
        $this->purchases(); $this->production(); $this->sales(); $this->documents(); $this->seedDefaults();
    }

    private function scoped(Blueprint $t, bool $location = true, bool $store = true): void
    {
        $t->unsignedBigInteger('business_id')->index();
        if ($location) $t->unsignedBigInteger('location_id')->nullable()->index();
        if ($store) $t->unsignedBigInteger('store_id')->nullable()->index();
        $t->unsignedBigInteger('created_by')->nullable()->index();
        $t->unsignedBigInteger('updated_by')->nullable()->index();
        $t->timestamps(); $t->softDeletes();
    }

    private function create(string $name, callable $callback): void
    {
        if (! Schema::hasTable($name)) Schema::create($name, $callback);
    }

    private function settings(): void
    {
        $this->create('ran_settings', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('key',120);$t->json('value')->nullable();$t->string('value_type',30)->default('string');$t->unique(['business_id','key'],'ran_settings_business_key_unique');});
        $this->create('ran_number_sequences', function(Blueprint $t){$t->id();$this->scoped($t,true,false);$t->string('document_type',60);$t->string('prefix',20)->nullable();$t->unsignedBigInteger('next_number')->default(1);$t->unsignedInteger('padding')->default(5);$t->string('reset_period',20)->default('never');$t->date('last_reset_on')->nullable();$t->unique(['business_id','location_id','document_type'],'ran_sequence_scope_unique');});
    }

    private function masters(): void
    {
        $this->create('ran_metals', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('code',30);$t->string('name',100);$t->string('symbol',20)->nullable();$t->decimal('default_density',14,6)->nullable();$t->boolean('is_active')->default(true);$t->unique(['business_id','code'],'ran_metals_code_unique');});
        $this->create('ran_purities', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->unsignedBigInteger('metal_id')->index();$t->string('code',30);$t->string('name',100);$t->decimal('fineness',10,6);$t->decimal('karat',8,3)->nullable();$t->boolean('is_active')->default(true);$t->unique(['business_id','metal_id','code'],'ran_purities_code_unique');});
        $this->create('ran_gemstones', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('code',30);$t->string('name',100);$t->string('category',60)->nullable();$t->string('colour',60)->nullable();$t->string('unit',20)->default('carat');$t->boolean('is_active')->default(true);$t->unique(['business_id','code'],'ran_gemstones_code_unique');});
        $this->create('ran_artisans', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('artisan_code',30);$t->string('name',150);$t->unsignedBigInteger('supplier_contact_id')->nullable()->index();$t->string('phone',40)->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->string('speciality',120)->nullable();$t->decimal('opening_balance',22,4)->default(0);$t->boolean('is_active')->default(true);$t->unique(['business_id','artisan_code'],'ran_artisans_code_unique');});
        $this->create('ran_designs', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('design_code',40);$t->string('name',150);$t->string('category',100)->nullable();$t->text('description')->nullable();$t->string('image_path')->nullable();$t->json('specifications')->nullable();$t->boolean('is_active')->default(true);$t->unique(['business_id','design_code'],'ran_designs_code_unique');});
    }

    private function items(): void
    {
        $this->create('ran_items', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('sku',60);$t->string('barcode',80)->nullable();$t->string('name',180);$t->string('item_type',40)->default('finished');$t->string('category',100)->nullable();$t->unsignedBigInteger('design_id')->nullable()->index();$t->unsignedBigInteger('metal_id')->nullable()->index();$t->unsignedBigInteger('purity_id')->nullable()->index();$t->string('stock_unit',20)->default('piece');$t->decimal('standard_gross_weight',20,3)->default(0);$t->decimal('standard_net_weight',20,3)->default(0);$t->decimal('standard_stone_weight',20,3)->default(0);$t->decimal('making_charge',22,4)->default(0);$t->string('making_charge_type',30)->default('fixed');$t->decimal('default_sale_price',22,4)->default(0);$t->decimal('minimum_sale_price',22,4)->default(0);$t->string('image_path')->nullable();$t->text('description')->nullable();$t->boolean('serialized')->default(true);$t->boolean('is_active')->default(true);$t->unique(['business_id','sku'],'ran_items_sku_unique');$t->unique(['business_id','barcode'],'ran_items_barcode_unique');});
        $this->create('ran_item_components', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->unsignedBigInteger('item_id')->index();$t->string('component_type',30);$t->unsignedBigInteger('metal_id')->nullable()->index();$t->unsignedBigInteger('purity_id')->nullable()->index();$t->unsignedBigInteger('gemstone_id')->nullable()->index();$t->decimal('quantity',20,4)->default(0);$t->decimal('weight',20,3)->default(0);$t->decimal('wastage_percent',10,4)->default(0);$t->decimal('unit_cost',22,4)->default(0);$t->text('notes')->nullable();});
        $this->create('ran_rate_cards', function(Blueprint $t){$t->id();$this->scoped($t,true,false);$t->date('effective_date');$t->unsignedBigInteger('metal_id')->index();$t->unsignedBigInteger('purity_id')->nullable()->index();$t->decimal('purchase_rate',22,4)->default(0);$t->decimal('sale_rate',22,4)->default(0);$t->string('rate_unit',20)->default('gram');$t->boolean('is_active')->default(true);$t->index(['business_id','location_id','effective_date'],'ran_rate_cards_date_idx');});
    }

    private function inventory(): void
    {
        $this->create('ran_stock_lots', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('lot_no',60);$t->unsignedBigInteger('item_id')->index();$t->string('serial_no',100)->nullable();$t->string('rfid_tag',100)->nullable();$t->decimal('quantity',20,4)->default(0);$t->decimal('gross_weight',20,3)->default(0);$t->decimal('net_weight',20,3)->default(0);$t->decimal('stone_weight',20,3)->default(0);$t->decimal('fine_weight',20,3)->default(0);$t->decimal('unit_cost',22,4)->default(0);$t->decimal('total_cost',22,4)->default(0);$t->decimal('sale_price',22,4)->default(0);$t->string('stock_status',30)->default('available');$t->string('source_type',60)->nullable();$t->unsignedBigInteger('source_id')->nullable();$t->date('received_on')->nullable();$t->string('bin_location',100)->nullable();$t->text('notes')->nullable();$t->unique(['business_id','lot_no'],'ran_stock_lots_no_unique');$t->index(['business_id','location_id','store_id','item_id','stock_status'],'ran_stock_lots_scope_idx');});
        $this->create('ran_stock_movements', function(Blueprint $t){$t->id();$this->scoped($t);$t->dateTime('movement_at');$t->string('movement_type',50);$t->unsignedBigInteger('item_id')->index();$t->unsignedBigInteger('stock_lot_id')->nullable()->index();$t->decimal('quantity_in',20,4)->default(0);$t->decimal('quantity_out',20,4)->default(0);$t->decimal('weight_in',20,3)->default(0);$t->decimal('weight_out',20,3)->default(0);$t->decimal('unit_cost',22,4)->default(0);$t->string('reference_type',60)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->string('reference_no',80)->nullable();$t->text('description')->nullable();$t->index(['business_id','movement_at','item_id'],'ran_stock_movements_date_idx');});
        $this->create('ran_transfers', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('transfer_no',60);$t->date('transfer_date');$t->unsignedBigInteger('from_location_id')->index();$t->unsignedBigInteger('from_store_id')->index();$t->unsignedBigInteger('to_location_id')->index();$t->unsignedBigInteger('to_store_id')->index();$t->string('status',30)->default('draft');$t->text('notes')->nullable();$t->unsignedBigInteger('dispatched_by')->nullable();$t->dateTime('dispatched_at')->nullable();$t->unsignedBigInteger('received_by')->nullable();$t->dateTime('received_at')->nullable();$t->unique(['business_id','transfer_no'],'ran_transfers_no_unique');});
        $this->create('ran_transfer_lines', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->unsignedBigInteger('transfer_id')->index();$t->unsignedBigInteger('stock_lot_id')->index();$t->unsignedBigInteger('item_id')->index();$t->decimal('quantity',20,4)->default(0);$t->decimal('weight',20,3)->default(0);$t->decimal('received_quantity',20,4)->default(0);$t->decimal('received_weight',20,3)->default(0);$t->text('notes')->nullable();});
        $this->create('ran_stocktakes', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('stocktake_no',60);$t->date('stocktake_date');$t->string('status',30)->default('draft');$t->text('notes')->nullable();$t->unsignedBigInteger('posted_by')->nullable();$t->dateTime('posted_at')->nullable();$t->unique(['business_id','stocktake_no'],'ran_stocktakes_no_unique');});
        $this->create('ran_stocktake_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('stocktake_id')->index();$t->unsignedBigInteger('stock_lot_id')->index();$t->unsignedBigInteger('item_id')->index();$t->decimal('system_quantity',20,4)->default(0);$t->decimal('counted_quantity',20,4)->default(0);$t->decimal('quantity_variance',20,4)->default(0);$t->decimal('system_weight',20,3)->default(0);$t->decimal('counted_weight',20,3)->default(0);$t->decimal('weight_variance',20,3)->default(0);$t->text('notes')->nullable();});
    }

    private function purchases(): void
    {
        $this->create('ran_purchases', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('purchase_no',60);$t->string('supplier_invoice_no',100)->nullable();$t->date('purchase_date');$t->unsignedBigInteger('supplier_contact_id')->index();$t->string('status',30)->default('draft');$t->decimal('subtotal',22,4)->default(0);$t->decimal('discount_amount',22,4)->default(0);$t->decimal('tax_amount',22,4)->default(0);$t->decimal('total_amount',22,4)->default(0);$t->decimal('paid_amount',22,4)->default(0);$t->decimal('balance_amount',22,4)->default(0);$t->text('notes')->nullable();$t->unsignedBigInteger('posted_by')->nullable();$t->dateTime('posted_at')->nullable();$t->unique(['business_id','purchase_no'],'ran_purchases_no_unique');});
        $this->create('ran_purchase_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('purchase_id')->index();$t->unsignedBigInteger('item_id')->index();$t->string('description')->nullable();$t->decimal('quantity',20,4)->default(0);$t->decimal('gross_weight',20,3)->default(0);$t->decimal('net_weight',20,3)->default(0);$t->decimal('stone_weight',20,3)->default(0);$t->decimal('unit_cost',22,4)->default(0);$t->decimal('line_total',22,4)->default(0);$t->string('lot_no',60)->nullable();$t->string('serial_no',100)->nullable();$t->decimal('sale_price',22,4)->default(0);});
        $this->create('ran_supplier_payments', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('payment_no',60);$t->date('payment_date');$t->unsignedBigInteger('purchase_id')->nullable()->index();$t->unsignedBigInteger('supplier_contact_id')->index();$t->unsignedBigInteger('finance_account_id')->nullable()->index();$t->decimal('amount',22,4);$t->string('payment_method',40);$t->string('reference_no',100)->nullable();$t->text('notes')->nullable();$t->string('status',30)->default('posted');$t->unique(['business_id','payment_no'],'ran_supplier_payments_no_unique');});
    }

    private function production(): void
    {
        $this->create('ran_production_orders', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('order_no',60);$t->date('order_date');$t->date('due_date')->nullable();$t->unsignedBigInteger('artisan_id')->nullable()->index();$t->unsignedBigInteger('supplier_contact_id')->nullable()->index();$t->unsignedBigInteger('customer_contact_id')->nullable()->index();$t->string('status',30)->default('draft');$t->string('priority',20)->default('normal');$t->text('instructions')->nullable();$t->decimal('estimated_cost',22,4)->default(0);$t->decimal('actual_cost',22,4)->default(0);$t->unsignedBigInteger('approved_by')->nullable();$t->dateTime('approved_at')->nullable();$t->unique(['business_id','order_no'],'ran_production_orders_no_unique');});
        $this->create('ran_production_order_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('production_order_id')->index();$t->unsignedBigInteger('item_id')->nullable()->index();$t->unsignedBigInteger('design_id')->nullable()->index();$t->string('description')->nullable();$t->decimal('planned_quantity',20,4)->default(1);$t->decimal('planned_gross_weight',20,3)->default(0);$t->decimal('planned_net_weight',20,3)->default(0);$t->decimal('planned_stone_weight',20,3)->default(0);$t->decimal('wastage_percent',10,4)->default(0);$t->decimal('making_charge',22,4)->default(0);$t->json('specifications')->nullable();});
        $this->create('ran_material_issues', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('issue_no',60);$t->date('issue_date');$t->unsignedBigInteger('production_order_id')->index();$t->unsignedBigInteger('artisan_id')->nullable()->index();$t->string('status',30)->default('posted');$t->text('notes')->nullable();$t->unique(['business_id','issue_no'],'ran_material_issues_no_unique');});
        $this->create('ran_material_issue_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('material_issue_id')->index();$t->unsignedBigInteger('stock_lot_id')->index();$t->unsignedBigInteger('item_id')->index();$t->decimal('quantity',20,4)->default(0);$t->decimal('gross_weight',20,3)->default(0);$t->decimal('net_weight',20,3)->default(0);$t->decimal('fine_weight',20,3)->default(0);$t->decimal('unit_cost',22,4)->default(0);$t->decimal('total_cost',22,4)->default(0);$t->text('notes')->nullable();});
        $this->create('ran_production_receipts', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('receipt_no',60);$t->date('receipt_date');$t->unsignedBigInteger('production_order_id')->index();$t->unsignedBigInteger('artisan_id')->nullable()->index();$t->string('status',30)->default('posted');$t->decimal('labour_cost',22,4)->default(0);$t->decimal('other_cost',22,4)->default(0);$t->text('notes')->nullable();$t->unique(['business_id','receipt_no'],'ran_production_receipts_no_unique');});
        $this->create('ran_production_receipt_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('production_receipt_id')->index();$t->unsignedBigInteger('production_order_line_id')->nullable()->index();$t->unsignedBigInteger('item_id')->index();$t->string('lot_no',60);$t->string('serial_no',100)->nullable();$t->decimal('quantity',20,4)->default(1);$t->decimal('gross_weight',20,3)->default(0);$t->decimal('net_weight',20,3)->default(0);$t->decimal('stone_weight',20,3)->default(0);$t->decimal('fine_weight',20,3)->default(0);$t->decimal('material_cost',22,4)->default(0);$t->decimal('labour_cost',22,4)->default(0);$t->decimal('other_cost',22,4)->default(0);$t->decimal('total_cost',22,4)->default(0);$t->decimal('sale_price',22,4)->default(0);});
        $this->create('ran_wastage_entries', function(Blueprint $t){$t->id();$this->scoped($t);$t->date('entry_date');$t->unsignedBigInteger('production_order_id')->index();$t->unsignedBigInteger('material_issue_line_id')->nullable()->index();$t->unsignedBigInteger('item_id')->nullable()->index();$t->string('entry_type',30)->default('wastage');$t->decimal('weight',20,3)->default(0);$t->decimal('fine_weight',20,3)->default(0);$t->decimal('value',22,4)->default(0);$t->text('reason')->nullable();$t->unsignedBigInteger('approved_by')->nullable();$t->dateTime('approved_at')->nullable();});
    }

    private function sales(): void
    {
        $this->create('ran_sales', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('invoice_no',60);$t->date('invoice_date');$t->unsignedBigInteger('customer_contact_id')->nullable()->index();$t->string('customer_name')->nullable();$t->string('customer_mobile',40)->nullable();$t->string('customer_email')->nullable();$t->string('status',30)->default('draft');$t->decimal('subtotal',22,4)->default(0);$t->decimal('making_charge_total',22,4)->default(0);$t->decimal('discount_amount',22,4)->default(0);$t->decimal('tax_amount',22,4)->default(0);$t->decimal('rounding_amount',22,4)->default(0);$t->decimal('total_amount',22,4)->default(0);$t->decimal('paid_amount',22,4)->default(0);$t->decimal('balance_amount',22,4)->default(0);$t->text('notes')->nullable();$t->text('terms')->nullable();$t->unsignedBigInteger('posted_by')->nullable();$t->dateTime('posted_at')->nullable();$t->unsignedBigInteger('cancelled_by')->nullable();$t->dateTime('cancelled_at')->nullable();$t->unique(['business_id','invoice_no'],'ran_sales_invoice_unique');$t->index(['business_id','location_id','invoice_date','status'],'ran_sales_date_idx');});
        $this->create('ran_sale_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('sale_id')->index();$t->unsignedBigInteger('item_id')->index();$t->unsignedBigInteger('stock_lot_id')->nullable()->index();$t->string('description')->nullable();$t->decimal('quantity',20,4)->default(1);$t->decimal('gross_weight',20,3)->default(0);$t->decimal('net_weight',20,3)->default(0);$t->decimal('stone_weight',20,3)->default(0);$t->decimal('metal_rate',22,4)->default(0);$t->decimal('metal_value',22,4)->default(0);$t->decimal('stone_value',22,4)->default(0);$t->decimal('making_charge',22,4)->default(0);$t->decimal('other_charge',22,4)->default(0);$t->decimal('discount_amount',22,4)->default(0);$t->decimal('tax_amount',22,4)->default(0);$t->decimal('unit_price',22,4)->default(0);$t->decimal('line_total',22,4)->default(0);$t->decimal('cost_amount',22,4)->default(0);});
        $this->create('ran_payments', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('payment_no',60);$t->date('payment_date');$t->unsignedBigInteger('sale_id')->nullable()->index();$t->unsignedBigInteger('customer_contact_id')->nullable()->index();$t->unsignedBigInteger('finance_account_id')->nullable()->index();$t->string('payment_method',40);$t->decimal('amount',22,4);$t->string('reference_no',100)->nullable();$t->text('notes')->nullable();$t->string('status',30)->default('posted');$t->unique(['business_id','payment_no'],'ran_payments_no_unique');});
        $this->create('ran_sale_returns', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('return_no',60);$t->date('return_date');$t->unsignedBigInteger('sale_id')->nullable()->index();$t->unsignedBigInteger('customer_contact_id')->nullable()->index();$t->string('status',30)->default('draft');$t->decimal('total_amount',22,4)->default(0);$t->text('reason')->nullable();$t->unsignedBigInteger('posted_by')->nullable();$t->dateTime('posted_at')->nullable();$t->unique(['business_id','return_no'],'ran_sale_returns_no_unique');});
        $this->create('ran_sale_return_lines', function(Blueprint $t){$t->id();$this->scoped($t);$t->unsignedBigInteger('sale_return_id')->index();$t->unsignedBigInteger('sale_line_id')->nullable()->index();$t->unsignedBigInteger('item_id')->index();$t->unsignedBigInteger('stock_lot_id')->nullable()->index();$t->decimal('quantity',20,4)->default(0);$t->decimal('weight',20,3)->default(0);$t->decimal('amount',22,4)->default(0);$t->string('condition',40)->default('good');$t->text('notes')->nullable();});
        $this->create('ran_finance_postings', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('source_type',60);$t->unsignedBigInteger('source_id');$t->string('posting_type',60);$t->unsignedBigInteger('debit_account_id')->nullable();$t->unsignedBigInteger('credit_account_id')->nullable();$t->decimal('amount',22,4);$t->unsignedBigInteger('debit_account_transaction_id')->nullable();$t->unsignedBigInteger('credit_account_transaction_id')->nullable();$t->string('status',30)->default('posted');$t->text('message')->nullable();$t->unique(['business_id','source_type','source_id','posting_type'],'ran_finance_postings_unique');});
    }

    private function documents(): void
    {
        $this->create('ran_document_templates', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->string('document_type',60);$t->string('name',120);$t->string('paper_size',30)->default('A4');$t->string('orientation',20)->default('portrait');$t->boolean('is_default')->default(false);$t->json('style_options')->nullable();$t->boolean('is_active')->default(true);$t->index(['business_id','document_type','is_default'],'ran_doc_templates_type_idx');});
        $this->create('ran_document_template_sections', function(Blueprint $t){$t->id();$this->scoped($t,false,false);$t->unsignedBigInteger('template_id')->index();$t->string('section_key',80);$t->string('title',120);$t->unsignedInteger('sort_order')->default(0);$t->boolean('enabled_by_default')->default(true);$t->boolean('allow_print')->default(true);$t->boolean('allow_sms')->default(true);$t->boolean('allow_email')->default(true);$t->boolean('allow_whatsapp')->default(true);$t->json('settings')->nullable();$t->unique(['template_id','section_key'],'ran_doc_sections_unique');});
        $this->create('ran_document_shares', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('token',100)->unique();$t->string('document_type',60);$t->unsignedBigInteger('document_id');$t->string('channel',30);$t->json('selected_sections');$t->dateTime('expires_at')->nullable();$t->unsignedInteger('view_count')->default(0);$t->unsignedInteger('download_count')->default(0);$t->dateTime('last_viewed_at')->nullable();$t->boolean('is_active')->default(true);$t->index(['business_id','document_type','document_id'],'ran_document_shares_doc_idx');});
        $this->create('ran_communication_logs', function(Blueprint $t){$t->id();$this->scoped($t);$t->string('channel',30);$t->string('document_type',60);$t->unsignedBigInteger('document_id');$t->string('recipient',255)->nullable();$t->text('subject')->nullable();$t->longText('message')->nullable();$t->string('share_url',500)->nullable();$t->string('status',30)->default('queued');$t->string('provider_reference',150)->nullable();$t->longText('provider_response')->nullable();$t->dateTime('sent_at')->nullable();$t->dateTime('failed_at')->nullable();$t->text('failure_reason')->nullable();$t->index(['business_id','document_type','document_id'],'ran_comms_doc_idx');});
        $this->create('ran_audit_logs', function(Blueprint $t){$t->id();$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('action',80);$t->string('entity_type',120);$t->unsignedBigInteger('entity_id')->nullable();$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->string('ip_address',64)->nullable();$t->text('user_agent')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['business_id','entity_type','entity_id'],'ran_audit_entity_idx');});
    }

    private function seedDefaults(): void
    {
        $now = now();
        DB::table('ran_metals')->insertOrIgnore([
            ['business_id'=>0,'code'=>'GOLD','name'=>'Gold','symbol'=>'Au','default_density'=>19.320000,'is_active'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['business_id'=>0,'code'=>'SILVER','name'=>'Silver','symbol'=>'Ag','default_density'=>10.490000,'is_active'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['business_id'=>0,'code'=>'PLATINUM','name'=>'Platinum','symbol'=>'Pt','default_density'=>21.450000,'is_active'=>1,'created_at'=>$now,'updated_at'=>$now],
        ]);
        $templates = [
            'sale' => ['Standard Jewellery Invoice', [['header','Business Header'],['customer','Customer Details'],['items','Jewellery Details'],['weights','Weight Summary'],['charges','Price and Charges'],['payments','Payment Details'],['terms','Terms and Notes'],['signature','Authorised Signature']]],
            'purchase' => ['Purchase Receipt', [['header','Business Header'],['supplier','Supplier Details'],['items','Purchased Jewellery and Materials'],['weights','Weight Summary'],['totals','Purchase Totals'],['signature','Authorised Signature']]],
            'production_order' => ['Production Work Order', [['header','Business Header'],['artisan','Artisan Details'],['design','Design and Specification'],['materials','Planned Materials'],['instructions','Production Instructions'],['approval','Approval']]],
            'stock_transfer' => ['Stock Transfer Note', [['header','Business Header'],['route','From and To Stores'],['items','Transferred Jewellery'],['weights','Weight Summary'],['dispatch','Dispatch Details'],['receipt','Receipt Confirmation']]],
        ];
        foreach ($templates as $type => [$name,$sections]) {
            $id = DB::table('ran_document_templates')->where('business_id',0)->where('document_type',$type)->value('id');
            if (! $id) $id = DB::table('ran_document_templates')->insertGetId(['business_id'=>0,'document_type'=>$type,'name'=>$name,'paper_size'=>'A4','orientation'=>'portrait','is_default'=>1,'is_active'=>1,'created_at'=>$now,'updated_at'=>$now]);
            foreach ($sections as $i => $row) DB::table('ran_document_template_sections')->insertOrIgnore(['business_id'=>0,'template_id'=>$id,'section_key'=>$row[0],'title'=>$row[1],'sort_order'=>($i+1)*10,'enabled_by_default'=>1,'allow_print'=>1,'allow_sms'=>1,'allow_email'=>1,'allow_whatsapp'=>1,'created_at'=>$now,'updated_at'=>$now]);
        }
    }

    public function down(): void
    {
        foreach (['ran_audit_logs','ran_communication_logs','ran_document_shares','ran_document_template_sections','ran_document_templates','ran_finance_postings','ran_sale_return_lines','ran_sale_returns','ran_payments','ran_sale_lines','ran_sales','ran_wastage_entries','ran_production_receipt_lines','ran_production_receipts','ran_material_issue_lines','ran_material_issues','ran_production_order_lines','ran_production_orders','ran_supplier_payments','ran_purchase_lines','ran_purchases','ran_stocktake_lines','ran_stocktakes','ran_transfer_lines','ran_transfers','ran_stock_movements','ran_stock_lots','ran_rate_cards','ran_item_components','ran_items','ran_designs','ran_artisans','ran_gemstones','ran_purities','ran_metals','ran_number_sequences','ran_settings'] as $table) Schema::dropIfExists($table);
    }
};
