@extends('leadsnew::layouts.app')
@section('title', __('leadsnew::lang.opportunity_centre'))
@section('leadsnew_subtitle', 'Manage sales opportunities, expected values, probability and closing dates from one professional register.')
@section('leadsnew_content')
<div class="ln-split-grid">
<div class="ln-panel"><div class="ln-panel-header"><div><h3 class="ln-panel-title"><i class="fa fa-line-chart"></i> Opportunity Pipeline</h3><div class="ch-card-subtitle">Latest opportunities are shown first.</div></div><span class="ln-badge">{{ method_exists($opportunities, 'total') ? $opportunities->total() : count($opportunities) }} opportunities</span></div><div class="ln-table table-responsive"><table class="table table-hover"><thead><tr><th>No.</th><th>Opportunity</th><th>Stage</th><th class="text-right">Expected Value</th><th class="text-right">Probability</th><th>Status</th></tr></thead><tbody>
@forelse($opportunities as $opportunity)<tr><td><strong>{{ $opportunity->opportunity_no ?: ('#' . $opportunity->id) }}</strong></td><td>{{ $opportunity->title ?: '-' }}<br><span class="text-muted">Lead #{{ $opportunity->lead_id ?: '-' }}</span></td><td><span class="ln-badge">{{ ucfirst($opportunity->stage ?: 'new') }}</span></td><td class="text-right">{{ number_format((float)$opportunity->estimated_value, 2) }}</td><td class="text-right">{{ number_format((float)$opportunity->probability, 0) }}%</td><td><span class="ln-badge {{ strtolower($opportunity->status) === 'won' ? 'status-converted' : (strtolower($opportunity->status) === 'lost' ? 'status-lost' : 'status-new') }}">{{ ucfirst($opportunity->status ?: 'open') }}</span></td></tr>@empty<tr><td colspan="6"><div class="ln-empty"><i class="fa fa-line-chart"></i>No opportunities found.</div></td></tr>@endforelse
</tbody></table></div>@if(method_exists($opportunities, 'links'))<div class="ln-panel-body">{{ $opportunities->links() }}</div>@endif</div>
<div class="ln-panel ln-sticky-panel"><div class="ln-panel-header"><h3 class="ln-panel-title"><i class="fa fa-plus-circle"></i> New Opportunity</h3></div><div class="ln-panel-body"><form method="post" action="{{ url('/leads-new/opportunities') }}">@csrf<div class="form-group"><label>Title</label><input type="text" name="title" class="form-control" value="{{ old('title') }}" required></div><div class="form-group"><label>Lead ID</label><input type="number" name="lead_id" class="form-control" value="{{ old('lead_id') }}"></div><div class="row"><div class="col-sm-7"><div class="form-group"><label>Expected Value</label><input type="number" step="0.01" name="estimated_value" class="form-control" value="{{ old('estimated_value', 0) }}"></div></div><div class="col-sm-5"><div class="form-group"><label>Probability %</label><input type="number" min="0" max="100" name="probability" class="form-control" value="{{ old('probability', 0) }}"></div></div></div><div class="row"><div class="col-sm-6"><div class="form-group"><label>Stage</label><select name="stage" class="form-control select2"><option value="new">New</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="negotiation">Negotiation</option></select></div></div><div class="col-sm-6"><div class="form-group"><label>Close Date</label><input type="date" name="expected_close_date" class="form-control" value="{{ old('expected_close_date') }}"></div></div></div><input type="hidden" name="status" value="open"><button class="btn btn-primary btn-block"><i class="fa fa-save"></i> Save Opportunity</button></form></div></div>
</div>
@endsection
