-- Stock Taking - New
-- File: 01_CREATE_TABLES_STOCK_TAKING_NEW.sql
-- Run on EACH tenant database. Safe to run more than once.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `stk_settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `setting_key` VARCHAR(120) NOT NULL,
  `setting_value` LONGTEXT NULL,
  `value_json` JSON NULL,
  `is_encrypted` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_settings_business_key_uq` (`business_id`,`setting_key`),
  KEY `stk_settings_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_number_sequences` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `sequence_key` VARCHAR(120) NOT NULL,
  `last_number` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_sequence_business_key_uq` (`business_id`,`sequence_key`),
  KEY `stk_number_sequences_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_templates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `count_method` VARCHAR(30) NOT NULL DEFAULT 'cycle',
  `scope_json` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_templates_business_id_index` (`business_id`),
  KEY `stk_templates_business_active_idx` (`business_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_template_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `template_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_variation_id` BIGINT UNSIGNED NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `sku` VARCHAR(120) NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_template_product_variation_uq` (`template_id`,`product_id`,`variation_id`),
  KEY `stk_template_lines_business_id_index` (`business_id`),
  KEY `stk_template_lines_template_id_index` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `template_id` BIGINT UNSIGNED NULL,
  `stock_take_no` VARCHAR(80) NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `count_date` DATE NOT NULL,
  `cutoff_at` DATETIME NULL,
  `count_method` VARCHAR(30) NOT NULL DEFAULT 'full',
  `count_mode` VARCHAR(30) NOT NULL DEFAULT 'blind',
  `scope_json` JSON NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `freeze_stock` TINYINT(1) NOT NULL DEFAULT 0,
  `require_recount` TINYINT(1) NOT NULL DEFAULT 1,
  `variance_qty_threshold` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `variance_value_threshold` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `line_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `counted_line_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `system_qty_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `counted_qty_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `variance_qty_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `variance_value_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `notes` TEXT NULL,
  `approval_remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `prepared_by` BIGINT UNSIGNED NULL,
  `started_by` BIGINT UNSIGNED NULL,
  `submitted_by` BIGINT UNSIGNED NULL,
  `approved_by` BIGINT UNSIGNED NULL,
  `posted_by` BIGINT UNSIGNED NULL,
  `prepared_at` DATETIME NULL,
  `started_at` DATETIME NULL,
  `submitted_at` DATETIME NULL,
  `approved_at` DATETIME NULL,
  `posted_at` DATETIME NULL,
  `closed_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_session_business_no_uq` (`business_id`,`stock_take_no`),
  KEY `stk_sessions_business_id_index` (`business_id`),
  KEY `stk_sessions_location_id_index` (`location_id`),
  KEY `stk_sessions_store_id_index` (`store_id`),
  KEY `stk_sessions_template_id_index` (`template_id`),
  KEY `stk_sessions_count_date_index` (`count_date`),
  KEY `stk_sessions_status_index` (`status`),
  KEY `stk_session_scope_status_idx` (`business_id`,`location_id`,`store_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_session_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_variation_id` BIGINT UNSIGNED NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `sku` VARCHAR(120) NULL,
  `barcode` VARCHAR(120) NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `batch_no` VARCHAR(120) NULL,
  `serial_no` VARCHAR(160) NULL,
  `bin_location` VARCHAR(120) NULL,
  `system_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `first_count_qty` DECIMAL(22,4) NULL,
  `recount_qty` DECIMAL(22,4) NULL,
  `final_count_qty` DECIMAL(22,4) NULL,
  `variance_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `variance_value` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `count_status` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `is_counted` TINYINT(1) NOT NULL DEFAULT 0,
  `requires_recount` TINYINT(1) NOT NULL DEFAULT 0,
  `is_frozen` TINYINT(1) NOT NULL DEFAULT 0,
  `notes` TEXT NULL,
  `counted_by` BIGINT UNSIGNED NULL,
  `recounted_by` BIGINT UNSIGNED NULL,
  `counted_at` DATETIME NULL,
  `recounted_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_session_line_scope_uq` (`session_id`,`product_id`,`variation_id`,`batch_no`,`serial_no`,`bin_location`),
  KEY `stk_session_lines_business_id_index` (`business_id`),
  KEY `stk_session_lines_location_id_index` (`location_id`),
  KEY `stk_session_lines_store_id_index` (`store_id`),
  KEY `stk_session_lines_session_id_index` (`session_id`),
  KEY `stk_session_lines_product_id_index` (`product_id`),
  KEY `stk_session_lines_variation_id_index` (`variation_id`),
  KEY `stk_session_lines_sku_index` (`sku`),
  KEY `stk_session_lines_count_status_index` (`count_status`),
  KEY `stk_session_lines_requires_recount_index` (`requires_recount`),
  KEY `stk_line_progress_idx` (`session_id`,`is_counted`,`requires_recount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_counts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `line_id` BIGINT UNSIGNED NOT NULL,
  `attempt_no` INT UNSIGNED NOT NULL DEFAULT 1,
  `count_type` VARCHAR(30) NOT NULL DEFAULT 'initial',
  `counted_qty` DECIMAL(22,4) NOT NULL,
  `barcode` VARCHAR(120) NULL,
  `bin_location` VARCHAR(120) NULL,
  `notes` TEXT NULL,
  `metadata` JSON NULL,
  `counted_by` BIGINT UNSIGNED NULL,
  `counted_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_count_line_attempt_uq` (`line_id`,`attempt_no`),
  KEY `stk_counts_business_id_index` (`business_id`),
  KEY `stk_counts_session_id_index` (`session_id`),
  KEY `stk_counts_line_id_index` (`line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_assignments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `role` VARCHAR(40) NOT NULL DEFAULT 'counter',
  `scope_json` JSON NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'assigned',
  `assigned_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `assigned_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_assignment_session_user_role_uq` (`session_id`,`user_id`,`role`),
  KEY `stk_assignments_business_id_index` (`business_id`),
  KEY `stk_assignments_session_id_index` (`session_id`),
  KEY `stk_assignments_user_id_index` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_approvals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `level_no` INT UNSIGNED NOT NULL DEFAULT 1,
  `action` VARCHAR(30) NOT NULL,
  `remarks` TEXT NULL,
  `acted_by` BIGINT UNSIGNED NULL,
  `acted_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_approvals_business_id_index` (`business_id`),
  KEY `stk_approvals_session_id_index` (`session_id`),
  KEY `stk_approval_session_level_idx` (`session_id`,`level_no`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_inventory_movements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `line_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_variation_id` BIGINT UNSIGNED NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `movement_type` VARCHAR(50) NOT NULL,
  `before_qty` DECIMAL(22,4) NOT NULL,
  `adjustment_qty` DECIMAL(22,4) NOT NULL,
  `after_qty` DECIMAL(22,4) NOT NULL,
  `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `value_change` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `source_table` VARCHAR(120) NULL,
  `reference_no` VARCHAR(100) NULL,
  `posted_by` BIGINT UNSIGNED NULL,
  `posted_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_movement_session_line_uq` (`session_id`,`line_id`),
  KEY `stk_inventory_movements_business_id_index` (`business_id`),
  KEY `stk_inventory_movements_location_id_index` (`location_id`),
  KEY `stk_inventory_movements_store_id_index` (`store_id`),
  KEY `stk_inventory_movements_session_id_index` (`session_id`),
  KEY `stk_inventory_movements_line_id_index` (`line_id`),
  KEY `stk_inventory_movements_product_id_index` (`product_id`),
  KEY `stk_inventory_movements_variation_id_index` (`variation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_share_links` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `document_type` VARCHAR(50) NOT NULL,
  `token_hash` CHAR(64) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `download_allowed` TINYINT(1) NOT NULL DEFAULT 1,
  `access_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_accessed_at` DATETIME NULL,
  `revoked_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_share_links_token_hash_unique` (`token_hash`),
  KEY `stk_share_links_business_id_index` (`business_id`),
  KEY `stk_share_links_session_id_index` (`session_id`),
  KEY `stk_share_links_expires_at_index` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_share_dispatches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `share_link_id` BIGINT UNSIGNED NOT NULL,
  `channel` VARCHAR(30) NOT NULL,
  `recipient` VARCHAR(255) NOT NULL,
  `recipient_name` VARCHAR(160) NULL,
  `message` TEXT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `payload` JSON NULL,
  `response` JSON NULL,
  `sent_at` DATETIME NULL,
  `failed_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_share_dispatches_business_id_index` (`business_id`),
  KEY `stk_share_dispatches_session_id_index` (`session_id`),
  KEY `stk_share_dispatches_share_link_id_index` (`share_link_id`),
  KEY `stk_share_dispatches_channel_index` (`channel`),
  KEY `stk_share_dispatches_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_schedules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `template_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(160) NOT NULL,
  `frequency` VARCHAR(30) NOT NULL,
  `day_of_week` VARCHAR(20) NULL,
  `day_of_month` TINYINT UNSIGNED NULL,
  `run_time` TIME NULL,
  `scope_json` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `next_run_at` DATETIME NULL,
  `last_run_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_schedules_business_id_index` (`business_id`),
  KEY `stk_schedules_location_id_index` (`location_id`),
  KEY `stk_schedules_store_id_index` (`store_id`),
  KEY `stk_schedules_next_run_at_index` (`next_run_at`),
  KEY `stk_schedules_due_idx` (`is_active`,`next_run_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_import_batches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `session_id` BIGINT UNSIGNED NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'processing',
  `total_rows` INT UNSIGNED NOT NULL DEFAULT 0,
  `success_rows` INT UNSIGNED NOT NULL DEFAULT 0,
  `failed_rows` INT UNSIGNED NOT NULL DEFAULT 0,
  `summary` JSON NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_import_batches_business_id_index` (`business_id`),
  KEY `stk_import_batches_session_id_index` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stk_audit_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `session_id` BIGINT UNSIGNED NULL,
  `entity_type` VARCHAR(80) NOT NULL,
  `entity_id` BIGINT UNSIGNED NULL,
  `event` VARCHAR(120) NOT NULL,
  `old_values` JSON NULL,
  `new_values` JSON NULL,
  `metadata` JSON NULL,
  `ip_address` VARCHAR(64) NULL,
  `user_agent` VARCHAR(500) NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stk_audit_logs_business_id_index` (`business_id`),
  KEY `stk_audit_logs_session_id_index` (`session_id`),
  KEY `stk_audit_logs_event_index` (`event`),
  KEY `stk_audit_logs_created_by_index` (`created_by`),
  KEY `stk_audit_business_session_date_idx` (`business_id`,`session_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
