/* S377 - Chequer Template + Write Cheque extended fields
   Run in each tenant database. No hard-coded database name. */

SET @table_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques');

SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'cheq_template_id'), 'ALTER TABLE cheq_cheques ADD COLUMN cheq_template_id BIGINT UNSIGNED NULL AFTER cheq_cheque_book_id, ADD INDEX cheq_cheques_template_idx (cheq_template_id)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'payee_type'), 'ALTER TABLE cheq_cheques ADD COLUMN payee_type VARCHAR(80) NULL AFTER payee_name', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'payee_id'), 'ALTER TABLE cheq_cheques ADD COLUMN payee_id BIGINT UNSIGNED NULL AFTER payee_type, ADD INDEX cheq_cheques_payee_idx (payee_id)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'payment_for'), 'ALTER TABLE cheq_cheques ADD COLUMN payment_for VARCHAR(120) NULL AFTER payment_type', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'purchase_id'), 'ALTER TABLE cheq_cheques ADD COLUMN purchase_id VARCHAR(120) NULL AFTER payment_for', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'purchase_bill_no'), 'ALTER TABLE cheq_cheques ADD COLUMN purchase_bill_no VARCHAR(191) NULL AFTER purchase_id', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'supplier_order_no'), 'ALTER TABLE cheq_cheques ADD COLUMN supplier_order_no VARCHAR(191) NULL AFTER purchase_bill_no', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'payable_amount'), 'ALTER TABLE cheq_cheques ADD COLUMN payable_amount DECIMAL(22,4) NULL AFTER supplier_order_no', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'payment_status'), 'ALTER TABLE cheq_cheques ADD COLUMN payment_status VARCHAR(80) NULL AFTER payable_amount', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'bank_account_id'), 'ALTER TABLE cheq_cheques ADD COLUMN bank_account_id BIGINT UNSIGNED NULL AFTER payment_status, ADD INDEX cheq_cheques_bank_idx (bank_account_id)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'stamp_id'), 'ALTER TABLE cheq_cheques ADD COLUMN stamp_id VARCHAR(120) NULL AFTER bank_account_id', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'date_condition'), 'ALTER TABLE cheq_cheques ADD COLUMN date_condition VARCHAR(80) NULL AFTER stamp_id', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'currency_id'), 'ALTER TABLE cheq_cheques ADD COLUMN currency_id VARCHAR(80) NULL AFTER date_condition', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'currency_code'), 'ALTER TABLE cheq_cheques ADD COLUMN currency_code VARCHAR(20) NULL AFTER currency_id', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'on_account_of'), 'ALTER TABLE cheq_cheques ADD COLUMN on_account_of VARCHAR(500) NULL AFTER currency_code', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'amount_words'), 'ALTER TABLE cheq_cheques ADD COLUMN amount_words VARCHAR(1000) NULL AFTER on_account_of', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'date_time'), 'ALTER TABLE cheq_cheques ADD COLUMN date_time VARCHAR(80) NULL AFTER amount_words', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'double_entry_account_id'), 'ALTER TABLE cheq_cheques ADD COLUMN double_entry_account_id BIGINT UNSIGNED NULL AFTER date_time, ADD INDEX cheq_cheques_double_entry_idx (double_entry_account_id)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'options'), 'ALTER TABLE cheq_cheques ADD COLUMN options JSON NULL AFTER double_entry_account_id', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@table_exists = 1 AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cheq_cheques' AND column_name = 'attachment_path'), 'ALTER TABLE cheq_cheques ADD COLUMN attachment_path VARCHAR(191) NULL AFTER options', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
