-- Egg Management Module - Tenant Database Master SQL
-- Prefix rule: ALL module-owned tables use egg_
-- Run this on each TENANT database only. The master/central tenancy database is not modified.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `egg_sequences` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`sequence_key` VARCHAR(50) NOT NULL,`current_value` BIGINT UNSIGNED NOT NULL DEFAULT 0,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_sequences_unique` (`business_id`,`sequence_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_grades` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`code` VARCHAR(30) NOT NULL,`name` VARCHAR(100) NOT NULL,`min_weight_g` DECIMAL(10,2) NULL,`max_weight_g` DECIMAL(10,2) NULL,`sort_order` INT UNSIGNED NOT NULL DEFAULT 0,`active` TINYINT(1) NOT NULL DEFAULT 1,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_grades_unique` (`business_id`,`code`),KEY `egg_grades_active` (`business_id`,`active`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_flocks` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`flock_code` VARCHAR(50) NOT NULL,`name` VARCHAR(100) NOT NULL,`breed` VARCHAR(100) NULL,`started_on` DATE NULL,`ended_on` DATE NULL,`bird_count` INT UNSIGNED NULL,`active` TINYINT(1) NOT NULL DEFAULT 1,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_flocks_unique` (`business_id`,`flock_code`),KEY `egg_flocks_scope` (`business_id`,`location_id`,`active`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_collections` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`collection_no` VARCHAR(50) NOT NULL,`collection_date` DATE NOT NULL,`flock_id` BIGINT UNSIGNED NULL,`shift` VARCHAR(30) NULL,`total_pieces` INT NOT NULL,`good_pieces` INT NOT NULL,`broken_pieces` INT NOT NULL DEFAULT 0,`dirty_pieces` INT NOT NULL DEFAULT 0,`rejected_pieces` INT NOT NULL DEFAULT 0,`status` VARCHAR(30) NOT NULL DEFAULT 'open',`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_collections_unique` (`business_id`,`collection_no`),KEY `egg_collections_date` (`business_id`,`collection_date`),KEY `egg_collections_flock` (`business_id`,`flock_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_collection_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`collection_id` BIGINT UNSIGNED NOT NULL,`quality_type` VARCHAR(30) NOT NULL,`pieces` INT NOT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_collection_lines_parent` (`business_id`,`collection_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_grading_runs` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`grading_no` VARCHAR(50) NOT NULL,`collection_id` BIGINT UNSIGNED NOT NULL,`graded_on` DATE NOT NULL,`input_pieces` INT NOT NULL,`output_pieces` INT NOT NULL,`status` VARCHAR(30) NOT NULL,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_grading_runs_unique` (`business_id`,`grading_no`),KEY `egg_grading_runs_date` (`business_id`,`graded_on`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_grading_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`grading_run_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`pieces` INT NOT NULL,`unit_cost` DECIMAL(18,4) NOT NULL DEFAULT 0,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_grading_lines_parent` (`business_id`,`grading_run_id`),KEY `egg_grading_lines_grade` (`business_id`,`grade_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_stock_lots` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`lot_no` VARCHAR(60) NOT NULL,`collection_date` DATE NULL,`best_before` DATE NULL,`received_pieces` INT NOT NULL,`available_pieces` INT NOT NULL,`unit_cost` DECIMAL(18,4) NOT NULL DEFAULT 0,`source_type` VARCHAR(50) NOT NULL,`source_id` BIGINT UNSIGNED NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'available',`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_stock_lots_unique` (`business_id`,`lot_no`),KEY `egg_stock_scope_idx` (`business_id`,`location_id`,`store_id`,`grade_id`,`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_stock_movements` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`movement_date` DATETIME NOT NULL,`direction` VARCHAR(10) NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`pieces` INT NOT NULL,`unit_cost` DECIMAL(18,4) NOT NULL DEFAULT 0,`stock_lot_id` BIGINT UNSIGNED NULL,`source_type` VARCHAR(50) NOT NULL,`source_id` BIGINT UNSIGNED NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_stock_movements_date` (`business_id`,`movement_date`),KEY `egg_move_scope_idx` (`business_id`,`grade_id`,`location_id`,`store_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_sales` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`sale_no` VARCHAR(50) NOT NULL,`sale_date` DATE NOT NULL,`customer_id` BIGINT UNSIGNED NULL,`subtotal` DECIMAL(18,4) NOT NULL DEFAULT 0,`discount` DECIMAL(18,4) NOT NULL DEFAULT 0,`total` DECIMAL(18,4) NOT NULL DEFAULT 0,`status` VARCHAR(30) NOT NULL,`payment_status` VARCHAR(30) NOT NULL,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_sales_unique` (`business_id`,`sale_no`),KEY `egg_sales_date` (`business_id`,`sale_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_sale_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`sale_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NULL,`pieces` INT NOT NULL,`unit_price` DECIMAL(18,4) NOT NULL,`amount` DECIMAL(18,4) NOT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_sale_lines_parent` (`business_id`,`sale_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_purchases` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`purchase_no` VARCHAR(50) NOT NULL,`purchase_date` DATE NOT NULL,`supplier_id` BIGINT UNSIGNED NULL,`supplier_reference` VARCHAR(100) NULL,`subtotal` DECIMAL(18,4) NOT NULL DEFAULT 0,`discount` DECIMAL(18,4) NOT NULL DEFAULT 0,`total` DECIMAL(18,4) NOT NULL DEFAULT 0,`status` VARCHAR(30) NOT NULL,`payment_status` VARCHAR(30) NOT NULL,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_purchases_unique` (`business_id`,`purchase_no`),KEY `egg_purchases_date` (`business_id`,`purchase_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_purchase_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`purchase_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NULL,`pieces` INT NOT NULL,`unit_cost` DECIMAL(18,4) NOT NULL,`amount` DECIMAL(18,4) NOT NULL,`best_before` DATE NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_purchase_lines_parent` (`business_id`,`purchase_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_transfers` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`transfer_no` VARCHAR(50) NOT NULL,`transfer_date` DATE NOT NULL,`from_location_id` BIGINT UNSIGNED NULL,`from_store_id` BIGINT UNSIGNED NULL,`to_location_id` BIGINT UNSIGNED NULL,`to_store_id` BIGINT UNSIGNED NULL,`status` VARCHAR(30) NOT NULL,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_transfers_unique` (`business_id`,`transfer_no`),KEY `egg_transfers_date` (`business_id`,`transfer_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_transfer_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`transfer_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`pieces` INT NOT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_transfer_lines_parent` (`business_id`,`transfer_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_adjustments` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`location_id` BIGINT UNSIGNED NULL,`store_id` BIGINT UNSIGNED NULL,`adjustment_no` VARCHAR(50) NOT NULL,`adjustment_date` DATE NOT NULL,`reason` VARCHAR(150) NOT NULL,`status` VARCHAR(30) NOT NULL,`note` TEXT NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_adjustments_unique` (`business_id`,`adjustment_no`),KEY `egg_adjustments_date` (`business_id`,`adjustment_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_adjustment_lines` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`adjustment_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`pieces` INT NOT NULL,`unit_cost` DECIMAL(18,4) NOT NULL DEFAULT 0,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_adjustment_lines_parent` (`business_id`,`adjustment_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_product_mappings` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`grade_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`pieces_per_unit` INT UNSIGNED NOT NULL DEFAULT 1,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_product_mapping_unique` (`business_id`,`grade_id`,`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_integration_outbox` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`event_type` VARCHAR(100) NOT NULL,`aggregate_type` VARCHAR(50) NULL,`aggregate_id` BIGINT UNSIGNED NULL,`payload` JSON NOT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'pending',`attempts` INT UNSIGNED NOT NULL DEFAULT 0,`last_error` TEXT NULL,`processed_at` DATETIME NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_outbox_idx` (`business_id`,`status`,`event_type`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_share_links` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`token_hash` VARCHAR(64) NOT NULL,`resource_type` VARCHAR(50) NOT NULL,`resource_id` BIGINT UNSIGNED NULL,`format` VARCHAR(20) NOT NULL DEFAULT 'html',`parameters` JSON NULL,`expires_at` DATETIME NOT NULL,`used_at` DATETIME NULL,`created_by` BIGINT UNSIGNED NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_share_links_token` (`token_hash`),KEY `egg_share_links_resource` (`business_id`,`resource_type`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_audit_logs` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`user_id` BIGINT UNSIGNED NULL,`action` VARCHAR(50) NOT NULL,`auditable_type` VARCHAR(80) NOT NULL,`auditable_id` BIGINT UNSIGNED NULL,`before_data` JSON NULL,`after_data` JSON NULL,`ip_address` VARCHAR(64) NULL,`user_agent` VARCHAR(500) NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),KEY `egg_audit_logs_date` (`business_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `egg_access_grants` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`business_id` BIGINT UNSIGNED NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`permission` VARCHAR(120) NOT NULL,`allowed` TINYINT(1) NOT NULL DEFAULT 1,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY (`id`),UNIQUE KEY `egg_access_unique` (`business_id`,`user_id`,`permission`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SET FOREIGN_KEY_CHECKS=1;
