-- DANGER: Permanently deletes all Restaurant-New data in the current tenant database.
-- Never run during an upgrade or normal deployment.
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `restnew_manager_approvals`;
DROP TABLE IF EXISTS `restnew_order_adjustments`;
DROP TABLE IF EXISTS `restnew_discount_usages`;
DROP TABLE IF EXISTS `restnew_discount_rules`;
DROP TABLE IF EXISTS `restnew_delivery_dispatches`;
DROP TABLE IF EXISTS `restnew_delivery_zones`;
DROP TABLE IF EXISTS `restnew_wastage_lines`;
DROP TABLE IF EXISTS `restnew_wastages`;
DROP TABLE IF EXISTS `restnew_stocktake_lines`;
DROP TABLE IF EXISTS `restnew_stocktakes`;
DROP TABLE IF EXISTS `restnew_stock_transfer_lines`;
DROP TABLE IF EXISTS `restnew_stock_transfers`;
DROP TABLE IF EXISTS `restnew_goods_receipt_lines`;
DROP TABLE IF EXISTS `restnew_goods_receipts`;
DROP TABLE IF EXISTS `restnew_suppliers`;
DROP TABLE IF EXISTS `restnew_audit_logs`;
DROP TABLE IF EXISTS `restnew_daily_closures`;
DROP TABLE IF EXISTS `restnew_payments`;
DROP TABLE IF EXISTS `restnew_print_jobs`;
DROP TABLE IF EXISTS `restnew_reservations`;
DROP TABLE IF EXISTS `restnew_collection_tokens`;
DROP TABLE IF EXISTS `restnew_order_status_logs`;
DROP TABLE IF EXISTS `restnew_kitchen_ticket_items`;
DROP TABLE IF EXISTS `restnew_kitchen_tickets`;
DROP TABLE IF EXISTS `restnew_order_item_modifiers`;
DROP TABLE IF EXISTS `restnew_order_items`;
DROP TABLE IF EXISTS `restnew_orders`;
DROP TABLE IF EXISTS `restnew_shifts`;
DROP TABLE IF EXISTS `restnew_stock_movements`;
DROP TABLE IF EXISTS `restnew_inventory_balances`;
DROP TABLE IF EXISTS `restnew_recipe_lines`;
DROP TABLE IF EXISTS `restnew_recipes`;
DROP TABLE IF EXISTS `restnew_ingredients`;
DROP TABLE IF EXISTS `restnew_menu_item_modifier_groups`;
DROP TABLE IF EXISTS `restnew_modifiers`;
DROP TABLE IF EXISTS `restnew_modifier_groups`;
DROP TABLE IF EXISTS `restnew_menu_items`;
DROP TABLE IF EXISTS `restnew_categories`;
DROP TABLE IF EXISTS `restnew_user_screen_assignments`;
DROP TABLE IF EXISTS `restnew_printers`;
DROP TABLE IF EXISTS `restnew_kitchen_stations`;
DROP TABLE IF EXISTS `restnew_tables`;
DROP TABLE IF EXISTS `restnew_floors`;
DROP TABLE IF EXISTS `restnew_number_sequences`;
DROP TABLE IF EXISTS `restnew_settings`;
DELETE FROM `permissions` WHERE `guard_name`='web' AND `name` LIKE 'restaurant\_new.%';
SET FOREIGN_KEY_CHECKS = 1;
