@extends('ezylaw::layouts.module')
@section('ezylaw_title','Client Trust Accounting')
@section('ezylaw_content')
<div class="ezylaw-grid"><div class="law-card"><span>Trust Accounts</span><strong>{{ number_format($accounts->count()) }}</strong></div><div class="law-card"><span>Selected Balance</span><strong>{{ number_format((float)optional($account)->current_balance,2) }}</strong></div><div class="law-card"><span>Open Client Invoices</span><strong>{{ number_format($invoices->count()) }}</strong></div><div class="law-card"><span>Trust Principle</span><strong class="law-small-strong">Client funds ≠ income</strong></div></div>
<div class="row"><div class="col-md-3"><div class="box box-primary"><div class="box-header"><h3 class="box-title">Trust Account</h3></div><form method="post" action="{{ route('ezylaw.trust.accounts.store') }}"><div class="box-body">@csrf<label>Name</label><input class="form-control" name="name" required><label>Bank</label><input class="form-control" name="bank_name"><label>Account No</label><input class="form-control" name="account_no"><label>Currency</label><input class="form-control" name="currency"></div><div class="box-footer"><button class="btn btn-primary">Create Account</button></div></form></div></div>
<div class="col-md-9">@if(!$account)<div class="alert alert-warning">Create a trust account before entering client trust transactions.</div>@else
<div class="box"><div class="box-header"><h3 class="box-title">Transaction Entry</h3><form class="pull-right" method="get"><select name="account_id" onchange="this.form.submit()">@foreach($accounts as $a)<option value="{{ $a->id }}" {{ $account->id==$a->id?'selected':'' }}>{{ $a->name }} - {{ number_format((float)$a->current_balance,2) }}</option>@endforeach</select></form></div><div class="box-body"><div class="row">
<div class="col-md-4"><h4>Deposit Client Funds</h4><form method="post" action="{{ route('ezylaw.trust.deposit') }}">@csrf<input type="hidden" name="trust_account_id" value="{{ $account->id }}">@include('ezylaw::trust.partials.client_matter_fields',['clients'=>$clients,'matters'=>$matters])<label>Date</label><input class="form-control" type="date" name="transaction_date" value="{{ now()->toDateString() }}" required><label>Amount</label><input class="form-control text-right" type="number" step="0.0001" min="0.0001" name="amount" required><label>Reference</label><input class="form-control" name="reference"><label>Description</label><textarea class="form-control" name="description"></textarea><br><button class="btn btn-success">Record Deposit</button></form></div>
<div class="col-md-4"><h4>Refund / Disbursement</h4><form method="post" action="{{ route('ezylaw.trust.withdrawal') }}">@csrf<input type="hidden" name="trust_account_id" value="{{ $account->id }}">@include('ezylaw::trust.partials.client_matter_fields',['clients'=>$clients,'matters'=>$matters])<label>Type</label><select class="form-control" name="type"><option value="refund">Refund to Client</option><option value="disbursement">Client Disbursement</option></select><label>Date</label><input class="form-control" type="date" name="transaction_date" value="{{ now()->toDateString() }}" required><label>Amount</label><input class="form-control text-right" type="number" step="0.0001" min="0.0001" name="amount" required><label>Payee</label><input class="form-control" name="payee"><label>Reference</label><input class="form-control" name="reference"><br><button class="btn btn-warning">Record Withdrawal</button></form></div>
<div class="col-md-4"><h4>Apply Trust to Invoice</h4><form method="post" action="{{ route('ezylaw.trust.apply_invoice') }}">@csrf<input type="hidden" name="trust_account_id" value="{{ $account->id }}"><label>Invoice</label><select class="form-control" name="invoice_id" required><option value="">Please Select</option>@foreach($invoices as $i)<option value="{{ $i->id }}">{{ $i->invoice_no }} - {{ optional($i->client)->name }} - {{ number_format((float)$i->balance,2) }}</option>@endforeach</select><label>Date</label><input class="form-control" type="date" name="transaction_date" value="{{ now()->toDateString() }}" required><label>Amount</label><input class="form-control text-right" type="number" step="0.0001" min="0.0001" name="amount" required><label>Reference</label><input class="form-control" name="reference"><label>Description</label><textarea class="form-control" name="description"></textarea><br><button class="btn btn-info">Apply to Invoice</button></form></div>
</div></div></div>@endif</div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Trust Ledger</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Date</th><th>Client / Matter</th><th>Type</th><th>Reference</th><th class="text-right">In</th><th class="text-right">Out</th><th class="text-right">Running Balance</th><th>Finance</th></tr></thead><tbody>@forelse($transactions as $t)<tr><td>{{ optional($t->transaction_date)->format('Y-m-d') }}</td><td>{{ optional($t->client)->name }}<br><small>{{ optional($t->matter)->matter_no }}</small></td><td>{{ ucwords(str_replace('_',' ',$t->type)) }}</td><td>{{ $t->reference }}</td><td class="text-right">{{ $t->direction==='credit'?number_format((float)$t->amount,2):'' }}</td><td class="text-right">{{ $t->direction==='debit'?number_format((float)$t->amount,2):'' }}</td><td class="text-right">{{ number_format((float)$t->running_balance,2) }}</td><td><form method="post" action="{{ route('ezylaw.trust.sync',$t) }}">@csrf<button class="btn btn-xs btn-default">Sync</button></form></td></tr>@empty<tr><td colspan="8">No trust transactions.</td></tr>@endforelse</tbody></table>{{ $transactions->links() }}</div></div>
@endsection
