@extends('ezylaw::layouts.module')
@section('ezylaw_title',$matter->exists?'Edit Matter':'Add Matter')
@section('ezylaw_content')<form method="post" action="{{ $matter->exists?route('ezylaw.matters.update',$matter):route('ezylaw.matters.store') }}" class="box box-primary"><div class="box-body law-form-grid">@csrf @if($matter->exists)@method('PUT')@endif
<label>Matter No<input class="form-control" name="matter_no" value="{{ old('matter_no',$matter->matter_no) }}"></label><label>Client *<select class="form-control select2" name="client_id" required><option value="">Select</option>@foreach($clients as $c)<option value="{{ $c->id }}" @selected(old('client_id',$matter->client_id)==$c->id)>{{ $c->client_no }} - {{ $c->name }}</option>@endforeach</select></label>
<label>Case No<input class="form-control" name="case_no" value="{{ old('case_no',$matter->case_no) }}"></label><label>Title *<input class="form-control" name="title" value="{{ old('title',$matter->title) }}" required></label>
<label>Practice Area<select class="form-control" name="practice_area_id"><option value="">Select</option>@foreach($areas as $a)<option value="{{ $a->id }}" @selected(old('practice_area_id',$matter->practice_area_id)==$a->id)>{{ $a->name }}</option>@endforeach</select></label><label>Court<select class="form-control" name="court_id"><option value="">Select</option>@foreach($courts as $c)<option value="{{ $c->id }}" @selected(old('court_id',$matter->court_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label>
<label>Status<select class="form-control" name="status">@foreach(['open','pending','closed','archived'] as $s)<option value="{{ $s }}" @selected(old('status',$matter->status?:'open')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label><label>Priority<select class="form-control" name="priority">@foreach(['low','normal','high','urgent'] as $s)<option value="{{ $s }}" @selected(old('priority',$matter->priority?:'normal')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label>
<label>Opened On<input type="date" class="form-control" name="opened_on" value="{{ old('opened_on',optional($matter->opened_on)->format('Y-m-d')?:date('Y-m-d')) }}" required></label><label>Closed On<input type="date" class="form-control" name="closed_on" value="{{ old('closed_on',optional($matter->closed_on)->format('Y-m-d')) }}"></label>
<label>Opposing Party<input class="form-control" name="opposing_party" value="{{ old('opposing_party',$matter->opposing_party) }}"></label><label>Opposing Counsel<input class="form-control" name="opposing_counsel" value="{{ old('opposing_counsel',$matter->opposing_counsel) }}"></label>
<label>Fee Type<select class="form-control" name="fee_type">@foreach(['hourly','fixed','retainer','contingency','other'] as $s)<option value="{{ $s }}" @selected(old('fee_type',$matter->fee_type?:'hourly')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label><label>Hourly Rate<input type="number" step="0.0001" class="form-control" name="hourly_rate" value="{{ old('hourly_rate',$matter->hourly_rate) }}"></label><label>Fixed Fee<input type="number" step="0.0001" class="form-control" name="fixed_fee" value="{{ old('fixed_fee',$matter->fixed_fee) }}"></label><label>Retainer Amount<input type="number" step="0.0001" class="form-control" name="retainer_amount" value="{{ old('retainer_amount',$matter->retainer_amount) }}"></label>
<label class="law-span-2">Description<textarea class="form-control" name="description">{{ old('description',$matter->description) }}</textarea></label></div><div class="box-footer"><button class="btn btn-primary">Save Matter</button> <a class="btn btn-default" href="{{ route('ezylaw.matters.index') }}">Cancel</a></div></form>@endsection