<?php

return [
    'name' => 'PetroPDNew',
    'display_name' => 'Petro PD-New',
    'route_prefix' => 'petro-pd-new',
    'route_name' => 'petro-pd-new.',
    'table_prefix' => 'pdnew_',
    'asset_version' => '20260802-authoritative-404-fix-v105',
    'auto_install_schema' => false,
    'source' => [
        'driver' => 'pumper_dashboard_new',
        'required_tables' => [
            'pone_shifts',
            'pone_pump_assignments',
            'pone_meter_readings',
            'pone_payments',
            'pone_payment_cash_denominations',
            'pone_payment_card_lines',
            'pone_credit_sales',
            'pone_credit_sale_lines',
            'pone_other_sales',
            'pone_other_sale_lines',
            'pone_unload_stocks',
            'pone_unload_stock_lines',
            'pone_day_entries',
            'pone_daily_collections',
            'pone_shortage_recoveries',
            'pone_excess_commissions',
            'pone_operator_ledger_entries',
            'pone_pd_operators',
            'pone_shift_settlement_references',
        ],
        'closed_statuses' => ['closed'],
        'allow_multiple_shifts_per_settlement' => false,
        'verify_hash_before_finalize' => true,
    ],
    'defaults' => [
        'settlement_prefix' => 'PDN-SET-',
        'day_end_prefix' => 'PDN-DE-',
        'adjustment_prefix' => 'PDN-ADJ-',
        'posting_prefix' => 'PDN-PST-',
        'amount_decimals' => 4,
        'quantity_decimals' => 3,
        'require_review' => true,
        'require_approval' => true,
        'require_zero_variance' => true,
        'allow_reopen' => true,
        'allow_finalize_with_warnings' => false,
        'auto_import_closed_shifts' => false,
        'receipt_paper_size' => 'A4',
    ],
    'statuses' => [
        'draft', 'review', 'approved', 'finalizing', 'finalized', 'reopened', 'cancelled',
    ],
    'payment_types' => [
        'cash', 'card', 'cheque', 'credit', 'expense', 'customer_loan',
        'loan_payment', 'owner_drawing', 'cash_deposit', 'shortage',
        'excess', 'pos', 'other_income', 'customer_payment',
    ],
];
