<?php

/*
 * Global Manage contract for Petro PD-New.
 *
 * Keep this list limited to the module parent, real menu pages and visible tab
 * pages. Action permissions remain in Permissions/permissions.php and roles.
 */
return [
    ['key' => 'petro_pd_new_module', 'label' => 'Petro PD-New Module', 'type' => 'module'],

    [
        'key' => 'petro_pd_new_dashboard',
        'label' => 'Dashboard',
        'type' => 'page',
        'route_paths' => ['petro-pd-new', 'petro-pd-new/dashboard'],
    ],
    [
        'key' => 'petro_pd_new_source_shifts',
        'label' => 'PD Closed Shifts',
        'type' => 'page',
        'route_paths' => [
            'petro-pd-new/source-shifts',
            'petro-pd-new/source-shifts/{shift}',
            'petro-pd-new/source-shifts/{shift}/import',
            'petro-pd-new/source-shifts/{shift}/create-settlement',
            'petro-pd-new/source-imports/{source}/verify',
        ],
    ],
    [
        'key' => 'petro_pd_new_settlements',
        'label' => 'PD Settlements',
        'type' => 'page',
        'route_paths' => [
            'petro-pd-new/settlements',
            'petro-pd-new/settlements/create',
            'petro-pd-new/settlements/{settlement}',
            'petro-pd-new/settlements/{settlement}/edit',
            'petro-pd-new/settlements/{settlement}/refresh-source',
            'petro-pd-new/settlements/{settlement}/cancel',
            'petro-pd-new/settlements/{settlement}/submit',
            'petro-pd-new/settlements/{settlement}/return',
            'petro-pd-new/settlements/{settlement}/approve',
            'petro-pd-new/settlements/{settlement}/finalize',
            'petro-pd-new/settlements/{settlement}/reopen',
            'petro-pd-new/settlements/{settlement}/reconcile',
            'petro-pd-new/settlements/{settlement}/payments',
            'petro-pd-new/settlements/{settlement}/adjustments',
            'petro-pd-new/settlements/{settlement}/documents',
            'petro-pd-new/settlements/{settlement}/print',
            'petro-pd-new/payments/{payment}',
            'petro-pd-new/payments/check-reference',
            'petro-pd-new/adjustments/{adjustment}/approve',
            'petro-pd-new/adjustments/{adjustment}/reject',
            'petro-pd-new/reconciliation-issues/{issue}/resolve',
            'petro-pd-new/documents/{document}/download',
            'petro-pd-new/documents/{document}',
        ],
    ],
    [
        'key' => 'petro_pd_new_day_end',
        'label' => 'Day End',
        'type' => 'page',
        'route_paths' => [
            'petro-pd-new/day-ends',
            'petro-pd-new/day-ends/create',
            'petro-pd-new/day-ends/{dayEnd}',
            'petro-pd-new/day-ends/{dayEnd}/refresh',
            'petro-pd-new/day-ends/{dayEnd}/finalize',
            'petro-pd-new/day-ends/{dayEnd}/print',
        ],
    ],
    [
        'key' => 'petro_pd_new_operators',
        'label' => 'PD Operators',
        'type' => 'page',
        'route_paths' => [
            'petro-pd-new/operators',
            'petro-pd-new/operators/sync',
            'petro-pd-new/operators/{operator}',
            'petro-pd-new/operators/{operator}/action/{section}',
            'petro-pd-new/operators/{operator}/profile',
            'petro-pd-new/operators/{operator}/toggle',
            'petro-pd-new/operators/{operator}/commission',
            'petro-pd-new/operators/{operator}/recovery',
            'petro-pd-new/operators/{operator}/notes',
            'petro-pd-new/operators/{operator}/documents',
            'petro-pd-new/operators/{operator}/documents/{document}/download',
        ],
    ],


    ['key' => 'petro_pd_new_operator_pump_operators', 'label' => 'Pump Operators', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-pump_operators']],
    ['key' => 'petro_pd_new_operator_excess_shortage', 'label' => 'Pumper Excess / Shortage Payments', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-pumper_excess_shortage_payments']],
    ['key' => 'petro_pd_new_operator_day_entries', 'label' => 'Pumper Day Entries', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-pumper_day_entries']],
    ['key' => 'petro_pd_new_operator_shift_summary', 'label' => 'Shift Summary', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-shift_summary']],
    ['key' => 'petro_pd_new_operator_payment_summary', 'label' => 'Payment Summary', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-payment_summary']],
    ['key' => 'petro_pd_new_operator_meters_with_payments', 'label' => 'Meters with Payments', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-meters_with_payments']],
    ['key' => 'petro_pd_new_operator_daily_pump_status', 'label' => 'Daily Pump Status', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-daily_pump_status']],
    ['key' => 'petro_pd_new_operator_close_shift', 'label' => 'Close Shift', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-close_shift']],
    ['key' => 'petro_pd_new_operator_current_meter', 'label' => 'Current Meter', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-current_meter']],
    ['key' => 'petro_pd_new_operator_unload_stock', 'label' => 'Unload Stock', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-unload_stock']],
    ['key' => 'petro_pd_new_operator_day_end_settlements', 'label' => 'Day End – Settlements', 'type' => 'tab', 'selectors' => ['#pdn-operator-tab-pd_day_end_settlement']],

    [
        'key' => 'petro_pd_new_reports',
        'label' => 'Reports',
        'type' => 'page',
        'route_paths' => ['petro-pd-new/reports', 'petro-pd-new/reports/{report}'],
    ],
    [
        'key' => 'petro_pd_new_integration',
        'label' => 'PD Integration',
        'type' => 'page',
        'route_paths' => [
            'petro-pd-new/integration',
            'petro-pd-new/integration/retry-all',
            'petro-pd-new/integration/verify-sources',
            'petro-pd-new/integration/{job}/retry',
        ],
    ],
    [
        'key' => 'petro_pd_new_notifications',
        'label' => 'Notifications',
        'type' => 'page',
        'route_paths' => ['petro-pd-new/notifications', 'petro-pd-new/notifications/{template}'],
    ],
    [
        'key' => 'petro_pd_new_audit',
        'label' => 'User Activity',
        'type' => 'page',
        'route_paths' => ['petro-pd-new/audit'],
    ],
    [
        'key' => 'petro_pd_new_settings',
        'label' => 'Settings',
        'type' => 'page',
        'route_paths' => ['petro-pd-new/settings'],
    ],

    ['key' => 'petro_pd_new_settlement_pumps', 'label' => 'Pump & Meter Sales', 'type' => 'tab', 'selectors' => ['#pdn-tab-pumps', '#pdn-pumps']],
    ['key' => 'petro_pd_new_settlement_payments', 'label' => 'Payments', 'type' => 'tab', 'selectors' => ['#pdn-tab-payments', '#pdn-payments']],
    ['key' => 'petro_pd_new_settlement_credit_sales', 'label' => 'Credit Sales', 'type' => 'tab', 'selectors' => ['#pdn-tab-credit', '#pdn-credit']],
    ['key' => 'petro_pd_new_settlement_other_operations', 'label' => 'Other Operations', 'type' => 'tab', 'selectors' => ['#pdn-tab-other', '#pdn-other']],
    ['key' => 'petro_pd_new_settlement_adjustments', 'label' => 'Adjust Amounts', 'type' => 'tab', 'selectors' => ['#pdn-tab-adjustments', '#pdn-adjustments']],
    ['key' => 'petro_pd_new_settlement_reconciliation', 'label' => 'Reconciliation', 'type' => 'tab', 'selectors' => ['#pdn-tab-reconciliation', '#pdn-reconciliation']],
    ['key' => 'petro_pd_new_settlement_documents', 'label' => 'Documents', 'type' => 'tab', 'selectors' => ['#pdn-tab-documents', '#pdn-documents']],
    ['key' => 'petro_pd_new_settlement_history', 'label' => 'History', 'type' => 'tab', 'selectors' => ['#pdn-tab-history', '#pdn-history']],

    ['key' => 'petro_pd_new_report_settlements', 'label' => 'Settlements Report', 'type' => 'tab', 'selectors' => ['#pdn-report-settlements-tab'], 'route_paths' => ['petro-pd-new/reports/settlements', 'petro-pd-new/reports/settlements/print', 'petro-pd-new/reports/settlements/export/{format}']],
    ['key' => 'petro_pd_new_report_shifts', 'label' => 'Shifts Report', 'type' => 'tab', 'selectors' => ['#pdn-report-shifts-tab'], 'route_paths' => ['petro-pd-new/reports/shifts', 'petro-pd-new/reports/shifts/print', 'petro-pd-new/reports/shifts/export/{format}']],
    ['key' => 'petro_pd_new_report_operators', 'label' => 'Operator Summary Report', 'type' => 'tab', 'selectors' => ['#pdn-report-operators-tab'], 'route_paths' => ['petro-pd-new/reports/operators', 'petro-pd-new/reports/operators/print', 'petro-pd-new/reports/operators/export/{format}']],
    ['key' => 'petro_pd_new_report_operator_payments', 'label' => 'Operator Payments Report', 'type' => 'tab', 'selectors' => ['#pdn-report-operator-payments-tab'], 'route_paths' => ['petro-pd-new/reports/operator_payments', 'petro-pd-new/reports/operator_payments/print', 'petro-pd-new/reports/operator_payments/export/{format}']],
    ['key' => 'petro_pd_new_report_payments', 'label' => 'Settlement Payments Report', 'type' => 'tab', 'selectors' => ['#pdn-report-payments-tab'], 'route_paths' => ['petro-pd-new/reports/payments', 'petro-pd-new/reports/payments/print', 'petro-pd-new/reports/payments/export/{format}']],
    ['key' => 'petro_pd_new_report_meters', 'label' => 'Meter Sales Report', 'type' => 'tab', 'selectors' => ['#pdn-report-meters-tab'], 'route_paths' => ['petro-pd-new/reports/meters', 'petro-pd-new/reports/meters/print', 'petro-pd-new/reports/meters/export/{format}']],
    ['key' => 'petro_pd_new_report_other_sales', 'label' => 'Other Sales Report', 'type' => 'tab', 'selectors' => ['#pdn-report-other-sales-tab'], 'route_paths' => ['petro-pd-new/reports/other_sales', 'petro-pd-new/reports/other_sales/print', 'petro-pd-new/reports/other_sales/export/{format}']],
    ['key' => 'petro_pd_new_report_unloads', 'label' => 'Unload Stock Report', 'type' => 'tab', 'selectors' => ['#pdn-report-unloads-tab'], 'route_paths' => ['petro-pd-new/reports/unloads', 'petro-pd-new/reports/unloads/print', 'petro-pd-new/reports/unloads/export/{format}']],
    ['key' => 'petro_pd_new_report_day_entries', 'label' => 'Day Entries Report', 'type' => 'tab', 'selectors' => ['#pdn-report-day-entries-tab'], 'route_paths' => ['petro-pd-new/reports/day_entries', 'petro-pd-new/reports/day_entries/print', 'petro-pd-new/reports/day_entries/export/{format}']],
    ['key' => 'petro_pd_new_report_collections', 'label' => 'Daily Collections Report', 'type' => 'tab', 'selectors' => ['#pdn-report-collections-tab'], 'route_paths' => ['petro-pd-new/reports/collections', 'petro-pd-new/reports/collections/print', 'petro-pd-new/reports/collections/export/{format}']],
    ['key' => 'petro_pd_new_report_ledger', 'label' => 'Operator Ledger Report', 'type' => 'tab', 'selectors' => ['#pdn-report-ledger-tab'], 'route_paths' => ['petro-pd-new/reports/ledger', 'petro-pd-new/reports/ledger/print', 'petro-pd-new/reports/ledger/export/{format}']],
    ['key' => 'petro_pd_new_report_shortages', 'label' => 'Shortage Recoveries Report', 'type' => 'tab', 'selectors' => ['#pdn-report-shortages-tab'], 'route_paths' => ['petro-pd-new/reports/shortages', 'petro-pd-new/reports/shortages/print', 'petro-pd-new/reports/shortages/export/{format}']],
    ['key' => 'petro_pd_new_report_commissions', 'label' => 'Excess Commissions Report', 'type' => 'tab', 'selectors' => ['#pdn-report-commissions-tab'], 'route_paths' => ['petro-pd-new/reports/commissions', 'petro-pd-new/reports/commissions/print', 'petro-pd-new/reports/commissions/export/{format}']],
    ['key' => 'petro_pd_new_report_day_end', 'label' => 'Day End Report', 'type' => 'tab', 'selectors' => ['#pdn-report-day-end-tab'], 'route_paths' => ['petro-pd-new/reports/day_end', 'petro-pd-new/reports/day_end/print', 'petro-pd-new/reports/day_end/export/{format}']],
    ['key' => 'petro_pd_new_report_reconciliation', 'label' => 'Payment Reconciliation Report', 'type' => 'tab', 'selectors' => ['#pdn-report-reconciliation-tab'], 'route_paths' => ['petro-pd-new/reports/reconciliation', 'petro-pd-new/reports/reconciliation/print', 'petro-pd-new/reports/reconciliation/export/{format}']],
    ['key' => 'petro_pd_new_report_adjustments', 'label' => 'Adjusted Amounts Report', 'type' => 'tab', 'selectors' => ['#pdn-report-adjustments-tab'], 'route_paths' => ['petro-pd-new/reports/adjustments', 'petro-pd-new/reports/adjustments/print', 'petro-pd-new/reports/adjustments/export/{format}']],
    ['key' => 'petro_pd_new_report_integrity', 'label' => 'Source Integrity Report', 'type' => 'tab', 'selectors' => ['#pdn-report-integrity-tab'], 'route_paths' => ['petro-pd-new/reports/integrity', 'petro-pd-new/reports/integrity/print', 'petro-pd-new/reports/integrity/export/{format}']],
    ['key' => 'petro_pd_new_report_activity', 'label' => 'User Activity Report', 'type' => 'tab', 'selectors' => ['#pdn-report-activity-tab'], 'route_paths' => ['petro-pd-new/reports/activity', 'petro-pd-new/reports/activity/print', 'petro-pd-new/reports/activity/export/{format}']],
    ['key' => 'petro_pd_new_report_integration', 'label' => 'Integration Report', 'type' => 'tab', 'selectors' => ['#pdn-report-integration-tab'], 'route_paths' => ['petro-pd-new/reports/integration', 'petro-pd-new/reports/integration/print', 'petro-pd-new/reports/integration/export/{format}']],
    ['key' => 'petro_pd_new_report_print_history', 'label' => 'Print History Report', 'type' => 'tab', 'selectors' => ['#pdn-report-print-history-tab'], 'route_paths' => ['petro-pd-new/reports/print_history', 'petro-pd-new/reports/print_history/print', 'petro-pd-new/reports/print_history/export/{format}']],
];
