@extends('airlineticketingnew::layouts.app')
@section('atn-title', $reservation->reservation_no)
@section('atn-content')
@include('airlineticketingnew::transactions.navigation')
<div class="atn-panel"><div class="atn-panel-header atn-flex-between"><h4>{{ $reservation->reservation_no }} @if($reservation->pnr_code) / {{ $reservation->pnr_code }} @endif</h4><span class="label label-primary">{{ $reservation->status }}</span></div>
<div class="atn-panel-body"><div class="row"><div class="col-md-3"><strong>{{ __('airlineticketingnew::transactions.reservation_date') }}</strong><br>{{ optional($reservation->reservation_date)->format('Y-m-d') }}</div><div class="col-md-3"><strong>{{ __('airlineticketingnew::transactions.ticketing_deadline') }}</strong><br>{{ $reservation->ticketing_deadline }}</div><div class="col-md-3"><strong>{{ __('airlineticketingnew::transactions.grand_total') }}</strong><br>{{ number_format((float)$reservation->grand_total,4) }}</div><div class="col-md-3"><strong>{{ __('airlineticketingnew::transactions.due_total') }}</strong><br>{{ number_format((float)$reservation->due_total,4) }}</div></div></div></div>
<div class="atn-panel"><div class="atn-panel-header"><h4>{{ __('airlineticketingnew::transactions.itinerary') }}</h4></div><div class="table-responsive"><table class="table table-bordered atn-table"><thead><tr><th>#</th><th>{{ __('airlineticketingnew::transactions.flight_number') }}</th><th>{{ __('airlineticketingnew::transactions.departure') }}</th><th>{{ __('airlineticketingnew::transactions.arrival') }}</th><th>{{ __('airlineticketingnew::transactions.status') }}</th></tr></thead><tbody>@foreach($reservation->segments as $segment)<tr><td>{{ $segment->segment_no }}</td><td>{{ $segment->flight_number }}</td><td>{{ $segment->departure_at }}</td><td>{{ $segment->arrival_at }}</td><td>{{ $segment->segment_status }}</td></tr>@endforeach</tbody></table></div></div>
@can('airline_ticketing_new.reservations.status')
<div class="atn-panel"><form method="POST" action="{{ route('airline-ticketing-new.reservations.status',$reservation) }}">@csrf
<div class="atn-panel-header"><h4>{{ __('airlineticketingnew::transactions.change_status') }}</h4></div><div class="atn-panel-body"><div class="row"><div class="col-md-4"><select class="form-control" name="status">@foreach(['reserved','confirmed','on_hold','cancelled','expired','ticketed'] as $status)<option value="{{ $status }}">{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="col-md-8"><input class="form-control" name="reason" placeholder="{{ __('airlineticketingnew::transactions.reason') }}"></div></div></div><div class="atn-panel-footer text-right"><button class="btn btn-primary">{{ __('airlineticketingnew::transactions.update_status') }}</button></div>
</form></div>
@endcan
<div class="atn-panel"><div class="atn-panel-header"><h4>{{ __('airlineticketingnew::transactions.status_history') }}</h4></div><div class="table-responsive"><table class="table table-bordered atn-table"><thead><tr><th>{{ __('airlineticketingnew::transactions.changed_at') }}</th><th>{{ __('airlineticketingnew::transactions.from_status') }}</th><th>{{ __('airlineticketingnew::transactions.to_status') }}</th><th>{{ __('airlineticketingnew::transactions.reason') }}</th></tr></thead><tbody>@foreach($reservation->statusHistory as $history)<tr><td>{{ $history->changed_at }}</td><td>{{ $history->from_status }}</td><td>{{ $history->to_status }}</td><td>{{ $history->reason }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
