-- DANGER: removes Petro Direct-New data from the current tenant database.
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `pdirectnew_saved_report_filters`;
DROP TABLE IF EXISTS `pdirectnew_audit_logs`;
DROP TABLE IF EXISTS `pdirectnew_print_logs`;
DROP TABLE IF EXISTS `pdirectnew_adjustments`;
DROP TABLE IF EXISTS `pdirectnew_dip_readings`;
DROP TABLE IF EXISTS `pdirectnew_dip_chart_lines`;
DROP TABLE IF EXISTS `pdirectnew_dip_charts`;
DROP TABLE IF EXISTS `pdirectnew_tank_transfers`;
DROP TABLE IF EXISTS `pdirectnew_unload_stock_lines`;
DROP TABLE IF EXISTS `pdirectnew_unload_stocks`;
DROP TABLE IF EXISTS `pdirectnew_pumper_day_entries`;
DROP TABLE IF EXISTS `pdirectnew_collection_lines`;
DROP TABLE IF EXISTS `pdirectnew_daily_collections`;
DROP TABLE IF EXISTS `pdirectnew_settlement_customer_payments`;
DROP TABLE IF EXISTS `pdirectnew_settlement_other_income`;
DROP TABLE IF EXISTS `pdirectnew_settlement_other_sale_lines`;
DROP TABLE IF EXISTS `pdirectnew_settlement_other_sales`;
DROP TABLE IF EXISTS `pdirectnew_settlement_payments`;
DROP TABLE IF EXISTS `pdirectnew_settlement_meter_sales`;
DROP TABLE IF EXISTS `pdirectnew_settlements`;
DROP TABLE IF EXISTS `pdirectnew_meter_resets`;
DROP TABLE IF EXISTS `pdirectnew_meter_readings`;
DROP TABLE IF EXISTS `pdirectnew_assignments`;
DROP TABLE IF EXISTS `pdirectnew_shifts`;
DROP TABLE IF EXISTS `pdirectnew_pumps`;
DROP TABLE IF EXISTS `pdirectnew_tanks`;
DROP TABLE IF EXISTS `pdirectnew_operators`;
DROP TABLE IF EXISTS `pdirectnew_number_sequences`;
DROP TABLE IF EXISTS `pdirectnew_settings`;
DELETE FROM `permissions` WHERE `name` LIKE 'petro_direct_new.%';
SET FOREIGN_KEY_CHECKS=1;
