@extends('layouts.app')
@section('title',$settlement->exists?'Edit Direct Settlement':'Add Direct Settlement')
@section('content')<div class="pdirectnew-module container-fluid py-3">@include('petrodirectnew::partials.styles')
<div class="pdn-page-head"><div><h1>{{ $settlement->exists?'Edit Direct Settlement':'Add Direct Settlement' }}</h1><p>Meter sales, other sales, income, customer receipts and settlement payments.</p></div><a class="btn btn-default" href="{{ route('petro-direct-new.settlements.index') }}">List Direct Settlements</a></div>
@if($errors->any())<div class="alert alert-danger"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $settlement->exists?route('petro-direct-new.settlements.update',$settlement->id):route('petro-direct-new.settlements.store') }}" id="pdirectnew-settlement-form">@csrf @if($settlement->exists)@method('PUT')@endif
<div class="pdn-card"><div class="row"><div class="col-md-3"><label>Business Location *</label><select name="location_id" class="form-control" required><option value="">Select</option>@foreach($locations as $loc)<option value="{{ $loc->id }}" @selected(old('location_id',$settlement->location_id)==$loc->id)>{{ $loc->name }}</option>@endforeach</select></div><div class="col-md-3"><label>Shift No</label><select name="shift_id" class="form-control"><option value="">Manual / No Shift</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" @selected(old('shift_id',$settlement->shift_id)==$shift->id)>{{ $shift->shift_no }} - {{ $shift->status }}</option>@endforeach</select></div><div class="col-md-3"><label>Pump Operator *</label><select name="operator_id" class="form-control" required><option value="">Select</option>@foreach($operators as $operator)<option value="{{ $operator->id }}" @selected(old('operator_id',$settlement->operator_id)==$operator->id)>{{ $operator->name }}</option>@endforeach</select></div><div class="col-md-2"><label>Transaction Date *</label><input type="date" name="transaction_date" class="form-control" required value="{{ old('transaction_date',$settlement->transaction_date?optional($settlement->transaction_date)->format('Y-m-d'):date('Y-m-d')) }}"></div><div class="col-md-1"><label>Work Shift</label><input name="work_shift" class="form-control" value="{{ old('work_shift',$settlement->work_shift) }}"></div></div><div class="row mt-3"><div class="col-md-12"><label>Note</label><textarea name="note" class="form-control">{{ old('note',$settlement->note) }}</textarea></div></div></div>
<div class="pdn-card"><div class="pdn-tabs"><a href="#" class="active" data-pdn-form-tab="meter">Meter Sales</a><a href="#" data-pdn-form-tab="payment">Payments</a><a href="#" data-pdn-form-tab="other-sale">Other Sales</a><a href="#" data-pdn-form-tab="income">Other Income</a><a href="#" data-pdn-form-tab="customer">Customer Payment</a></div>
<div data-pdn-panel="meter"><h3>Meter Sales</h3><div class="pdn-scroll"><table class="table table-bordered" id="pdn-meter-table"><thead><tr><th>Pump</th><th>Product</th><th>Opening Meter</th><th>Closing Meter</th><th>Testing Qty</th><th>Sold Qty</th><th>Unit Price</th><th>Discount</th><th>Amount</th><th></th></tr></thead><tbody>@php($meterRows=old('meter_sales',$settlement->exists?$settlement->meterSales->toArray():[[]]))@foreach($meterRows as $i=>$row)@include('petrodirectnew::settlements.partials.meter-row',['i'=>$i,'row'=>$row])@endforeach</tbody></table></div><button type="button" class="btn btn-info" data-pdn-add="meter">Add Meter Row</button></div>
<div data-pdn-panel="payment" style="display:none"><h3>Settlement Payments</h3><div class="pdn-scroll"><table class="table table-bordered" id="pdn-payment-table"><thead><tr><th>Type</th><th>Reference</th><th>Customer</th><th>Account</th><th>Amount</th><th></th></tr></thead><tbody>@php($paymentRows=old('payments',$settlement->exists?$settlement->payments->toArray():[[]]))@foreach($paymentRows as $i=>$row)@include('petrodirectnew::settlements.partials.payment-row',['i'=>$i,'row'=>$row])@endforeach</tbody></table></div><button type="button" class="btn btn-info" data-pdn-add="payment">Add Payment</button></div>

<div data-pdn-panel="other-sale" style="display:none"><h3>Other Sales</h3><div class="pdn-scroll"><table class="table table-bordered" id="pdn-other-sale-table"><thead><tr><th>Reference</th><th>Customer</th><th>Product</th><th>Qty</th><th>Unit Price</th><th></th></tr></thead><tbody>@php($otherSaleRows=old('other_sales',$settlement->exists?$settlement->otherSales->load('lines')->toArray():[[]]))@foreach($otherSaleRows as $i=>$row)@include('petrodirectnew::settlements.partials.other-sale-row',['i'=>$i,'row'=>$row])@endforeach</tbody></table></div><button type="button" class="btn btn-info" data-pdn-add="other-sale">Add Other Sale</button></div>
<div data-pdn-panel="income" style="display:none"><h3>Other Income</h3><table class="table table-bordered" id="pdn-income-table"><thead><tr><th>Description</th><th>Account</th><th>Amount</th><th></th></tr></thead><tbody>@php($incomeRows=old('other_income',$settlement->exists?$settlement->otherIncome->toArray():[[]]))@foreach($incomeRows as $i=>$row)@include('petrodirectnew::settlements.partials.income-row',['i'=>$i,'row'=>$row])@endforeach</tbody></table><button type="button" class="btn btn-info" data-pdn-add="income">Add Other Income</button></div>
<div data-pdn-panel="customer" style="display:none"><h3>Customer Payments</h3><table class="table table-bordered" id="pdn-customer-table"><thead><tr><th>Customer</th><th>Reference</th><th>Method</th><th>Amount</th><th></th></tr></thead><tbody>@php($customerRows=old('customer_payments',$settlement->exists?$settlement->customerPayments->toArray():[[]]))@foreach($customerRows as $i=>$row)@include('petrodirectnew::settlements.partials.customer-row',['i'=>$i,'row'=>$row])@endforeach</tbody></table><button type="button" class="btn btn-info" data-pdn-add="customer">Add Customer Payment</button></div></div>
<div class="pdn-card text-right"><button class="btn btn-primary btn-lg">Save Direct Settlement</button></div></form></div>
<script>window.PDIRECTNEW_FORM_DATA={products:@json($products),pumps:@json($pumps),contacts:@json($contacts),accounts:@json($accounts)};</script><script>@include('petrodirectnew::partials.form-script')</script>@endsection
