@extends('petropdnew::layouts.app')
@section('title','Day End '.$dayEnd->day_end_number)
@section('page_title','Day End '.$dayEnd->day_end_number)
@section('pdnew_content')
<div class="pdn-page-head"><div><h2>{{ $dayEnd->day_end_number }}</h2><p>{{ optional($dayEnd->day_end_date)->format('d M Y') }} • Location {{ $dayEnd->location_id ?: 'All' }}</p></div><div class="pdn-actions"><a class="pdn-btn light" href="{{ route('petro-pd-new.day-ends.index') }}">Back</a><a class="pdn-btn purple" target="_blank" href="{{ route('petro-pd-new.day-ends.print',$dayEnd->id) }}">Print</a>
@if($dayEnd->status==='prepared')@can('petro_pd_new.day_end.manage')<form method="post" action="{{ route('petro-pd-new.day-ends.refresh',$dayEnd->id) }}" data-prevent-double-submit>@csrf<button class="pdn-btn warning">Refresh</button></form>@endcan
@can('petro_pd_new.day_end.finalize')<form method="post" action="{{ route('petro-pd-new.day-ends.finalize',$dayEnd->id) }}" data-confirm="Finalize this Day End?" data-prevent-double-submit>@csrf<input type="hidden" name="note" value="Finalized from Day End screen"><button class="pdn-btn success">Finalize</button></form>@endcan @endif
</div></div>
<div class="pdn-card"><div class="pdn-summary"><div class="pdn-summary-item"><span>Status</span><strong><span class="pdn-badge {{ $dayEnd->status }}">{{ $dayEnd->status }}</span></strong></div><div class="pdn-summary-item"><span>Settlement Count</span><strong>{{ $dayEnd->settlement_count }}</strong></div><div class="pdn-summary-item"><span>Settlement Total</span><strong>{{ number_format((float)$dayEnd->settlements_total,4) }}</strong></div><div class="pdn-summary-item"><span>Payment Total</span><strong>{{ number_format((float)$dayEnd->payments_total,4) }}</strong></div><div class="pdn-summary-item"><span>Variance Total</span><strong>{{ number_format((float)$dayEnd->variance_total,4) }}</strong></div><div class="pdn-summary-item"><span>Prepared At</span><strong>{{ optional($dayEnd->prepared_at)->format('d M Y H:i') }}</strong></div><div class="pdn-summary-item"><span>Finalized At</span><strong>{{ optional($dayEnd->finalized_at)->format('d M Y H:i') ?: '—' }}</strong></div></div>@if($dayEnd->note)<div class="pdn-note">{{ $dayEnd->note }}</div>@endif</div>
<div class="pdn-card" style="margin-top:14px"><h3>Included Settlements</h3><div class="pdn-table-wrap"><table class="pdn-table"><thead><tr><th>Settlement</th><th>PONE Shift</th><th>Operator</th><th>Date</th><th class="amount">Expected</th><th class="amount">Payments</th><th class="amount">Variance</th><th>Action</th></tr></thead><tbody>
@forelse($dayEnd->settlements as $row)<tr><td>{{ $row->settlement_number }}</td><td>{{ $row->pone_shift_number }}</td><td>{{ $row->operator_name }}</td><td>{{ optional($row->settlement_date)->format('d M Y') }}</td><td class="amount">{{ number_format((float)$row->pivot->settlement_amount,4) }}</td><td class="amount">{{ number_format((float)$row->pivot->payment_amount,4) }}</td><td class="amount">{{ number_format((float)$row->pivot->variance_amount,4) }}</td><td><a class="pdn-btn small primary" href="{{ route('petro-pd-new.settlements.show',$row->id) }}">View</a></td></tr>@empty<tr><td colspan="8" class="pdn-empty">No finalized settlements were available for this Day End.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
