@extends('pumperdashboardnew::layouts.operator')
@section('title','Daily Collection')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Collection & Reconciliation</div><h1>Daily Collection</h1><p>Shift {{ $shift->shift_number }} · declare the physical/confirmed collection by payment method.</p></div><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.dashboard') }}">Dashboard</a></div>
<div class="pone-grid pone-grid-6" style="margin-bottom:16px">@foreach(['expected_amount'=>'Expected','cash_amount'=>'Cash Payments','card_amount'=>'Card Payments','cheque_amount'=>'Cheque Payments','credit_amount'=>'Credit Sales','other_amount'=>'Other'] as $key=>$label)<div class="pone-stat"><div class="pone-stat-label">{{ $label }}</div><div class="pone-stat-value">{{ number_format((float)($breakdown[$key]??0),4) }}</div></div>@endforeach</div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Confirm Collection</h2></div><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.collections.store') }}" data-confirm-message="Confirm this collection declaration?" data-processing-text="Confirming collection…">@csrf<div class="pone-form-grid">
<div class="pone-field pone-col-3"><label>Collection Form No.</label><input name="collection_number" maxlength="100" placeholder="Auto generated when blank"></div><div class="pone-field pone-col-3"><label>Collection Date/Time</label><input name="collection_at" type="datetime-local" value="{{ now()->format('Y-m-d\TH:i') }}"></div><div class="pone-field pone-col-6"><label>Note</label><input name="note" maxlength="2000"></div>
@foreach(['cash_amount'=>'Cash','card_amount'=>'Card','cheque_amount'=>'Cheque','credit_amount'=>'Credit','other_amount'=>'Other'] as $field=>$label)<div class="pone-field pone-col-2"><label>{{ $label }} Amount</label><input name="{{ $field }}" data-collection-amount type="number" min="0" step="0.0001" value="{{ number_format((float)($breakdown[$field]??0),4,'.','') }}"></div>@endforeach<div class="pone-field pone-col-2"><label>Declared Total</label><div class="pone-readonly-total" data-collection-total>{{ number_format(array_sum(array_map('floatval',array_intersect_key($breakdown,array_flip(['cash_amount','card_amount','cheque_amount','credit_amount','other_amount'])))),4) }}</div></div>
</div><div class="pone-actions pone-actions-end" style="margin-top:16px"><button class="pone-btn pone-btn-success">Confirm Collection</button></div></form></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Collection History</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table"><thead><tr><th>Collection No.</th><th>Date/Time</th><th class="pone-text-right">Expected</th><th class="pone-text-right">Declared</th><th class="pone-text-right">Difference</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($collections as $collection)<tr class="{{ $collection->status==='void'?'is-void':'' }}"><td><strong>{{ $collection->collection_number }}</strong></td><td>{{ optional($collection->collection_at)->format('Y-m-d H:i') }}</td><td class="pone-text-right">{{ number_format((float)$collection->expected_amount,4) }}</td><td class="pone-text-right">{{ number_format((float)$collection->declared_amount,4) }}</td><td class="pone-text-right {{ (float)$collection->difference_amount>0?'pone-danger-text':((float)$collection->difference_amount<0?'pone-success-text':'') }}">{{ number_format((float)$collection->difference_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $collection->status }}">{{ $collection->status }}</span></td><td><div class="pone-actions"><a class="pone-btn pone-btn-light pone-btn-sm" href="{{ route('pumper-dashboard-new.operator.collections.show',$collection) }}">View</a><a class="pone-btn pone-btn-primary pone-btn-sm" href="{{ route('pumper-dashboard-new.operator.collections.print',$collection) }}?paper_size=80mm">Print</a>@if($collection->status==='confirmed')<form method="post" action="{{ route('pumper-dashboard-new.operator.collections.destroy',$collection) }}" data-confirm-message="Void this collection declaration?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" class="pone-empty">No collection declarations.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
