-- PETROPD PAYMENT INTEGRITY - PARCEL 3 AUDIT TABLES
-- Run on EACH tenant database after Parcels 1 and 2.

CREATE TABLE IF NOT EXISTS `petro_pd_payment_integrity_repair_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `tenant_reference` VARCHAR(191) NULL,
  `apply_changes` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL DEFAULT 'running',
  `scanned_rows` INT UNSIGNED NOT NULL DEFAULT 0,
  `issues_found` INT UNSIGNED NOT NULL DEFAULT 0,
  `safe_repairs_found` INT UNSIGNED NOT NULL DEFAULT 0,
  `repairs_applied` INT UNSIGNED NOT NULL DEFAULT 0,
  `options_json` LONGTEXT NULL,
  `summary_json` LONGTEXT NULL,
  `error_message` TEXT NULL,
  `started_at` TIMESTAMP NULL,
  `finished_at` TIMESTAMP NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `petro_pd_repair_runs_business_idx` (`business_id`),
  KEY `petro_pd_repair_runs_tenant_idx` (`tenant_reference`),
  KEY `petro_pd_repair_runs_apply_idx` (`apply_changes`),
  KEY `petro_pd_repair_runs_status_idx` (`status`),
  KEY `petro_pd_repair_runs_created_by_idx` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `petro_pd_payment_integrity_repair_actions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `repair_run_id` BIGINT UNSIGNED NOT NULL,
  `business_id` BIGINT UNSIGNED NULL,
  `table_name` VARCHAR(100) NOT NULL,
  `row_id` BIGINT UNSIGNED NULL,
  `pump_payment_id` BIGINT UNSIGNED NULL,
  `shift_id` BIGINT UNSIGNED NULL,
  `action_type` VARCHAR(100) NOT NULL,
  `severity` VARCHAR(20) NOT NULL DEFAULT 'warning',
  `is_safe_repair` TINYINT(1) NOT NULL DEFAULT 0,
  `was_applied` TINYINT(1) NOT NULL DEFAULT 0,
  `message` TEXT NOT NULL,
  `before_json` LONGTEXT NULL,
  `after_json` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `petro_pd_repair_actions_run_idx` (`repair_run_id`),
  KEY `petro_pd_repair_actions_business_idx` (`business_id`),
  KEY `petro_pd_repair_actions_table_idx` (`table_name`),
  KEY `petro_pd_repair_actions_row_idx` (`row_id`),
  KEY `petro_pd_repair_actions_payment_idx` (`pump_payment_id`),
  KEY `petro_pd_repair_actions_shift_idx` (`shift_id`),
  KEY `petro_pd_repair_actions_type_idx` (`action_type`),
  KEY `petro_pd_repair_actions_severity_idx` (`severity`),
  KEY `petro_pd_repair_actions_safe_idx` (`is_safe_repair`),
  KEY `petro_pd_repair_actions_applied_idx` (`was_applied`),
  KEY `petro_pd_repair_run_applied_idx` (`repair_run_id`,`was_applied`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
