<?php

return [
    'pumper_dashboard_new.access' => 'Access Pumper Dashboard-New',
    'pumper_dashboard_new.dashboard.view' => 'View Pumper Dashboard-New dashboard',
    'pumper_dashboard_new.operators.view' => 'View mapped pump operators',
    'pumper_dashboard_new.operators.manage' => 'Manage mapped pump operators',
    'pumper_dashboard_new.shifts.view' => 'View Pumper Dashboard-New shifts',
    'pumper_dashboard_new.shifts.manage' => 'Manage Pumper Dashboard-New shifts',
    'pumper_dashboard_new.assignments.manage' => 'Manage Pumper Dashboard-New pump assignments',
    'pumper_dashboard_new.collections.view' => 'View Pumper Dashboard-New daily collections',
    'pumper_dashboard_new.collections.manage' => 'Manage Pumper Dashboard-New daily collections',
    'pumper_dashboard_new.reconciliation.view' => 'View shortage recovery and excess commission',
    'pumper_dashboard_new.reconciliation.manage' => 'Manage shortage recovery and excess commission',
    'pumper_dashboard_new.ledger.view' => 'View pump operator ledger',
    'pumper_dashboard_new.documents.view' => 'View pump operator notes and documents',
    'pumper_dashboard_new.documents.manage' => 'Manage pump operator notes and documents',
    'pumper_dashboard_new.login_attempts.view' => 'View blocked Pumper Dashboard-New logins',
    'pumper_dashboard_new.login_attempts.manage' => 'Unblock Pumper Dashboard-New logins',
    'pumper_dashboard_new.print_logs.view' => 'View Pumper Dashboard-New print history',
    'pumper_dashboard_new.reports.view' => 'View Pumper Dashboard-New reports',
    'pumper_dashboard_new.reports.export' => 'Export Pumper Dashboard-New reports',
    'pumper_dashboard_new.reports.print' => 'Print Pumper Dashboard-New reports',
    'pumper_dashboard_new.reports.shifts' => 'View Pumper Dashboard-New shift report',
    'pumper_dashboard_new.reports.payments' => 'View Pumper Dashboard-New payment report',
    'pumper_dashboard_new.reports.meters' => 'View Pumper Dashboard-New meter report',
    'pumper_dashboard_new.reports.other_sales' => 'View Pumper Dashboard-New other-sales report',
    'pumper_dashboard_new.reports.unloads' => 'View Pumper Dashboard-New unload-stock report',
    'pumper_dashboard_new.reports.day_entries' => 'View Pumper Dashboard-New day-entry report',
    'pumper_dashboard_new.reports.collections' => 'View Pumper Dashboard-New collection report',
    'pumper_dashboard_new.reports.ledger' => 'View Pumper Dashboard-New ledger report',
    'pumper_dashboard_new.reports.shortages' => 'View Pumper Dashboard-New shortage report',
    'pumper_dashboard_new.reports.commissions' => 'View Pumper Dashboard-New excess-commission report',
    'pumper_dashboard_new.reports.print_logs' => 'View Pumper Dashboard-New print-history report',
    'pumper_dashboard_new.reports.audit' => 'View Pumper Dashboard-New audit report',
    'pumper_dashboard_new.integration.view' => 'View Petro PD-New pairing status',
    'pumper_dashboard_new.integration.manage' => 'Reprocess Petro PD-New source-ready events',
    'pumper_dashboard_new.settings.manage' => 'Manage Pumper Dashboard-New settings',
    'pumper_dashboard_new.operator.use' => 'Use Pump Operator Display 2',
];
