<?php

return [
    [
        'key' => 'reports_other.cash_receipt',
        'module_key' => 'reports_other',
        'module' => 'ReportsOther',
        'module_name' => 'Reports - Other',
        'page' => 'Cash Receipt',
        'label' => 'Cash Receipt',
        'route' => 'reports-other.cash-receipt.index',
        'url' => '/reports-other/cash-receipt',
        'permission' => 'reports_other.cash_receipt.view',
        'is_sidebar' => true,
        'is_menu_page' => true,
        'order' => 10,
    ],
    [
        'key' => 'reports_other.cash_receipt.receipt_tab',
        'module_key' => 'reports_other',
        'parent_key' => 'reports_other.cash_receipt',
        'module' => 'ReportsOther',
        'module_name' => 'Reports - Other',
        'page' => 'Receipt',
        'label' => 'Receipt',
        'route' => 'reports-other.cash-receipt.index',
        'url' => '/reports-other/cash-receipt?tab=receipt',
        'permission' => 'reports_other.cash_receipt.create',
        'is_sidebar' => false,
        'is_menu_page' => false,
        'is_tab_page' => true,
        'order' => 11,
    ],
    [
        'key' => 'reports_other.cash_receipt.list_tab',
        'module_key' => 'reports_other',
        'parent_key' => 'reports_other.cash_receipt',
        'module' => 'ReportsOther',
        'module_name' => 'Reports - Other',
        'page' => 'List Receipt',
        'label' => 'List Receipt',
        'route' => 'reports-other.cash-receipt.index',
        'url' => '/reports-other/cash-receipt?tab=list',
        'permission' => 'reports_other.cash_receipt.list',
        'is_sidebar' => false,
        'is_menu_page' => false,
        'is_tab_page' => true,
        'order' => 12,
    ],
    [
        'key' => 'reports_other.cash_receipt.mapping_tab',
        'module_key' => 'reports_other',
        'parent_key' => 'reports_other.cash_receipt',
        'module' => 'ReportsOther',
        'module_name' => 'Reports - Other',
        'page' => 'Map Sub Products to Source',
        'label' => 'Map Sub Products to Source',
        'route' => 'reports-other.cash-receipt.index',
        'url' => '/reports-other/cash-receipt?tab=mapping',
        'permission' => 'reports_other.source_mapping.manage',
        'is_sidebar' => false,
        'is_menu_page' => false,
        'is_tab_page' => true,
        'order' => 13,
    ],
    [
        'key' => 'reports_other.cash_receipt.numbering_tab',
        'module_key' => 'reports_other',
        'parent_key' => 'reports_other.cash_receipt',
        'module' => 'ReportsOther',
        'module_name' => 'Reports - Other',
        'page' => 'Prefix & Starting Nos',
        'label' => 'Prefix & Starting Nos',
        'route' => 'reports-other.cash-receipt.index',
        'url' => '/reports-other/cash-receipt?tab=numbering',
        'permission' => 'reports_other.numbering.manage',
        'is_sidebar' => false,
        'is_menu_page' => false,
        'is_tab_page' => true,
        'order' => 14,
    ],
];
