@extends('communicationhub::layout')
@section('title', 'Communication Analytics')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.ch-toolbar .form-control{min-width:145px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.ch-grid{grid-template-columns:1fr}.ch-toolbar .form-control{width:100%}}</style>
<div class="container-fluid"><h3 class="mb-3">Communication Analytics</h3>
<div class="ch-grid">@foreach($stats as $label => $value)<div class="ch-stat"><h3>{{ number_format($value) }}</h3><p>{{ ucwords(str_replace('_',' ', $label)) }}</p></div>@endforeach</div>
<div class="ch-card ch-actions"><a class="btn btn-primary" href="{{ route('communicationhub.commercial.message_history_report') }}">Message History</a><a class="btn btn-info" href="{{ route('communicationhub.commercial.provider_performance_report') }}">Provider Performance</a><a class="btn btn-success" href="{{ route('communicationhub.commercial.campaign_performance_report') }}">Campaign Analytics</a><a class="btn btn-warning" href="{{ route('communicationhub.commercial.api_gateway_dashboard') }}">API Gateway</a><a class="btn btn-default" href="{{ route('communicationhub.commercial.communication_audit_centre') }}">Audit Centre</a></div>
<div class="ch-card"><h4>Channel Summary</h4><table class="ch-table"><thead><tr><th>Channel</th><th>Total</th><th>Sent</th><th>Failed</th><th>Pending</th><th>Success %</th></tr></thead><tbody>@foreach($channelStats as $channel => $row)<tr><td>{{ strtoupper(str_replace('_',' ', $channel)) }}</td><td>{{ number_format($row['total']) }}</td><td>{{ number_format($row['sent']) }}</td><td>{{ number_format($row['failed']) }}</td><td>{{ number_format($row['pending']) }}</td><td>{{ $row['total'] ? number_format(($row['sent']/$row['total'])*100,2) : '0.00' }}%</td></tr>@endforeach</tbody></table></div>
<div class="ch-card"><h4>Recent Messages</h4><table class="ch-table"><thead><tr><th>ID</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Created</th></tr></thead><tbody>@forelse($recentMessages as $m)<tr><td>{{ $m->id }}</td><td>{{ strtoupper($m->channel ?? '-') }}</td><td>{{ $m->recipient ?? '-' }}</td><td><span class="ch-badge">{{ ucfirst($m->status ?? '-') }}</span></td><td>{{ $m->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="5">No messages found.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
