@extends('communicationhub::layout')
@section('title', 'Communication API Gateway')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.ch-toolbar .form-control{min-width:145px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.ch-grid{grid-template-columns:1fr}.ch-toolbar .form-control{width:100%}}</style>
<div class="container-fluid"><h3 class="mb-3">Communication API Gateway</h3><div class="ch-grid">@foreach($stats as $label=>$value)<div class="ch-stat"><h3>{{ number_format($value) }}</h3><p>{{ ucwords(str_replace('_',' ', $label)) }}</p></div>@endforeach</div>
<div class="ch-card"><h4>Create API Token</h4><form method="POST" action="{{ route('communicationhub.commercial.api_gateway.tokens.store') }}" class="ch-toolbar">@csrf<input name="name" class="form-control" placeholder="Client / application name" required><input name="daily_limit" type="number" class="form-control" placeholder="Daily limit"><button class="btn btn-primary">Create Token</button></form></div>
<div class="ch-card"><h4>API Clients</h4><table class="ch-table"><thead><tr><th>ID</th><th>Name</th><th>Daily Limit</th><th>Active</th><th>Created</th></tr></thead><tbody>@forelse($tokens as $t)<tr><td>{{ $t->id }}</td><td>{{ $t->name ?? $t->client_name ?? '-' }}</td><td>{{ $t->daily_limit ?? '-' }}</td><td><span class="ch-badge">{{ !empty($t->is_active) ? 'Active' : 'Inactive' }}</span></td><td>{{ $t->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="5">No API clients found.</td></tr>@endforelse</tbody></table></div>
<div class="ch-card"><h4>Recent API Logs</h4><table class="ch-table"><thead><tr><th>ID</th><th>Endpoint</th><th>Status</th><th>IP</th><th>Created</th></tr></thead><tbody>@forelse($logs as $l)<tr><td>{{ $l->id }}</td><td>{{ $l->endpoint ?? $l->request_path ?? '-' }}</td><td><span class="ch-badge">{{ $l->status ?? $l->response_status ?? '-' }}</span></td><td>{{ $l->ip_address ?? '-' }}</td><td>{{ $l->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="5">No API logs found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
