@extends('communicationhub::layout')
@section('title', 'Communication Automation Dashboard')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}@media(max-width:900px){.ch-grid,.ch-form-grid{grid-template-columns:1fr}}</style>
<div class="container-fluid"><h3 class="mb-3">Communication Automation Dashboard</h3>
<div class="ch-grid">@foreach($stats as $label => $value)<div class="ch-stat"><h3>{{ number_format($value) }}</h3><p>{{ ucwords(str_replace('_',' ', $label)) }}</p></div>@endforeach</div>
<div class="ch-card ch-actions"><a class="btn btn-primary" href="{{ route('communicationhub.commercial.automation_rules') }}">Automation Rules</a><a class="btn btn-info" href="{{ route('communicationhub.commercial.automation_events') }}">Automation Events</a><form method="POST" action="{{ route('communicationhub.commercial.automation_events.process_pending') }}">@csrf<button class="btn btn-success">Process Pending Events</button></form></div>
<div class="ch-card"><h4>Recent Rules</h4><table class="ch-table"><thead><tr><th>ID</th><th>Rule</th><th>Event</th><th>Channels</th><th>Status</th></tr></thead><tbody>@forelse($rules as $row)<tr><td>{{ $row->id }}</td><td>{{ $row->rule_name }}</td><td>{{ $row->event_code }}</td><td>{{ $row->channels }}</td><td><span class="ch-badge">{{ ucfirst($row->status ?? '-') }}</span></td></tr>@empty<tr><td colspan="5">No rules found.</td></tr>@endforelse</tbody></table></div>
<div class="ch-card"><h4>Recent Events</h4><table class="ch-table"><thead><tr><th>ID</th><th>Event</th><th>Recipient</th><th>Status</th><th>Messages</th></tr></thead><tbody>@forelse($events as $row)<tr><td>{{ $row->id }}</td><td>{{ $row->event_code }}</td><td>{{ $row->recipient_name ?? $row->recipient_mobile ?? $row->recipient_email ?? '-' }}</td><td><span class="ch-badge">{{ ucfirst($row->status ?? '-') }}</span></td><td>{{ $row->created_messages ?? 0 }}</td></tr>@empty<tr><td colspan="5">No events found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
