@extends('communicationhub::layout')
@section('title', 'Automation Events')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}@media(max-width:900px){.ch-grid,.ch-form-grid{grid-template-columns:1fr}}</style>
<div class="container-fluid"><h3 class="mb-3">Automation Events</h3>
<div class="ch-card"><form method="POST" action="{{ route('communicationhub.commercial.automation_events.test') }}">@csrf<div class="ch-form-grid"><div><label>Event Code</label><input name="event_code" class="form-control" placeholder="sales.invoice.created" required></div><div><label>Recipient Name</label><input name="recipient_name" class="form-control"></div><div><label>Mobile</label><input name="recipient_mobile" class="form-control"></div><div><label>Email</label><input name="recipient_email" class="form-control"></div><div><label>WhatsApp</label><input name="recipient_whatsapp" class="form-control"></div><div><label>Source Module</label><input name="source_module" class="form-control"></div><div><label>Source Record ID</label><input name="source_record_id" class="form-control"></div></div><button class="btn btn-primary mt-3">Create Test Event</button></form></div>
<div class="ch-card ch-actions"><form method="POST" action="{{ route('communicationhub.commercial.automation_events.process_pending') }}">@csrf<button class="btn btn-success">Process Pending</button></form><a class="btn btn-info" href="{{ route('communicationhub.commercial.automation_dashboard') }}">Dashboard</a></div>
<div class="ch-card"><h4>Automation Event Log</h4><table class="ch-table"><thead><tr><th>ID</th><th>Event</th><th>Source</th><th>Recipient</th><th>Status</th><th>Messages</th><th>Processed</th><th>Action</th></tr></thead><tbody>@forelse($events as $row)<tr><td>{{ $row->id }}</td><td>{{ $row->event_code }}</td><td>{{ $row->source_module ?? '-' }} #{{ $row->source_record_id ?? '-' }}</td><td>{{ $row->recipient_name ?? $row->recipient_mobile ?? $row->recipient_email ?? '-' }}</td><td><span class="ch-badge">{{ ucfirst($row->status ?? '-') }}</span></td><td>{{ $row->created_messages ?? 0 }}</td><td>{{ $row->processed_at ?? '-' }}</td><td><form method="POST" action="{{ route('communicationhub.commercial.automation_events.execute', $row->id) }}">@csrf<button class="btn btn-sm btn-primary">Execute</button></form></td></tr>@empty<tr><td colspan="8">No automation events found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
