@extends('communicationhub::layout')
@section('title', 'Communication Audit Centre')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.ch-toolbar .form-control{min-width:145px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.ch-grid{grid-template-columns:1fr}.ch-toolbar .form-control{width:100%}}</style>
<div class="container-fluid"><h3 class="mb-3">Communication Audit Centre</h3>
<div class="ch-card"><h4>Audit Logs</h4><table class="ch-table"><thead><tr><th>ID</th><th>Action</th><th>Description</th><th>User</th><th>Created</th></tr></thead><tbody>@forelse($auditLogs as $a)<tr><td>{{ $a->id }}</td><td>{{ $a->action ?? $a->event ?? '-' }}</td><td>{{ $a->description ?? $a->message ?? '-' }}</td><td>{{ $a->created_by ?? $a->user_id ?? '-' }}</td><td>{{ $a->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="5">No audit logs found.</td></tr>@endforelse</tbody></table></div>
<div class="ch-card"><h4>Delivery Events</h4><table class="ch-table"><thead><tr><th>ID</th><th>Message</th><th>Event</th><th>Status</th><th>Created</th></tr></thead><tbody>@forelse($deliveryEvents as $d)<tr><td>{{ $d->id }}</td><td>{{ $d->message_id ?? '-' }}</td><td>{{ $d->event_type ?? $d->event ?? '-' }}</td><td><span class="ch-badge">{{ $d->status ?? '-' }}</span></td><td>{{ $d->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="5">No delivery events found.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
