@extends('communicationhub::layout')
@section('title', 'Message History Report')
@section('content')
<style>.ch-card{background:#fff;border:1px solid #e7edf5;border-radius:14px;padding:18px;margin-bottom:18px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.ch-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ch-stat{background:#f8fafc;border:1px solid #e7edf5;border-radius:12px;padding:16px}.ch-stat h3{margin:0;font-size:24px;font-weight:700}.ch-stat p{margin:4px 0 0;color:#64748b}.ch-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.ch-toolbar .form-control{min-width:145px}.ch-table{width:100%;border-collapse:collapse}.ch-table th,.ch-table td{padding:10px 12px;border-bottom:1px solid #edf2f7;vertical-align:top}.ch-table th{font-weight:600;color:#475569;background:#f8fafc}.ch-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}.ch-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.ch-grid{grid-template-columns:1fr}.ch-toolbar .form-control{width:100%}}</style>
<div class="container-fluid"><h3 class="mb-3">Message History Report</h3>
<div class="ch-card"><form method="GET" class="ch-toolbar"><div><label>Channel</label><select name="channel" class="form-control"><option value="">All</option>@foreach(['sms','email','whatsapp','push','in_app'] as $c)<option value="{{ $c }}" @selected(request('channel')==$c)>{{ strtoupper(str_replace('_',' ', $c)) }}</option>@endforeach</select></div><div><label>Status</label><select name="status" class="form-control"><option value="">All</option>@foreach(['pending','scheduled','sent','delivered','failed','read'] as $s)<option value="{{ $s }}" @selected(request('status')==$s)>{{ ucfirst($s) }}</option>@endforeach</select></div><div><label>Recipient</label><input name="recipient" class="form-control" value="{{ request('recipient') }}"></div><div><label>From</label><input type="date" name="date_from" class="form-control" value="{{ request('date_from') }}"></div><div><label>To</label><input type="date" name="date_to" class="form-control" value="{{ request('date_to') }}"></div><button class="btn btn-primary">Search</button><button type="button" onclick="window.print()" class="btn btn-default">Print</button></form></div>
<div class="ch-card"><table class="ch-table"><thead><tr><th>ID</th><th>Channel</th><th>Recipient</th><th>Subject/Message</th><th>Status</th><th>Cost</th><th>Created</th></tr></thead><tbody>@forelse($messages as $m)<tr><td>{{ $m->id }}</td><td>{{ strtoupper($m->channel ?? '-') }}</td><td>{{ $m->recipient ?? '-' }}</td><td>{{ \Illuminate\Support\Str::limit($m->subject ?? $m->message ?? $m->body ?? '-', 80) }}</td><td><span class="ch-badge">{{ ucfirst($m->status ?? '-') }}</span></td><td>{{ number_format((float)($m->cost ?? 0), 4) }}</td><td>{{ $m->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="7">No records found.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
