@extends('communicationhub::layout')
@section('communicationhub_title', 'Push Templates')
@section('communicationhub_content')
@include('communicationhub::partials.professional-styles')
<div class="ch-card"><div class="ch-card-header"><div><h3 class="ch-card-title"><i class="fa fa-file-text-o"></i> Push Templates</h3><div class="ch-card-subtitle">Reusable templates for ERP event notifications and manual campaigns.</div></div></div>
<div class="ch-card-body"><form method="POST" action="{{ route('communicationhub.commercial.push_templates.store') }}">@csrf
<div class="row"><div class="col-md-4"><div class="form-group"><label>Template Name</label><input name="template_name" class="form-control" required></div></div><div class="col-md-3"><div class="form-group"><label>Category</label><input name="category" class="form-control" placeholder="finance / petro / customer"></div></div><div class="col-md-3"><div class="form-group"><label>Status</label><select name="status" class="form-control"><option>active</option><option>draft</option><option>inactive</option></select></div></div></div>
<div class="form-group"><label>Title</label><input name="title" class="form-control" required></div><div class="form-group"><label>Body</label><textarea name="body" class="form-control" rows="4" required></textarea></div><div class="row"><div class="col-md-6"><div class="form-group"><label>Action URL</label><input name="action_url" class="form-control"></div></div><div class="col-md-6"><div class="form-group"><label>Variables</label><input name="variables" class="form-control" placeholder="{customer_name}, {invoice_no}"></div></div></div><button class="btn btn-primary">Save Template</button></form></div></div>
<div class="ch-card"><div class="ch-card-header"><div><h3 class="ch-card-title">Templates</h3></div></div><div class="table-responsive"><table class="table table-striped table-bordered"><thead><tr><th>ID</th><th>Name</th><th>Category</th><th>Title</th><th>Status</th><th>Created</th></tr></thead><tbody>@forelse($templates as $t)<tr><td>{{ $t->id }}</td><td>{{ $t->template_name ?? '' }}</td><td>{{ $t->category ?? '' }}</td><td>{{ $t->title ?? '' }}</td><td>{{ $t->status ?? '' }}</td><td>{{ $t->created_at ?? '' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No push templates found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
