@extends('communicationhub::layout')
@section('communicationhub_title', 'Push Devices')
@section('communicationhub_content')
@include('communicationhub::partials.professional-styles')
<div class="ch-card"><div class="ch-card-header"><div><h3 class="ch-card-title"><i class="fa fa-mobile"></i> Push Devices</h3><div class="ch-card-subtitle">Register and manage browser/mobile device tokens business-wise.</div></div></div>
<div class="ch-card-body"><form method="POST" action="{{ route('communicationhub.commercial.push_devices.store') }}">@csrf
<div class="row"><div class="col-md-3"><div class="form-group"><label>Device Name</label><input name="device_name" class="form-control"></div></div><div class="col-md-2"><div class="form-group"><label>User ID</label><input name="user_id" type="number" class="form-control"></div></div><div class="col-md-2"><div class="form-group"><label>Platform</label><select name="platform" class="form-control" required><option>web</option><option>android</option><option>ios</option><option>windows</option></select></div></div><div class="col-md-2"><div class="form-group"><label>Browser</label><input name="browser" class="form-control"></div></div><div class="col-md-3"><div class="form-group"><label>Device Group</label><input name="device_group" class="form-control" placeholder="customers / staff"></div></div></div>
<div class="form-group"><label>Device Token</label><textarea name="device_token" class="form-control" rows="3" required></textarea></div><button class="btn btn-primary">Save Device</button></form></div></div>
<div class="ch-card"><div class="ch-card-header"><div><h3 class="ch-card-title">Registered Devices</h3></div></div><div class="table-responsive"><table class="table table-striped table-bordered"><thead><tr><th>ID</th><th>Name</th><th>User</th><th>Platform</th><th>Group</th><th>Status</th><th>Last Seen</th></tr></thead><tbody>@forelse($devices as $d)<tr><td>{{ $d->id }}</td><td>{{ $d->device_name ?? '' }}</td><td>{{ $d->user_id ?? '' }}</td><td>{{ $d->platform ?? '' }}</td><td>{{ $d->device_group ?? '' }}</td><td>{{ $d->status ?? '' }}</td><td>{{ $d->last_seen_at ?? '' }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No devices found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
