@extends('leadsnew::layouts.app')
@section('title', 'Lead Documents')
@section('leadsnew_subtitle', 'Upload and manage supporting documents while keeping files inside the standalone Leads-New workflow.')
@section('leadsnew_content')
<div class="ln-split-grid">
<div class="ln-panel"><div class="ln-panel-header"><div><h3 class="ln-panel-title"><i class="fa fa-files-o"></i> Document Register</h3><div class="ch-card-subtitle">Latest uploads are shown first.</div></div><span class="ln-badge">{{ method_exists($documents, 'total') ? $documents->total() : count($documents) }} files</span></div><div class="ln-table table-responsive"><table class="table table-hover"><thead><tr><th>File Name</th><th>Type</th><th class="text-right">Size</th><th>Uploaded</th><th class="text-right">Action</th></tr></thead><tbody>
@forelse($documents as $document)<tr><td><strong>{{ $document->original_name }}</strong><br><span class="text-muted">Lead #{{ $document->lead_id }}</span></td><td>{{ $document->mime_type ?: '-' }}</td><td class="text-right">{{ $document->size ? number_format($document->size / 1024, 1) . ' KB' : '-' }}</td><td>{{ optional($document->uploaded_at)->format('Y-m-d h:i A') ?? '-' }}</td><td class="text-right"><form method="post" action="{{ url('/leads-new/documents/' . $document->id) }}" onsubmit="return confirm('Delete this document?')">@csrf @method('DELETE')<button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="5"><div class="ln-empty"><i class="fa fa-file-o"></i>No documents uploaded yet.</div></td></tr>@endforelse
</tbody></table></div>@if(method_exists($documents, 'links'))<div class="ln-panel-body">{{ $documents->links() }}</div>@endif</div>
<div class="ln-panel ln-sticky-panel"><div class="ln-panel-header"><h3 class="ln-panel-title"><i class="fa fa-cloud-upload"></i> Upload Document</h3></div><div class="ln-panel-body"><form method="post" action="{{ url('/leads-new/documents') }}" enctype="multipart/form-data">@csrf<div class="form-group"><label>Lead ID</label><input type="number" name="lead_id" class="form-control" value="{{ old('lead_id', request('lead_id')) }}" required></div><div class="form-group"><label>Select File</label><input type="file" name="document" class="form-control" required><p class="help-block">Maximum file size: 10 MB.</p></div><button class="btn btn-primary btn-block"><i class="fa fa-upload"></i> Upload Document</button></form></div></div>
</div>
@endsection
