@extends('layouts.app')
@section('title', 'Hotel Assets & Equipment')
@section('content')
<section class="content-header hm-page-header"><h1><i class="fa fa-archive"></i> Assets & Equipment <small>Hotel fixed asset, room equipment and inspection control</small></h1></section>
<section class="content hm-pos-scope">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please check:</strong> {{ $errors->first() }}</div>@endif
<div class="row hm-kpi-row">
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Total Assets</div><div class="hm-kpi-value">{{ $assetEquipment['total_assets'] }}</div><div class="hm-kpi-sub">Registered items</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Active Assets</div><div class="hm-kpi-value">{{ $assetEquipment['active_assets'] }}</div><div class="hm-kpi-sub">Available/in use</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Assigned</div><div class="hm-kpi-value">{{ $assetEquipment['assigned_assets'] }}</div><div class="hm-kpi-sub">Room/staff allocation</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Value</div><div class="hm-kpi-value">{{ number_format($assetEquipment['asset_value'],2) }}</div><div class="hm-kpi-sub">Current asset value</div></div></div>
</div>
<div class="row">
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Register Asset</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.asset-equipment.asset') }}">@csrf
  <div class="form-group"><label>Code / Name</label><input name="asset_code" class="form-control" placeholder="Auto if blank"><input name="asset_name" class="form-control" style="margin-top:6px" required placeholder="Asset name"></div>
  <div class="form-group"><label>Category / Department</label><div class="row"><div class="col-xs-6"><select name="asset_category" class="form-control" required><option value="room_equipment">Room Equipment</option><option value="fb_equipment">F&B Equipment</option><option value="housekeeping">Housekeeping</option><option value="it">IT</option><option value="vehicle">Vehicle</option><option value="other">Other</option></select></div><div class="col-xs-6"><input name="department" class="form-control" placeholder="Department"></div></div></div>
  <div class="form-group"><label>Room / Serial</label><div class="row"><div class="col-xs-6"><select name="room_id" class="form-control"><option value="">No room</option>@foreach($assetEquipment['rooms'] as $room)<option value="{{ $room->id }}">{{ $room->room_no ?? $room->id }}</option>@endforeach</select></div><div class="col-xs-6"><input name="serial_no" class="form-control" placeholder="Serial no"></div></div></div>
  <div class="form-group"><label>Purchase Date / Cost</label><div class="row"><div class="col-xs-6"><input type="date" name="purchase_date" class="form-control"></div><div class="col-xs-6"><input type="number" step="0.01" name="purchase_cost" class="form-control" placeholder="Cost"></div></div></div>
  <div class="form-group"><label>Current Value</label><input type="number" step="0.01" name="current_value" class="form-control" placeholder="Current value"></div>
  <div class="text-right"><button class="btn hm-btn-add"><i class="fa fa-save"></i> Save Asset</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Assign Asset</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.asset-equipment.assignment') }}">@csrf
  <div class="form-group"><label>Asset</label><select name="asset_id" class="form-control" required><option value="">Select Asset</option>@foreach($assetEquipment['assets'] as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} - {{ $asset->asset_name }}</option>@endforeach</select></div>
  <div class="form-group"><label>Assign To</label><div class="row"><div class="col-xs-6"><select name="assigned_to_type" class="form-control" required><option value="room">Room</option><option value="staff">Staff</option><option value="department">Department</option><option value="guest">Guest</option></select></div><div class="col-xs-6"><input type="number" name="assigned_to_id" class="form-control" placeholder="Ref ID"></div></div></div>
  <div class="form-group"><label>Room / Date</label><div class="row"><div class="col-xs-6"><select name="room_id" class="form-control"><option value="">No room</option>@foreach($assetEquipment['rooms'] as $room)<option value="{{ $room->id }}">{{ $room->room_no ?? $room->id }}</option>@endforeach</select></div><div class="col-xs-6"><input type="date" name="assigned_date" class="form-control" required></div></div></div>
  <div class="form-group"><label>Condition</label><select name="condition_out" class="form-control"><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></select></div>
  <div class="text-right"><button class="btn hm-btn-excel"><i class="fa fa-share"></i> Assign</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Inspect Asset</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.asset-equipment.inspection') }}">@csrf
  <div class="form-group"><label>Asset</label><select name="asset_id" class="form-control" required><option value="">Select Asset</option>@foreach($assetEquipment['assets'] as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} - {{ $asset->asset_name }}</option>@endforeach</select></div>
  <div class="form-group"><label>Inspection Date / Next</label><div class="row"><div class="col-xs-6"><input type="date" name="inspection_date" class="form-control" required></div><div class="col-xs-6"><input type="date" name="next_inspection_date" class="form-control"></div></div></div>
  <div class="form-group"><label>Condition / Estimated Cost</label><div class="row"><div class="col-xs-6"><select name="condition_status" class="form-control" required><option value="good">Good</option><option value="fair">Fair</option><option value="repair_required">Repair Required</option><option value="unsafe">Unsafe</option></select></div><div class="col-xs-6"><input type="number" step="0.01" name="estimated_cost" class="form-control" placeholder="Cost"></div></div></div>
  <div class="checkbox"><label><input type="checkbox" name="maintenance_required" value="1"> Maintenance required</label></div>
  <div class="text-right"><button class="btn hm-btn-pdf"><i class="fa fa-check-square-o"></i> Save Inspection</button></div>
 </form></div></div></div>
</div>
<div class="box hm-card"><div class="box-header with-border"><div class="hm-toolbar"><input class="form-control hm-search-input" style="max-width:260px" placeholder="Search assets..."><button class="btn hm-btn-csv">CSV</button><button class="btn hm-btn-excel">Excel</button><button class="btn hm-btn-pdf">PDF</button><button class="btn hm-btn-print">Print</button><button class="btn hm-btn-col">Column Visibility</button></div><h3 class="box-title">Asset Register</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>Code</th><th>Name</th><th>Category</th><th>Department</th><th>Room</th><th>Serial</th><th>Cost</th><th>Value</th><th>Status</th><th>Dispose</th></tr></thead><tbody>@forelse($assetEquipment['assets'] as $asset)<tr><td>{{ $asset->asset_code }}</td><td>{{ $asset->asset_name }}</td><td>{{ ucfirst(str_replace('_',' ',$asset->asset_category)) }}</td><td>{{ $asset->department }}</td><td>{{ $asset->room_id }}</td><td>{{ $asset->serial_no }}</td><td>{{ number_format($asset->purchase_cost ?? 0,2) }}</td><td>{{ number_format($asset->current_value ?? 0,2) }}</td><td><span class="hm-badge {{ $asset->status }}">{{ ucfirst($asset->status) }}</span></td><td><form method="POST" action="{{ route('hotel-management.asset-equipment.dispose',$asset->id) }}" class="form-inline">@csrf<input type="date" name="disposal_date" class="form-control input-sm" required><input type="number" step="0.01" name="disposal_value" class="form-control input-sm" style="width:90px" placeholder="Value"><input name="disposal_reason" class="form-control input-sm" style="width:120px" required placeholder="Reason"><button class="btn btn-xs hm-btn-pdf">Dispose</button></form></td></tr>@empty<tr><td colspan="10" class="text-center text-muted">No hotel assets registered yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Recent Inspections</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>No</th><th>Asset</th><th>Date</th><th>Condition</th><th>Next Inspection</th><th>Maintenance</th><th>Estimated Cost</th><th>Remarks</th></tr></thead><tbody>@forelse($assetEquipment['inspections'] as $i)<tr><td>{{ $i->inspection_no }}</td><td>{{ $i->asset_id }}</td><td>{{ $i->inspection_date }}</td><td><span class="hm-badge {{ $i->condition_status }}">{{ ucfirst(str_replace('_',' ',$i->condition_status)) }}</span></td><td>{{ $i->next_inspection_date }}</td><td>{{ !empty($i->maintenance_required) ? 'Yes' : 'No' }}</td><td>{{ number_format($i->estimated_cost ?? 0,2) }}</td><td>{{ $i->remarks }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">No asset inspections yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Asset Control Notes</h3></div><div class="box-body"><ul class="hm-note-list">@foreach($assetEquipment['notes'] as $note)<li>{{ $note }}</li>@endforeach</ul></div></div>
</section>
@endsection
