<?php
use Illuminate\Support\Facades\Route;
use Modules\ProductsNew\Http\Controllers\Reports\ReportsCenterController;
use Modules\ProductsNew\Http\Controllers\Reports\ProductMasterReportController;
use Modules\ProductsNew\Http\Controllers\Reports\StockValuationReportController;
use Modules\ProductsNew\Http\Controllers\Reports\LowStockReportController;
use Modules\ProductsNew\Http\Controllers\Reports\PriceChangeReportController;
use Modules\ProductsNew\Http\Controllers\Reports\BatchReportController;
use Modules\ProductsNew\Http\Controllers\Reports\ProductMovementReportController;
use Modules\ProductsNew\Http\Controllers\Reports\ProductProfitabilityReportController;
use Modules\ProductsNew\Http\Controllers\Reports\ProductAgingReportController;
use Modules\ProductsNew\Http\Controllers\Reports\FastSlowDeadStockReportController;
use Modules\ProductsNew\Http\Controllers\Reports\NegativeOverstockReportController;
use Modules\ProductsNew\Http\Controllers\Reports\ExpiryReportController;
use Modules\ProductsNew\Http\Controllers\Reports\SerialReportController;
use Modules\ProductsNew\Http\Controllers\Reports\CategoryBrandReportController;
use Modules\ProductsNew\Http\Controllers\Reports\PriceHistoryAnalyticsController;
use Modules\ProductsNew\Http\Controllers\Reports\InventoryTurnoverReportController;
use Modules\ProductsNew\Http\Controllers\Reports\AbcXyzAnalysisReportController;
use Modules\ProductsNew\Http\Controllers\Reports\ReorderRecommendationReportController;
use Modules\ProductsNew\Http\Middleware\InitializeProductsNewTenantContext;
Route::group(['prefix'=>'products-new/reports','as'=>'products-new.reports.','middleware'=>['web', InitializeProductsNewTenantContext::class, 'auth', 'check.route.permission']],function(){
    Route::get('/',[ReportsCenterController::class,'index'])->name('index');
    Route::get('/product-master',[ProductMasterReportController::class,'index'])->name('product-master');
    Route::get('/stock-valuation',[StockValuationReportController::class,'index'])->name('stock-valuation');
    Route::get('/low-stock',[LowStockReportController::class,'index'])->name('low-stock');
    Route::get('/price-changes',[PriceChangeReportController::class,'index'])->name('price-changes');
    Route::get('/batch-lot',[BatchReportController::class,'index'])->name('batch');
    Route::get('/product-movement',[ProductMovementReportController::class,'index'])->name('product-movement');
    Route::get('/profitability',[ProductProfitabilityReportController::class,'index'])->name('profitability');
    Route::get('/aging',[ProductAgingReportController::class,'index'])->name('aging');
    Route::get('/fast-slow-dead-stock',[FastSlowDeadStockReportController::class,'index'])->name('fast-slow-dead-stock');
    Route::get('/negative-overstock',[NegativeOverstockReportController::class,'index'])->name('negative-overstock');
    Route::get('/expiry',[ExpiryReportController::class,'index'])->name('expiry');
    Route::get('/serial',[SerialReportController::class,'index'])->name('serial');
    Route::get('/category-brand',[CategoryBrandReportController::class,'index'])->name('category-brand');
    Route::get('/price-history-analytics',[PriceHistoryAnalyticsController::class,'index'])->name('price-history-analytics');
    Route::get('/inventory-turnover',[InventoryTurnoverReportController::class,'index'])->name('inventory-turnover');
    Route::get('/abc-xyz',[AbcXyzAnalysisReportController::class,'index'])->name('abc-xyz');
    Route::get('/reorder-recommendation',[ReorderRecommendationReportController::class,'index'])->name('reorder-recommendation');
});
