-- Products New 8033 - Stock History / Opening Stock compatibility
-- Run in EACH tenant database. Safe to run repeatedly.
CREATE TABLE IF NOT EXISTS `products_new_inventory_movements` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `business_id` INT UNSIGNED NOT NULL, `product_id` INT UNSIGNED NOT NULL, `variation_id` INT UNSIGNED NULL, `location_id` INT UNSIGNED NULL, `store_id` BIGINT UNSIGNED NULL, `movement_type` VARCHAR(50) NOT NULL, `movement_date` DATETIME NOT NULL, `qty` DECIMAL(22,3) NOT NULL DEFAULT 0.000, `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0.0000, `total_cost` DECIMAL(22,4) NOT NULL DEFAULT 0.0000, `reference_no` VARCHAR(100) NULL, `notes` TEXT NULL, `source_table` VARCHAR(100) NULL, `source_id` BIGINT UNSIGNED NULL, `created_by` INT UNSIGNED NULL, `created_at` TIMESTAMP NULL DEFAULT NULL, `updated_at` TIMESTAMP NULL DEFAULT NULL,
 PRIMARY KEY (`id`), KEY `pn_im_business_idx` (`business_id`), KEY `pn_im_product_idx` (`product_id`), KEY `pn_im_variation_location_idx` (`variation_id`,`location_id`), KEY `pn_im_type_date_idx` (`movement_type`,`movement_date`), KEY `pn_im_store_idx` (`business_id`,`store_id`), KEY `pn_im_source_idx` (`source_table`,`source_id`), KEY `pn_im_history_scope_idx` (`business_id`,`product_id`,`location_id`,`movement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND COLUMN_NAME='store_id'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD COLUMN `store_id` BIGINT UNSIGNED NULL AFTER `location_id`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND COLUMN_NAME='source_table'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD COLUMN `source_table` VARCHAR(100) NULL AFTER `notes`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND COLUMN_NAME='source_id'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD COLUMN `source_id` BIGINT UNSIGNED NULL AFTER `source_table`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_business_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_business_idx` (`business_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_product_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_product_idx` (`product_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_variation_location_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_variation_location_idx` (`variation_id`,`location_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_type_date_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_type_date_idx` (`movement_type`,`movement_date`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_store_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_store_idx` (`business_id`,`store_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_source_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_source_idx` (`source_table`,`source_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql:=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='products_new_inventory_movements' AND INDEX_NAME='pn_im_history_scope_idx'),'SELECT 1','ALTER TABLE `products_new_inventory_movements` ADD INDEX `pn_im_history_scope_idx` (`business_id`,`product_id`,`location_id`,`movement_date`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
