@extends('layouts.app') @section('title','Dealer Management') @section('content')
@include('dealermanagement::partials.system-standard')<section class="content-header"><h1>Dealer Management</h1></section><section class="content">@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<div class="box box-primary"><div class="box-header"><h3 class="box-title">Create Dealer</h3></div><div class="box-body"><form method="post" action="{{ route('dealermanagement.admin.dealers.store') }}">@csrf<div class="row"><div class="col-md-4"><label>Link Customer</label><input type="hidden" name="customer_id" id="dlr_customer_id"><input type="text" class="form-control" id="dlr_customer_search" autocomplete="off" placeholder="Type 2+ characters to search"><div id="dlr_customer_results" style="position:absolute;z-index:20;background:#fff;border:1px solid #ddd;width:calc(100% - 30px);max-height:220px;overflow:auto;display:none"></div></div><div class="col-md-2"><label>Dealer Code</label><input class="form-control" name="dealer_code" required></div><div class="col-md-3"><label>Dealer Name</label><input class="form-control" name="name" required></div><div class="col-md-3"><label>Mobile</label><input class="form-control" name="mobile"></div></div><hr><h4>First Dealer Administrator</h4><div class="row"><div class="col-md-4"><label>Admin Name</label><input class="form-control" name="admin_name" required></div><div class="col-md-4"><label>Admin Mobile</label><input class="form-control" name="admin_mobile"></div><div class="col-md-4"><label>Admin Email</label><input class="form-control" type="email" name="admin_email"></div></div><div class="row"><div class="col-md-12 dlr-form-note"><label>Note</label><textarea class="form-control" name="notes" rows="3" placeholder="Enter note"></textarea></div></div><br><button class="btn btn-primary">Create Dealer & Admin Login</button></form></div></div><div class="box"><div class="box-header"><h3 class="box-title">Dealers</h3><a class="btn btn-default pull-right" href="{{ route('dealermanagement.admin.sync.index') }}">Distribution Sync</a></div><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>Dealer Code</th><th>Name</th><th>Customer ID</th><th>Mobile</th><th>Status</th><th>Note</th></tr></thead><tbody>@foreach($dealers as $d)<tr><td>{{ $d->dealer_code }}</td><td>{{ $d->name }}</td><td>{{ $d->customer_id }}</td><td>{{ $d->mobile }}</td><td>{{ $d->status }}</td><td>{{ $d->notes ?: '-' }}</td></tr>@endforeach</tbody></table>{{ $dealers->links() }}</div></div></section>
@push('javascript')
<script>
(function(){
 var input=document.getElementById('dlr_customer_search'), hidden=document.getElementById('dlr_customer_id'), box=document.getElementById('dlr_customer_results'), timer=null;
 if(!input) return;
 input.addEventListener('input',function(){ clearTimeout(timer); hidden.value=''; var q=this.value.trim(); if(q.length<2){box.style.display='none';box.innerHTML='';return;} timer=setTimeout(function(){fetch(@json(route('dealermanagement.admin.customers.search'))+'?q='+encodeURIComponent(q),{headers:{'X-Requested-With':'XMLHttpRequest'}}).then(r=>r.json()).then(rows=>{box.innerHTML=''; rows.forEach(x=>{var a=document.createElement('div');a.style.cssText='padding:8px 10px;cursor:pointer;border-bottom:1px solid #eee';a.textContent=x.name+(x.mobile?' - '+x.mobile:'');a.onclick=function(){hidden.value=x.id;input.value=x.name;box.style.display='none';};box.appendChild(a);});box.style.display=rows.length?'block':'none';}).catch(()=>{box.style.display='none';});},180); });
 document.addEventListener('click',e=>{if(e.target!==input&&!box.contains(e.target))box.style.display='none';});
})();
</script>
@endpush
@endsection
