@extends('stocktransfernew::layouts.app')
@section('title', $claim->claim_no)
@section('content')
<div class="stn-claims-page">
    <div class="stn-page-header"><div><h3>{{ $claim->claim_no }}</h3><p>Transfer: {{ $claim->transfer_no }} | Status: {{ ucfirst($claim->claim_status) }}</p></div><a href="{{ route('stock-transfer-new.claims.index') }}" class="btn btn-default">Back</a></div>
    <div class="stn-kpi-grid"><div class="stn-kpi"><span>Claimed</span><strong>{{ number_format($claim->claimed_value,2) }}</strong></div><div class="stn-kpi"><span>Recovered</span><strong>{{ number_format($claim->recovered_value,2) }}</strong></div><div class="stn-kpi"><span>Write-off</span><strong>{{ number_format($claim->writeoff_value,2) }}</strong></div><div class="stn-kpi"><span>Outstanding</span><strong>{{ number_format($claim->outstanding_value,2) }}</strong></div></div>
    <div class="stn-action-row">
        @if($claim->claim_status === 'draft')<form method="post" action="{{ route('stock-transfer-new.claims.submit',$claim->id) }}">@csrf<button class="btn btn-primary">Submit</button></form>@endif
        @if($claim->claim_status === 'submitted')<form method="post" action="{{ route('stock-transfer-new.claims.approve',$claim->id) }}">@csrf<button class="btn btn-success">Approve</button></form>@endif
        @if($claim->claim_status === 'approved')<form method="post" action="{{ route('stock-transfer-new.claims.close',$claim->id) }}" class="stn-inline-form">@csrf<input type="number" step="0.0001" name="recovered_qty" placeholder="Recovered qty"><input type="number" step="0.0001" name="recovered_value" placeholder="Recovered value"><input type="number" step="0.0001" name="writeoff_value" placeholder="Write-off"><input type="text" name="reference_no" placeholder="Reference"><button class="btn btn-warning">Close Claim</button></form>@endif
        @if(!in_array($claim->claim_status, ['closed','cancelled']))<form method="post" action="{{ route('stock-transfer-new.claims.cancel',$claim->id) }}" class="stn-inline-form">@csrf<input type="text" name="reason" placeholder="Cancel reason" required><button class="btn btn-danger">Cancel</button></form>@endif
    </div>
    <div class="table-responsive stn-card"><h4>Claim Lines</h4><table class="table table-bordered table-sm stn-table"><thead><tr><th>Product</th><th>SKU</th><th>Batch</th><th class="text-right">Transferred</th><th class="text-right">Received</th><th class="text-right">Shortage</th><th class="text-right">Damage</th><th class="text-right">Excess</th><th class="text-right">Value</th></tr></thead><tbody>@foreach($lines as $line)<tr><td>{{ $line->product_name }}</td><td>{{ $line->sku }}</td><td>{{ $line->batch_no }}</td><td class="text-right">{{ number_format($line->transferred_qty,4) }}</td><td class="text-right">{{ number_format($line->received_qty,4) }}</td><td class="text-right">{{ number_format($line->shortage_qty,4) }}</td><td class="text-right">{{ number_format($line->damage_qty,4) }}</td><td class="text-right">{{ number_format($line->excess_qty,4) }}</td><td class="text-right">{{ number_format($line->claim_value,2) }}</td></tr>@endforeach</tbody></table></div>
    <div class="table-responsive stn-card"><h4>Action History</h4><table class="table table-bordered table-sm stn-table"><thead><tr><th>Date</th><th>Action</th><th>Reference</th><th class="text-right">Qty</th><th class="text-right">Amount</th><th>Remarks</th></tr></thead><tbody>@foreach($actions as $action)<tr><td>{{ $action->action_date }}</td><td>{{ ucfirst($action->action_type) }}</td><td>{{ $action->reference_no }}</td><td class="text-right">{{ number_format($action->qty,4) }}</td><td class="text-right">{{ number_format($action->amount,2) }}</td><td>{{ $action->remarks }}</td></tr>@endforeach</tbody></table></div>
</div>
@endsection
