@extends('teaestate::layouts.app',['title'=>'Tea Plantation','heading'=>'Plantation'])
@section('tea_content')
<div class="tea-card"><div class="tea-card-h">Add Estate</div><div class="tea-card-b"><form method="post" action="{{ route('teaestate.plantation.estates.store') }}">@csrf<div class="tea-form"><div><label>Location *</label><select name="location_id" required><option value="">Select Location</option>@foreach($locationOptions as $id=>$name)<option value="{{ $id }}" @selected((string)old('location_id',$defaultLocationId)===(string)$id)>{{ $name }}</option>@endforeach</select></div><div><label>Estate Code</label><input name="estate_code"></div><div><label>Estate Name *</label><input name="name" required></div><div><label>Area (acres)</label><input name="area_acres" type="number" step="0.0001"></div><div class="wide"><label>Address</label><input name="address"></div><div class="wide"><label>Note</label><input name="notes"></div></div><div class="tea-actions"><button class="tea-btn">Save Estate</button></div></form></div></div>
<div class="tea-card"><div class="tea-card-h">Add Field</div><div class="tea-card-b"><form method="post" action="{{ route('teaestate.plantation.fields.store') }}">@csrf<div class="tea-form"><div><label>Estate *</label><select name="estate_id" required><option value="">Select</option>@foreach($estates as $e)<option value="{{ $e->id }}">{{ $e->name }}</option>@endforeach</select></div><div><label>Field Code *</label><input name="field_code" required></div><div><label>Field Name *</label><input name="name" required></div><div><label>Area (acres)</label><input name="area_acres" type="number" step="0.0001"></div><div><label>Plant Count</label><input name="plant_count" type="number"></div><div><label>Planted Date</label><input name="planted_date" type="date"></div></div><div class="tea-actions"><button class="tea-btn">Save Field</button></div></form></div></div>

<div class="tea-card"><div class="tea-card-h">Field Activity / Cost</div><div class="tea-card-b"><form method="post" action="{{ route('teaestate.plantation.activities.store') }}">@csrf<div class="tea-form">
<div><label>Location *</label><select name="location_id" required><option value="">Select Location</option>@foreach($locationOptions as $id=>$name)<option value="{{ $id }}" @selected((string)old('location_id',$defaultLocationId)===(string)$id)>{{ $name }}</option>@endforeach</select></div>
<div><label>Field *</label><select name="field_id" required><option value="">Select</option>@foreach($fields as $f)<option value="{{ $f->id }}">{{ $f->field_code }} - {{ $f->name }}</option>@endforeach</select></div>
<div><label>Date *</label><input name="activity_date" type="date" value="{{ date('Y-m-d') }}" required></div><div><label>Activity *</label><input name="activity_type" placeholder="Pruning / Fertilizing / Weeding" required></div>
<div><label>Quantity</label><input name="quantity" type="number" step="0.0001"></div><div><label>Unit</label><input name="unit"></div><div><label>Cost Amount</label><input name="cost_amount" type="number" step="0.0001" value="0"></div>
<div><label>Finance Cash/Bank Account</label><select name="finance_account_id"><option value="">Select</option>@foreach($financeAccounts as $id=>$name)<option value="{{ $id }}">{{ $name }}</option>@endforeach</select></div><div class="wide"><label>Notes</label><input name="notes"></div></div><div class="tea-actions"><button class="tea-btn secondary">Record Activity</button></div></form></div></div>
<div class="tea-card"><div class="tea-card-h">Latest Field Activities</div><div class="tea-card-b tea-scroll"><table class="tea-table"><tr><th>Date</th><th>Field</th><th>Activity</th><th>Qty</th><th>Cost</th></tr>@foreach($activities as $a)<tr><td>{{ $a->activity_date }}</td><td>{{ $a->field_name }}</td><td>{{ $a->activity_type }}</td><td>{{ $a->quantity }} {{ $a->unit }}</td><td>{{ number_format($a->cost_amount,2) }}</td></tr>@endforeach</table></div></div>

<div class="tea-card"><div class="tea-card-h">Fields</div><div class="tea-card-b tea-scroll"><table class="tea-table"><tr><th>Code</th><th>Name</th><th>Estate</th><th>Location</th><th>Area</th><th>Status</th></tr>@foreach($fields as $f)<tr><td>{{ $f->field_code }}</td><td>{{ $f->name }}</td><td>{{ $f->estate_id }}</td><td>{{ $f->location_id }}</td><td>{{ number_format($f->area_acres,4) }}</td><td><span class="tea-status">{{ $f->status }}</span></td></tr>@endforeach</table></div></div>
@endsection
