@extends('leadsnew::layouts.app')
@section('title', 'Message Templates')
@section('leadsnew_subtitle', 'Maintain reusable email, SMS and notification wording for consistent lead communication.')
@section('leadsnew_content')
<div class="ln-split-grid">
<div class="ln-panel"><div class="ln-panel-header"><div><h3 class="ln-panel-title"><i class="fa fa-envelope-o"></i> Template Register</h3><div class="ch-card-subtitle">Reusable module-owned communication templates.</div></div><span class="ln-badge">{{ method_exists($templates, 'total') ? $templates->total() : count($templates) }} templates</span></div><div class="ln-table table-responsive"><table class="table table-hover"><thead><tr><th>Type</th><th>Name</th><th>Subject</th><th>Default</th><th>Status</th></tr></thead><tbody>
@forelse($templates as $template)<tr><td><span class="ln-badge status-new">{{ strtoupper($template->type ?: 'GENERAL') }}</span></td><td><strong>{{ $template->name }}</strong></td><td>{{ $template->subject ?: '-' }}</td><td>{{ $template->is_default ? 'Yes' : 'No' }}</td><td><span class="ln-badge {{ $template->is_active ? 'status-converted' : 'status-lost' }}">{{ $template->is_active ? 'Active' : 'Inactive' }}</span></td></tr>@empty<tr><td colspan="5"><div class="ln-empty"><i class="fa fa-envelope-o"></i>No templates created yet.</div></td></tr>@endforelse
</tbody></table></div>@if(method_exists($templates, 'links'))<div class="ln-panel-body">{{ $templates->links() }}</div>@endif</div>
<div class="ln-panel ln-sticky-panel"><div class="ln-panel-header"><h3 class="ln-panel-title"><i class="fa fa-plus-circle"></i> New Template</h3></div><div class="ln-panel-body"><form method="post" action="{{ url('/leads-new/templates') }}">@csrf<div class="form-group"><label>Template Type</label><select name="type" class="form-control select2"><option value="email">Email</option><option value="sms">SMS</option><option value="notification">Notification</option></select></div><div class="form-group"><label>Name</label><input type="text" name="name" class="form-control" value="{{ old('name') }}" required></div><div class="form-group"><label>Subject</label><input type="text" name="subject" class="form-control" value="{{ old('subject') }}"></div><div class="form-group"><label>Message Body</label><textarea name="body" class="form-control" rows="6" required>{{ old('body') }}</textarea></div><div class="checkbox"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked> Active</label></div><br><button class="btn btn-primary btn-block"><i class="fa fa-save"></i> Save Template</button></form></div></div>
</div>
@endsection
