document.addEventListener('DOMContentLoaded', function(){
  var qPrec=parseInt(document.body.dataset.quantityPrecision||'2',10), cPrec=parseInt(document.body.dataset.currencyPrecision||'2',10);
  document.querySelectorAll('[data-confirm]').forEach(function(el){el.addEventListener('click',function(e){if(!confirm(el.getAttribute('data-confirm')))e.preventDefault();});});
  function parseNum(v){var n=parseFloat(String(v).replace(/,/g,'').trim());return isNaN(n)?null:n}
  document.querySelectorAll('.dlr-table').forEach(function(table){
    var holder=table.closest('.dlr-card')||table.parentElement;if(!holder||holder.querySelector('.dlr-toolbar'))return;
    var bar=document.createElement('div');bar.className='dlr-toolbar';bar.innerHTML='<input class="search" placeholder="Universal Search..."><select class="range"><option value="">All Dates</option><option value="this_year">This Year</option><option value="last_year">Last Year</option><option value="this_fy">This FY</option><option value="last_fy">Last FY</option><option value="custom">Custom</option></select><input type="date" class="from"><input type="date" class="to"><select class="limit"><option>10</option><option>25</option><option selected>50</option><option>100</option></select><button type="button" class="csv"><i class="fa fa-file-text-o"></i> CSV</button><button type="button" class="xls"><i class="fa fa-file-excel-o"></i> Excel</button><button type="button" class="print"><i class="fa fa-print"></i> Print</button><button type="button" class="pdf"><i class="fa fa-file-pdf-o"></i> PDF</button><button type="button" class="email"><i class="fa fa-envelope-o"></i> Email</button><button type="button" class="wa"><i class="fa fa-whatsapp"></i> WhatsApp</button>';
    var tw=table.closest('.dlr-table-wrap');holder.insertBefore(bar,tw||table);
    var rows=Array.from(table.querySelectorAll('tbody tr'));function filter(){var s=bar.querySelector('.search').value.toLowerCase(),lim=+bar.querySelector('.limit').value,c=0,hs=Array.from(table.querySelectorAll('thead th')).map(function(x){return x.textContent.toLowerCase()}),di=hs.findIndex(function(x){return x.indexOf('date')>-1||x.indexOf('time')>-1}),from=bar.querySelector('.from').value,to=bar.querySelector('.to').value;rows.forEach(function(r){var ok=r.textContent.toLowerCase().includes(s);if(ok&&di>=0&&(from||to)){var d=new Date((r.children[di]?r.children[di].textContent:'').trim());if(!isNaN(d)){if(from&&d<new Date(from+'T00:00:00'))ok=false;if(to&&d>new Date(to+'T23:59:59'))ok=false;}}r.style.display=ok&&c++<lim?'':'none';});}bar.querySelector('.search').oninput=filter;bar.querySelector('.limit').onchange=filter;bar.querySelector('.from').onchange=filter;bar.querySelector('.to').onchange=filter;bar.querySelector('.range').onchange=function(){var n=new Date(),y=n.getFullYear(),v=this.value,f='',t='';if(v==='this_year'){f=y+'-01-01';t=y+'-12-31'}else if(v==='last_year'){f=(y-1)+'-01-01';t=(y-1)+'-12-31'}else if(v==='this_fy'){var sy=n.getMonth()>=3?y:y-1;f=sy+'-04-01';t=(sy+1)+'-03-31'}else if(v==='last_fy'){var sy2=(n.getMonth()>=3?y:y-1)-1;f=sy2+'-04-01';t=(sy2+1)+'-03-31'}bar.querySelector('.from').value=f;bar.querySelector('.to').value=t;filter();};filter();
    var heads=Array.from(table.querySelectorAll('thead th'));heads.forEach(function(th,i){var h=th.textContent.trim().toLowerCase();if(/qty|quantity|balance|current|min|max|level|avg|suggested|variance|total|amount/.test(h)){rows.forEach(function(r){var td=r.children[i];if(!td)return;td.classList.add('dlr-num');var n=parseNum(td.textContent);if(n!==null){var p=/amount|total/.test(h)?cPrec:qPrec;td.textContent=n.toLocaleString(undefined,{minimumFractionDigits:p,maximumFractionDigits:p});}})}if(h==='notes'||h==='note'){rows.forEach(function(r){var td=r.children[i];if(!td)return;var t=td.textContent.trim();if(t&&t!=='-')td.innerHTML='<button type="button" class="dlr-note-btn" data-note="'+t.replace(/"/g,'&quot;')+'">Note</button>';});}});
    function exp(ext,sep,mime){var lines=[];table.querySelectorAll('tr').forEach(function(r){if(r.style.display==='none')return;lines.push(Array.from(r.children).map(function(c){return '"'+c.innerText.replace(/"/g,'""')+'"'}).join(sep));});var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:mime}));a.download=(document.title||'dealer').replace(/\W+/g,'_')+'.'+ext;a.click();URL.revokeObjectURL(a.href)}
    bar.querySelector('.csv').onclick=function(){exp('csv',',','text/csv')};bar.querySelector('.xls').onclick=function(){exp('xls','\t','application/vnd.ms-excel')};bar.querySelector('.print').onclick=function(){window.print()};bar.querySelector('.pdf').onclick=function(){window.print()};bar.querySelector('.email').onclick=function(){location.href='mailto:?subject='+encodeURIComponent(document.title)+'&body='+encodeURIComponent(location.href)};bar.querySelector('.wa').onclick=function(){window.open('https://wa.me/?text='+encodeURIComponent(document.title+' '+location.href),'_blank')};
  });
  document.querySelectorAll('select.dlr-select').forEach(function(sel){if(sel.options.length<6)return;var inp=document.createElement('input');inp.className='dlr-input dlr-select-search';inp.placeholder='Type to filter...';sel.parentNode.insertBefore(inp,sel);inp.oninput=function(){var v=this.value.toLowerCase();Array.from(sel.options).forEach(function(o){o.hidden=v&&o.text.toLowerCase().indexOf(v)<0});};});
  document.addEventListener('click',function(e){if(e.target.classList.contains('dlr-note-btn')){var m=document.querySelector('.dlr-modal-backdrop');m.querySelector('.dlr-modal-text').textContent=e.target.dataset.note;m.classList.add('show');}});
});
