<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
class CreateLawDocumentAdminTables extends Migration{public function up(){
Schema::create('law_documents',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->string('category',100)->nullable();$t->string('title');$t->string('file_name');$t->string('file_path');$t->string('mime_type',150)->nullable();$t->unsignedBigInteger('file_size')->default(0);$t->unsignedInteger('version')->default(1);$t->boolean('confidential')->default(0);$t->unsignedBigInteger('uploaded_by')->nullable();$t->timestamps();});
Schema::create('law_notes',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->string('note_type',80)->default('general');$t->longText('body');$t->boolean('confidential')->default(0);$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
Schema::create('law_settings',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('setting_key',120);$t->longText('setting_value')->nullable();$t->timestamps();$t->unique(['business_id','location_id','setting_key'],'law_settings_unique');});
Schema::create('law_integration_queue',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('target_module',80)->index();$t->string('event_type',100)->index();$t->string('aggregate_type',80);$t->unsignedBigInteger('aggregate_id')->index();$t->longText('payload_json')->nullable();$t->string('status',30)->default('pending')->index();$t->unsignedInteger('attempts')->default(0);$t->text('last_error')->nullable();$t->dateTime('processed_at')->nullable();$t->timestamps();});
Schema::create('law_activity_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('action',80)->index();$t->string('subject_type',100);$t->unsignedBigInteger('subject_id')->nullable()->index();$t->text('description')->nullable();$t->longText('metadata_json')->nullable();$t->dateTime('created_at')->index();});
}public function down(){foreach(['law_activity_logs','law_integration_queue','law_settings','law_notes','law_documents'] as $x)Schema::dropIfExists($x);}}
