<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
class CreateLawCoreTables extends Migration{public function up(){
Schema::create('law_clients',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('client_no',50)->index();$t->string('client_type',30)->default('individual');$t->string('name');$t->string('company_name')->nullable();$t->string('nic_passport',100)->nullable();$t->string('registration_no',100)->nullable();$t->string('email')->nullable();$t->string('phone',50)->nullable();$t->string('mobile',50)->nullable();$t->string('address_line_1')->nullable();$t->string('address_line_2')->nullable();$t->string('city',100)->nullable();$t->string('state',100)->nullable();$t->string('country',100)->nullable();$t->string('postal_code',30)->nullable();$t->string('tax_no',100)->nullable();$t->string('contact_person')->nullable();$t->string('status',30)->default('active')->index();$t->text('notes')->nullable();$t->unsignedBigInteger('created_by')->nullable()->index();$t->timestamps();$t->softDeletes();$t->unique(['business_id','client_no']);});
Schema::create('law_practice_areas',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('name');$t->string('code',50)->nullable();$t->text('description')->nullable();$t->boolean('active')->default(1);$t->timestamps();$t->unique(['business_id','name']);});
Schema::create('law_courts',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('name');$t->string('code',50)->nullable();$t->string('court_type',100)->nullable();$t->string('address')->nullable();$t->string('city',100)->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->boolean('active')->default(1);$t->timestamps();});
Schema::create('law_matters',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('matter_no',50)->index();$t->unsignedBigInteger('client_id')->index();$t->unsignedBigInteger('practice_area_id')->nullable()->index();$t->unsignedBigInteger('court_id')->nullable()->index();$t->string('case_no',100)->nullable()->index();$t->string('title');$t->text('description')->nullable();$t->string('status',30)->default('open')->index();$t->string('priority',30)->default('normal');$t->date('opened_on')->index();$t->date('closed_on')->nullable();$t->unsignedBigInteger('assigned_user_id')->nullable()->index();$t->unsignedBigInteger('responsible_lawyer_id')->nullable()->index();$t->string('opposing_party')->nullable();$t->string('opposing_counsel')->nullable();$t->decimal('estimated_value',22,4)->default(0);$t->string('fee_type',30)->default('hourly');$t->decimal('hourly_rate',22,4)->default(0);$t->decimal('fixed_fee',22,4)->default(0);$t->decimal('retainer_amount',22,4)->default(0);$t->unsignedBigInteger('created_by')->nullable()->index();$t->timestamps();$t->softDeletes();$t->unique(['business_id','matter_no']);});
Schema::create('law_matter_parties',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->index();$t->string('party_type',50);$t->string('name');$t->string('role',100)->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->timestamps();});
}public function down(){foreach(['law_matter_parties','law_matters','law_courts','law_practice_areas','law_clients'] as $x)Schema::dropIfExists($x);}}
