<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
class CreateLawAdvancedPracticeTables extends Migration {
 public function up(){
  Schema::create('law_workflow_templates',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('name');$t->unsignedBigInteger('practice_area_id')->nullable()->index();$t->text('description')->nullable();$t->boolean('active')->default(1)->index();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('law_workflow_stages',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('workflow_template_id')->index();$t->string('name');$t->unsignedInteger('sequence_no')->default(1);$t->unsignedInteger('default_days')->nullable();$t->boolean('required')->default(0);$t->boolean('active')->default(1)->index();$t->timestamps();});
  Schema::create('law_matter_stage_history',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->index();$t->unsignedBigInteger('workflow_stage_id')->nullable()->index();$t->string('stage_name');$t->string('status',30)->default('active')->index();$t->dateTime('started_at')->index();$t->dateTime('due_at')->nullable()->index();$t->dateTime('completed_at')->nullable();$t->text('notes')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('law_deadlines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->string('deadline_type',80)->index();$t->string('title');$t->date('basis_date')->nullable();$t->dateTime('due_at')->index();$t->unsignedInteger('warning_days')->default(7);$t->string('status',30)->default('open')->index();$t->string('source_type',80)->nullable();$t->unsignedBigInteger('source_id')->nullable()->index();$t->unsignedBigInteger('assigned_user_id')->nullable()->index();$t->text('notes')->nullable();$t->dateTime('completed_at')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('law_evidence_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->index();$t->string('evidence_no',80)->index();$t->string('title');$t->string('evidence_type',80)->index();$t->text('description')->nullable();$t->date('received_on')->nullable()->index();$t->string('custody_location')->nullable();$t->boolean('confidential')->default(0);$t->string('status',30)->default('received')->index();$t->unsignedBigInteger('document_id')->nullable()->index();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','matter_id','evidence_no']);});
  Schema::create('law_document_versions',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('document_id')->index();$t->unsignedInteger('version_no');$t->string('file_name');$t->string('file_path');$t->string('mime_type',150)->nullable();$t->unsignedBigInteger('file_size')->default(0);$t->text('change_note')->nullable();$t->unsignedBigInteger('uploaded_by')->nullable();$t->timestamps();$t->unique(['business_id','document_id','version_no']);});
  Schema::create('law_billing_rates',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->unsignedBigInteger('practice_area_id')->nullable()->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->string('rate_type',30)->default('hourly');$t->decimal('hourly_rate',22,4)->default(0);$t->decimal('fixed_rate',22,4)->default(0);$t->date('effective_from')->nullable()->index();$t->date('effective_to')->nullable()->index();$t->boolean('active')->default(1)->index();$t->timestamps();});
  Schema::create('law_invoice_adjustments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('invoice_id')->index();$t->string('adjustment_type',20)->index();$t->decimal('amount',22,4);$t->text('reason');$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
 }
 public function down(){foreach(['law_invoice_adjustments','law_billing_rates','law_document_versions','law_evidence_items','law_deadlines','law_matter_stage_history','law_workflow_stages','law_workflow_templates'] as $x)Schema::dropIfExists($x);}
}
