<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
class CreateLawOperationsTables extends Migration{public function up(){
Schema::create('law_hearings',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->index();$t->unsignedBigInteger('court_id')->nullable()->index();$t->dateTime('hearing_at')->index();$t->string('hearing_type',100)->nullable();$t->string('judge_name')->nullable();$t->text('purpose')->nullable();$t->text('outcome')->nullable();$t->dateTime('next_hearing_at')->nullable()->index();$t->string('status',30)->default('scheduled')->index();$t->integer('reminder_minutes')->default(1440);$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
Schema::create('law_tasks',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->unsignedBigInteger('assigned_user_id')->nullable()->index();$t->string('title');$t->text('description')->nullable();$t->dateTime('due_at')->nullable()->index();$t->string('priority',30)->default('normal');$t->string('status',30)->default('open')->index();$t->dateTime('completed_at')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
Schema::create('law_time_entries',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->index();$t->unsignedBigInteger('user_id')->index();$t->date('work_date')->index();$t->unsignedInteger('minutes');$t->decimal('rate',22,4)->default(0);$t->decimal('amount',22,4)->default(0);$t->boolean('billable')->default(1);$t->boolean('invoiced')->default(0)->index();$t->text('description');$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
Schema::create('law_expenses',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->date('expense_date')->index();$t->string('category',100);$t->text('description');$t->decimal('amount',22,4);$t->boolean('billable')->default(0);$t->boolean('invoiced')->default(0)->index();$t->string('finance_sync_status',30)->default('pending')->index();$t->string('finance_reference',100)->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
Schema::create('law_appointments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->string('title');$t->dateTime('start_at')->index();$t->dateTime('end_at')->nullable();$t->string('appointment_type',80)->nullable();$t->string('location')->nullable();$t->string('status',30)->default('scheduled');$t->unsignedBigInteger('assigned_user_id')->nullable()->index();$t->text('notes')->nullable();$t->timestamps();});
}public function down(){foreach(['law_appointments','law_expenses','law_time_entries','law_tasks','law_hearings'] as $x)Schema::dropIfExists($x);}}
