<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
class CreateLawReconciliationPortalNotificationTables extends Migration {
 public function up(){
  Schema::create('law_trust_reconciliations',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('trust_account_id')->index();$t->date('statement_date')->index();$t->decimal('statement_balance',22,4);$t->decimal('book_balance',22,4);$t->decimal('difference',22,4);$t->string('status',30)->default('open')->index();$t->unsignedBigInteger('reconciled_by')->nullable();$t->dateTime('reconciled_at')->nullable();$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('law_trust_reconciliation_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('reconciliation_id')->index();$t->unsignedBigInteger('trust_transaction_id')->index();$t->string('line_type',20);$t->decimal('amount',22,4);$t->boolean('matched')->default(0)->index();$t->text('note')->nullable();$t->timestamps();});
  Schema::create('law_portal_access',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('client_id')->index();$t->unsignedBigInteger('contact_id')->nullable()->index();$t->string('email')->index();$t->string('token_hash',64);$t->string('status',30)->default('active')->index();$t->dateTime('last_login_at')->nullable();$t->dateTime('expires_at')->nullable()->index();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','client_id','email']);});
  Schema::create('law_portal_messages',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('client_id')->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->string('direction',20)->default('outbound')->index();$t->string('subject')->nullable();$t->longText('body');$t->string('status',30)->default('logged')->index();$t->dateTime('sent_at')->nullable()->index();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('law_notifications',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->unsignedBigInteger('client_id')->nullable()->index();$t->unsignedBigInteger('matter_id')->nullable()->index();$t->string('type',50)->index();$t->string('title');$t->longText('body')->nullable();$t->string('channel',30)->default('in_app')->index();$t->string('status',30)->default('pending')->index();$t->dateTime('scheduled_at')->nullable()->index();$t->dateTime('sent_at')->nullable();$t->dateTime('read_at')->nullable();$t->string('source_type',80)->nullable();$t->unsignedBigInteger('source_id')->nullable()->index();$t->timestamps();});
 }
 public function down(){foreach(['law_notifications','law_portal_messages','law_portal_access','law_trust_reconciliation_lines','law_trust_reconciliations'] as $x)Schema::dropIfExists($x);}
}
