<?php

return [
    'reports' => [
        'expense_register' => ['code' => 'expense_register', 'title' => 'Expense Register', 'category' => 'enterprise'],
        'expense_summary' => ['code' => 'expense_summary', 'title' => 'Expense Summary', 'category' => 'enterprise'],
        'expense_by_category' => ['code' => 'expense_by_category', 'title' => 'Expense By Category', 'category' => 'enterprise'],
        'expense_by_payee' => ['code' => 'expense_by_payee', 'title' => 'Expense By Payee', 'category' => 'enterprise'],
        'expense_by_department' => ['code' => 'expense_by_department', 'title' => 'Expense By Department', 'category' => 'enterprise'],
        'expense_by_business' => ['code' => 'expense_by_business', 'title' => 'Expense By Business', 'category' => 'enterprise'],
        'expense_by_location' => ['code' => 'expense_by_location', 'title' => 'Expense By Location', 'category' => 'enterprise'],
        'expense_by_cost_centre' => ['code' => 'expense_by_cost_centre', 'title' => 'Expense By Cost Centre', 'category' => 'enterprise'],
        'expense_by_project' => ['code' => 'expense_by_project', 'title' => 'Expense By Project', 'category' => 'enterprise'],
        'payment_register' => ['code' => 'payment_register', 'title' => 'Payment Register', 'category' => 'enterprise'],
        'outstanding_payments' => ['code' => 'outstanding_payments', 'title' => 'Outstanding Payments', 'category' => 'enterprise'],
        'budget_vs_actual' => ['code' => 'budget_vs_actual', 'title' => 'Budget Vs Actual', 'category' => 'enterprise'],
        'budget_variance' => ['code' => 'budget_variance', 'title' => 'Budget Variance', 'category' => 'enterprise'],
        'budget_utilization' => ['code' => 'budget_utilization', 'title' => 'Budget Utilization', 'category' => 'enterprise'],
        'employee_claims' => ['code' => 'employee_claims', 'title' => 'Employee Claims', 'category' => 'enterprise'],
        'petty_cash' => ['code' => 'petty_cash', 'title' => 'Petty Cash', 'category' => 'enterprise'],
        'cash_advances' => ['code' => 'cash_advances', 'title' => 'Cash Advances', 'category' => 'enterprise'],
        'tax_summary' => ['code' => 'tax_summary', 'title' => 'Tax Summary', 'category' => 'enterprise'],
        'approval_history' => ['code' => 'approval_history', 'title' => 'Approval History', 'category' => 'enterprise'],
        'policy_violations' => ['code' => 'policy_violations', 'title' => 'Policy Violations', 'category' => 'enterprise'],
        'duplicate_detection' => ['code' => 'duplicate_detection', 'title' => 'Duplicate Detection', 'category' => 'enterprise'],
        'audit_register' => ['code' => 'audit_register', 'title' => 'Audit Register', 'category' => 'enterprise'],
        'ceo_dashboard' => ['code' => 'ceo_dashboard', 'title' => 'Ceo Dashboard', 'category' => 'enterprise'],
        'cfo_dashboard' => ['code' => 'cfo_dashboard', 'title' => 'Cfo Dashboard', 'category' => 'enterprise'],
        'board_summary' => ['code' => 'board_summary', 'title' => 'Board Summary', 'category' => 'enterprise'],
        'kpi_dashboard' => ['code' => 'kpi_dashboard', 'title' => 'Kpi Dashboard', 'category' => 'enterprise'],
        'trend_analysis' => ['code' => 'trend_analysis', 'title' => 'Trend Analysis', 'category' => 'enterprise'],
        'profitability_analysis' => ['code' => 'profitability_analysis', 'title' => 'Profitability Analysis', 'category' => 'enterprise'],
        'monthly_closing' => ['code' => 'monthly_closing', 'title' => 'Monthly Closing', 'category' => 'enterprise'],
        'year_end_summary' => ['code' => 'year_end_summary', 'title' => 'Year End Summary', 'category' => 'enterprise'],
    ],
];
