<?php

return [
    'module_name' => 'Finance Reports',
    'framework_adapter' => Modules\FinanceReports\Services\Adapters\FinanceReportsEnterpriseAdapter::class,
    'read_only' => true,
    'reports' => [
        /*
         * MA-002: the reports below were MISSING from this list.
         *
         * The module has 69 current "-new" report pages, all routed and all
         * with controllers, but only 10 appeared here - so the dashboard
         * listed 10 and there was no way to reach the rest. Journal Register
         * and Day Book were among the missing, which is why you could not
         * find Journal.
         *
         * Generated from the route file itself, so every entry points at a
         * route that genuinely exists. Categories and labels are derived from
         * the route names - tell me any you would like worded differently.
         */
        ['key' => 'finance_reports.executive_bi_dashboard', 'category' => 'Dashboard', 'name' => 'Executive BI Dashboard - New', 'route' => 'finance-reports.executive-bi-dashboard-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.journal_register', 'category' => 'Ledgers', 'name' => 'Journal Register - New', 'route' => 'finance-reports.journal-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.day_book', 'category' => 'Ledgers', 'name' => 'Day Book - New', 'route' => 'finance-reports.day-book-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_dashboard', 'category' => 'Dashboard', 'name' => 'Financial Dashboard - New', 'route' => 'finance-reports.financial-dashboard-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.budget_vs_actual', 'category' => 'Analysis', 'name' => 'Budget Vs Actual - New', 'route' => 'finance-reports.budget-vs-actual-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.revenue_analysis', 'category' => 'Analysis', 'name' => 'Revenue Analysis - New', 'route' => 'finance-reports.revenue-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.expense_analysis', 'category' => 'Analysis', 'name' => 'Expense Analysis - New', 'route' => 'finance-reports.expense-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.branch_performance', 'category' => 'Dashboard', 'name' => 'Branch Performance - New', 'route' => 'finance-reports.branch-performance-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_ratios', 'category' => 'Analysis', 'name' => 'Financial Ratios - New', 'route' => 'finance-reports.financial-ratios-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.comparative_report', 'category' => 'Analysis', 'name' => 'Comparative Report - New', 'route' => 'finance-reports.comparative-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.customer_outstanding', 'category' => 'Receivables & Payables', 'name' => 'Customer Outstanding - New', 'route' => 'finance-reports.customer-outstanding-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.supplier_outstanding', 'category' => 'Receivables & Payables', 'name' => 'Supplier Outstanding - New', 'route' => 'finance-reports.supplier-outstanding-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.customer_aging', 'category' => 'Receivables & Payables', 'name' => 'Customer Aging - New', 'route' => 'finance-reports.customer-aging-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.supplier_aging', 'category' => 'Receivables & Payables', 'name' => 'Supplier Aging - New', 'route' => 'finance-reports.supplier-aging-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.collection_analysis', 'category' => 'Receivables & Payables', 'name' => 'Collection Analysis - New', 'route' => 'finance-reports.collection-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.payment_analysis', 'category' => 'Analysis', 'name' => 'Payment Analysis - New', 'route' => 'finance-reports.payment-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.receivable_summary', 'category' => 'Receivables & Payables', 'name' => 'Receivable Summary - New', 'route' => 'finance-reports.receivable-summary-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.payable_summary', 'category' => 'Receivables & Payables', 'name' => 'Payable Summary - New', 'route' => 'finance-reports.payable-summary-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.customer_statement', 'category' => 'Receivables & Payables', 'name' => 'Customer Statement - New', 'route' => 'finance-reports.customer-statement-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.supplier_statement', 'category' => 'Receivables & Payables', 'name' => 'Supplier Statement - New', 'route' => 'finance-reports.supplier-statement-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cash_flow_statement', 'category' => 'Cash & Banking', 'name' => 'Cash Flow Statement - New', 'route' => 'finance-reports.cash-flow-statement-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cash_position_report', 'category' => 'Cash & Banking', 'name' => 'Cash Position Report - New', 'route' => 'finance-reports.cash-position-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.bank_position_report', 'category' => 'Cash & Banking', 'name' => 'Bank Position Report - New', 'route' => 'finance-reports.bank-position-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.bank_reconciliation', 'category' => 'Cash & Banking', 'name' => 'Bank Reconciliation - New', 'route' => 'finance-reports.bank-reconciliation-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cheque_register', 'category' => 'Cash & Banking', 'name' => 'Cheque Register - New', 'route' => 'finance-reports.cheque-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.post_dated_cheque_register', 'category' => 'Cash & Banking', 'name' => 'Post Dated Cheque Register - New', 'route' => 'finance-reports.post-dated-cheque-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cash_movement_analysis', 'category' => 'Cash & Banking', 'name' => 'Cash Movement Analysis - New', 'route' => 'finance-reports.cash-movement-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.audit_trail', 'category' => 'Audit & Control', 'name' => 'Audit Trail - New', 'route' => 'finance-reports.audit-trail-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.transaction_history', 'category' => 'Audit & Control', 'name' => 'Transaction History - New', 'route' => 'finance-reports.transaction-history-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.user_financial_activity', 'category' => 'Audit & Control', 'name' => 'User Financial Activity - New', 'route' => 'finance-reports.user-financial-activity-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.deleted_transactions', 'category' => 'Audit & Control', 'name' => 'Deleted Transactions - New', 'route' => 'finance-reports.deleted-transactions-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.edited_transactions', 'category' => 'Audit & Control', 'name' => 'Edited Transactions - New', 'route' => 'finance-reports.edited-transactions-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.voucher_approval_history', 'category' => 'Audit & Control', 'name' => 'Voucher Approval History - New', 'route' => 'finance-reports.voucher-approval-history-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.exception_report', 'category' => 'Audit & Control', 'name' => 'Exception Report - New', 'route' => 'finance-reports.exception-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_log_viewer', 'category' => 'Audit & Control', 'name' => 'Financial Log Viewer - New', 'route' => 'finance-reports.financial-log-viewer-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.fixed_asset_dashboard', 'category' => 'Fixed Assets', 'name' => 'Fixed Asset Dashboard - New', 'route' => 'finance-reports.fixed-asset-dashboard-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.fixed_asset_register', 'category' => 'Fixed Assets', 'name' => 'Fixed Asset Register - New', 'route' => 'finance-reports.fixed-asset-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.depreciation_register', 'category' => 'Fixed Assets', 'name' => 'Depreciation Register - New', 'route' => 'finance-reports.depreciation-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.asset_movement_register', 'category' => 'Fixed Assets', 'name' => 'Asset Movement Register - New', 'route' => 'finance-reports.asset-movement-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.asset_transfer_report', 'category' => 'Fixed Assets', 'name' => 'Asset Transfer Report - New', 'route' => 'finance-reports.asset-transfer-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.asset_disposal_register', 'category' => 'Fixed Assets', 'name' => 'Asset Disposal Register - New', 'route' => 'finance-reports.asset-disposal-register-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.asset_category_summary', 'category' => 'Fixed Assets', 'name' => 'Asset Category Summary - New', 'route' => 'finance-reports.asset-category-summary-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.asset_valuation_report', 'category' => 'Fixed Assets', 'name' => 'Asset Valuation Report - New', 'route' => 'finance-reports.asset-valuation-report-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cash_flow_forecast', 'category' => 'Cash & Banking', 'name' => 'Cash Flow Forecast - New', 'route' => 'finance-reports.cash-flow-forecast-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.revenue_forecast', 'category' => 'Forecasting', 'name' => 'Revenue Forecast - New', 'route' => 'finance-reports.revenue-forecast-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.expense_forecast', 'category' => 'Forecasting', 'name' => 'Expense Forecast - New', 'route' => 'finance-reports.expense-forecast-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.profit_forecast', 'category' => 'Forecasting', 'name' => 'Profit Forecast - New', 'route' => 'finance-reports.profit-forecast-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.consolidation_center', 'category' => 'Tools', 'name' => 'Consolidation Center - New', 'route' => 'finance-reports.consolidation-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.performance_center', 'category' => 'Dashboard', 'name' => 'Performance Center - New', 'route' => 'finance-reports.performance-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.standalone_audit', 'category' => 'Audit & Control', 'name' => 'Standalone Audit - New', 'route' => 'finance-reports.standalone-audit-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.export_center', 'category' => 'Tools', 'name' => 'Export Center - New', 'route' => 'finance-reports.export-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.print_layout_center', 'category' => 'Tools', 'name' => 'Print Layout Center - New', 'route' => 'finance-reports.print-layout-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.drilldown_center', 'category' => 'Tools', 'name' => 'Drilldown Center - New', 'route' => 'finance-reports.drilldown-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_pack', 'category' => 'Tools', 'name' => 'Financial Pack - New', 'route' => 'finance-reports.financial-pack-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.report_scheduler', 'category' => 'Tools', 'name' => 'Report Scheduler - New', 'route' => 'finance-reports.report-scheduler-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.executive_kpi_center', 'category' => 'Dashboard', 'name' => 'Executive KPI Center - New', 'route' => 'finance-reports.executive-kpi-center-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.calculation_verification', 'category' => 'Tools', 'name' => 'Calculation Verification - New', 'route' => 'finance-reports.calculation-verification-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.production_readiness', 'category' => 'Tools', 'name' => 'Production Readiness - New', 'route' => 'finance-reports.production-readiness-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cfo_dashboard', 'category' => 'Dashboard', 'name' => 'CFO Dashboard - New', 'route' => 'finance-reports.cfo-dashboard-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_health_score', 'category' => 'Dashboard', 'name' => 'Financial Health Score - New', 'route' => 'finance-reports.financial-health-score-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.scenario_analysis', 'category' => 'Forecasting', 'name' => 'Scenario Analysis - New', 'route' => 'finance-reports.scenario-analysis-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.board_pack', 'category' => 'Dashboard', 'name' => 'Board Pack - New', 'route' => 'finance-reports.board-pack-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.enterprise_data_hub', 'category' => 'Tools', 'name' => 'Enterprise Data Hub - New', 'route' => 'finance-reports.enterprise-data-hub-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cross_module_financial_intelligence', 'category' => 'Analysis', 'name' => 'Cross Module Financial Intelligence - New', 'route' => 'finance-reports.cross-module-financial-intelligence-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.enterprise_dashboard_builder', 'category' => 'Dashboard', 'name' => 'Enterprise Dashboard Builder - New', 'route' => 'finance-reports.enterprise-dashboard-builder-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.enterprise_report_builder', 'category' => 'Tools', 'name' => 'Enterprise Report Builder - New', 'route' => 'finance-reports.enterprise-report-builder-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_workspace', 'category' => 'Tools', 'name' => 'Financial Workspace - New', 'route' => 'finance-reports.financial-workspace-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.enterprise_report_scheduler', 'category' => 'Tools', 'name' => 'Enterprise Report Scheduler - New', 'route' => 'finance-reports.enterprise-report-scheduler-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.enterprise_platform_audit', 'category' => 'Audit & Control', 'name' => 'Enterprise Platform Audit - New', 'route' => 'finance-reports.enterprise-platform-audit-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.dashboard', 'category' => 'Dashboard', 'name' => 'Finance Reports Dashboard', 'route' => 'finance-reports.dashboard', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.trial_balance', 'category' => 'Financial Statements', 'name' => 'Trial Balance - New', 'route' => 'finance-reports.trial-balance-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.balance_sheet', 'category' => 'Financial Statements', 'name' => 'Balance Sheet - New', 'route' => 'finance-reports.balance-sheet-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.profit_loss', 'category' => 'Financial Statements', 'name' => 'Profit & Loss - New', 'route' => 'finance-reports.profit-loss-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.income_statement', 'category' => 'Financial Statements', 'name' => 'Income Statement - New', 'route' => 'finance-reports.income-statement-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.general_ledger', 'category' => 'Ledgers', 'name' => 'General Ledger - New', 'route' => 'finance-reports.general-ledger-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.account_ledger', 'category' => 'Ledgers', 'name' => 'Account Ledger - New', 'route' => 'finance-reports.account-ledger-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.cash_book', 'category' => 'Cash & Banking', 'name' => 'Cash Book - New', 'route' => 'finance-reports.cash-book-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.bank_book', 'category' => 'Cash & Banking', 'name' => 'Bank Book - New', 'route' => 'finance-reports.bank-book-new', 'permission' => 'finance_reports.view'],
        ['key' => 'finance_reports.financial_intelligence', 'category' => 'Intelligence', 'name' => 'Financial Intelligence - New', 'route' => 'finance-reports.financial-intelligence-new', 'permission' => 'finance_reports.view'],
    ],
];
