<?php
return [
    'module_key' => 'dealer_management',
    'module_name' => 'Dealer Management',
    'route_prefix' => 'dealermanagement.',
    'icon' => 'fa fa-handshake-o',
    'condition_service' => Modules\DealerManagement\Services\DistributionAvailabilityService::class,
    'items' => [
        ['title'=>'Dashboard','route'=>'dealermanagement.admin.dashboard','permission'=>'dealer_management_dashboard','icon'=>'fa fa-dashboard'],
        ['title'=>'Dealers','route'=>'dealermanagement.admin.dealers.index','permission'=>'dealer_management_dealers','icon'=>'fa fa-users'],
        ['title'=>'Multi-Distributor Dealer Hub','route'=>'dealermanagement.admin.hub.index','permission'=>'dealer_management_hub','icon'=>'fa fa-sitemap'],
        ['title'=>'Dealer Outlets','route'=>'dealermanagement.admin.outlets.index','permission'=>'dealer_management_outlets','icon'=>'fa fa-map-marker'],
        ['title'=>'Dealer Users','route'=>'dealermanagement.admin.users.index','permission'=>'dealer_management_users','icon'=>'fa fa-user'],
        ['title'=>'Dealer Roles','route'=>'dealermanagement.admin.roles.index','permission'=>'dealer_management_roles','icon'=>'fa fa-key'],
        ['title'=>'Dealer Stock Balances','route'=>'dealermanagement.admin.stock.index','permission'=>'dealer_management_stock','icon'=>'fa fa-cubes'],
        ['title'=>'Dealer Stock History','route'=>'dealermanagement.admin.stock.history','permission'=>'dealer_management_stock_history','icon'=>'fa fa-history'],
        ['title'=>'Hub Dealer Sales','route'=>'dealermanagement.admin.hub-sales.index','permission'=>'dealer_management_hub_sales','icon'=>'fa fa-line-chart'],
        ['title'=>'Dealer Stock Updates','route'=>'dealermanagement.admin.stock.updates','permission'=>'dealer_management_stock_updates','icon'=>'fa fa-check-square-o'],
        ['title'=>'Re-order Planning','route'=>'dealermanagement.admin.reorder.index','permission'=>'dealer_management_reorder','icon'=>'fa fa-refresh'],
        ['title'=>'Dealer Orders','route'=>'dealermanagement.admin.orders.index','permission'=>'dealer_management_orders','icon'=>'fa fa-shopping-cart'],
        ['title'=>'Deliveries','route'=>'dealermanagement.admin.deliveries.index','permission'=>'dealer_management_deliveries','icon'=>'fa fa-truck'],
        ['title'=>'Returns','route'=>'dealermanagement.admin.returns.index','permission'=>'dealer_management_returns','icon'=>'fa fa-reply'],
        ['title'=>'Notifications & Alerts','route'=>'dealermanagement.admin.notifications.index','permission'=>'dealer_management_notifications','icon'=>'fa fa-bell'],
        ['title'=>'Reports','route'=>'dealermanagement.admin.reports.index','permission'=>'dealer_management_reports','icon'=>'fa fa-bar-chart'],
        ['title'=>'Distribution Sync','route'=>'dealermanagement.admin.sync.index','permission'=>'dealer_management_distribution_sync','icon'=>'fa fa-exchange'],
        ['title'=>'Dealer Login','route'=>'dealermanagement.login','permission'=>'dealer_management_dealer_login','icon'=>'fa fa-sign-in'],
        ['title'=>'Dealer Hub Login','route'=>'dealermanagement.hub.login','permission'=>'dealer_management_hub_login','icon'=>'fa fa-globe'],
    ],
];
