<?php
return [
    'dashboard.view' => 'View dealer dashboard',
    'stock.view' => 'View stock balances',
    'stock.update' => 'Submit physical stock updates',
    'stock.history' => 'View stock history',
    'orders.view' => 'View orders',
    'orders.create' => 'Create orders',
    'orders.submit' => 'Submit orders',
    'deliveries.view' => 'View deliveries',
    'returns.view' => 'View returns',
    'notifications.view' => 'View notifications',
    'reports.view' => 'View reports',
    'users.view' => 'View dealer users',
    'users.manage' => 'Create/edit/reset dealer users',
    'outlets.view' => 'View dealer outlets',
    'outlets.manage' => 'Manage dealer outlets',
    'settings.manage' => 'Manage dealer settings and reorder rules',
    'hub.view' => 'View multi-distributor Dealer Hub',
    'hub.sales.create' => 'Enter combined daily sales',
    'hub.connections.manage' => 'Manage distributor connections',
    'hub.orders.create' => 'Create combined split orders',
    'hub.users.manage' => 'Manage Dealer Hub staff users',
];
