@extends('ezylaw::layouts.module')
@section('ezylaw_title','Advanced Legal Reports')
@section('ezylaw_content')
<div class="box"><div class="box-body"><form class="form-inline" method="get"><label>From <input type="date" class="form-control" name="from" value="{{ $from }}"></label><label>To <input type="date" class="form-control" name="to" value="{{ $to }}"></label><button class="btn btn-primary">Apply</button></form></div></div>
<div class="ezylaw-grid"><div class="law-card"><span>Open Matters</span><strong>{{ $open_matters->count() }}</strong></div><div class="law-card"><span>Overdue Deadlines</span><strong>{{ $overdue_deadlines }}</strong></div><div class="law-card"><span>Open Tasks</span><strong>{{ $open_tasks }}</strong></div><div class="law-card"><span>Recorded Hours</span><strong>{{ number_format($hours,2) }}</strong></div><div class="law-card"><span>Receivables</span><strong>{{ number_format($receivables,2) }}</strong></div><div class="law-card"><span>Evidence Added</span><strong>{{ $evidence->count() }}</strong></div><div class="law-card"><span>Deadlines in Period</span><strong>{{ $deadlines->count() }}</strong></div><div class="law-card"><span>Trust Reconciliations</span><strong>{{ $trust_recs->count() }}</strong></div><div class="law-card"><span>Court Filings</span><strong>{{ $filings->count() }}</strong></div><div class="law-card"><span>Settlements</span><strong>{{ $settlements->count() }}</strong></div><div class="law-card"><span>Fee Estimates</span><strong>{{ $estimates->count() }}</strong></div><div class="law-card"><span>Advance Balance</span><strong>{{ number_format($advance_balance,2) }}</strong></div><div class="law-card"><span>Pending E-Sign</span><strong>{{ $pending_esign }}</strong></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Deadline Diary</h3></div><div class="box-body table-responsive"><table class="table table-bordered law-table-compact"><tr><th>Due</th><th>Matter</th><th>Type</th><th>Title</th></tr>@foreach($deadlines as $d)<tr><td>{{ optional($d->due_at)->format('Y-m-d H:i') }}</td><td>{{ optional($d->matter)->matter_no }}</td><td>{{ $d->deadline_type }}</td><td>{{ $d->title }}</td></tr>@endforeach</table></div></div>

<div class="row"><div class="col-md-7"><div class="box"><div class="box-header"><h3 class="box-title">Court Filing Report</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Date</th><th>Filing</th><th>Matter</th><th>Court</th><th>Type</th><th>Status</th></tr></thead><tbody>@foreach($filings as $f)<tr><td>{{ optional($f->filed_on)->format('Y-m-d') }}</td><td>{{ $f->filing_no }}</td><td>{{ optional($f->matter)->matter_no }}</td><td>{{ optional($f->court)->name }}</td><td>{{ $f->filing_type }}</td><td>{{ $f->status }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-md-5"><div class="box"><div class="box-header"><h3 class="box-title">Settlement Report</h3></div><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>Matter</th><th>Status</th><th class="text-right">Agreed</th></tr></thead><tbody>@foreach($settlements as $s)<tr><td>{{ optional($s->matter)->matter_no }}</td><td>{{ $s->status }}</td><td class="text-right">{{ number_format((float)$s->agreed_amount,2) }}</td></tr>@endforeach</tbody></table></div></div></div></div>
@endsection
