@extends('layouts.app')
@section('title', 'Hotel Staff Payroll')
@section('content')
<section class="content-header hm-page-header"><h1><i class="fa fa-money"></i> Staff Payroll <small>Hotel payroll costing, service-charge review and pay run control</small></h1></section>
<section class="content hm-pos-scope">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please check:</strong> {{ $errors->first() }}</div>@endif
<div class="row hm-kpi-row">
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Active Rules</div><div class="hm-kpi-value">{{ $staffPayroll['active_rules'] }}</div><div class="hm-kpi-sub">Salary rules ready</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Draft Runs</div><div class="hm-kpi-value">{{ $staffPayroll['draft_runs'] }}</div><div class="hm-kpi-sub">Pending approval</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Gross Total</div><div class="hm-kpi-value">{{ number_format($staffPayroll['latest_gross'], 2) }}</div><div class="hm-kpi-sub">Loaded run gross</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Net Total</div><div class="hm-kpi-value">{{ number_format($staffPayroll['latest_net'], 2) }}</div><div class="hm-kpi-sub">Loaded run net</div></div></div>
</div>
<div class="row">
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Payroll Rule</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.staff-payroll.rule') }}">@csrf
  <div class="form-group"><label>Staff</label><select name="staff_id" class="form-control" required><option value="">Select Staff</option>@foreach($staffPayroll['staff'] as $s)<option value="{{ $s->id }}">{{ $s->employee_no }} - {{ $s->name }}</option>@endforeach</select></div>
  <div class="form-group"><label>Salary Type</label><select name="salary_type" class="form-control" required><option value="monthly">Monthly</option><option value="daily">Daily</option><option value="hourly">Hourly</option></select></div>
  <div class="form-group"><label>Basic / OT Rate</label><div class="row"><div class="col-xs-6"><input type="number" step="0.01" name="basic_salary" class="form-control" required></div><div class="col-xs-6"><input type="number" step="0.01" name="ot_rate" class="form-control" placeholder="OT rate"></div></div></div>
  <div class="form-group"><label>Allowance / Deduction</label><div class="row"><div class="col-xs-6"><input type="number" step="0.01" name="allowance_amount" class="form-control" placeholder="Allowance"></div><div class="col-xs-6"><input type="number" step="0.01" name="deduction_amount" class="form-control" placeholder="Deduction"></div></div></div>
  <div class="form-group"><label>Effective From</label><input type="date" name="effective_from" class="form-control" required></div>
  <div class="text-right"><button class="btn hm-btn-add"><i class="fa fa-save"></i> Save Rule</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Generate Pay Run</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.staff-payroll.run') }}">@csrf
  <div class="form-group"><label>Payroll No</label><input name="payroll_no" class="form-control" placeholder="Auto if blank"></div>
  <div class="form-group"><label>Period</label><div class="row"><div class="col-xs-6"><input type="date" name="period_from" class="form-control" required></div><div class="col-xs-6"><input type="date" name="period_to" class="form-control" required></div></div></div>
  <div class="form-group"><label>Pay Date / Department</label><input type="date" name="pay_date" class="form-control"><input name="department" class="form-control" style="margin-top:6px" placeholder="Optional department filter"></div>
  <div class="form-group"><label>Remarks</label><textarea name="remarks" class="form-control" rows="2"></textarea></div>
  <div class="text-right"><button class="btn hm-btn-excel"><i class="fa fa-cogs"></i> Generate Run</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Operating Notes</h3></div><div class="box-body"><ul class="hm-note-list">@foreach($staffPayroll['notes'] as $note)<li>{{ $note }}</li>@endforeach</ul><div class="alert alert-info" style="margin-bottom:0">Approved hotel payroll can be posted to Finance later through a controlled bridge. This parcel keeps records inside the standalone Hotel module.</div></div></div></div>
</div>
<div class="box hm-card"><div class="box-header with-border"><div class="hm-toolbar"><input class="form-control hm-search-input" style="max-width:260px" placeholder="Search payroll..."><button class="btn hm-btn-csv">CSV</button><button class="btn hm-btn-excel">Excel</button><button class="btn hm-btn-pdf">PDF</button><button class="btn hm-btn-print">Print</button><button class="btn hm-btn-col">Column Visibility</button></div><h3 class="box-title">Payroll Runs</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>Payroll No</th><th>Period</th><th>Pay Date</th><th>Department</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($staffPayroll['runs'] as $r)<tr><td>{{ $r->payroll_no }}</td><td>{{ $r->period_from }} - {{ $r->period_to }}</td><td>{{ $r->pay_date }}</td><td>{{ $r->department }}</td><td>{{ number_format($r->gross_amount,2) }}</td><td>{{ number_format($r->deduction_amount,2) }}</td><td>{{ number_format($r->net_amount,2) }}</td><td><span class="hm-badge {{ $r->status }}">{{ ucfirst($r->status) }}</span></td><td><form method="POST" action="{{ route('hotel-management.staff-payroll.status',$r->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="draft">Draft</option><option value="approved">Approved</option><option value="posted">Posted</option><option value="cancelled">Cancelled</option></select><button class="btn btn-xs hm-btn-add">Update</button></form></td></tr>@empty<tr><td colspan="9" class="text-center text-muted">No payroll runs yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Payroll Lines</h3></div><div class="box-body table-responsive"><table class="table table-bordered hm-table"><thead><tr><th>Run</th><th>Staff</th><th>Attendance Days</th><th>Basic</th><th>OT</th><th>Allowance</th><th>Deduction</th><th>Net</th><th>Adjust</th></tr></thead><tbody>@forelse($staffPayroll['lines'] as $l)<tr><td>{{ $l->payroll_run_id }}</td><td>{{ $l->staff_id }}</td><td>{{ $l->attendance_days }}</td><td>{{ number_format($l->basic_amount,2) }}</td><td>{{ number_format($l->ot_amount,2) }}</td><td>{{ number_format($l->allowance_amount,2) }}</td><td>{{ number_format($l->deduction_amount,2) }}</td><td>{{ number_format($l->net_amount,2) }}</td><td><form method="POST" action="{{ route('hotel-management.staff-payroll.line-adjust',$l->id) }}" class="form-inline">@csrf<input type="number" step="0.01" name="ot_hours" class="form-control input-sm" style="width:70px" placeholder="OT"><input type="number" step="0.01" name="allowance_amount" class="form-control input-sm" style="width:85px" placeholder="Allow"><input type="number" step="0.01" name="deduction_amount" class="form-control input-sm" style="width:85px" placeholder="Ded"><button class="btn btn-xs hm-btn-excel">Save</button></form></td></tr>@empty<tr><td colspan="9" class="text-center text-muted">No payroll lines yet.</td></tr>@endforelse</tbody></table></div></div>
</section>
@endsection
