-- Tea Estate Management - MASTER INSTALL
-- IMPORTANT: run only in the intended TENANT database. Do NOT run operational tea_* tables in the central database.
-- Safe/idempotent foundation: CREATE TABLE IF NOT EXISTS + permission INSERT WHERE NOT EXISTS.

-- Tea Estate Management - Operational schema
-- Safe for a selected TENANT database. All module tables use the tea_ prefix.
-- No foreign keys are added to core/common tables; business/location/user ids are scoped application references.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `tea_settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `setting_key` VARCHAR(120) NOT NULL,
  `setting_value` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_settings_business_location_key_unique` (`business_id`,`location_id`,`setting_key`),
  KEY `tea_settings_business_id_index` (`business_id`),
  KEY `tea_settings_location_id_index` (`location_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_number_sequences` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `document_type` VARCHAR(40) NOT NULL,
  `prefix` VARCHAR(20) NULL,
  `current_number` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_number_sequences_business_type_unique` (`business_id`,`document_type`),
  KEY `tea_number_sequences_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_varieties` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `clone_reference` VARCHAR(100) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_varieties_business_code_unique` (`business_id`,`code`),
  KEY `tea_varieties_business_id_index` (`business_id`),
  KEY `tea_varieties_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_estates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `estate_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `address` TEXT NULL,
  `area_acres` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_estates_business_code_unique` (`business_id`,`estate_code`),
  KEY `tea_estates_business_id_index` (`business_id`),
  KEY `tea_estates_location_id_index` (`location_id`),
  KEY `tea_estates_status_index` (`status`),
  KEY `tea_estates_scope_index` (`business_id`,`location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_divisions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `estate_id` BIGINT UNSIGNED NOT NULL,
  `division_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `manager_name` VARCHAR(150) NULL,
  `area_acres` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_divisions_estate_code_unique` (`business_id`,`estate_id`,`division_code`),
  KEY `tea_divisions_business_id_index` (`business_id`),
  KEY `tea_divisions_estate_id_index` (`estate_id`),
  KEY `tea_divisions_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_fields` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `estate_id` BIGINT UNSIGNED NOT NULL,
  `division_id` BIGINT UNSIGNED NULL,
  `field_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `variety_id` BIGINT UNSIGNED NULL,
  `planted_date` DATE NULL,
  `area_acres` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `plant_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `elevation_meters` DECIMAL(12,2) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_fields_business_code_unique` (`business_id`,`field_code`),
  KEY `tea_fields_business_id_index` (`business_id`),
  KEY `tea_fields_location_id_index` (`location_id`),
  KEY `tea_fields_estate_id_index` (`estate_id`),
  KEY `tea_fields_division_id_index` (`division_id`),
  KEY `tea_fields_variety_id_index` (`variety_id`),
  KEY `tea_fields_status_index` (`status`),
  KEY `tea_fields_scope_index` (`business_id`,`location_id`,`estate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_field_activities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `field_id` BIGINT UNSIGNED NOT NULL,
  `activity_date` DATE NOT NULL,
  `activity_type` VARCHAR(60) NOT NULL,
  `quantity` DECIMAL(20,4) NULL,
  `unit` VARCHAR(30) NULL,
  `cost_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `finance_account_id` BIGINT UNSIGNED NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_field_activities_business_id_index` (`business_id`),
  KEY `tea_field_activities_location_id_index` (`location_id`),
  KEY `tea_field_activities_field_id_index` (`field_id`),
  KEY `tea_field_activities_activity_date_index` (`activity_date`),
  KEY `tea_field_activities_activity_type_index` (`activity_type`),
  KEY `tea_field_activities_finance_account_id_index` (`finance_account_id`),
  KEY `tea_field_activities_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_harvests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `estate_id` BIGINT UNSIGNED NOT NULL,
  `division_id` BIGINT UNSIGNED NULL,
  `field_id` BIGINT UNSIGNED NOT NULL,
  `harvest_no` VARCHAR(50) NOT NULL,
  `harvest_date` DATE NOT NULL,
  `plucker_reference` VARCHAR(150) NULL,
  `green_leaf_qty_kg` DECIMAL(20,3) NOT NULL,
  `rejected_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `accepted_qty_kg` DECIMAL(20,3) NOT NULL,
  `quality_grade` VARCHAR(50) NULL,
  `moisture_percent` DECIMAL(8,3) NULL,
  `inventory_lot_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'received',
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_harvests_business_no_unique` (`business_id`,`harvest_no`),
  KEY `tea_harvests_business_id_index` (`business_id`),
  KEY `tea_harvests_location_id_index` (`location_id`),
  KEY `tea_harvests_estate_id_index` (`estate_id`),
  KEY `tea_harvests_division_id_index` (`division_id`),
  KEY `tea_harvests_field_id_index` (`field_id`),
  KEY `tea_harvests_harvest_date_index` (`harvest_date`),
  KEY `tea_harvests_inventory_lot_id_index` (`inventory_lot_id`),
  KEY `tea_harvests_status_index` (`status`),
  KEY `tea_harvests_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_parties` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `party_code` VARCHAR(50) NOT NULL,
  `party_type` VARCHAR(20) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `mobile` VARCHAR(40) NULL,
  `email` VARCHAR(150) NULL,
  `address` TEXT NULL,
  `tax_no` VARCHAR(80) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_parties_business_code_unique` (`business_id`,`party_code`),
  KEY `tea_parties_business_id_index` (`business_id`),
  KEY `tea_parties_party_type_index` (`party_type`),
  KEY `tea_parties_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_leaf_purchases` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `purchase_no` VARCHAR(50) NOT NULL,
  `purchase_date` DATE NOT NULL,
  `supplier_id` BIGINT UNSIGNED NOT NULL,
  `vehicle_no` VARCHAR(60) NULL,
  `weighbridge_ref` VARCHAR(80) NULL,
  `source_estate_name` VARCHAR(180) NULL,
  `gross_weight_kg` DECIMAL(20,3) NOT NULL,
  `tare_weight_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `net_weight_kg` DECIMAL(20,3) NOT NULL,
  `rejected_weight_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `accepted_weight_kg` DECIMAL(20,3) NOT NULL,
  `quality_grade` VARCHAR(50) NULL,
  `rate_per_kg` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `quality_deduction_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `other_deduction_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `gross_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `net_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `payment_status` VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  `inventory_lot_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'received',
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_leaf_purchases_business_no_unique` (`business_id`,`purchase_no`),
  KEY `tea_leaf_purchases_business_id_index` (`business_id`),
  KEY `tea_leaf_purchases_location_id_index` (`location_id`),
  KEY `tea_leaf_purchases_purchase_date_index` (`purchase_date`),
  KEY `tea_leaf_purchases_supplier_id_index` (`supplier_id`),
  KEY `tea_leaf_purchases_payment_status_index` (`payment_status`),
  KEY `tea_leaf_purchases_inventory_lot_id_index` (`inventory_lot_id`),
  KEY `tea_leaf_purchases_status_index` (`status`),
  KEY `tea_leaf_purchases_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_purchase_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `purchase_id` BIGINT UNSIGNED NOT NULL,
  `paid_on` DATETIME NOT NULL,
  `method` VARCHAR(30) NOT NULL DEFAULT 'cash',
  `reference_no` VARCHAR(100) NULL,
  `amount` DECIMAL(20,4) NOT NULL,
  `finance_account_id` BIGINT UNSIGNED NULL,
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_purchase_payments_finance_account_id_index` (`finance_account_id`),
  KEY `tea_purchase_payments_business_id_index` (`business_id`),
  KEY `tea_purchase_payments_location_id_index` (`location_id`),
  KEY `tea_purchase_payments_purchase_id_index` (`purchase_id`),
  KEY `tea_purchase_payments_paid_on_index` (`paid_on`),
  KEY `tea_purchase_payments_method_index` (`method`),
  KEY `tea_purchase_payments_reference_no_index` (`reference_no`),
  KEY `tea_purchase_payments_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_factories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `factory_code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `address` TEXT NULL,
  `daily_capacity_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_factories_business_code_unique` (`business_id`,`factory_code`),
  KEY `tea_factories_business_id_index` (`business_id`),
  KEY `tea_factories_location_id_index` (`location_id`),
  KEY `tea_factories_status_index` (`status`),
  KEY `tea_factories_scope_index` (`business_id`,`location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_processing_stages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `stage_code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `sequence_no` INT UNSIGNED NOT NULL DEFAULT 1,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_processing_stages_business_code_unique` (`business_id`,`stage_code`),
  KEY `tea_processing_stages_business_id_index` (`business_id`),
  KEY `tea_processing_stages_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_processing_batches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `factory_id` BIGINT UNSIGNED NOT NULL,
  `batch_no` VARCHAR(50) NOT NULL,
  `process_date` DATE NOT NULL,
  `input_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `output_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `process_loss_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `yield_percent` DECIMAL(10,3) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'in_progress',
  `completed_at` DATETIME NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_processing_batches_business_no_unique` (`business_id`,`batch_no`),
  KEY `tea_processing_batches_business_id_index` (`business_id`),
  KEY `tea_processing_batches_location_id_index` (`location_id`),
  KEY `tea_processing_batches_factory_id_index` (`factory_id`),
  KEY `tea_processing_batches_process_date_index` (`process_date`),
  KEY `tea_processing_batches_status_index` (`status`),
  KEY `tea_processing_batches_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_batch_inputs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `processing_batch_id` BIGINT UNSIGNED NOT NULL,
  `inventory_lot_id` BIGINT UNSIGNED NOT NULL,
  `source_type` VARCHAR(50) NULL,
  `source_id` BIGINT UNSIGNED NULL,
  `qty_kg` DECIMAL(20,3) NOT NULL,
  `unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_batch_inputs_business_id_index` (`business_id`),
  KEY `tea_batch_inputs_processing_batch_id_index` (`processing_batch_id`),
  KEY `tea_batch_inputs_inventory_lot_id_index` (`inventory_lot_id`),
  KEY `tea_batch_inputs_source_type_index` (`source_type`),
  KEY `tea_batch_inputs_source_id_index` (`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_processing_stage_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `processing_batch_id` BIGINT UNSIGNED NOT NULL,
  `stage_id` BIGINT UNSIGNED NOT NULL,
  `sequence_no` INT UNSIGNED NOT NULL DEFAULT 1,
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `input_qty_kg` DECIMAL(20,3) NULL,
  `output_qty_kg` DECIMAL(20,3) NULL,
  `temperature_c` DECIMAL(10,2) NULL,
  `moisture_percent` DECIMAL(8,3) NULL,
  `cost_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `finance_account_id` BIGINT UNSIGNED NULL,
  `operator_user_id` BIGINT UNSIGNED NULL,
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_stage_entries_business_id_index` (`business_id`),
  KEY `tea_stage_entries_location_id_index` (`location_id`),
  KEY `tea_stage_entries_batch_id_index` (`processing_batch_id`),
  KEY `tea_stage_entries_stage_id_index` (`stage_id`),
  KEY `tea_stage_entries_started_at_index` (`started_at`),
  KEY `tea_stage_entries_finance_account_id_index` (`finance_account_id`),
  KEY `tea_stage_entries_operator_user_id_index` (`operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_grades` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `grade_code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `default_sale_price` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_grades_business_code_unique` (`business_id`,`grade_code`),
  KEY `tea_grades_business_id_index` (`business_id`),
  KEY `tea_grades_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_batch_outputs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `processing_batch_id` BIGINT UNSIGNED NOT NULL,
  `grade_id` BIGINT UNSIGNED NOT NULL,
  `item_type` VARCHAR(30) NOT NULL DEFAULT 'made_tea',
  `qty_kg` DECIMAL(20,3) NOT NULL,
  `unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `inventory_lot_id` BIGINT UNSIGNED NULL,
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_batch_outputs_business_id_index` (`business_id`),
  KEY `tea_batch_outputs_location_id_index` (`location_id`),
  KEY `tea_batch_outputs_processing_batch_id_index` (`processing_batch_id`),
  KEY `tea_batch_outputs_grade_id_index` (`grade_id`),
  KEY `tea_batch_outputs_item_type_index` (`item_type`),
  KEY `tea_batch_outputs_inventory_lot_id_index` (`inventory_lot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_inventory_lots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `lot_no` VARCHAR(60) NOT NULL,
  `item_type` VARCHAR(30) NOT NULL,
  `grade_id` BIGINT UNSIGNED NULL,
  `processing_batch_id` BIGINT UNSIGNED NULL,
  `source_type` VARCHAR(50) NULL,
  `source_id` BIGINT UNSIGNED NULL,
  `opening_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `current_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'available',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_inventory_lots_business_no_unique` (`business_id`,`lot_no`),
  KEY `tea_inventory_lots_business_id_index` (`business_id`),
  KEY `tea_inventory_lots_location_id_index` (`location_id`),
  KEY `tea_inventory_lots_item_type_index` (`item_type`),
  KEY `tea_inventory_lots_grade_id_index` (`grade_id`),
  KEY `tea_inventory_lots_processing_batch_id_index` (`processing_batch_id`),
  KEY `tea_inventory_lots_source_type_index` (`source_type`),
  KEY `tea_inventory_lots_source_id_index` (`source_id`),
  KEY `tea_inventory_lots_status_index` (`status`),
  KEY `tea_inventory_lots_scope_index` (`business_id`,`location_id`,`item_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_stock_movements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `inventory_lot_id` BIGINT UNSIGNED NOT NULL,
  `movement_no` VARCHAR(60) NOT NULL,
  `movement_date` DATETIME NOT NULL,
  `movement_type` VARCHAR(40) NOT NULL,
  `qty_in_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `qty_out_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `reference_type` VARCHAR(50) NULL,
  `reference_id` BIGINT UNSIGNED NULL,
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_stock_movements_business_no_unique` (`business_id`,`movement_no`),
  KEY `tea_stock_movements_business_id_index` (`business_id`),
  KEY `tea_stock_movements_location_id_index` (`location_id`),
  KEY `tea_stock_movements_inventory_lot_id_index` (`inventory_lot_id`),
  KEY `tea_stock_movements_movement_date_index` (`movement_date`),
  KEY `tea_stock_movements_movement_type_index` (`movement_type`),
  KEY `tea_stock_movements_reference_type_index` (`reference_type`),
  KEY `tea_stock_movements_reference_id_index` (`reference_id`),
  KEY `tea_stock_movements_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_sales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `sale_no` VARCHAR(50) NOT NULL,
  `sale_date` DATE NOT NULL,
  `buyer_id` BIGINT UNSIGNED NOT NULL,
  `invoice_ref` VARCHAR(80) NULL,
  `currency_code` VARCHAR(10) NOT NULL DEFAULT 'LKR',
  `total_qty_kg` DECIMAL(20,3) NOT NULL DEFAULT 0,
  `subtotal` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `tax_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `payment_status` VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  `status` VARCHAR(20) NOT NULL DEFAULT 'posted',
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_sales_business_no_unique` (`business_id`,`sale_no`),
  KEY `tea_sales_business_id_index` (`business_id`),
  KEY `tea_sales_location_id_index` (`location_id`),
  KEY `tea_sales_sale_date_index` (`sale_date`),
  KEY `tea_sales_buyer_id_index` (`buyer_id`),
  KEY `tea_sales_payment_status_index` (`payment_status`),
  KEY `tea_sales_status_index` (`status`),
  KEY `tea_sales_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_sale_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `sale_id` BIGINT UNSIGNED NOT NULL,
  `inventory_lot_id` BIGINT UNSIGNED NOT NULL,
  `grade_id` BIGINT UNSIGNED NULL,
  `description` VARCHAR(180) NULL,
  `qty_kg` DECIMAL(20,3) NOT NULL,
  `unit_price` DECIMAL(20,4) NOT NULL,
  `amount` DECIMAL(20,4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_sale_lines_business_id_index` (`business_id`),
  KEY `tea_sale_lines_sale_id_index` (`sale_id`),
  KEY `tea_sale_lines_inventory_lot_id_index` (`inventory_lot_id`),
  KEY `tea_sale_lines_grade_id_index` (`grade_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_sale_receipts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `sale_id` BIGINT UNSIGNED NOT NULL,
  `received_on` DATETIME NOT NULL,
  `method` VARCHAR(30) NOT NULL DEFAULT 'cash',
  `reference_no` VARCHAR(100) NULL,
  `amount` DECIMAL(20,4) NOT NULL,
  `finance_account_id` BIGINT UNSIGNED NULL,
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_sale_receipts_finance_account_id_index` (`finance_account_id`),
  KEY `tea_sale_receipts_business_id_index` (`business_id`),
  KEY `tea_sale_receipts_location_id_index` (`location_id`),
  KEY `tea_sale_receipts_sale_id_index` (`sale_id`),
  KEY `tea_sale_receipts_received_on_index` (`received_on`),
  KEY `tea_sale_receipts_method_index` (`method`),
  KEY `tea_sale_receipts_reference_no_index` (`reference_no`),
  KEY `tea_sale_receipts_created_by_index` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_audit_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `action` VARCHAR(60) NOT NULL,
  `entity_type` VARCHAR(80) NOT NULL,
  `entity_id` BIGINT UNSIGNED NULL,
  `before_json` LONGTEXT NULL,
  `after_json` LONGTEXT NULL,
  `ip_address` VARCHAR(64) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tea_audit_logs_business_id_index` (`business_id`),
  KEY `tea_audit_logs_user_id_index` (`user_id`),
  KEY `tea_audit_logs_action_index` (`action`),
  KEY `tea_audit_logs_entity_type_index` (`entity_type`),
  KEY `tea_audit_logs_entity_id_index` (`entity_id`),
  KEY `tea_audit_entity_index` (`business_id`,`entity_type`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE IF NOT EXISTS `tea_finance_account_mappings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `purpose` VARCHAR(60) NOT NULL,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_fin_map_business_location_purpose_unique` (`business_id`,`location_id`,`purpose`),
  KEY `tea_fin_map_account_index` (`account_id`),
  KEY `tea_fin_map_business_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tea_finance_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `source_type` VARCHAR(50) NOT NULL,
  `source_id` BIGINT UNSIGNED NOT NULL,
  `event_type` VARCHAR(50) NOT NULL,
  `document_no` VARCHAR(100) NOT NULL,
  `operation_date` DATETIME NOT NULL,
  `amount` DECIMAL(20,4) NOT NULL DEFAULT 0,
  `payload_json` LONGTEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `core_transaction_id` BIGINT UNSIGNED NULL,
  `attempts` INT UNSIGNED NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `posted_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tea_fin_event_source_unique` (`business_id`,`source_type`,`source_id`,`event_type`),
  KEY `tea_fin_event_status_index` (`business_id`,`status`),
  KEY `tea_fin_event_location_index` (`location_id`),
  KEY `tea_fin_event_core_transaction_index` (`core_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
