<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('rcm_settings',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->json('settings')->nullable();$t->unsignedBigInteger('updated_by')->nullable();$t->timestamps();$t->unique('business_id');});
  Schema::create('rcm_number_series',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('series_type',60);$t->string('prefix',20);$t->unsignedBigInteger('next_number')->default(1);$t->timestamps();$t->unique(['business_id','series_type']);});
  Schema::create('rcm_paddy_varieties',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('paddy_product_id')->nullable()->index();$t->string('code',30)->nullable();$t->string('name',120);$t->decimal('default_moisture_percent',8,3)->nullable();$t->decimal('foreign_matter_limit_percent',8,3)->nullable();$t->decimal('expected_rice_yield_percent',8,3)->nullable();$t->decimal('expected_broken_rice_percent',8,3)->nullable();$t->decimal('expected_bran_percent',8,3)->nullable();$t->decimal('expected_husk_percent',8,3)->nullable();$t->decimal('expected_process_loss_percent',8,3)->nullable();$t->string('quality_grade',50)->nullable();$t->unsignedBigInteger('lot_opening_number')->default(1);$t->boolean('active')->default(true);$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','name']);$t->unique(['business_id','paddy_product_id'],'rcm_paddy_variety_business_product_unique');});
  Schema::create('rcm_mills',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('code',30)->nullable();$t->string('name',120);$t->decimal('capacity_per_hour',20,3)->nullable();$t->boolean('active')->default(true);$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('rcm_products',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('products_new_product_id')->nullable();$t->index('products_new_product_id','rcm_products_products_new_product_idx');$t->unique(['business_id','products_new_product_id'],'rcm_products_business_products_new_unique');$t->string('code',40)->nullable();$t->string('name',150);$t->string('rice_type',100)->nullable();$t->unsignedBigInteger('paddy_variety_id')->nullable();$t->index(['business_id','paddy_variety_id'],'rcm_products_business_paddy_variety_idx');$t->decimal('current_qty',20,3)->default(0);$t->boolean('active')->default(true);$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','name']);});
  Schema::create('rcm_paddy_purchases',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('purchase_no',40);$t->date('purchase_date');$t->unsignedBigInteger('supplier_id')->index();$t->decimal('subtotal',20,4)->default(0);$t->decimal('other_charges',20,4)->default(0);$t->decimal('net_total',20,4)->default(0);$t->string('status',30)->default('draft')->index();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->unsignedBigInteger('approved_by')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['business_id','purchase_no']);});
  Schema::create('rcm_paddy_purchase_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('purchase_id')->index();$t->unsignedBigInteger('paddy_variety_id')->index();$t->decimal('net_weight',20,3);$t->decimal('unit_rate',20,4);$t->decimal('deduction_amount',20,4)->default(0);$t->decimal('line_total',20,4)->default(0);$t->timestamps();});
  Schema::create('rcm_weighbridge_entries',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('entry_no',40);$t->string('vehicle_no',50)->nullable();$t->unsignedBigInteger('supplier_id')->nullable()->index();$t->decimal('gross_weight',20,3);$t->decimal('tare_weight',20,3);$t->decimal('net_weight',20,3);$t->unsignedBigInteger('receipt_id')->nullable()->index();$t->timestamp('weighed_at')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','entry_no']);});
  Schema::create('rcm_paddy_receipts',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('receipt_no',40);$t->unsignedBigInteger('weighbridge_entry_id')->nullable()->index();$t->unsignedBigInteger('purchase_id')->nullable()->index();$t->unsignedBigInteger('supplier_id')->index();$t->unsignedBigInteger('paddy_variety_id')->index();$t->unsignedBigInteger('paddy_lot_id')->nullable()->index();$t->string('vehicle_no',50)->nullable();$t->decimal('gross_weight',20,3);$t->decimal('tare_weight',20,3);$t->decimal('net_weight',20,3);$t->decimal('moisture_percent',8,3)->nullable();$t->decimal('foreign_matter_percent',8,3)->nullable();$t->decimal('foreign_matter_limit_percent',8,3)->nullable();$t->string('quality_grade',50)->nullable();$t->string('status',30)->default('received');$t->timestamp('received_at');$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','receipt_no']);});
  Schema::create('rcm_paddy_lots',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('lot_no',40);$t->unsignedBigInteger('receipt_id')->nullable()->index();$t->unsignedBigInteger('paddy_variety_id')->index();$t->unsignedBigInteger('supplier_id')->nullable()->index();$t->decimal('original_qty',20,3);$t->decimal('balance_qty',20,3)->default(0)->index();$t->decimal('moisture_percent',8,3)->nullable();$t->string('quality_grade',50)->nullable();$t->date('received_date');$t->string('status',30)->default('available')->index();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','lot_no']);});
  Schema::create('rcm_paddy_stock_movements',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->unsignedBigInteger('paddy_lot_id')->index();$t->date('movement_date')->index();$t->string('movement_type',40)->index();$t->decimal('quantity',20,3);$t->decimal('signed_quantity',20,3);$t->string('reference_type',60)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->index(['reference_type','reference_id']);});
  Schema::create('rcm_production_batches',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->unsignedBigInteger('mill_id')->nullable()->index();$t->string('batch_no',40);$t->string('status',30)->default('draft')->index();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->decimal('input_qty',20,3)->default(0);$t->decimal('rice_output_qty',20,3)->default(0);$t->decimal('total_output_qty',20,3)->default(0);$t->decimal('process_loss_qty',20,3)->default(0);$t->decimal('rice_yield_percent',10,4)->default(0);$t->decimal('production_cost',20,4)->default(0);$t->decimal('cost_per_kg',20,4)->default(0);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->unsignedBigInteger('completed_by')->nullable();$t->timestamps();$t->unique(['business_id','batch_no']);});
  Schema::create('rcm_production_inputs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('production_batch_id')->index();$t->unsignedBigInteger('paddy_lot_id')->index();$t->decimal('quantity',20,3);$t->timestamps();});
  Schema::create('rcm_production_outputs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('production_batch_id')->index();$t->string('output_type',40)->index();$t->unsignedBigInteger('product_id')->nullable()->index();$t->decimal('quantity',20,3);$t->decimal('unit_cost',20,4)->default(0);$t->timestamps();});
  Schema::create('rcm_byproduct_movements',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('byproduct_type',60)->index();$t->date('movement_date')->index();$t->string('movement_type',40);$t->decimal('quantity',20,3);$t->decimal('signed_quantity',20,3);$t->string('reference_type',60)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('rcm_packing_batches',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('packing_no',40);$t->timestamp('packed_at')->nullable();$t->decimal('total_packed_qty',20,3)->default(0);$t->string('status',30)->default('completed');$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','packing_no']);});
  Schema::create('rcm_packing_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('packing_batch_id')->index();$t->unsignedBigInteger('product_id')->index();$t->decimal('bag_size_kg',12,3);$t->unsignedInteger('bag_count');$t->decimal('total_qty',20,3);$t->timestamps();});
  Schema::create('rcm_finished_stock_movements',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->unsignedBigInteger('product_id')->index();$t->date('movement_date')->index();$t->string('movement_type',40)->index();$t->decimal('quantity',20,3);$t->decimal('signed_quantity',20,3);$t->string('reference_type',60)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->index(['reference_type','reference_id']);});
  Schema::create('rcm_dispatches',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('store_id')->nullable()->index();$t->string('dispatch_no',40);$t->date('dispatch_date')->index();$t->unsignedBigInteger('customer_id')->index();$t->string('vehicle_no',60)->nullable();$t->string('driver_name',120)->nullable();$t->decimal('subtotal',20,4)->default(0);$t->decimal('unit_discount_amount',20,4)->default(0);$t->string('discount_type',20)->default('fixed');$t->decimal('discount_value',20,4)->default(0);$t->decimal('discount_amount',20,4)->default(0);$t->decimal('tax_percent',10,4)->default(0);$t->decimal('tax_amount',20,4)->default(0);$t->decimal('net_total',20,4)->default(0);$t->string('status',30)->default('draft')->index();$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->unsignedBigInteger('approved_by')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['business_id','dispatch_no']);});
  Schema::create('rcm_dispatch_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('dispatch_id')->index();$t->unsignedBigInteger('product_id')->index();$t->decimal('quantity',20,3);$t->decimal('unit_price',20,4);$t->string('unit_discount_type',20)->default('fixed');$t->decimal('unit_discount_value',20,4)->default(0);$t->decimal('unit_discount_amount',20,4)->default(0);$t->decimal('net_unit_price',20,4)->default(0);$t->decimal('line_total',20,4);$t->timestamps();});
  Schema::create('rcm_cost_entries',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('production_batch_id')->nullable()->index();$t->date('cost_date')->index();$t->string('cost_type',80)->index();$t->decimal('amount',20,4);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
  Schema::create('rcm_finance_outbox',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('event_type',80)->index();$t->string('source_type',80);$t->unsignedBigInteger('source_id');$t->json('payload');$t->string('status',30)->default('pending')->index();$t->unsignedInteger('attempts')->default(0);$t->text('last_error')->nullable();$t->timestamp('processed_at')->nullable();$t->timestamps();$t->index(['source_type','source_id']);});
  Schema::create('rcm_integration_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('integration',80)->index();$t->string('direction',20);$t->string('status',30)->index();$t->json('payload')->nullable();$t->text('message')->nullable();$t->timestamps();});
 }
 public function down(): void { foreach(['rcm_integration_logs','rcm_finance_outbox','rcm_cost_entries','rcm_dispatch_lines','rcm_dispatches','rcm_finished_stock_movements','rcm_packing_lines','rcm_packing_batches','rcm_byproduct_movements','rcm_production_outputs','rcm_production_inputs','rcm_production_batches','rcm_paddy_stock_movements','rcm_paddy_lots','rcm_paddy_receipts','rcm_weighbridge_entries','rcm_paddy_purchase_lines','rcm_paddy_purchases','rcm_products','rcm_mills','rcm_paddy_varieties','rcm_number_series','rcm_settings'] as $t) Schema::dropIfExists($t); }
};
