@extends('ezylaw::layouts.module')
@section('ezylaw_title','Legal Calendar & Reminders')
@section('ezylaw_content')
<div class="box"><div class="box-body"><form class="form-inline" method="get"><label>From <input class="form-control" type="date" name="from" value="{{ $from }}"></label><label>To <input class="form-control" type="date" name="to" value="{{ $to }}"></label><button class="btn btn-primary">Apply</button></form></div></div>
<div class="row"><div class="col-md-4"><div class="box box-primary"><div class="box-header"><h3 class="box-title">New Appointment</h3></div><form method="post" action="{{ route('ezylaw.appointments.store') }}"><div class="box-body">@csrf<label>Client</label><select class="form-control" name="client_id"><option value="">None</option>@foreach($clients as $c)<option value="{{ $c->id }}">{{ $c->client_no }} - {{ $c->name }}</option>@endforeach</select><label>Matter</label><select class="form-control" name="matter_id"><option value="">None</option>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select><label>Title</label><input class="form-control" name="title" required><label>Start</label><input class="form-control" type="datetime-local" name="start_at" required><label>End</label><input class="form-control" type="datetime-local" name="end_at"><label>Type</label><input class="form-control" name="appointment_type"><label>Location</label><input class="form-control" name="location"><input type="hidden" name="status" value="scheduled"><label>Notes</label><textarea class="form-control" name="notes"></textarea></div><div class="box-footer"><button class="btn btn-primary">Save Appointment</button></div></form></div></div>
<div class="col-md-4"><div class="box box-warning"><div class="box-header"><h3 class="box-title">New Reminder</h3></div><form method="post" action="{{ route('ezylaw.reminders.store') }}"><div class="box-body">@csrf<label>Client</label><select class="form-control" name="client_id"><option value="">None</option>@foreach($clients as $c)<option value="{{ $c->id }}">{{ $c->client_no }} - {{ $c->name }}</option>@endforeach</select><label>Matter</label><select class="form-control" name="matter_id"><option value="">None</option>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select><label>Title</label><input class="form-control" name="title" required><label>Remind At</label><input class="form-control" type="datetime-local" name="remind_at" required><label>Channel</label><select class="form-control" name="channel"><option value="in_app">In App</option><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select><label>Repeat Rule</label><input class="form-control" name="repeat_rule" placeholder="Optional"><label>Notes</label><textarea class="form-control" name="notes"></textarea></div><div class="box-footer"><button class="btn btn-warning">Save Reminder</button></div></form></div></div>
<div class="col-md-4"><div class="box"><div class="box-header"><h3 class="box-title">Period Summary</h3></div><div class="box-body"><p><b>Total Events:</b> {{ count($events) }}</p><p><b>Appointments:</b> {{ $appointments->count() }}</p><p><b>Reminders:</b> {{ $reminders->count() }}</p><p class="help-block">Hearings and task deadlines are automatically included from their own EzyLaw records.</p></div></div></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Combined Legal Calendar</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Date/Time</th><th>Type</th><th>Matter</th><th>Event</th><th>Status</th></tr></thead><tbody>@forelse($events as $e)<tr><td>{{ $e['at']->format('Y-m-d H:i') }}</td><td>{{ $e['type'] }}</td><td>{{ $e['matter'] }}</td><td>{{ $e['title'] }}</td><td>{{ ucfirst($e['status']) }}</td></tr>@empty<tr><td colspan="5">No calendar events for this period.</td></tr>@endforelse</tbody></table></div></div>
<div class="row"><div class="col-md-6"><div class="box"><div class="box-header"><h3 class="box-title">Appointments</h3></div><div class="box-body table-responsive"><table class="table table-bordered"><tr><th>Start</th><th>Title</th><th>Action</th></tr>@foreach($appointments as $a)<tr><td>{{ optional($a->start_at)->format('Y-m-d H:i') }}</td><td>{{ $a->title }}</td><td><form method="post" action="{{ route('ezylaw.appointments.destroy',$a) }}">@csrf @method('DELETE')<button class="btn btn-xs btn-danger">Delete</button></form></td></tr>@endforeach</table></div></div></div><div class="col-md-6"><div class="box"><div class="box-header"><h3 class="box-title">Reminders</h3></div><div class="box-body table-responsive"><table class="table table-bordered"><tr><th>Remind At</th><th>Title</th><th>Status</th><th>Action</th></tr>@foreach($reminders as $r)<tr><td>{{ optional($r->remind_at)->format('Y-m-d H:i') }}</td><td>{{ $r->title }}</td><td>{{ ucfirst($r->status) }}</td><td>@if($r->status==='pending')<form style="display:inline" method="post" action="{{ route('ezylaw.reminders.dismiss',$r) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-warning">Dismiss</button></form>@endif<form style="display:inline" method="post" action="{{ route('ezylaw.reminders.destroy',$r) }}">@csrf @method('DELETE')<button class="btn btn-xs btn-danger">Delete</button></form></td></tr>@endforeach</table></div></div></div></div>
@endsection
