@extends('pumperdashboardnew::layouts.admin')
@section('title','Reconciliation')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Management Control</div><h1>Shortage Recovery & Excess Commission</h1><p>Review every operator shift and post controlled recovery or commission entries.</p></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Shift Reconciliation</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table"><thead><tr><th>Shift</th><th>Operator</th><th>Date</th><th class="pone-text-right">Expected</th><th class="pone-text-right">Declared</th><th class="pone-text-right">Shortage</th><th class="pone-text-right">Recovered</th><th class="pone-text-right">Excess</th><th class="pone-text-right">Commissioned</th><th>Result</th><th>Action</th></tr></thead><tbody>@forelse($shifts as $shift) @php($recovered=(float)$shift->shortageRecoveries->where('status','confirmed')->sum('amount')) @php($commissioned=(float)$shift->excessCommissions->where('status','confirmed')->sum('commission_amount')) @php($availableShort=max(0,(float)$shift->shortage_amount-$recovered)) @php($availableExcess=max(0,(float)$shift->excess_amount-$commissioned))
<tr><td><a href="{{ route('pumper-dashboard-new.admin.shifts.show',$shift) }}"><strong>{{ $shift->shift_number }}</strong></a></td><td>{{ $shift->operatorProfile->display_name ?? ('Operator '.$shift->pd_operator_id) }}</td><td>{{ optional($shift->opened_at)->format('Y-m-d H:i') }}</td><td class="pone-text-right">{{ number_format((float)$shift->expected_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$shift->declared_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$shift->shortage_amount,4) }}</td><td class="pone-text-right">{{ number_format($recovered,4) }}</td><td class="pone-text-right">{{ number_format((float)$shift->excess_amount,4) }}</td><td class="pone-text-right">{{ number_format($commissioned,4) }}</td><td><span class="pone-badge pone-badge-{{ $shift->reconciliation_status }}">{{ $shift->reconciliation_status }}</span></td><td><div class="pone-actions">@can('pumper_dashboard_new.reconciliation.manage')@if($availableShort>0)<button type="button" class="pone-btn pone-btn-danger pone-btn-sm" data-toggle-target="#recover-{{ $shift->id }}">Recover</button>@endif @if($availableExcess>0)<button type="button" class="pone-btn pone-btn-success pone-btn-sm" data-toggle-target="#commission-{{ $shift->id }}">Commission</button>@endif @endcan</div></td></tr>
@can('pumper_dashboard_new.reconciliation.manage')
@if($availableShort>0)<tr id="recover-{{ $shift->id }}" class="pone-section-hidden"><td colspan="11"><form method="post" action="{{ route('pumper-dashboard-new.admin.reconciliation.recover',$shift) }}" data-confirm-message="Confirm shortage recovery for {{ $shift->shift_number }}?">@csrf<div class="pone-form-grid"><div class="pone-field pone-col-2"><label>Available</label><input readonly value="{{ number_format($availableShort,4,'.','') }}"></div><div class="pone-field pone-col-2"><label class="pone-required">Amount</label><input name="amount" type="number" min="0.0001" max="{{ $availableShort }}" step="0.0001" required></div><div class="pone-field pone-col-2"><label>Method</label><select name="payment_method"><option>cash</option><option>card</option><option>cheque</option><option>bank</option><option>other</option></select></div><div class="pone-field pone-col-2"><label>Date</label><input name="recovery_date" type="date" value="{{ now()->toDateString() }}"></div><div class="pone-field pone-col-2"><label>Reference</label><input name="reference_no"></div><div class="pone-field pone-col-2" style="align-self:end"><button class="pone-btn pone-btn-danger pone-btn-block">Save Recovery</button></div><div class="pone-field pone-col-12"><label>Note</label><input name="note"></div></div></form></td></tr>@endif
@if($availableExcess>0)<tr id="commission-{{ $shift->id }}" class="pone-section-hidden"><td colspan="11"><form method="post" action="{{ route('pumper-dashboard-new.admin.reconciliation.commission',$shift) }}" data-confirm-message="Confirm excess commission for {{ $shift->shift_number }}?">@csrf<div class="pone-form-grid"><div class="pone-field pone-col-2"><label>Available Excess</label><input readonly value="{{ number_format($availableExcess,4,'.','') }}"></div><div class="pone-field pone-col-2"><label>Type</label><select name="commission_type"><option value="percentage">Percentage</option><option value="fixed">Fixed Amount</option></select></div><div class="pone-field pone-col-2"><label class="pone-required">Rate / Amount</label><input name="commission_rate" type="number" min="0.000001" step="0.000001" required></div><div class="pone-field pone-col-2"><label>Date</label><input name="commission_date" type="date" value="{{ now()->toDateString() }}"></div><div class="pone-field pone-col-3"><label>Note</label><input name="note"></div><div class="pone-field pone-col-1" style="align-self:end"><button class="pone-btn pone-btn-success pone-btn-block">Save</button></div></div></form></td></tr>@endif
@endcan
@empty<tr><td colspan="11" class="pone-empty">No shifts available.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Shortage Recovery History</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>No.</th><th>Shift</th><th>Operator</th><th>Date</th><th class="pone-text-right">Amount</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recoveries as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->recovery_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->operatorProfile->display_name ?? '-' }}</td><td>{{ optional($row->recovery_date)->format('Y-m-d') }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td>@can('pumper_dashboard_new.reconciliation.manage')@if($row->status==='confirmed')<form method="post" action="{{ route('pumper-dashboard-new.admin.reconciliation.recoveries.destroy',$row) }}" data-confirm-message="Void this recovery?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form>@endif@endcan</td></tr>@empty<tr><td colspan="7" class="pone-empty">None</td></tr>@endforelse</tbody></table></div></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Excess Commission History</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>No.</th><th>Shift</th><th>Operator</th><th>Date</th><th class="pone-text-right">Amount</th><th>Status</th><th></th></tr></thead><tbody>@forelse($commissions as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->commission_number }}</td><td>{{ $row->shift->shift_number ?? '-' }}</td><td>{{ $row->operatorProfile->display_name ?? '-' }}</td><td>{{ optional($row->commission_date)->format('Y-m-d') }}</td><td class="pone-text-right">{{ number_format((float)$row->commission_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td>@can('pumper_dashboard_new.reconciliation.manage')@if($row->status==='confirmed')<form method="post" action="{{ route('pumper-dashboard-new.admin.reconciliation.commissions.destroy',$row) }}" data-confirm-message="Void this commission?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form>@endif@endcan</td></tr>@empty<tr><td colspan="7" class="pone-empty">None</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
