@extends('leadsnew::layouts.app')
@section('title', 'Leads-New Quotations')
@section('leadsnew_subtitle', 'Create and review quotations linked to leads and opportunities without leaving the standalone module.')
@section('leadsnew_content')
<div class="ln-split-grid">
<div class="ln-panel"><div class="ln-panel-header"><div><h3 class="ln-panel-title"><i class="fa fa-file-text-o"></i> Quotation Register</h3><div class="ch-card-subtitle">Latest quotation drafts and outcomes.</div></div><span class="ln-badge">{{ method_exists($quotes, 'total') ? $quotes->total() : count($quotes) }} quotations</span></div><div class="ln-table table-responsive"><table class="table table-hover"><thead><tr><th>Quotation No.</th><th>Date</th><th>Valid Until</th><th class="text-right">Subtotal</th><th class="text-right">Tax</th><th class="text-right">Total</th><th>Status</th></tr></thead><tbody>
@forelse($quotes as $quote)<tr><td><strong>{{ $quote->quote_no }}</strong><br><span class="text-muted">Lead #{{ $quote->lead_id ?: '-' }}</span></td><td>{{ optional($quote->quote_date)->format('Y-m-d') ?: '-' }}</td><td>{{ optional($quote->valid_until)->format('Y-m-d') ?: '-' }}</td><td class="text-right">{{ number_format((float)$quote->subtotal, 2) }}</td><td class="text-right">{{ number_format((float)$quote->tax_total, 2) }}</td><td class="text-right"><strong>{{ number_format((float)$quote->total, 2) }}</strong></td><td><span class="ln-badge">{{ ucfirst($quote->status ?: 'draft') }}</span></td></tr>@empty<tr><td colspan="7"><div class="ln-empty"><i class="fa fa-file-text-o"></i>No quotations found.</div></td></tr>@endforelse
</tbody></table></div>@if(method_exists($quotes, 'links'))<div class="ln-panel-body">{{ $quotes->links() }}</div>@endif</div>
<div class="ln-panel ln-sticky-panel"><div class="ln-panel-header"><h3 class="ln-panel-title"><i class="fa fa-plus-circle"></i> New Draft Quotation</h3></div><div class="ln-panel-body"><form method="post" action="{{ url('/leads-new/quotes') }}">@csrf<div class="row"><div class="col-sm-6"><div class="form-group"><label>Lead ID</label><input type="number" name="lead_id" class="form-control" value="{{ old('lead_id') }}"></div></div><div class="col-sm-6"><div class="form-group"><label>Opportunity ID</label><input type="number" name="opportunity_id" class="form-control" value="{{ old('opportunity_id') }}"></div></div></div><div class="row"><div class="col-sm-6"><div class="form-group"><label>Quotation Date</label><input type="date" name="quote_date" class="form-control" value="{{ old('quote_date', date('Y-m-d')) }}"></div></div><div class="col-sm-6"><div class="form-group"><label>Valid Until</label><input type="date" name="valid_until" class="form-control" value="{{ old('valid_until') }}"></div></div></div><div class="row"><div class="col-sm-5"><div class="form-group"><label>Quantity</label><input type="number" step="0.001" name="items[0][qty]" class="form-control" value="{{ old('items.0.qty', 1) }}"></div></div><div class="col-sm-7"><div class="form-group"><label>Rate</label><input type="number" step="0.01" name="items[0][rate]" class="form-control" value="{{ old('items.0.rate', 0) }}"></div></div></div><div class="form-group"><label>Tax Total</label><input type="number" step="0.01" name="tax_total" class="form-control" value="{{ old('tax_total', 0) }}"></div><button class="btn btn-primary btn-block"><i class="fa fa-save"></i> Create Draft</button></form></div></div>
</div>
@endsection
