<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if (!Schema::hasTable('pos_categories')) { Schema::create('pos_categories', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->string('name');$table->string('code')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();}); }
  if (!Schema::hasTable('pos_brands')) { Schema::create('pos_brands', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->string('name');$table->string('code')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();}); }
  if (!Schema::hasTable('pos_products')) { Schema::create('pos_products', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->unsignedBigInteger('category_id')->nullable();$table->unsignedBigInteger('brand_id')->nullable();$table->string('name');$table->string('sku')->nullable();$table->string('barcode')->nullable();$table->decimal('sell_price',22,4)->default(0);$table->decimal('stock_qty',22,4)->default(0);$table->boolean('enable_stock')->default(true);$table->string('image')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();}); }
  if (!Schema::hasTable('pos_customers')) { Schema::create('pos_customers', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->string('name');$table->string('mobile')->nullable();$table->string('customer_code')->nullable();$table->string('email')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();}); }
  if (!Schema::hasTable('pos_registers')) { Schema::create('pos_registers', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->unsignedInteger('business_location_id')->nullable();$table->string('name');$table->string('code')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();}); }
  if (!Schema::hasTable('pos_sales')) { Schema::create('pos_sales', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->unsignedInteger('business_location_id')->nullable();$table->unsignedBigInteger('register_id')->nullable();$table->string('invoice_no')->nullable();$table->decimal('total_amount',22,4)->default(0);$table->decimal('paid_amount',22,4)->default(0);$table->string('payment_status')->default('due');$table->timestamps();}); }
  if (!Schema::hasTable('pos_sale_lines')) { Schema::create('pos_sale_lines', function(Blueprint $table){$table->id();$table->unsignedBigInteger('pos_sale_id');$table->unsignedInteger('product_id')->nullable();$table->decimal('quantity',22,4)->default(0);$table->decimal('unit_price',22,4)->default(0);$table->decimal('line_total',22,4)->default(0);$table->timestamps();}); }
  if (!Schema::hasTable('pos_payments')) { Schema::create('pos_payments', function(Blueprint $table){$table->id();$table->unsignedBigInteger('pos_sale_id');$table->string('method');$table->decimal('amount',22,4)->default(0);$table->string('reference_no')->nullable();$table->date('paid_on')->nullable();$table->timestamps();}); }
  if (!Schema::hasTable('pos_holds')) { Schema::create('pos_holds', function(Blueprint $table){$table->id();$table->unsignedInteger('business_id')->nullable();$table->string('hold_no')->nullable();$table->json('cart_payload')->nullable();$table->timestamps();}); }
 }
 public function down(): void { Schema::dropIfExists('pos_holds'); Schema::dropIfExists('pos_payments'); Schema::dropIfExists('pos_sale_lines'); Schema::dropIfExists('pos_sales'); Schema::dropIfExists('pos_registers'); Schema::dropIfExists('pos_customers'); Schema::dropIfExists('pos_products'); Schema::dropIfExists('pos_brands'); Schema::dropIfExists('pos_categories'); }
};
