<?php
return [
    ['key'=>'ezylaw_dashboard_view','label'=>'Dashboard','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_clients_view','label'=>'Clients - View','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_clients_create','label'=>'Clients - Add','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_clients_update','label'=>'Clients - Edit','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_clients_delete','label'=>'Clients - Delete','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_matters_view','label'=>'Matters / Cases - View','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_matters_create','label'=>'Matters / Cases - Add','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_matters_update','label'=>'Matters / Cases - Edit','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_matters_delete','label'=>'Matters / Cases - Delete','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_chronology_view','label'=>'Matter Chronology','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_chronology_manage','label'=>'Matter Chronology - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_parties_view','label'=>'Matter Parties / Counsel','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_parties_manage','label'=>'Matter Parties / Counsel - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_hearings_view','label'=>'Hearings / Court Diary','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_hearings_manage','label'=>'Hearings - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_tasks_view','label'=>'Tasks','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_tasks_manage','label'=>'Tasks - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_calendar_view','label'=>'Legal Calendar / Reminders','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_calendar_manage','label'=>'Legal Calendar / Reminders - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_time_view','label'=>'Time Entries','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_time_manage','label'=>'Time Entries - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_retainers_view','label'=>'Retainer Agreements','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_retainers_manage','label'=>'Retainer Agreements - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_trust_view','label'=>'Client Trust Accounting','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_trust_manage','label'=>'Client Trust Accounting - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_trust_finance','label'=>'Client Trust Accounting - Finance Sync','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_billing_view','label'=>'Billing / Invoices','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_billing_manage','label'=>'Billing - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_expenses_view','label'=>'Matter Expenses','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_expenses_manage','label'=>'Matter Expenses - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_documents_view','label'=>'Documents','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_documents_manage','label'=>'Documents - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_templates_view','label'=>'Legal Document Templates','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_templates_manage','label'=>'Legal Document Templates - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_communications_view','label'=>'Client Communications','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_communications_manage','label'=>'Client Communications - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_conflicts_view','label'=>'Conflict Checks','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_conflicts_manage','label'=>'Conflict Checks - Run','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_reports_view','label'=>'Reports','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_settings_view','label'=>'Settings','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_settings_manage','label'=>'Settings - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_workflow_view','label'=>'Case Stages / Workflow','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_workflow_manage','label'=>'Case Stages / Workflow - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_deadlines_view','label'=>'Limitation / Legal Deadlines','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_deadlines_manage','label'=>'Limitation / Legal Deadlines - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_evidence_view','label'=>'Evidence / Exhibits','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_evidence_manage','label'=>'Evidence / Exhibits - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_billing_rates','label'=>'Billing Rates - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_billing_adjust','label'=>'Invoice Adjustments','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_trust_reconcile','label'=>'Trust Reconciliation','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_workload_view','label'=>'Lawyer Workload / Capacity','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_portal_view','label'=>'Client Portal Administration','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_portal_manage','label'=>'Client Portal Administration - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_notifications_view','label'=>'Notifications','type'=>'page','source'=>'module_pages'],
    ['key'=>'ezylaw_notifications_manage','label'=>'Notifications - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_reports_advanced','label'=>'Advanced Legal Reports','type'=>'page','source'=>'module_pages'],

    ['key'=>'ezylaw_court_filings_view','label'=>'Court Filings','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/court-filings']],
    ['key'=>'ezylaw_court_filings_manage','label'=>'Court Filings - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_settlements_view','label'=>'Settlements / Mediation','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/settlements']],
    ['key'=>'ezylaw_settlements_manage','label'=>'Settlements / Mediation - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_research_view','label'=>'Legal Research / Precedents','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/research']],
    ['key'=>'ezylaw_research_manage','label'=>'Legal Research / Precedents - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_estimates_view','label'=>'Fee Estimates / Quotations','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/estimates']],
    ['key'=>'ezylaw_estimates_manage','label'=>'Fee Estimates / Quotations - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_estimates_convert','label'=>'Fee Estimates - Convert to Invoice','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_advances_view','label'=>'Client Advances','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/advances']],
    ['key'=>'ezylaw_advances_manage','label'=>'Client Advances - Record','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_advances_allocate','label'=>'Client Advances - Allocate','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_advances_finance','label'=>'Client Advances - Finance Sync','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_document_approvals_view','label'=>'Document Approvals / E-Sign','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/document-approvals']],
    ['key'=>'ezylaw_document_approvals_manage','label'=>'Document Approvals - Request','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_document_approvals_respond','label'=>'Document Approvals - Respond','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_document_approvals_respond_any','label'=>'Document Approvals - Respond for Any Approver','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_esign_manage','label'=>'E-Sign Requests - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_notification_rules_view','label'=>'Notification Rules','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/notification-rules']],
    ['key'=>'ezylaw_notification_rules_manage','label'=>'Notification Rules - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_matter_closure_view','label'=>'Matter Closing / Reopening','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/matter-closures']],
    ['key'=>'ezylaw_matter_closure_manage','label'=>'Matter Closing / Reopening - Manage','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_matter_closure_force','label'=>'Matter Closing - Force Close','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_management_dashboard_view','label'=>'Management Dashboard','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/management-dashboard']],
    ['key'=>'ezylaw_management_dashboard_manage','label'=>'Management Dashboard - Lawyer Targets / Cost Rates','type'=>'permission','source'=>'module_pages'],
    ['key'=>'ezylaw_trust_audit_view','label'=>'Trust Audit Report','type'=>'page','source'=>'module_pages','route_paths'=>['ezylaw/trust-audit']],
];
