@extends('pumperdashboardnew::layouts.operator')
@section('title','Edit Day Entry')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Controlled Edit</div><h1>Edit Day Entry #{{ $entry->id }}</h1><p>Shift {{ $shift->shift_number }}</p></div><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.day-entries.index') }}">Back</a></div>
<div class="pone-panel"><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.day-entries.update',$entry) }}" data-confirm-message="Save this day-entry change?">@csrf @method('PUT')<div class="pone-form-grid">
<div class="pone-field pone-col-3"><label class="pone-required">Entry Type</label><select name="entry_type" required>@foreach(['note','incident','expense','deposit','meter','testing','other'] as $type)<option value="{{ $type }}" @selected(old('entry_type',$entry->entry_type)===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div>
<div class="pone-field pone-col-3"><label>Pump Assignment</label><select name="assignment_id"><option value="">Not linked</option>@foreach($assignments as $a)<option value="{{ $a->id }}" @selected((string)old('assignment_id',$entry->assignment_id)===(string)$a->id)>{{ $pumps->get($a->pump_id)->pump_name ?? $pumps->get($a->pump_id)->pump_no ?? ('Pump '.$a->pump_id) }}</option>@endforeach</select></div>
<div class="pone-field pone-col-3"><label>Reference No.</label><input name="reference_no" value="{{ old('reference_no',$entry->reference_no) }}"></div><div class="pone-field pone-col-3"><label>Date/Time</label><input name="entry_at" type="datetime-local" value="{{ old('entry_at',optional($entry->entry_at)->format('Y-m-d\TH:i')) }}"></div>
<div class="pone-field pone-col-2"><label>Quantity</label><input name="quantity" type="number" min="0" step="0.001" value="{{ old('quantity',$entry->quantity) }}"></div><div class="pone-field pone-col-2"><label>Amount</label><input name="amount" type="number" min="0" step="0.0001" value="{{ old('amount',$entry->amount) }}"></div><div class="pone-field pone-col-2"><label>Starting Meter</label><input name="starting_meter" type="number" min="0" step="0.001" value="{{ old('starting_meter',$entry->starting_meter) }}"></div><div class="pone-field pone-col-2"><label>Closing Meter</label><input name="closing_meter" type="number" min="0" step="0.001" value="{{ old('closing_meter',$entry->closing_meter) }}"></div><div class="pone-field pone-col-2"><label>Testing Qty</label><input name="testing_quantity" type="number" min="0" step="0.001" value="{{ old('testing_quantity',$entry->testing_quantity) }}"></div><div class="pone-field pone-col-2"><label>Settlement No.</label><input name="settlement_no" value="{{ old('settlement_no',$entry->settlement_no) }}"></div>
<div class="pone-field pone-col-6"><label>Note</label><textarea name="note">{{ old('note',$entry->note) }}</textarea></div><div class="pone-field pone-col-6"><label class="pone-required">Reason for Edit</label><textarea name="edit_reason" required>{{ old('edit_reason') }}</textarea></div>
</div><div class="pone-actions pone-actions-end" style="margin-top:16px"><button class="pone-btn pone-btn-success">Save Changes</button></div></form></div></div>
@endsection
