@extends('pumperdashboardnew::layouts.operator')
@section('title','Day Entries')
@section('pone_content')
@php($assignmentMap=$assignments->keyBy('id'))
<div class="pone-page-head"><div><div class="pone-page-kicker">Operational Journal</div><h1>Day Entries</h1><p>Shift {{ $shift->shift_number }} · notes, incidents, expenses, deposits, meters and testing.</p></div><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.dashboard') }}">Dashboard</a></div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Add Day Entry</h2></div><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.day-entries.store') }}" data-processing-text="Saving day entry…">@csrf<div class="pone-form-grid">
<div class="pone-field pone-col-4"><label class="pone-required">Entry Type</label><select name="entry_type" required>@foreach(['note'=>'Note','incident'=>'Incident','expense'=>'Expense','deposit'=>'Deposit','meter'=>'Meter','testing'=>'Testing','other'=>'Other'] as $value=>$label)<option value="{{ $value }}" @selected(old('entry_type')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="pone-field pone-col-4"><label>Pump Assignment</label><select name="assignment_id" data-search-select><option value="">Not linked to a pump</option>@foreach($assignments as $a)<option value="{{ $a->id }}" @selected((string)old('assignment_id')===(string)$a->id)>{{ $pumps->get($a->pump_id)->pump_name ?? $pumps->get($a->pump_id)->pump_no ?? ('Pump '.$a->pump_id) }}</option>@endforeach</select></div>
<div class="pone-field pone-col-4"><label>Date/Time</label><input name="entry_at" type="datetime-local" value="{{ old('entry_at',now()->format('Y-m-d\TH:i')) }}"></div>
<div class="pone-field pone-col-3"><label>Reference No.</label><input name="reference_no" maxlength="191" value="{{ old('reference_no') }}"></div><div class="pone-field pone-col-3"><label>Settlement No.</label><input name="settlement_no" maxlength="100" value="{{ old('settlement_no',$shift->settlement_no) }}" readonly></div><div class="pone-field pone-col-2"><label>Quantity</label><input name="quantity" type="number" min="0" step="0.001" value="{{ old('quantity',0) }}"></div><div class="pone-field pone-col-2"><label>Amount</label><input name="amount" type="number" min="0" step="0.0001" value="{{ old('amount',0) }}"></div><div class="pone-field pone-col-2"><label>Testing Qty</label><input name="testing_quantity" type="number" min="0" step="0.001" value="{{ old('testing_quantity',0) }}"></div>
<div class="pone-field pone-col-3"><label>Starting Meter</label><input name="starting_meter" type="number" min="0" step="0.001" value="{{ old('starting_meter') }}"></div><div class="pone-field pone-col-3"><label>Closing Meter</label><input name="closing_meter" type="number" min="0" step="0.001" value="{{ old('closing_meter') }}"></div><div class="pone-field pone-col-6"><label>Note</label><textarea name="note">{{ old('note') }}</textarea></div>
</div><div class="pone-actions pone-actions-end" style="margin-top:14px"><button class="pone-btn pone-btn-success">Save Day Entry</button></div></form></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Petro PD-New Settlement Reference</h2></div><div class="pone-panel-body"><div class="pone-alert pone-alert-info">The final settlement reference is written automatically by Petro PD-New after successful finalization. Operators cannot enter it manually.</div>
@if($references->isNotEmpty())<div class="pone-table-wrap"><table class="pone-table pone-table-compact"><thead><tr><th>Settlement No.</th><th>Date</th><th>Note</th></tr></thead><tbody>@foreach($references as $reference)<tr><td><strong>{{ $reference->settlement_no }}</strong></td><td>{{ optional($reference->settlement_date)->format('Y-m-d') }}</td><td>{{ $reference->note ?: '-' }}</td></tr>@endforeach</tbody></table></div>@endif</div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Current Shift Entries</h2><span class="pone-badge pone-badge-open">{{ $entries->count() }} records</span></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table"><thead><tr><th>Date/Time</th><th>Type</th><th>Pump</th><th>Reference</th><th>Settlement</th><th class="pone-text-right">Quantity</th><th class="pone-text-right">Amount</th><th>Note</th><th>Sync</th><th>Action</th></tr></thead><tbody>@forelse($entries as $entry) @php($assignment=$assignmentMap->get($entry->assignment_id))<tr class="{{ $entry->status==='void'?'is-void':'' }}"><td>{{ optional($entry->entry_at)->format('Y-m-d H:i') }}</td><td><span class="pone-badge pone-badge-{{ $entry->entry_type }}">{{ ucfirst($entry->entry_type) }}</span></td><td>{{ $assignment ? ($pumps->get($assignment->pump_id)->pump_name ?? $pumps->get($assignment->pump_id)->pump_no ?? ('Pump '.$assignment->pump_id)) : '-' }}</td><td>{{ $entry->reference_no ?: '-' }}</td><td>{{ $entry->settlement_no ?: '-' }}</td><td class="pone-text-right">{{ number_format((float)$entry->quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$entry->amount,4) }}</td><td class="pone-wrap">{{ $entry->note ?: '-' }}</td><td><span class="pone-badge pone-badge-{{ $entry->integration_status }}">{{ $entry->integration_status }}</span></td><td>@if($entry->status!=='void')<div class="pone-actions"><a class="pone-btn pone-btn-warning pone-btn-sm" href="{{ route('pumper-dashboard-new.operator.day-entries.edit',$entry) }}">Edit</a><form method="post" action="{{ route('pumper-dashboard-new.operator.day-entries.destroy',$entry) }}" data-confirm-message="Void this day entry?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form></div>@endif</td></tr>@empty<tr><td colspan="10" class="pone-empty">No day entries.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
