<?php

return [
    'name' => 'PumperDashboardNew',
    'display_name' => 'Pumper Dashboard-New',
    'route_prefix' => 'pumper-dashboard-new',
    'route_name' => 'pumper-dashboard-new.',
    'table_prefix' => 'pone_',
    'asset_version' => '20260802-current-system-layout-01',
    'auto_install_schema' => true,
    'login' => [
        'maximum_attempts' => 5,
        'block_minutes' => 30,
        'passcode_min_length' => 1,
        'passcode_max_length' => 20,
    ],
    'documents' => [
        'disk' => env('PONE_DOCUMENT_DISK', 'public'),
        'maximum_kilobytes' => 10240,
        'allowed_mimes' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt'],
    ],
    'integration' => [
        'enabled' => true,
        'driver' => 'petropd',
        'source_type' => 'pumper_dashboard_new',
        'sync_during_operation' => true,
        'require_clean_sync_before_close' => true,
        'maximum_retry_attempts' => 10,
    ],
    'defaults' => [
        'shift_prefix' => 'PONE-SH-',
        'payment_prefix' => 'PONE-PAY-',
        'other_sale_prefix' => 'PONE-OS-',
        'unload_prefix' => 'PONE-UL-',
        'settlement_prefix' => 'PONE-SET-',
        'collection_prefix' => 'PONE-COL-',
        'recovery_prefix' => 'PONE-REC-',
        'commission_prefix' => 'PONE-COM-',
        'amount_decimals' => 4,
        'quantity_decimals' => 3,
        'meter_decimals' => 3,
        'allow_operator_open_shift' => false,
        'allow_close_with_open_pumps' => false,
        'allow_close_with_pending_sync' => false,
        'cash_denomination_enabled' => true,
        'multi_card_enabled' => true,
        'cheque_enabled' => true,
        'credit_sale_enabled' => true,
        'require_credit_dual_confirmation' => true,
        'require_collection_before_close' => false,
        'allow_payment_edit' => true,
        'payment_edit_lock_minutes' => 1440,
        'auto_logout_minutes' => 0,
        'receipt_paper_size' => '80mm',
        'default_store_id' => null,
    ],
    'cash_denominations' => [5000, 2000, 1000, 500, 100, 50, 20, 10, 5, 2, 1],
];
