<?php

return [
    ['key' => 'pumper_dashboard_new_module', 'label' => 'Pumper Dashboard-New Module', 'type' => 'module'],
    ['key' => 'pumper_dashboard_new_dashboard', 'label' => 'Dashboard', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_operators', 'label' => 'Pump Operator Profiles', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_shifts', 'label' => 'Shift Monitor', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_assignments', 'label' => 'Pump Assignments', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_collections', 'label' => 'Daily Collections', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_reconciliation', 'label' => 'Shortage / Excess', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_ledger', 'label' => 'Operator Ledger', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_documents', 'label' => 'Documents & Notes', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_login_attempts', 'label' => 'Blocked Login Attempts', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_print_logs', 'label' => 'Print History', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_reports', 'label' => 'Reports', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_report_shifts', 'label' => 'Shift Summary', 'type' => 'tab', 'selectors' => ['#pone-report-shifts-tab', '#pone-report-shifts-panel']],
    ['key' => 'pumper_dashboard_new_report_payments', 'label' => 'Payment Summary', 'type' => 'tab', 'selectors' => ['#pone-report-payments-tab', '#pone-report-payments-panel']],
    ['key' => 'pumper_dashboard_new_report_meters', 'label' => 'Meter Sales', 'type' => 'tab', 'selectors' => ['#pone-report-meters-tab', '#pone-report-meters-panel']],
    ['key' => 'pumper_dashboard_new_report_other_sales', 'label' => 'Other Sales', 'type' => 'tab', 'selectors' => ['#pone-report-other-sales-tab', '#pone-report-other-sales-panel']],
    ['key' => 'pumper_dashboard_new_report_unloads', 'label' => 'Unload Stock', 'type' => 'tab', 'selectors' => ['#pone-report-unloads-tab', '#pone-report-unloads-panel']],
    ['key' => 'pumper_dashboard_new_report_day_entries', 'label' => 'Day Entries', 'type' => 'tab', 'selectors' => ['#pone-report-day-entries-tab', '#pone-report-day-entries-panel']],
    ['key' => 'pumper_dashboard_new_report_collections', 'label' => 'Daily Collections', 'type' => 'tab', 'selectors' => ['#pone-report-collections-tab', '#pone-report-collections-panel']],
    ['key' => 'pumper_dashboard_new_report_ledger', 'label' => 'Operator Ledger', 'type' => 'tab', 'selectors' => ['#pone-report-ledger-tab', '#pone-report-ledger-panel']],
    ['key' => 'pumper_dashboard_new_report_shortages', 'label' => 'Shortage Recoveries', 'type' => 'tab', 'selectors' => ['#pone-report-shortages-tab', '#pone-report-shortages-panel']],
    ['key' => 'pumper_dashboard_new_report_commissions', 'label' => 'Excess Commissions', 'type' => 'tab', 'selectors' => ['#pone-report-commissions-tab', '#pone-report-commissions-panel']],
    ['key' => 'pumper_dashboard_new_report_print_logs', 'label' => 'Print History', 'type' => 'tab', 'selectors' => ['#pone-report-print-logs-tab', '#pone-report-print-logs-panel']],
    ['key' => 'pumper_dashboard_new_report_audit', 'label' => 'Audit Trail', 'type' => 'tab', 'selectors' => ['#pone-report-audit-tab', '#pone-report-audit-panel']],
    ['key' => 'pumper_dashboard_new_integration', 'label' => 'Petro PD-New Pairing', 'type' => 'page'],
    ['key' => 'pumper_dashboard_new_settings', 'label' => 'Settings', 'type' => 'page'],
];
