<?php

namespace Modules\Distribution\Services\Print;

use App\Services\Documents\GlobalPdfService;

/**
 * Backward-compatible Distribution adapter for the application's single PDF
 * engine. Existing callers may continue using loadView()->setPaper()->stream(),
 * while all output is generated by GlobalPdfService / GlobalMpdf.
 */
class DistributionPdfService
{
    /** @var string */
    protected $html = '';

    /** @var array<string,mixed> */
    protected $config = [];

    /** @var array<string,mixed> */
    protected $context = [];

    public function loadView(string $view, array $data = [], string $paper = 'a4', string $orientation = 'portrait')
    {
        $this->html = view($view, $data)->render();
        $this->setPaper($paper, $orientation);
        $location = $data['business_location'] ?? null;
        $loading = $data['loading'] ?? null;
        $this->context = array_filter([
            'business_id' => $data['business_id'] ?? data_get($loading, 'business_id'),
            'business_name' => $data['business_name'] ?? data_get($data, 'business.name'),
            'location_id' => $data['location_id'] ?? data_get($location, 'id') ?? data_get($loading, 'location_id'),
            'business_location' => is_scalar($location) ? $location : data_get($location, 'name'),
            'page_title' => $data['page_title'] ?? 'Distribution Loading Sheet',
            'date_range' => $data['date_range'] ?? data_get($loading, 'loading_date') ?? data_get($loading, 'date'),
        ], static function ($value) {
            return $value !== null && $value !== '';
        });

        return $this;
    }

    public function setPaper(string $paper = 'a4', string $orientation = 'portrait')
    {
        $this->config['format'] = strtoupper($paper);
        $this->config['orientation'] = strtolower($orientation) === 'landscape' ? 'L' : 'P';

        return $this;
    }

    /**
     * Retained only for compatibility with the old DomPDF wrapper. GlobalMpdf
     * owns parser/font/security options centrally, so module options are ignored.
     */
    public function setOptions(array $options = [])
    {
        return $this;
    }

    public function stream(string $filename = 'document.pdf')
    {
        return app(GlobalPdfService::class)->stream($this->html, $filename, $this->config, $this->context);
    }

    public function download(string $filename = 'document.pdf')
    {
        return app(GlobalPdfService::class)->download($this->html, $filename, $this->config, $this->context);
    }

    public function output()
    {
        return app(GlobalPdfService::class)->binary($this->html, $this->config, $this->context);
    }
}
