CREATE TABLE IF NOT EXISTS rn_sale_orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 business_id BIGINT UNSIGNED NOT NULL,
 location_id BIGINT UNSIGNED NULL,
 order_no VARCHAR(191) NOT NULL UNIQUE,
 order_type VARCHAR(50) NOT NULL DEFAULT 'dine_in',
 table_id BIGINT UNSIGNED NULL,
 customer_id BIGINT UNSIGNED NULL,
 waiter_id BIGINT UNSIGNED NULL,
 cashier_id BIGINT UNSIGNED NULL,
 status VARCHAR(50) NOT NULL DEFAULT 'received',
 kitchen_status VARCHAR(50) NOT NULL DEFAULT 'received',
 payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
 sub_total DECIMAL(22,4) NOT NULL DEFAULT 0,
 discount_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
 tax_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
 service_charge_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
 grand_total DECIMAL(22,4) NOT NULL DEFAULT 0,
 note TEXT NULL,
 created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP NULL,
 updated_at TIMESTAMP NULL,
 INDEX rn_sale_orders_business_location_status_idx (business_id, location_id, status)
);
CREATE TABLE IF NOT EXISTS rn_sale_order_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 menu_item_id BIGINT UNSIGNED NULL,
 menu_item_name VARCHAR(191) NOT NULL,
 kitchen_section_id BIGINT UNSIGNED NULL,
 quantity DECIMAL(22,4) NOT NULL,
 unit_price DECIMAL(22,4) NOT NULL DEFAULT 0,
 line_total DECIMAL(22,4) NOT NULL DEFAULT 0,
 status VARCHAR(50) NOT NULL DEFAULT 'received',
 note TEXT NULL,
 created_at TIMESTAMP NULL,
 updated_at TIMESTAMP NULL,
 INDEX rn_sale_order_lines_order_section_status_idx (order_id, kitchen_section_id, status)
);
CREATE TABLE IF NOT EXISTS rn_kitchen_queue (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 business_id BIGINT UNSIGNED NOT NULL,
 location_id BIGINT UNSIGNED NULL,
 order_id BIGINT UNSIGNED NOT NULL UNIQUE,
 queue_no VARCHAR(191) NOT NULL,
 status VARCHAR(50) NOT NULL DEFAULT 'received',
 received_at TIMESTAMP NULL,
 started_at TIMESTAMP NULL,
 ready_at TIMESTAMP NULL,
 served_at TIMESTAMP NULL,
 print_count INT UNSIGNED NOT NULL DEFAULT 0,
 last_printed_at TIMESTAMP NULL,
 created_at TIMESTAMP NULL,
 updated_at TIMESTAMP NULL,
 INDEX rn_kitchen_queue_business_location_status_idx (business_id, location_id, status)
);
