CREATE TABLE IF NOT EXISTS `resnew_kitchen_queues` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `kitchen_section_id` BIGINT UNSIGNED NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `order_item_id` BIGINT UNSIGNED NULL,
  `kot_id` BIGINT UNSIGNED NULL,
  `queue_no` VARCHAR(40) NOT NULL,
  `priority` ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  `status` ENUM('received','preparing','ready','served','cancelled') NOT NULL DEFAULT 'received',
  `received_at` DATETIME NULL,
  `started_at` DATETIME NULL,
  `ready_at` DATETIME NULL,
  `served_at` DATETIME NULL,
  `estimated_minutes` INT NOT NULL DEFAULT 15,
  `actual_minutes` INT NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_kq_business_location_status_idx` (`business_id`,`location_id`,`status`),
  KEY `rn_kq_priority_idx` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `resnew_kitchen_timers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `queue_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `order_item_id` BIGINT UNSIGNED NULL,
  `timer_type` VARCHAR(30) NOT NULL,
  `started_at` DATETIME NULL,
  `paused_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  `total_seconds` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'running',
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_kt_queue_status_idx` (`queue_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `resnew_kitchen_route_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `menu_category_id` BIGINT UNSIGNED NULL,
  `menu_item_id` BIGINT UNSIGNED NULL,
  `kitchen_section_id` BIGINT UNSIGNED NOT NULL,
  `order_type` VARCHAR(30) NULL,
  `priority` INT NOT NULL DEFAULT 10,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_krr_active_idx` (`business_id`,`location_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `resnew_kitchen_performance_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NOT NULL,
  `kitchen_section_id` BIGINT UNSIGNED NULL,
  `queue_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `order_item_id` BIGINT UNSIGNED NULL,
  `staff_id` BIGINT UNSIGNED NULL,
  `metric_date` DATE NOT NULL,
  `target_minutes` INT NOT NULL DEFAULT 0,
  `actual_minutes` INT NULL,
  `delay_minutes` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `remarks` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_kpl_metric_idx` (`business_id`,`location_id`,`metric_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
