CREATE TABLE IF NOT EXISTS restaurant_new_online_channels (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  channel_name VARCHAR(255) NOT NULL,
  channel_code VARCHAR(50) NOT NULL,
  allow_delivery TINYINT(1) NOT NULL DEFAULT 1,
  allow_pickup TINYINT(1) NOT NULL DEFAULT 1,
  allow_dine_in TINYINT(1) NOT NULL DEFAULT 1,
  accept_scheduled_orders TINYINT(1) NOT NULL DEFAULT 1,
  min_preparation_minutes INT NOT NULL DEFAULT 20,
  minimum_order_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  settings JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_online_channels_business_idx (business_id),
  INDEX rn_online_channels_location_idx (location_id),
  INDEX rn_online_channels_code_idx (channel_code)
);
CREATE TABLE IF NOT EXISTS restaurant_new_online_customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  mobile VARCHAR(50) NOT NULL,
  email VARCHAR(255) NULL,
  default_address TEXT NULL,
  city VARCHAR(255) NULL,
  landmark VARCHAR(255) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_online_customers_business_idx (business_id),
  INDEX rn_online_customers_mobile_idx (mobile)
);
CREATE TABLE IF NOT EXISTS restaurant_new_online_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  online_channel_id BIGINT UNSIGNED NULL,
  online_customer_id BIGINT UNSIGNED NULL,
  online_order_no VARCHAR(80) NOT NULL,
  order_type VARCHAR(30) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'received',
  payment_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  scheduled_at TIMESTAMP NULL,
  accepted_at TIMESTAMP NULL,
  ready_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  subtotal DECIMAL(22,4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  delivery_charge DECIMAL(22,4) NOT NULL DEFAULT 0,
  total_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  customer_note TEXT NULL,
  delivery_address TEXT NULL,
  meta JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_online_orders_business_idx (business_id),
  INDEX rn_online_orders_location_idx (location_id),
  INDEX rn_online_orders_no_idx (online_order_no),
  INDEX rn_online_orders_status_idx (status)
);
CREATE TABLE IF NOT EXISTS restaurant_new_online_order_lines (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  online_order_id BIGINT UNSIGNED NOT NULL,
  menu_item_id BIGINT UNSIGNED NULL,
  item_name VARCHAR(255) NOT NULL,
  quantity DECIMAL(22,4) NOT NULL DEFAULT 0,
  unit_price DECIMAL(22,4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(22,4) NOT NULL DEFAULT 0,
  line_total DECIMAL(22,4) NOT NULL DEFAULT 0,
  item_note TEXT NULL,
  modifiers JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_online_lines_business_idx (business_id),
  INDEX rn_online_lines_order_idx (online_order_id)
);
CREATE TABLE IF NOT EXISTS restaurant_new_online_order_status_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  online_order_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(40) NULL,
  to_status VARCHAR(40) NOT NULL,
  remarks TEXT NULL,
  changed_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_online_logs_business_idx (business_id),
  INDEX rn_online_logs_order_idx (online_order_id),
  INDEX rn_online_logs_status_idx (to_status)
);
