CREATE TABLE IF NOT EXISTS restaurant_new_kds_screens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  screen_name VARCHAR(120) NOT NULL,
  screen_code VARCHAR(80) NOT NULL,
  kitchen_section VARCHAR(80) NULL,
  visible_order_types JSON NULL,
  status_filter JSON NULL,
  sound_enabled TINYINT(1) NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_kds_screen_business_idx (business_id),
  INDEX rn_kds_screen_location_idx (location_id),
  INDEX rn_kds_screen_code_idx (screen_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restaurant_new_kds_queue_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  order_item_id BIGINT UNSIGNED NULL,
  kot_id BIGINT UNSIGNED NULL,
  order_no VARCHAR(80) NULL,
  item_name VARCHAR(191) NOT NULL,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  order_type VARCHAR(40) NOT NULL DEFAULT 'dine_in',
  kitchen_section VARCHAR(80) NULL,
  priority VARCHAR(40) NOT NULL DEFAULT 'normal',
  current_status VARCHAR(50) NOT NULL DEFAULT 'received',
  expected_prep_minutes INT NOT NULL DEFAULT 0,
  received_at TIMESTAMP NULL,
  accepted_at TIMESTAMP NULL,
  started_at TIMESTAMP NULL,
  ready_at TIMESTAMP NULL,
  collected_at TIMESTAMP NULL,
  served_at TIMESTAMP NULL,
  assigned_chef_id BIGINT UNSIGNED NULL,
  kitchen_note TEXT NULL,
  meta JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_kds_queue_business_idx (business_id),
  INDEX rn_kds_queue_location_idx (location_id),
  INDEX rn_kds_queue_order_idx (order_id),
  INDEX rn_kds_queue_status_idx (current_status),
  INDEX rn_kds_queue_section_idx (kitchen_section),
  INDEX rn_kds_queue_priority_idx (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restaurant_new_kds_status_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  queue_item_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(50) NULL,
  to_status VARCHAR(50) NOT NULL,
  remarks TEXT NULL,
  changed_by BIGINT UNSIGNED NULL,
  changed_at TIMESTAMP NULL,
  meta JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_kds_log_business_idx (business_id),
  INDEX rn_kds_log_queue_idx (queue_item_id),
  INDEX rn_kds_log_order_idx (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restaurant_new_kds_notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  queue_item_id BIGINT UNSIGNED NULL,
  notification_type VARCHAR(80) NOT NULL,
  title VARCHAR(191) NOT NULL,
  message TEXT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  target_user_id BIGINT UNSIGNED NULL,
  payload JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX rn_kds_notification_business_idx (business_id),
  INDEX rn_kds_notification_type_idx (notification_type),
  INDEX rn_kds_notification_read_idx (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
