CREATE TABLE IF NOT EXISTS `rn_gift_vouchers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `voucher_no` VARCHAR(40) NOT NULL,
  `voucher_type` VARCHAR(30) NOT NULL DEFAULT 'gift_card',
  `customer_name` VARCHAR(255) NULL,
  `customer_mobile` VARCHAR(30) NULL,
  `customer_email` VARCHAR(255) NULL,
  `issue_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `balance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `issued_on` DATE NULL,
  `expires_on` DATE NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rn_gift_vouchers_business_voucher_unique` (`business_id`,`voucher_no`),
  KEY `rn_gift_vouchers_business_id_index` (`business_id`),
  KEY `rn_gift_vouchers_location_index` (`business_location_id`),
  KEY `rn_gift_vouchers_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `rn_gift_voucher_transactions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `gift_voucher_id` BIGINT UNSIGNED NOT NULL,
  `transaction_type` VARCHAR(30) NOT NULL,
  `reference_type` VARCHAR(60) NULL,
  `reference_id` BIGINT UNSIGNED NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `balance_after` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_gift_voucher_txn_business_index` (`business_id`),
  KEY `rn_gift_voucher_txn_location_index` (`business_location_id`),
  KEY `rn_gift_voucher_txn_voucher_index` (`gift_voucher_id`),
  KEY `rn_gift_voucher_txn_ref_index` (`reference_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
