-- RestaurantNew Stage 044 Equipment / Assets - corrected CREATE SQL
-- Generated from 2026_07_08_044000_create_restaurant_new_equipment_asset_tables.php

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(191) NOT NULL,
  `code` VARCHAR(80) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_eq_cat_business_idx` (`business_id`),
  KEY `rn_eq_cat_location_idx` (`location_id`),
  KEY `rn_eq_cat_code_idx` (`code`),
  KEY `rn_eq_cat_active_idx` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `asset_code` VARCHAR(80) NOT NULL,
  `asset_name` VARCHAR(191) NOT NULL,
  `brand` VARCHAR(191) NULL,
  `model` VARCHAR(191) NULL,
  `serial_no` VARCHAR(191) NULL,
  `purchase_date` DATE NULL,
  `purchase_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `warranty_expiry` DATE NULL,
  `supplier_id` BIGINT UNSIGNED NULL,
  `kitchen_section` VARCHAR(191) NULL,
  `assigned_employee_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'working',
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rn_asset_code_unique` (`business_id`,`asset_code`),
  KEY `rn_eq_asset_business_idx` (`business_id`),
  KEY `rn_eq_asset_location_idx` (`location_id`),
  KEY `rn_eq_asset_category_idx` (`category_id`),
  KEY `rn_eq_asset_code_idx` (`asset_code`),
  KEY `rn_eq_asset_serial_idx` (`serial_no`),
  KEY `rn_eq_asset_warranty_idx` (`warranty_expiry`),
  KEY `rn_eq_asset_supplier_idx` (`supplier_id`),
  KEY `rn_eq_asset_kitchen_idx` (`kitchen_section`),
  KEY `rn_eq_asset_employee_idx` (`assigned_employee_id`),
  KEY `rn_eq_asset_status_idx` (`status`),
  KEY `rn_eq_asset_created_by_idx` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_maintenance_schedules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL,
  `schedule_type` VARCHAR(50) NOT NULL DEFAULT 'preventive',
  `frequency` VARCHAR(50) NOT NULL DEFAULT 'monthly',
  `next_due_date` DATE NULL,
  `running_hours_due` INT NULL,
  `usage_count_due` INT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `checklist` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_eq_ms_business_idx` (`business_id`),
  KEY `rn_eq_ms_location_idx` (`location_id`),
  KEY `rn_eq_ms_asset_idx` (`asset_id`),
  KEY `rn_eq_ms_type_idx` (`schedule_type`),
  KEY `rn_eq_ms_frequency_idx` (`frequency`),
  KEY `rn_eq_ms_due_idx` (`next_due_date`),
  KEY `rn_eq_ms_active_idx` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_work_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `work_order_no` VARCHAR(80) NOT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL,
  `work_type` VARCHAR(50) NOT NULL DEFAULT 'repair',
  `priority` VARCHAR(30) NOT NULL DEFAULT 'normal',
  `status` VARCHAR(50) NOT NULL DEFAULT 'open',
  `assigned_technician_id` BIGINT UNSIGNED NULL,
  `requested_at` DATETIME NULL,
  `expected_completion_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `labour_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `parts_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `downtime_hours` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `problem_description` TEXT NULL,
  `resolution_note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_eq_wo_business_idx` (`business_id`),
  KEY `rn_eq_wo_location_idx` (`location_id`),
  KEY `rn_eq_wo_no_idx` (`work_order_no`),
  KEY `rn_eq_wo_asset_idx` (`asset_id`),
  KEY `rn_eq_wo_type_idx` (`work_type`),
  KEY `rn_eq_wo_priority_idx` (`priority`),
  KEY `rn_eq_wo_status_idx` (`status`),
  KEY `rn_eq_wo_tech_idx` (`assigned_technician_id`),
  KEY `rn_eq_wo_requested_idx` (`requested_at`),
  KEY `rn_eq_wo_completed_idx` (`completed_at`),
  KEY `rn_eq_wo_created_by_idx` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_spare_parts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `part_code` VARCHAR(80) NOT NULL,
  `part_name` VARCHAR(191) NOT NULL,
  `unit` VARCHAR(30) NOT NULL DEFAULT 'nos',
  `current_stock` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `minimum_stock` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `reorder_level` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `last_purchase_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rn_part_code_unique` (`business_id`,`part_code`),
  KEY `rn_eq_sp_business_idx` (`business_id`),
  KEY `rn_eq_sp_location_idx` (`location_id`),
  KEY `rn_eq_sp_code_idx` (`part_code`),
  KEY `rn_eq_sp_active_idx` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_work_order_parts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `work_order_id` BIGINT UNSIGNED NOT NULL,
  `spare_part_id` BIGINT UNSIGNED NOT NULL,
  `quantity` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `total_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_eq_wop_business_idx` (`business_id`),
  KEY `rn_eq_wop_work_order_idx` (`work_order_id`),
  KEY `rn_eq_wop_spare_idx` (`spare_part_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_equipment_alerts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `asset_id` BIGINT UNSIGNED NULL,
  `spare_part_id` BIGINT UNSIGNED NULL,
  `alert_type` VARCHAR(60) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `message` TEXT NULL,
  `severity` VARCHAR(30) NOT NULL DEFAULT 'info',
  `status` VARCHAR(30) NOT NULL DEFAULT 'open',
  `resolved_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `rn_eq_alert_business_idx` (`business_id`),
  KEY `rn_eq_alert_location_idx` (`location_id`),
  KEY `rn_eq_alert_asset_idx` (`asset_id`),
  KEY `rn_eq_alert_spare_idx` (`spare_part_id`),
  KEY `rn_eq_alert_type_idx` (`alert_type`),
  KEY `rn_eq_alert_severity_idx` (`severity`),
  KEY `rn_eq_alert_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
