CREATE TABLE IF NOT EXISTS restnew_haccp_temperature_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  business_location_id BIGINT UNSIGNED NULL,
  asset_name VARCHAR(191) NOT NULL,
  check_type VARCHAR(100) NOT NULL,
  temperature DECIMAL(10,3) NOT NULL,
  min_temperature DECIMAL(10,3) NULL,
  max_temperature DECIMAL(10,3) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ok',
  checked_at DATETIME NOT NULL,
  remarks TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX restnew_haccp_temp_business_idx (business_id),
  INDEX restnew_haccp_temp_location_idx (business_location_id),
  INDEX restnew_haccp_temp_status_idx (status),
  INDEX restnew_haccp_temp_checked_idx (checked_at)
);

CREATE TABLE IF NOT EXISTS restnew_haccp_corrective_actions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  business_location_id BIGINT UNSIGNED NULL,
  source_type VARCHAR(191) NULL,
  source_id BIGINT UNSIGNED NULL,
  title VARCHAR(191) NOT NULL,
  description TEXT NULL,
  priority VARCHAR(50) NOT NULL DEFAULT 'normal',
  status VARCHAR(50) NOT NULL DEFAULT 'open',
  assigned_to BIGINT UNSIGNED NULL,
  due_at DATETIME NULL,
  completed_at DATETIME NULL,
  verified_by BIGINT UNSIGNED NULL,
  verified_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  INDEX restnew_haccp_ca_business_idx (business_id),
  INDEX restnew_haccp_ca_location_idx (business_location_id),
  INDEX restnew_haccp_ca_status_idx (status),
  INDEX restnew_haccp_ca_due_idx (due_at)
);
