CREATE TABLE IF NOT EXISTS `restaurant_new_kitchen_tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `ticket_no` VARCHAR(50) NOT NULL,
  `kitchen_section_id` BIGINT UNSIGNED NULL,
  `ticket_type` VARCHAR(30) NOT NULL DEFAULT 'kot',
  `status` VARCHAR(30) NOT NULL DEFAULT 'new',
  `printed_at` TIMESTAMP NULL,
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `cancelled_at` TIMESTAMP NULL,
  `cancel_reason` TEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `restaurant_new_kot_unique` (`business_id`,`business_location_id`,`ticket_no`),
  KEY `restaurant_new_kot_business_idx` (`business_id`),
  KEY `restaurant_new_kot_location_idx` (`business_location_id`),
  KEY `restaurant_new_kot_order_idx` (`order_id`),
  KEY `restaurant_new_kot_section_idx` (`kitchen_section_id`),
  KEY `restaurant_new_kot_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_kitchen_ticket_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `kitchen_ticket_id` BIGINT UNSIGNED NOT NULL,
  `order_line_id` BIGINT UNSIGNED NULL,
  `menu_item_id` BIGINT UNSIGNED NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `modifiers_text` TEXT NULL,
  `special_instruction` TEXT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'new',
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `cancelled_at` TIMESTAMP NULL,
  `cancel_reason` TEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_kotl_business_idx` (`business_id`),
  KEY `restaurant_new_kotl_location_idx` (`business_location_id`),
  KEY `restaurant_new_kotl_ticket_idx` (`kitchen_ticket_id`),
  KEY `restaurant_new_kotl_order_line_idx` (`order_line_id`),
  KEY `restaurant_new_kotl_menu_item_idx` (`menu_item_id`),
  KEY `restaurant_new_kotl_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
