CREATE TABLE IF NOT EXISTS `restaurant_new_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NULL,
  `dining_area_id` BIGINT UNSIGNED NULL,
  `restaurant_table_id` BIGINT UNSIGNED NULL,
  `customer_id` INT UNSIGNED NULL,
  `order_no` VARCHAR(50) NOT NULL,
  `order_type` ENUM('dine_in','takeaway','delivery') NOT NULL DEFAULT 'dine_in',
  `order_status` VARCHAR(50) NOT NULL DEFAULT 'open',
  `kot_status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `payment_status` VARCHAR(50) NOT NULL DEFAULT 'due',
  `guest_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `waiter_id` INT UNSIGNED NULL,
  `cashier_id` INT UNSIGNED NULL,
  `subtotal` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_type` VARCHAR(20) NULL,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `service_charge_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `delivery_charge` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `round_off` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `grand_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `paid_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `balance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `order_note` TEXT NULL,
  `opened_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `cancelled_at` TIMESTAMP NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `restaurant_new_orders_business_order_unique` (`business_id`, `order_no`),
  KEY `restaurant_new_orders_lookup_idx` (`business_id`, `location_id`, `order_status`, `payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_order_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `menu_item_id` BIGINT UNSIGNED NULL,
  `variant_id` BIGINT UNSIGNED NULL,
  `kitchen_section_id` BIGINT UNSIGNED NULL,
  `item_name` VARCHAR(191) NOT NULL,
  `variant_name` VARCHAR(191) NULL,
  `qty` DECIMAL(22,4) NOT NULL DEFAULT 1.0000,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `line_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `kot_status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `is_printed_to_kitchen` TINYINT(1) NOT NULL DEFAULT 0,
  `line_note` TEXT NULL,
  `cancel_reason` TEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_order_lines_order_idx` (`order_id`),
  KEY `restaurant_new_order_lines_kot_idx` (`business_id`, `location_id`, `kot_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_order_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `payment_account_id` INT UNSIGNED NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `reference_no` VARCHAR(191) NULL,
  `paid_on` TIMESTAMP NULL,
  `payment_note` TEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_order_payments_order_idx` (`order_id`),
  KEY `restaurant_new_order_payments_method_idx` (`business_id`, `location_id`, `payment_method`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
