CREATE TABLE IF NOT EXISTS `restaurant_new_bills` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `restaurant_new_order_id` BIGINT UNSIGNED NULL,
  `bill_no` VARCHAR(191) NOT NULL,
  `bill_date` DATETIME NOT NULL,
  `customer_id` BIGINT UNSIGNED NULL,
  `cashier_id` BIGINT UNSIGNED NULL,
  `waiter_id` BIGINT UNSIGNED NULL,
  `subtotal` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_type` VARCHAR(20) NOT NULL DEFAULT 'fixed',
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `service_charge_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `round_off_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `grand_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `paid_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `balance_due` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `change_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `payment_status` VARCHAR(20) NOT NULL DEFAULT 'due',
  `bill_status` VARCHAR(20) NOT NULL DEFAULT 'open',
  `notes` TEXT NULL,
  `void_reason` TEXT NULL,
  `voided_by` BIGINT UNSIGNED NULL,
  `voided_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `restaurant_new_bills_unique_no` (`business_id`,`location_id`,`bill_no`),
  KEY `restaurant_new_bills_business_id_index` (`business_id`),
  KEY `restaurant_new_bills_location_id_index` (`location_id`),
  KEY `restaurant_new_bills_order_id_index` (`restaurant_new_order_id`),
  KEY `restaurant_new_bills_bill_date_index` (`bill_date`),
  KEY `restaurant_new_bills_payment_status_index` (`payment_status`),
  KEY `restaurant_new_bills_bill_status_index` (`bill_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_bill_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `restaurant_new_bill_id` BIGINT UNSIGNED NOT NULL,
  `restaurant_new_order_line_id` BIGINT UNSIGNED NULL,
  `menu_item_id` BIGINT UNSIGNED NULL,
  `item_name` VARCHAR(191) NOT NULL,
  `variant_name` VARCHAR(191) NULL,
  `quantity` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `service_charge_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `line_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `line_status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_bill_lines_business_id_index` (`business_id`),
  KEY `restaurant_new_bill_lines_bill_id_index` (`restaurant_new_bill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_bill_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `restaurant_new_bill_id` BIGINT UNSIGNED NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `account_id` BIGINT UNSIGNED NULL,
  `reference_no` VARCHAR(191) NULL,
  `card_type` VARCHAR(191) NULL,
  `card_last_four` VARCHAR(4) NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `payment_status` VARCHAR(20) NOT NULL DEFAULT 'posted',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `voided_by` BIGINT UNSIGNED NULL,
  `voided_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_bill_payments_bill_id_index` (`restaurant_new_bill_id`),
  KEY `restaurant_new_bill_payments_method_index` (`payment_method`),
  KEY `restaurant_new_bill_payments_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `restaurant_new_refunds` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `restaurant_new_bill_id` BIGINT UNSIGNED NOT NULL,
  `refund_no` VARCHAR(191) NOT NULL,
  `refund_date` DATETIME NOT NULL,
  `refund_method` VARCHAR(50) NOT NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `reason` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'posted',
  `approved_by` BIGINT UNSIGNED NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_new_refunds_bill_id_index` (`restaurant_new_bill_id`),
  KEY `restaurant_new_refunds_date_index` (`refund_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
