@php
$isEdit=isset($unload);
$oldLines=old('lines',$isEdit?$unload->lines->map(fn($line)=>['product_id'=>$line->product_id,'tank_id'=>$line->tank_id,'quantity'=>$line->quantity,'unit_cost'=>$line->unit_cost,'dip_reading'=>$line->dip_reading,'current_stock'=>$line->current_stock])->all():[['product_id'=>'','tank_id'=>'','quantity'=>0,'unit_cost'=>0,'dip_reading'=>'','current_stock'=>'']]);
@endphp
<div class="pone-panel"><div class="pone-panel-head"><div><h2>Unload Information</h2><div class="pone-panel-subtitle">Record supplier, receiving store, tank and stock readings.</div></div></div><div class="pone-panel-body"><div class="pone-form-grid">
<div class="pone-field pone-col-3"><label>Store</label><select name="store_id" data-search-select><option value="">Please Select</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected((string)old('store_id',$unload->store_id ?? '')===(string)$store->id)>{{ $store->name }}</option>@endforeach</select></div>
<div class="pone-field pone-col-3"><label>Supplier</label><select name="supplier_id" data-search-select><option value="">Please Select</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string)old('supplier_id',$unload->supplier_id ?? '')===(string)$supplier->id)>{{ $supplier->name }} @if($supplier->contact_id) ({{ $supplier->contact_id }}) @endif</option>@endforeach</select></div>
<div class="pone-field pone-col-2"><label>Bill No.</label><input name="bill_number" maxlength="191" value="{{ old('bill_number',$unload->bill_number ?? '') }}"></div>
<div class="pone-field pone-col-2"><label>Supplier Reference</label><input name="supplier_reference" maxlength="191" value="{{ old('supplier_reference',$unload->supplier_reference ?? '') }}"></div>
<div class="pone-field pone-col-2"><label>Date/Time</label><input name="unloaded_at" type="datetime-local" value="{{ old('unloaded_at',isset($unload)&&$unload->unloaded_at?$unload->unloaded_at->format('Y-m-d\TH:i'):now()->format('Y-m-d\TH:i')) }}"></div>
<div class="pone-field pone-col-12"><label>Note</label><textarea name="note">{{ old('note',$unload->note ?? '') }}</textarea></div>
@if($isEdit)<div class="pone-field pone-col-12"><label class="pone-required">Reason for Edit</label><textarea name="edit_reason" required>{{ old('edit_reason') }}</textarea></div>@endif
</div></div></div>
<div class="pone-panel" data-line-table><div class="pone-panel-head"><div><h2>Unload Lines</h2><div class="pone-panel-subtitle">Quantity, unit cost, dip reading and stock snapshot are retained per line.</div></div><button class="pone-btn pone-btn-primary pone-btn-sm" type="button" data-add-line data-target="#pone-unload-lines" data-template="#pone-unload-template">+ Add Line</button></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-line-table"><thead><tr><th>Product</th><th>Tank</th><th>Quantity</th><th>Unit Cost</th><th>Dip Reading</th><th>Current Stock</th><th class="pone-text-right">Amount</th><th></th></tr></thead><tbody id="pone-unload-lines" data-next-index="{{ count($oldLines) }}">@foreach($oldLines as $i=>$line)<tr data-line-row><td><select name="lines[{{ $i }}][product_id]" data-product-select data-search-select required><option value="">Select Product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string)($line['product_id']??'')===(string)$product->id)>{{ $product->name }} @if($product->sku) ({{ $product->sku }}) @endif</option>@endforeach</select></td><td><select name="lines[{{ $i }}][tank_id]" data-search-select><option value="">Select Tank</option>@foreach($tanks as $tank)<option value="{{ $tank->id }}" @selected((string)($line['tank_id']??'')===(string)$tank->id)>{{ $tank->fuel_tank_number ?? $tank->name ?? ('Tank '.$tank->id) }}</option>@endforeach</select></td><td><input name="lines[{{ $i }}][quantity]" data-line-qty type="number" step="0.001" min="0.001" value="{{ $line['quantity']??0 }}" required></td><td><input name="lines[{{ $i }}][unit_cost]" data-line-price type="number" step="0.0001" min="0" value="{{ $line['unit_cost']??0 }}"></td><td><input name="lines[{{ $i }}][dip_reading]" type="number" step="0.001" min="0" value="{{ $line['dip_reading']??'' }}"></td><td><input name="lines[{{ $i }}][current_stock]" type="number" step="0.001" min="0" value="{{ $line['current_stock']??'' }}"></td><td class="pone-text-right pone-line-total" data-line-total>0.0000</td><td><button class="pone-btn pone-btn-danger pone-btn-sm" type="button" data-remove-line>×</button></td></tr>@endforeach</tbody><tfoot><tr><th colspan="6" class="pone-text-right">Total</th><th class="pone-text-right" data-grand-total>0.0000</th><th></th></tr></tfoot></table></div></div></div>
<template id="pone-unload-template"><tr data-line-row><td><select name="lines[__INDEX__][product_id]" data-product-select required><option value="">Select Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} @if($product->sku) ({{ $product->sku }}) @endif</option>@endforeach</select></td><td><select name="lines[__INDEX__][tank_id]"><option value="">Select Tank</option>@foreach($tanks as $tank)<option value="{{ $tank->id }}">{{ $tank->fuel_tank_number ?? $tank->name ?? ('Tank '.$tank->id) }}</option>@endforeach</select></td><td><input name="lines[__INDEX__][quantity]" data-line-qty type="number" step="0.001" min="0.001" value="0" required></td><td><input name="lines[__INDEX__][unit_cost]" data-line-price type="number" step="0.0001" min="0" value="0"></td><td><input name="lines[__INDEX__][dip_reading]" type="number" step="0.001" min="0"></td><td><input name="lines[__INDEX__][current_stock]" type="number" step="0.001" min="0"></td><td class="pone-text-right pone-line-total" data-line-total>0.0000</td><td><button class="pone-btn pone-btn-danger pone-btn-sm" type="button" data-remove-line>×</button></td></tr></template>
<div class="pone-actions pone-actions-end"><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.unload-stock.index') }}">Cancel</a><button class="pone-btn pone-btn-success" type="submit">{{ $isEdit?'Save Changes':'Save Unload Stock' }}</button></div>
