@extends('ezylaw::layouts.module')
@section('ezylaw_title','EzyLaw Settings')
@section('ezylaw_content')
<div class="row"><div class="col-md-7"><div class="box box-primary"><div class="box-header"><h3 class="box-title">Numbering & Finance Mapping</h3></div><form method="post" action="{{ route('ezylaw.settings.update') }}"><div class="box-body">@csrf @method('PUT')<div class="law-form-grid">
@foreach([
'client_prefix'=>'Client Prefix','client_next'=>'Next Client No','matter_prefix'=>'Matter Prefix','matter_next'=>'Next Matter No','invoice_prefix'=>'Invoice Prefix','invoice_next'=>'Next Invoice No','retainer_prefix'=>'Retainer Prefix','retainer_next'=>'Next Retainer No','conflict_prefix'=>'Conflict Check Prefix','conflict_next'=>'Next Conflict Check No','estimate_prefix'=>'Estimate Prefix','estimate_next'=>'Next Estimate No','advance_prefix'=>'Client Advance Prefix','advance_next'=>'Next Advance No','settlement_prefix'=>'Settlement Prefix','settlement_next'=>'Next Settlement No','default_hourly_rate'=>'Default Hourly Rate','finance_receivable_account_id'=>'Finance A/R Account ID','finance_fee_income_account_id'=>'Finance Fee Income Account ID','finance_cash_account_id'=>'Finance Cash/Bank Account ID','finance_expense_account_id'=>'Finance Expense Account ID','finance_trust_cash_account_id'=>'Finance Trust Cash/Bank Account ID','finance_client_trust_liability_account_id'=>'Finance Client Trust Liability Account ID','finance_client_advance_liability_account_id'=>'Finance Client Advance Liability Account ID','finance_expense_advance_account_id'=>'Finance Expense Advance Asset Account ID'] as $k=>$label)
<label>{{ $label }}<input class="form-control" name="setting_{{ $k }}" value="{{ $settings[$k] }}"></label>
@endforeach
</div><p class="help-block">Finance IDs are optional. EzyLaw remains operational without Finance; unsynchronized entries stay within EzyLaw / its integration queue.</p></div><div class="box-footer"><button class="btn btn-primary">Save Settings</button></div></form></div></div>
<div class="col-md-5"><div class="box"><div class="box-header"><h3 class="box-title">Practice Areas</h3></div><form method="post" action="{{ route('ezylaw.settings.areas.store') }}"><div class="box-body">@csrf<input class="form-control" name="name" placeholder="Practice area name" required><br><input class="form-control" name="code" placeholder="Code"></div><div class="box-footer"><button class="btn btn-success">Add</button></div></form><div class="box-body"><ul>@foreach($areas as $a)<li>{{ $a->code }} - {{ $a->name }}</li>@endforeach</ul></div></div><div class="box"><div class="box-header"><h3 class="box-title">Courts</h3></div><form method="post" action="{{ route('ezylaw.settings.courts.store') }}"><div class="box-body">@csrf<input class="form-control" name="name" placeholder="Court name" required><br><input class="form-control" name="court_type" placeholder="Court type"></div><div class="box-footer"><button class="btn btn-success">Add</button></div></form><div class="box-body"><ul>@foreach($courts as $c)<li>{{ $c->name }} - {{ $c->court_type }}</li>@endforeach</ul></div></div></div></div>
@endsection
