<?php

return [
    ['key' => 'restaurant_new_module', 'label' => 'Restaurant-New Module', 'type' => 'module'],
    ['key' => 'restaurant_new_dashboard', 'label' => 'Dashboard', 'type' => 'page'],
    ['key' => 'restaurant_new_manager', 'label' => 'Control Centre', 'type' => 'page'],
    ['key' => 'restaurant_new_waiter', 'label' => 'Waiter Screen', 'type' => 'page'],
    ['key' => 'restaurant_new_cashier', 'label' => 'Cashier Screen', 'type' => 'page'],
    ['key' => 'restaurant_new_kitchen', 'label' => 'Kitchen Display', 'type' => 'page'],
    ['key' => 'restaurant_new_takeaway', 'label' => 'Takeaway Operations', 'type' => 'page'],
    ['key' => 'restaurant_new_collection', 'label' => 'Collection Centre', 'type' => 'page'],
    ['key' => 'restaurant_new_reservations', 'label' => 'Reservations', 'type' => 'page'],
    ['key' => 'restaurant_new_delivery', 'label' => 'Delivery Operations', 'type' => 'page'],
    ['key' => 'restaurant_new_orders', 'label' => 'Orders', 'type' => 'page'],
    ['key' => 'restaurant_new_shifts', 'label' => 'Shifts and Cash Drawer', 'type' => 'page'],
    ['key' => 'restaurant_new_menu', 'label' => 'Menu Setup', 'type' => 'page'],
    ['key' => 'restaurant_new_modifiers', 'label' => 'Menu Modifiers', 'type' => 'page'],
    ['key' => 'restaurant_new_discounts', 'label' => 'Discount Rules', 'type' => 'page'],
    ['key' => 'restaurant_new_setup', 'label' => 'Floor, Tables, Stations and Printers', 'type' => 'page'],
    ['key' => 'restaurant_new_recipes', 'label' => 'Ingredients and Recipes', 'type' => 'page'],
    ['key' => 'restaurant_new_stock', 'label' => 'Ingredient Stock', 'type' => 'page'],
    ['key' => 'restaurant_new_procurement', 'label' => 'Suppliers and Goods Receipts', 'type' => 'page'],
    ['key' => 'restaurant_new_stock_transfers', 'label' => 'Stock Transfers', 'type' => 'page'],
    ['key' => 'restaurant_new_stocktakes', 'label' => 'Stocktakes', 'type' => 'page'],
    ['key' => 'restaurant_new_wastage', 'label' => 'Wastage', 'type' => 'page'],
    ['key' => 'restaurant_new_reports', 'label' => 'Reports', 'type' => 'page'],
    ['key' => 'restaurant_new_report_sales', 'label' => 'Sales Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_item_sales', 'label' => 'Item Sales Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_kitchen', 'label' => 'Kitchen Performance Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_cashier', 'label' => 'Cashier Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_takeaway', 'label' => 'Takeaway Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_hourly', 'label' => 'Hourly Sales Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_waiter', 'label' => 'Waiter Performance Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_discounts', 'label' => 'Discount Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_voids', 'label' => 'Voids and Adjustments Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_stock_usage', 'label' => 'Stock Usage Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_purchases', 'label' => 'Purchases Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_wastage', 'label' => 'Wastage Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_report_profitability', 'label' => 'Profitability Report', 'type' => 'tab'],
    ['key' => 'restaurant_new_settings', 'label' => 'Settings', 'type' => 'page'],
    ['key' => 'restaurant_new_screen_assignments', 'label' => 'User Screen Assignments', 'type' => 'tab'],
];
