@extends('layouts.app')
@section('title', 'Hotel Sustainability & Waste Management')
@section('content')
<section class="content-header hm-page-header"><h1><i class="fa fa-leaf"></i> Sustainability & Waste Management <small>Green goals, waste logs and saving initiatives</small></h1></section>
<section class="content hm-pos-scope">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please check:</strong> {{ $errors->first() }}</div>@endif
<div class="row hm-kpi-row">
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Active Goals</div><div class="hm-kpi-value">{{ $sustainability['active_goals'] }}</div><div class="hm-kpi-sub">Targets being monitored</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Open Initiatives</div><div class="hm-kpi-value">{{ $sustainability['open_initiatives'] }}</div><div class="hm-kpi-sub">Planned / in progress</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Monthly Waste Qty</div><div class="hm-kpi-value">{{ number_format($sustainability['monthly_waste_qty'], 3) }}</div><div class="hm-kpi-sub">Current month</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Monthly Waste Cost</div><div class="hm-kpi-value">{{ number_format($sustainability['monthly_waste_cost'], 2) }}</div><div class="hm-kpi-sub">Disposal / handling</div></div></div>
</div>
<div class="row">
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Sustainability Goal</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.sustainability.goal') }}">@csrf
  <div class="form-group"><label>Goal Name</label><input name="goal_name" class="form-control" required></div>
  <div class="form-group"><label>Category</label><select name="category" class="form-control"><option value="energy">Energy</option><option value="water">Water</option><option value="waste">Waste</option><option value="carbon">Carbon</option><option value="community">Community</option></select></div>
  <div class="form-group"><label>Target / Unit</label><div class="row"><div class="col-xs-7"><input type="number" step="0.001" name="target_value" class="form-control"></div><div class="col-xs-5"><input name="unit" class="form-control" placeholder="kWh / L / kg"></div></div></div>
  <div class="form-group"><label>Start / End</label><div class="row"><div class="col-xs-6"><input type="date" name="start_date" class="form-control"></div><div class="col-xs-6"><input type="date" name="end_date" class="form-control"></div></div></div>
  <div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="active">Active</option><option value="in_progress">In Progress</option><option value="achieved">Achieved</option><option value="paused">Paused</option></select></div>
  <div class="text-right"><button class="btn hm-btn-add"><i class="fa fa-save"></i> Save Goal</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Waste Log</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.sustainability.waste-log') }}">@csrf
  <div class="form-group"><label>Date</label><input type="date" name="log_date" class="form-control"></div>
  <div class="form-group"><label>Department</label><input name="department" class="form-control" placeholder="Kitchen / Housekeeping / Garden"></div>
  <div class="form-group"><label>Waste Type</label><select name="waste_type" class="form-control" required><option value="food">Food Waste</option><option value="plastic">Plastic</option><option value="paper">Paper</option><option value="glass">Glass</option><option value="linen">Linen</option><option value="other">Other</option></select></div>
  <div class="form-group"><label>Qty / Unit</label><div class="row"><div class="col-xs-7"><input type="number" step="0.001" name="quantity" class="form-control"></div><div class="col-xs-5"><input name="unit" class="form-control" placeholder="kg"></div></div></div>
  <div class="form-group"><label>Disposal Method</label><input name="disposal_method" class="form-control" placeholder="Recycle / compost / supplier pickup"></div>
  <div class="form-group"><label>Cost</label><input type="number" step="0.01" name="cost" class="form-control"></div>
  <div class="text-right"><button class="btn hm-btn-excel"><i class="fa fa-recycle"></i> Save Waste</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Green Initiative</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.sustainability.initiative') }}">@csrf
  <div class="form-group"><label>Initiative No</label><input name="initiative_no" class="form-control" placeholder="Auto if blank"></div>
  <div class="form-group"><label>Title</label><input name="title" class="form-control" required></div>
  <div class="form-group"><label>Category</label><select name="category" class="form-control"><option value="energy">Energy</option><option value="water">Water</option><option value="waste">Waste</option><option value="supplier">Supplier</option><option value="guest_awareness">Guest Awareness</option></select></div>
  <div class="form-group"><label>Owner</label><input name="owner_name" class="form-control"></div>
  <div class="form-group"><label>Planned Dates</label><div class="row"><div class="col-xs-6"><input type="date" name="planned_start" class="form-control"></div><div class="col-xs-6"><input type="date" name="planned_end" class="form-control"></div></div></div>
  <div class="form-group"><label>Estimated Saving</label><input type="number" step="0.01" name="estimated_saving" class="form-control"></div>
  <div class="text-right"><button class="btn hm-btn-pdf"><i class="fa fa-leaf"></i> Save Initiative</button></div>
 </form></div></div></div>
</div>
<div class="box hm-card"><div class="box-header with-border"><div class="hm-toolbar"><input class="form-control hm-search-input" style="max-width:260px" placeholder="Search initiatives..."><button class="btn hm-btn-csv">CSV</button><button class="btn hm-btn-excel">Excel</button><button class="btn hm-btn-pdf">PDF</button><button class="btn hm-btn-print">Print</button><button class="btn hm-btn-col">Column Visibility</button></div><h3 class="box-title">Green Initiatives</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>No</th><th>Title</th><th>Category</th><th>Owner</th><th>Dates</th><th>Saving</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($sustainability['initiatives'] as $i)<tr><td>{{ $i->initiative_no }}</td><td>{{ $i->title }}</td><td>{{ ucfirst(str_replace('_',' ',$i->category)) }}</td><td>{{ $i->owner_name }}</td><td>{{ $i->planned_start }} - {{ $i->planned_end }}</td><td class="text-right">{{ number_format((float)$i->estimated_saving,2) }}</td><td><span class="hm-badge {{ $i->status }}">{{ ucfirst(str_replace('_',' ',$i->status)) }}</span></td><td><form method="POST" action="{{ route('hotel-management.sustainability.initiative-status',$i->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="planned">Planned</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button class="btn btn-xs hm-btn-add">Update</button></form></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">No initiatives yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="row"><div class="col-md-6"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Goals</h3></div><div class="box-body table-responsive"><table class="table table-bordered hm-table"><thead><tr><th>Goal</th><th>Category</th><th>Target</th><th>Period</th><th>Status</th></tr></thead><tbody>@forelse($sustainability['goals'] as $g)<tr><td>{{ $g->goal_name }}</td><td>{{ ucfirst($g->category) }}</td><td>{{ number_format((float)$g->target_value,3) }} {{ $g->unit }}</td><td>{{ $g->start_date }} - {{ $g->end_date }}</td><td><span class="hm-badge {{ $g->status }}">{{ ucfirst(str_replace('_',' ',$g->status)) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No goals yet.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-md-6"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Waste Logs</h3></div><div class="box-body table-responsive"><table class="table table-bordered hm-table"><thead><tr><th>Date</th><th>Department</th><th>Type</th><th>Qty</th><th>Method</th><th>Cost</th></tr></thead><tbody>@forelse($sustainability['waste'] as $w)<tr><td>{{ $w->log_date }}</td><td>{{ $w->department }}</td><td>{{ ucfirst($w->waste_type) }}</td><td class="text-right">{{ number_format((float)$w->quantity,3) }} {{ $w->unit }}</td><td>{{ $w->disposal_method }}</td><td class="text-right">{{ number_format((float)$w->cost,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No waste logs yet.</td></tr>@endforelse</tbody></table></div></div></div></div>
</section>
@endsection
