@extends('layouts.app')
@section('title', 'Hotel Security & Key Control')
@section('content')
<section class="content-header hm-page-header"><h1><i class="fa fa-key"></i> Security & Key Control <small>Room keys, visitor passes and incident register</small></h1></section>
<section class="content hm-pos-scope">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please check:</strong> {{ $errors->first() }}</div>@endif
<div class="row hm-kpi-row">
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Active Keys</div><div class="hm-kpi-value">{{ $securityKeyControl['active_keys'] }}</div><div class="hm-kpi-sub">Issued / active cards</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Visitors Inside</div><div class="hm-kpi-value">{{ $securityKeyControl['open_visitors'] }}</div><div class="hm-kpi-sub">Checked-in passes</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">Open Incidents</div><div class="hm-kpi-value">{{ $securityKeyControl['open_incidents'] }}</div><div class="hm-kpi-sub">Awaiting action</div></div></div>
 <div class="col-md-3 col-sm-6"><div class="hm-kpi"><div class="hm-kpi-label">High Severity</div><div class="hm-kpi-value">{{ $securityKeyControl['high_incidents'] }}</div><div class="hm-kpi-sub">High / critical</div></div></div>
</div>
<div class="row">
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Issue Room Key/Card</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.security-key-control.key-card') }}">@csrf
  <div class="form-group"><label>Key/Card No</label><input name="key_no" class="form-control" placeholder="Auto if blank"></div>
  <div class="form-group"><label>Room ID</label><input type="number" name="room_id" class="form-control"></div>
  <div class="form-group"><label>Reservation ID</label><input type="number" name="reservation_id" class="form-control"></div>
  <div class="form-group"><label>Guest Name</label><input name="guest_name" class="form-control"></div>
  <div class="form-group"><label>Issued At</label><input type="datetime-local" name="issued_at" class="form-control"></div>
  <div class="form-group"><label>Expires At</label><input type="datetime-local" name="expires_at" class="form-control"></div>
  <div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="issued">Issued</option><option value="active">Active</option><option value="lost">Lost</option><option value="returned">Returned</option><option value="void">Void</option></select></div>
  <div class="text-right"><button class="btn hm-btn-add"><i class="fa fa-save"></i> Save Key</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Visitor Pass</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.security-key-control.visitor-pass') }}">@csrf
  <div class="form-group"><label>Pass No</label><input name="pass_no" class="form-control" placeholder="Auto if blank"></div>
  <div class="form-group"><label>Visitor Name</label><input name="visitor_name" class="form-control" required></div>
  <div class="form-group"><label>Mobile</label><input name="mobile" class="form-control"></div>
  <div class="form-group"><label>NIC / ID No</label><input name="nic_no" class="form-control"></div>
  <div class="form-group"><label>Guest / Room Reference</label><input name="guest_name" class="form-control" placeholder="Guest name"><input type="number" name="room_id" class="form-control" style="margin-top:6px" placeholder="Room ID"></div>
  <div class="form-group"><label>Purpose</label><input name="purpose" class="form-control" placeholder="Visit / delivery / contractor"></div>
  <div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="checked_in">Checked In</option><option value="active">Active</option><option value="checked_out">Checked Out</option><option value="blocked">Blocked</option></select></div>
  <div class="text-right"><button class="btn hm-btn-excel"><i class="fa fa-id-badge"></i> Save Visitor</button></div>
 </form></div></div></div>
 <div class="col-md-4"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Security Incident</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.security-key-control.incident') }}">@csrf
  <div class="form-group"><label>Incident No</label><input name="incident_no" class="form-control" placeholder="Auto if blank"></div>
  <div class="form-group"><label>Date / Time</label><input type="date" name="incident_date" class="form-control"><input name="incident_time" class="form-control" style="margin-top:6px" placeholder="HH:MM"></div>
  <div class="form-group"><label>Type</label><select name="incident_type" class="form-control" required><option value="guest_complaint">Guest Complaint</option><option value="lost_key">Lost Key</option><option value="visitor_issue">Visitor Issue</option><option value="theft">Theft</option><option value="accident">Accident</option><option value="other">Other</option></select></div>
  <div class="form-group"><label>Severity</label><select name="severity" class="form-control"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div>
  <div class="form-group"><label>Location / Guest</label><input name="location_reference" class="form-control" placeholder="Lobby / Room / Restaurant"><input name="guest_name" class="form-control" style="margin-top:6px" placeholder="Guest name"></div>
  <div class="form-group"><label>Description</label><textarea name="description" class="form-control" rows="3"></textarea></div>
  <div class="text-right"><button class="btn hm-btn-pdf"><i class="fa fa-shield"></i> Save Incident</button></div>
 </form></div></div></div>
</div>
<div class="box hm-card"><div class="box-header with-border"><div class="hm-toolbar"><input class="form-control hm-search-input" style="max-width:260px" placeholder="Search incidents..."><button class="btn hm-btn-csv">CSV</button><button class="btn hm-btn-excel">Excel</button><button class="btn hm-btn-pdf">PDF</button><button class="btn hm-btn-print">Print</button><button class="btn hm-btn-col">Column Visibility</button></div><h3 class="box-title">Security Incidents</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped hm-table"><thead><tr><th>No</th><th>Date</th><th>Type</th><th>Severity</th><th>Location</th><th>Guest</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($securityKeyControl['incidents'] as $i)<tr><td>{{ $i->incident_no }}</td><td>{{ $i->incident_date }} {{ $i->incident_time }}</td><td>{{ ucwords(str_replace('_',' ',$i->incident_type)) }}</td><td><span class="hm-badge {{ $i->severity }}">{{ ucfirst($i->severity) }}</span></td><td>{{ $i->location_reference }}</td><td>{{ $i->guest_name }}</td><td><span class="hm-badge {{ $i->status }}">{{ ucfirst($i->status) }}</span></td><td><form method="POST" action="{{ route('hotel-management.security-key-control.incident-status',$i->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><button class="btn btn-xs hm-btn-add">Update</button></form></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">No incidents yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="row"><div class="col-md-6"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Room Keys / Cards</h3></div><div class="box-body table-responsive"><table class="table table-bordered hm-table"><thead><tr><th>No</th><th>Room</th><th>Guest</th><th>Issued</th><th>Expires</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($securityKeyControl['keys'] as $k)<tr><td>{{ $k->key_no }}</td><td>{{ $k->room_id }}</td><td>{{ $k->guest_name }}</td><td>{{ $k->issued_at }}</td><td>{{ $k->expires_at }}</td><td><span class="hm-badge {{ $k->status }}">{{ ucfirst($k->status) }}</span></td><td><form method="POST" action="{{ route('hotel-management.security-key-control.key-status',$k->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="returned">Returned</option><option value="lost">Lost</option><option value="void">Void</option><option value="active">Active</option></select><button class="btn btn-xs hm-btn-add">Save</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No room key/card records.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-md-6"><div class="box hm-card"><div class="box-header with-border"><h3 class="box-title">Visitor Passes</h3></div><div class="box-body table-responsive"><table class="table table-bordered hm-table"><thead><tr><th>Pass</th><th>Visitor</th><th>Mobile</th><th>Guest</th><th>Room</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($securityKeyControl['visitors'] as $v)<tr><td>{{ $v->pass_no }}</td><td>{{ $v->visitor_name }}</td><td>{{ $v->mobile }}</td><td>{{ $v->guest_name }}</td><td>{{ $v->room_id }}</td><td><span class="hm-badge {{ $v->status }}">{{ ucfirst(str_replace('_',' ',$v->status)) }}</span></td><td><form method="POST" action="{{ route('hotel-management.security-key-control.visitor-status',$v->id) }}" class="form-inline">@csrf<select name="status" class="form-control input-sm"><option value="checked_out">Checked Out</option><option value="blocked">Blocked</option><option value="active">Active</option></select><button class="btn btn-xs hm-btn-add">Save</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No visitor passes.</td></tr>@endforelse</tbody></table></div></div></div></div>
</section>
@endsection
