@extends('autoservice::layouts.master')
@section('content')
@include('autoservice::layouts.nav')
<section class="content-header"><h1>Customer Communication Centre</h1></section>
<section class="content">
<div class="box"><div class="box-header"><h3 class="box-title">Record Communication</h3></div><div class="box-body"><form method="post" action="{{ route('autoservice.communications.store') }}">@csrf<div class="row"><div class="col-md-3"><label>Job</label><select name="job_id" class="form-control"><option value="">Please Select</option>@foreach($jobs as $j)<option value="{{ $j->id }}">{{ $j->job_no ?? $j->id }}</option>@endforeach</select></div><div class="col-md-2"><label>Channel</label><select name="channel" class="form-control"><option>internal</option><option>sms</option><option>email</option><option>whatsapp</option><option>phone</option></select></div><div class="col-md-2"><label>Direction</label><select name="direction" class="form-control"><option>outbound</option><option>inbound</option><option>internal</option></select></div><div class="col-md-3"><label>Recipient</label><input class="form-control" name="recipient"></div><div class="col-md-2"><label>Status</label><select name="status" class="form-control"><option>draft</option><option>sent</option><option>received</option></select></div></div><br><label>Subject</label><input class="form-control" name="subject"><br><label>Message</label><textarea class="form-control" name="message" required></textarea><br><button class="btn btn-primary">Save</button></form></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Communication History</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Date</th><th>Job</th><th>Channel</th><th>Direction</th><th>Recipient</th><th>Subject</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($communications as $c)<tr><td>{{ $c->created_at }}</td><td>{{ $c->job_id }}</td><td>{{ $c->channel }}</td><td>{{ $c->direction }}</td><td>{{ $c->recipient }}</td><td>{{ $c->subject }}</td><td>{{ $c->status }}</td><td>@if($c->status!='sent')<form method="post" action="{{ route('autoservice.communications.mark_sent',$c->id) }}">@csrf<button class="btn btn-xs btn-success">Mark Sent</button></form>@endif</td></tr><tr><td colspan="8">{{ $c->message }}</td></tr>@endforeach</tbody></table></div></div>
</section>
@endsection
