-- HOTELMGT_027_SQL.sql
-- Hotel Management Parcel 027 - Laundry / Guest Garment Services
-- Run this SQL in every tenant database where Hotel Management is enabled.

CREATE TABLE IF NOT EXISTS `hm_laundry_services` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NULL,
  `business_location_id` int unsigned NULL,
  `service_code` varchar(80) NOT NULL,
  `service_name` varchar(150) NOT NULL,
  `category` varchar(80) NULL,
  `unit` varchar(30) NULL,
  `standard_rate` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `express_rate` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `remarks` text NULL,
  `created_by` int unsigned NULL,
  `updated_by` int unsigned NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_laundry_services_business_code_unique` (`business_id`,`service_code`),
  KEY `hm_laundry_services_business_location_index` (`business_id`,`business_location_id`),
  KEY `hm_laundry_services_active_index` (`business_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_laundry_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NULL,
  `business_location_id` int unsigned NULL,
  `order_no` varchar(80) NOT NULL,
  `order_date` date NULL,
  `room_id` bigint unsigned NULL,
  `room_no` varchar(30) NULL,
  `reservation_id` bigint unsigned NULL,
  `folio_id` bigint unsigned NULL,
  `guest_name` varchar(150) NULL,
  `service_id` bigint unsigned NULL,
  `service_code` varchar(80) NULL,
  `service_name` varchar(150) NULL,
  `qty` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `rate_type` varchar(30) NULL,
  `unit_price` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `total_amount` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `paid_amount` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `balance_amount` decimal(22,4) NOT NULL DEFAULT 0.0000,
  `payment_method` varchar(40) NULL,
  `payment_reference` varchar(150) NULL,
  `pickup_time` varchar(30) NULL,
  `delivery_time` varchar(30) NULL,
  `status` varchar(30) NOT NULL DEFAULT 'received',
  `folio_posted_charge_id` bigint unsigned NULL,
  `posted_charge_id` bigint unsigned NULL,
  `posted_by` int unsigned NULL,
  `posted_at` timestamp NULL DEFAULT NULL,
  `paid_by` int unsigned NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `remarks` text NULL,
  `created_by` int unsigned NULL,
  `updated_by` int unsigned NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_laundry_orders_business_order_unique` (`business_id`,`order_no`),
  KEY `hm_laundry_orders_business_location_index` (`business_id`,`business_location_id`),
  KEY `hm_laundry_orders_date_index` (`business_id`,`order_date`),
  KEY `hm_laundry_orders_room_index` (`business_id`,`room_id`,`room_no`),
  KEY `hm_laundry_orders_folio_index` (`business_id`,`folio_id`),
  KEY `hm_laundry_orders_status_index` (`business_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
