-- HOTELMGT_029_SQL.sql
-- Hotel Management Parcel 029: Procurement / Purchasing / GRN
-- Run this inside each tenant database. No database name is hardcoded.

CREATE TABLE IF NOT EXISTS `hm_procurement_suppliers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `supplier_code` VARCHAR(80) NULL,
  `supplier_name` VARCHAR(160) NOT NULL,
  `contact_person` VARCHAR(120) NULL,
  `mobile` VARCHAR(40) NULL,
  `email` VARCHAR(160) NULL,
  `address` TEXT NULL,
  `category` VARCHAR(80) NULL,
  `credit_days` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_proc_sup_biz_name_unique` (`business_id`, `supplier_name`),
  KEY `hm_proc_sup_biz_loc_idx` (`business_id`, `business_location_id`),
  KEY `hm_proc_sup_code_idx` (`supplier_code`),
  KEY `hm_proc_sup_active_idx` (`business_id`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_purchase_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `request_no` VARCHAR(80) NOT NULL,
  `request_date` DATE NULL,
  `department` VARCHAR(100) NOT NULL,
  `requested_by` VARCHAR(120) NULL,
  `required_date` DATE NULL,
  `priority` VARCHAR(30) NOT NULL DEFAULT 'normal',
  `item_name` VARCHAR(160) NOT NULL,
  `description` TEXT NULL,
  `qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `estimated_unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `estimated_total` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `status` VARCHAR(30) NOT NULL DEFAULT 'submitted',
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_pr_biz_no_unique` (`business_id`, `request_no`),
  KEY `hm_pr_scope_idx` (`business_id`, `business_location_id`),
  KEY `hm_pr_date_idx` (`business_id`, `request_date`),
  KEY `hm_pr_department_idx` (`business_id`, `department`),
  KEY `hm_pr_status_idx` (`business_id`, `status`),
  KEY `hm_pr_priority_idx` (`business_id`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_purchase_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `po_no` VARCHAR(80) NOT NULL,
  `po_date` DATE NULL,
  `supplier_id` BIGINT UNSIGNED NOT NULL,
  `request_id` BIGINT UNSIGNED NULL,
  `item_name` VARCHAR(160) NOT NULL,
  `description` TEXT NULL,
  `qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `unit_cost` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `gross_amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `net_amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `received_qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `expected_delivery_date` DATE NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ordered',
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_po_biz_no_unique` (`business_id`, `po_no`),
  KEY `hm_po_scope_idx` (`business_id`, `business_location_id`),
  KEY `hm_po_supplier_idx` (`business_id`, `supplier_id`),
  KEY `hm_po_request_idx` (`business_id`, `request_id`),
  KEY `hm_po_date_idx` (`business_id`, `po_date`),
  KEY `hm_po_status_idx` (`business_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_goods_received_notes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `grn_no` VARCHAR(80) NOT NULL,
  `po_id` BIGINT UNSIGNED NOT NULL,
  `received_date` DATE NULL,
  `received_qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `accepted_qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `rejected_qty` DECIMAL(20,3) NOT NULL DEFAULT 0.000,
  `accepted_value` DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  `received_by` VARCHAR(120) NULL,
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hm_grn_biz_no_unique` (`business_id`, `grn_no`),
  KEY `hm_grn_scope_idx` (`business_id`, `business_location_id`),
  KEY `hm_grn_po_idx` (`business_id`, `po_id`),
  KEY `hm_grn_date_idx` (`business_id`, `received_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
