-- HOTELMGT_010_SQL.sql
-- Hotel Management Parcel 010 only: Room Service / In-room Dining workflow.
-- Run against each tenant database that uses Hotel Management.

CREATE TABLE IF NOT EXISTS `hm_room_service_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `room_service_no` VARCHAR(50) NOT NULL,
  `order_date` DATE NOT NULL,
  `delivery_time` TIME NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `folio_id` BIGINT UNSIGNED NULL,
  `guest_name` VARCHAR(191) NULL,
  `menu_item_id` BIGINT UNSIGNED NOT NULL,
  `item_name` VARCHAR(191) NOT NULL,
  `quantity` DECIMAL(22,4) NOT NULL DEFAULT 1.0000,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `subtotal` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `service_charge` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `grand_total` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `payment_mode` VARCHAR(40) NOT NULL DEFAULT 'room',
  `priority` VARCHAR(30) NOT NULL DEFAULT 'normal',
  `status` VARCHAR(30) NOT NULL DEFAULT 'ordered',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `delivered_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `hm_rs_business_id_index` (`business_id`),
  KEY `hm_rs_location_id_index` (`business_location_id`),
  KEY `hm_rs_order_no_index` (`room_service_no`),
  KEY `hm_rs_order_date_index` (`order_date`),
  KEY `hm_rs_room_id_index` (`room_id`),
  KEY `hm_rs_folio_id_index` (`folio_id`),
  KEY `hm_rs_menu_item_id_index` (`menu_item_id`),
  KEY `hm_rs_payment_mode_index` (`payment_mode`),
  KEY `hm_rs_priority_index` (`priority`),
  KEY `hm_rs_status_index` (`status`),
  KEY `hm_rs_scope_date_idx` (`business_id`, `business_location_id`, `order_date`),
  KEY `hm_rs_scope_no_idx` (`business_id`, `room_service_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
