-- HOTELMGT_012_SQL.sql
-- Hotel Management Parcel 012 specific SQL only.
-- Adds Conference & Meeting Hall booking tables.

CREATE TABLE IF NOT EXISTS `hm_conference_rooms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `room_code` VARCHAR(50) NULL,
  `room_name` VARCHAR(191) NOT NULL,
  `capacity` INT NOT NULL DEFAULT 0,
  `hourly_rate` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `half_day_rate` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `full_day_rate` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `setup_style` VARCHAR(80) NULL,
  `equipment` TEXT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `hm_conference_rooms_business_id_index` (`business_id`),
  KEY `hm_conference_rooms_business_location_id_index` (`business_location_id`),
  KEY `hm_conference_rooms_room_code_index` (`room_code`),
  KEY `hm_conference_rooms_status_index` (`status`),
  KEY `hm_conf_rooms_scope_status_idx` (`business_id`,`business_location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_conference_bookings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `booking_no` VARCHAR(50) NULL,
  `booking_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `conference_room_id` BIGINT UNSIGNED NOT NULL,
  `room_name` VARCHAR(191) NULL,
  `meeting_title` VARCHAR(191) NOT NULL,
  `customer_name` VARCHAR(191) NOT NULL,
  `customer_mobile` VARCHAR(50) NULL,
  `customer_email` VARCHAR(191) NULL,
  `attendees` INT NOT NULL DEFAULT 0,
  `setup_style` VARCHAR(80) NULL,
  `equipment_required` TEXT NULL,
  `catering_required` TINYINT(1) NOT NULL DEFAULT 0,
  `catering_note` TEXT NULL,
  `rental_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `catering_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `advance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `total_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `balance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` VARCHAR(30) NOT NULL DEFAULT 'reserved',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `hm_conference_bookings_business_id_index` (`business_id`),
  KEY `hm_conference_bookings_business_location_id_index` (`business_location_id`),
  KEY `hm_conference_bookings_booking_no_index` (`booking_no`),
  KEY `hm_conference_bookings_booking_date_index` (`booking_date`),
  KEY `hm_conference_bookings_conference_room_id_index` (`conference_room_id`),
  KEY `hm_conference_bookings_status_index` (`status`),
  KEY `hm_conf_booking_scope_date_idx` (`business_id`,`business_location_id`,`booking_date`),
  KEY `hm_conf_booking_clash_idx` (`conference_room_id`,`booking_date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
