-- HOTELMGT_011_SQL.sql
-- Banquet & Event Management tables only for parcel 011.

CREATE TABLE IF NOT EXISTS `hm_banquet_halls` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `hall_code` VARCHAR(50) NOT NULL,
  `hall_name` VARCHAR(191) NOT NULL,
  `capacity` INT NOT NULL DEFAULT 0,
  `base_rate` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `description` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `hm_bh_business_id_idx` (`business_id`),
  KEY `hm_bh_location_id_idx` (`business_location_id`),
  KEY `hm_bh_hall_code_idx` (`hall_code`),
  KEY `hm_bh_status_idx` (`status`),
  KEY `hm_bh_scope_status_idx` (`business_id`,`business_location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hm_banquet_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `event_no` VARCHAR(50) NOT NULL,
  `event_date` DATE NOT NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `hall_id` BIGINT UNSIGNED NOT NULL,
  `hall_name` VARCHAR(191) NOT NULL,
  `event_type` VARCHAR(80) NOT NULL,
  `customer_name` VARCHAR(191) NOT NULL,
  `customer_mobile` VARCHAR(50) NULL,
  `guest_count` INT NOT NULL DEFAULT 0,
  `package_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `advance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `total_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `balance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` VARCHAR(30) NOT NULL DEFAULT 'reserved',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `hm_be_business_id_idx` (`business_id`),
  KEY `hm_be_location_id_idx` (`business_location_id`),
  KEY `hm_be_event_no_idx` (`event_no`),
  KEY `hm_be_event_date_idx` (`event_date`),
  KEY `hm_be_hall_id_idx` (`hall_id`),
  KEY `hm_be_event_type_idx` (`event_type`),
  KEY `hm_be_status_idx` (`status`),
  KEY `hm_be_scope_date_idx` (`business_id`,`business_location_id`,`event_date`),
  KEY `hm_be_hall_date_status_idx` (`hall_id`,`event_date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
