<div class="ezylaw-nav">
<a href="{{ route('ezylaw.dashboard') }}">Dashboard</a>
<a href="{{ route('ezylaw.management.index') }}">Management</a>
<a href="{{ route('ezylaw.clients.index') }}">Clients</a>
<a href="{{ route('ezylaw.matters.index') }}">Matters</a>
<a href="{{ route('ezylaw.workflow.index') }}">Workflow</a>
<a href="{{ route('ezylaw.closures.index') }}">Matter Closing</a>
<a href="{{ route('ezylaw.court_filings.index') }}">Court Filings</a>
<a href="{{ route('ezylaw.hearings.index') }}">Hearings</a>
<a href="{{ route('ezylaw.settlements.index') }}">Settlements</a>
<a href="{{ route('ezylaw.research.index') }}">Research</a>
<a href="{{ route('ezylaw.deadlines.index') }}">Deadlines</a>
<a href="{{ route('ezylaw.evidence.index') }}">Evidence</a>
<a href="{{ route('ezylaw.calendar.index') }}">Calendar</a>
<a href="{{ route('ezylaw.tasks.index') }}">Tasks</a>
<a href="{{ route('ezylaw.time.index') }}">Time</a>
<a href="{{ route('ezylaw.retainers.index') }}">Retainers</a>
<a href="{{ route('ezylaw.estimates.index') }}">Estimates</a>
<a href="{{ route('ezylaw.billing.index') }}">Billing</a>
<a href="{{ route('ezylaw.advances.index') }}">Advances</a>
<a href="{{ route('ezylaw.expenses.index') }}">Expenses</a>
<a href="{{ route('ezylaw.trust.index') }}">Trust</a>
<a href="{{ route('ezylaw.trust.reconcile') }}">Trust Reconcile</a>
<a href="{{ route('ezylaw.trust.audit') }}">Trust Audit</a>
<a href="{{ route('ezylaw.documents.index') }}">Documents</a>
<a href="{{ route('ezylaw.approvals.index') }}">Approvals / E-Sign</a>
<a href="{{ route('ezylaw.templates.index') }}">Templates</a>
<a href="{{ route('ezylaw.communications.index') }}">Communications</a>
<a href="{{ route('ezylaw.portal.index') }}">Client Portal</a>
<a href="{{ route('ezylaw.notifications.index') }}">Notifications</a>
<a href="{{ route('ezylaw.notification_rules.index') }}">Notification Rules</a>
<a href="{{ route('ezylaw.workload.index') }}">Workload</a>
<a href="{{ route('ezylaw.conflicts.index') }}">Conflict Check</a>
<a href="{{ route('ezylaw.reports.index') }}">Reports</a>
<a href="{{ route('ezylaw.reports.legal') }}">Legal Reports</a>
<a href="{{ route('ezylaw.settings.index') }}">Settings</a>
</div>
