@extends('hrmanager::layouts.master')
@section('hr_content')
<div class="hr-page">
@include('hrmanager::dashboard.partials.header',['title'=>'Travel & Expense Claims','subtitle'=>'Travel requests, expense claims, approvals, payments and documents connected to Employee Central Record.','section'=>'Claims'])
<div class="hr-card-grid"><div class="hr-kpi purple"><i class="fa fa-users"></i><span>Employees</span><strong>{{ number_format($stats['employees'] ?? 0) }}</strong></div><div class="hr-kpi blue"><i class="fa fa-folder"></i><span>Categories</span><strong>{{ number_format($stats['categories'] ?? 0) }}</strong></div><div class="hr-kpi orange"><i class="fa fa-plane"></i><span>Travel Requests</span><strong>{{ number_format($stats['travel_requests'] ?? 0) }}</strong></div><div class="hr-kpi green"><i class="fa fa-file-text"></i><span>Claims</span><strong>{{ number_format($stats['claims'] ?? 0) }}</strong></div><div class="hr-kpi purple"><i class="fa fa-hourglass"></i><span>Pending</span><strong>{{ number_format($stats['pending'] ?? 0) }}</strong></div><div class="hr-kpi blue"><i class="fa fa-check"></i><span>Approved</span><strong>{{ number_format($stats['approved'] ?? 0) }}</strong></div><div class="hr-kpi orange"><i class="fa fa-money"></i><span>Paid</span><strong>{{ number_format($stats['paid'] ?? 0) }}</strong></div><div class="hr-kpi green"><i class="fa fa-calculator"></i><span>Claim Total</span><strong>{{ number_format($stats['claim_total'] ?? 0, 2) }}</strong></div></div>
<div class="claim-grid"><div class="hr-panel"><h3>Submit Claim</h3><form method="POST" action="{{ route('hrmanager.claims.claims.store') }}" class="hr-form">@csrf<label>Employee</label><select name="employee_id" required><option value="">Select Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no ?? $employee->id }} - {{ $employee->full_name ?? '' }}</option>@endforeach</select><label>Claim Title</label><input name="claim_title" required><label>Claim Date</label><input type="date" name="claim_date" value="{{ date('Y-m-d') }}"><label>Total Amount</label><input type="number" step="0.0001" name="total_amount" value="0"><label>Remarks</label><textarea name="remarks"></textarea><button class="hr-primary-btn">Submit Claim</button></form></div>
<div class="hr-panel wide"><h3>Expense Claims</h3>@include('hrmanager::components.list-toolbar',['searchPlaceholder'=>'Search claim no, title, status'])<table class="hr-table"><thead><tr><th>Claim No</th><th>Employee</th><th>Title</th><th>Date</th><th>Total</th><th>Approval</th><th>Payment</th></tr></thead><tbody>@forelse($claims as $row)<tr><td>{{ $row->claim_no }}</td><td>#{{ $row->employee_id }}</td><td>{{ $row->claim_title }}</td><td>{{ $row->claim_date }}</td><td>{{ number_format($row->total_amount ?? 0, 2) }}</td><td><em class="status-pill">{{ ucfirst($row->approval_status) }}</em></td><td><em class="status-pill">{{ ucfirst($row->payment_status) }}</em></td></tr>@empty<tr><td colspan="7" class="empty-row">No claims found.</td></tr>@endforelse</tbody></table>@if(method_exists($claims,'links')){{ $claims->links() }}@endif</div></div>
<div class="claim-grid bottom"><div class="hr-panel"><h3>Travel Requests</h3><table class="hr-table compact-table"><thead><tr><th>No</th><th>Employee</th><th>Status</th></tr></thead><tbody>@forelse($travelRequests as $row)<tr><td>{{ $row->request_no }}</td><td>#{{ $row->employee_id }}</td><td><em class="status-pill">{{ $row->request_status }}</em></td></tr>@empty<tr><td colspan="3" class="empty-row">No travel requests.</td></tr>@endforelse</tbody></table></div><div class="hr-panel"><h3>Approvals</h3><table class="hr-table compact-table"><thead><tr><th>Ref</th><th>Employee</th><th>Status</th></tr></thead><tbody>@forelse($approvals as $row)<tr><td>{{ $row->reference_type }} #{{ $row->reference_id }}</td><td>#{{ $row->employee_id }}</td><td><em class="status-pill">{{ $row->approval_status }}</em></td></tr>@empty<tr><td colspan="3" class="empty-row">No approvals.</td></tr>@endforelse</tbody></table></div><div class="hr-panel"><h3>Payments</h3><table class="hr-table compact-table"><thead><tr><th>No</th><th>Employee</th><th>Amount</th></tr></thead><tbody>@forelse($payments as $row)<tr><td>{{ $row->payment_no }}</td><td>#{{ $row->employee_id }}</td><td>{{ number_format($row->paid_amount ?? 0, 2) }}</td></tr>@empty<tr><td colspan="3" class="empty-row">No payments.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
