<?php

return [
    'accounts' => ['name' => 'Accounting', 'aliases' => ['account', 'accounts']],
    'agent' => ['name' => 'Agent', 'aliases' => ['agent', 'agent_module']],
    'airline_ticketing' => ['name' => 'Airline Ticketing', 'aliases' => ['airline_ticketing', 'airline_ticketing_module', 'airlineticketing']],
    'asset_management' => ['name' => 'Asset Management', 'aliases' => ['asset_management', 'asset_management_module', 'asset_module', 'assetmanagement', 'ns_asset_management']],
    'auto_repair_services' => ['name' => 'Auto Repair Services', 'aliases' => ['auto_repair_services', 'auto_repair_services_module', 'auto_services_and_repair_module', 'autorepairservices', 'autorepairservices_module']],
    'auto_service' => ['name' => 'Auto Service', 'aliases' => ['auto_service', 'auto_service_module', 'autoservice', 'autoservice_module']],
    'bakery' => ['name' => 'Bakery', 'aliases' => ['bakery', 'bakery_module']],
    'banking_aml' => ['name' => 'Banking AML', 'aliases' => ['banking_aml', 'banking_aml_module', 'bankingaml']],
    'banking_atm_debit_card' => ['name' => 'Banking Atm Debit Card', 'aliases' => ['banking_atm_debit_card', 'banking_atm_debit_card_module', 'bankingatmdebitcard']],
    'banking_cheque' => ['name' => 'Banking Cheque', 'aliases' => ['banking_cheque', 'banking_cheque_module', 'bankingcheque']],
    'banking_core_deposits' => ['name' => 'Banking Core Deposits', 'aliases' => ['banking_core_deposits', 'banking_core_deposits_module', 'bankingcoredeposits']],
    'banking_core_teller' => ['name' => 'Banking Core Teller', 'aliases' => ['banking_core_teller', 'banking_core_teller_module', 'bankingcoreteller']],
    'banking_corporate_banking' => ['name' => 'Banking Corporate Banking', 'aliases' => ['banking_corporate_banking', 'banking_corporate_banking_module', 'bankingcorporatebanking']],
    'banking_crm' => ['name' => 'Banking CRM', 'aliases' => ['banking_crm', 'banking_crm_module', 'bankingcrm']],
    'banking_insurance' => ['name' => 'Banking Insurance', 'aliases' => ['banking_insurance', 'banking_insurance_module', 'bankinginsurance']],
    'banking_internet_banking' => ['name' => 'Banking Internet Banking', 'aliases' => ['banking_internet_banking', 'banking_internet_banking_module', 'bankinginternetbanking']],
    'banking_microfinance' => ['name' => 'Banking Microfinance', 'aliases' => ['banking_microfinance', 'banking_microfinance_module', 'bankingmicrofinance']],
    'banking_microfinance_treasury' => ['name' => 'Banking Microfinance Treasury', 'aliases' => ['banking_microfinance_treasury', 'banking_microfinance_treasury_module', 'bankingmicrofinancetreasury']],
    'banking_mobile_banking' => ['name' => 'Banking Mobile Banking', 'aliases' => ['banking_mobile_banking', 'banking_mobile_banking_module', 'bankingmobilebanking']],
    'banking_payments_hub' => ['name' => 'Banking Payments Hub', 'aliases' => ['banking_payments_hub', 'banking_payments_hub_module', 'bankingpaymentshub']],
    'banking_risk' => ['name' => 'Banking Risk', 'aliases' => ['banking_risk', 'banking_risk_module', 'bankingrisk']],
    'banking_tester_ui' => ['name' => 'Banking Tester UI', 'aliases' => ['banking_tester_ui', 'banking_tester_ui_module', 'bankingtesterui']],
    'banking_trade_finance' => ['name' => 'Banking Trade Finance', 'aliases' => ['banking_trade_finance', 'banking_trade_finance_module', 'bankingtradefinance']],
    'banking_treasury' => ['name' => 'Banking Treasury', 'aliases' => ['banking_treasury', 'banking_treasury_module', 'bankingtreasury']],
    'banking_ui' => ['name' => 'Banking UI', 'aliases' => ['banking_ui', 'banking_ui_module', 'bankingui']],
    'beauty_saloons' => ['name' => 'Beauty Saloons', 'aliases' => ['beauty_saloons', 'beauty_saloons_module', 'beautysaloons']],
    'chequer' => ['name' => 'Chequer', 'aliases' => ['chequer', 'chequer_module']],
    'closing_balance_report' => ['name' => 'Closing Balance Report', 'aliases' => ['closing_balance_report', 'closing_balance_report_module', 'closingbalancereport']],
    'communication_hub' => ['name' => 'Communication Hub', 'aliases' => ['communication_hub', 'communication_hub_module', 'communicationhub']],
    'core_ui' => ['name' => 'Core UI', 'aliases' => ['core_ui', 'core_ui_module', 'coreui']],
    'crm' => ['name' => 'Crm', 'aliases' => ['crm', 'crm_module']],
    'customer_statements' => ['name' => 'Customer Statements', 'aliases' => ['customer_statements', 'customer_statements_module', 'customerstatements']],
    'customers' => ['name' => 'Customers', 'aliases' => ['customer', 'customers', 'customers_module']],
    'customers_core' => ['name' => 'Customers', 'aliases' => ['customers', 'customer']],
    'customizer' => ['name' => 'Customizer', 'aliases' => ['customizer', 'customizer_module']],
    'daily_activity_report' => ['name' => 'Daily Activity Report', 'aliases' => ['daily_activity_report', 'daily_activity_report_module', 'dailyactivityreport']],
    'daily_collection_sw' => ['name' => 'Daily Collection SW', 'aliases' => ['daily_collection_sw', 'daily_collection_sw_enabled', 'daily_collection_sw_module', 'dailycollectionsw', 'dailycollectionsw_module']],
    'deposits' => ['name' => 'Deposits', 'aliases' => ['deposits', 'deposits_module', 'ns_deposits_module']],
    'development' => ['name' => 'Development', 'aliases' => ['development', 'development_module']],
    'digital_business_cards' => ['name' => 'Digital Business Cards', 'aliases' => ['digital_business_cards', 'digital_business_cards_module', 'digitalbusinesscards']],
    'digital_wallet' => ['name' => 'Digital Wallet', 'aliases' => ['digital_wallet', 'digital_wallet_module', 'digitalwallet']],
    'dis_stock_transfer' => ['name' => 'Dis Stock Transfer', 'aliases' => ['dis_stock_transfer', 'dis_stock_transfer_module', 'disstocktransfer']],
    'discount' => ['name' => 'Discount', 'aliases' => ['discount', 'discount_module', 'ns_discount_module']],
    'distribution' => ['name' => 'Distribution', 'aliases' => ['distribution', 'distribution_module']],
    'distribution_new' => ['name' => 'Distribution New', 'aliases' => ['distribution_new', 'distribution_new_module', 'distributionnew']],
    'doc_management' => ['name' => 'Doc Management', 'aliases' => ['doc_management', 'doc_management_module', 'docmanagement']],
    'dsr' => ['name' => 'Dsr', 'aliases' => ['dsr', 'dsr_module', 'ns_dsr_module']],
    'enterprise_framework' => ['name' => 'Enterprise Framework', 'aliases' => ['enterprise_framework', 'enterprise_framework_module', 'enterpriseframework']],
    'essentials' => ['name' => 'Essentials', 'aliases' => ['essentials', 'essentials_module']],
    'ev_charging' => ['name' => 'EV Charging', 'aliases' => ['ev_charging', 'ev_charging_module', 'evcharging']],
    'expenses' => ['name' => 'Expenses', 'aliases' => ['expenses']],
    'expenses_new' => ['name' => 'Expenses New', 'aliases' => ['expenses_new', 'expenses_new_module', 'expensesnew']],
    'ezy_invoice' => ['name' => 'Ezy Invoice', 'aliases' => ['ezy_invoice', 'ezy_invoice_module', 'ezyinvoice']],
    'finance' => ['name' => 'Finance', 'aliases' => ['account', 'accounts_finance', 'accounts_finance_module', 'finance', 'finance_module']],
    'finance_reports' => ['name' => 'Finance Reports', 'aliases' => ['finance_reports', 'finance_reports_module', 'financereports']],
    'fleet' => ['name' => 'Fleet', 'aliases' => ['fleet', 'fleet_module']],
    'hms' => ['name' => 'Hms', 'aliases' => ['hms', 'hms_module']],
    'hotel_management' => ['name' => 'Hotel Management', 'aliases' => ['hotel_management', 'hotel_management_module', 'hotelmanagement']],
    'hr' => ['name' => 'HR', 'aliases' => ['hr', 'hr_module']],
    'hr_manager' => ['name' => 'HR Manager', 'aliases' => ['hr_manager', 'hr_manager_module', 'hrmanager']],
    'identity_access' => ['name' => 'Identity Access', 'aliases' => ['identity_access', 'identity_access_module', 'identityaccess']],
    'installment' => ['name' => 'Installment', 'aliases' => ['installment', 'installment_module']],
    'leads' => ['name' => 'Leads', 'aliases' => ['leads', 'leads_module']],
    'leads_new' => ['name' => 'Leads New', 'aliases' => ['leads_new', 'leads_new_module', 'leadsnew']],
    'leasing' => ['name' => 'Leasing', 'aliases' => ['leasing', 'leasing_module']],
    'loan' => ['name' => 'Loan', 'aliases' => ['loan', 'loan_module']],
    'management_report' => ['name' => 'Management Report', 'aliases' => ['management_report', 'management_report_module', 'managementreport']],
    'manufacturing' => ['name' => 'Manufacturing', 'aliases' => ['manufacturing', 'manufacturing_module', 'mf_module']],
    'member' => ['name' => 'Member', 'aliases' => ['member', 'member_module']],
    'membership' => ['name' => 'Membership', 'aliases' => ['member_registration', 'membership', 'membership_module']],
    'membership_new' => ['name' => 'Membership New', 'aliases' => ['membership_new', 'membership_new_module', 'membershipnew']],
    'mpcs' => ['name' => 'MPCS', 'aliases' => ['mpcs', 'mpcs_module']],
    'my_auto' => ['name' => 'My Auto', 'aliases' => ['my_auto', 'my_auto_module', 'myauto']],
    'my_health' => ['name' => 'My Health', 'aliases' => ['my_health', 'my_health_module', 'myhealth', 'myhealth_module', 'patient_module']],
    'my_health_members' => ['name' => 'My Health Members', 'aliases' => ['my_health_members', 'my_health_members_module', 'myhealthmembers']],
    'pawning' => ['name' => 'Pawning', 'aliases' => ['pawning', 'pawning_module']],
    'petro' => ['name' => 'Petro', 'aliases' => ['enable_petro_module', 'petro', 'petro_module']],
    'petro_direct' => ['name' => 'Petro Direct', 'aliases' => ['petro_direct', 'petro_direct_module', 'petrodirect']],
    'petro_direct_new' => ['name' => 'Petro Direct New', 'aliases' => ['petro_direct_new', 'petro_direct_new_module', 'petrodirectnew']],
    'petro_general' => ['name' => 'Petro General', 'aliases' => ['petro_general', 'petro_general_module', 'petrogeneral']],
    'petro_pd' => ['name' => 'Petro PD', 'aliases' => ['pd_operators', 'pd_settlements', 'petro_p_d', 'petro_p_d_module', 'petro_pd', 'petro_pd_module', 'petropd']],
    'petro_pd_new' => ['name' => 'Petro PD New', 'aliases' => ['petro_pd_new', 'petro_pd_new_module', 'petropdnew']],
    'pos' => ['name' => 'POS', 'aliases' => ['add_sale', 'pos', 'pos_module', 'pos_sale']],
    'pos2' => ['name' => 'POS2', 'aliases' => ['pos2', 'pos2_module']],
    'poultry' => ['name' => 'Poultry', 'aliases' => ['poultry', 'poultry_module']],
    'price_change_new' => ['name' => 'Price Change New', 'aliases' => ['price_change_new', 'price_change_new_module', 'pricechangenew']],
    'price_changes' => ['name' => 'Price Changes', 'aliases' => ['price_changes', 'price_changes_module', 'pricechanges']],
    'product' => ['name' => 'Product', 'aliases' => ['product', 'product_module']],
    'product_catalogue' => ['name' => 'Product Catalogue', 'aliases' => ['catalogue_qr', 'product_catalogue', 'product_catalogue_module', 'productcatalogue']],
    'products' => ['name' => 'Products', 'aliases' => ['products']],
    'products_new' => ['name' => 'Products New', 'aliases' => ['product_new_module', 'productnew_module', 'products_new', 'products_new_module', 'productsnew', 'productsnew_module']],
    'property' => ['name' => 'Property', 'aliases' => ['property', 'property_module']],
    'pumper_dashboard' => ['name' => 'Pumper Dashboard', 'aliases' => ['pumper_dashboard', 'pumper_dashboard_module', 'pumperdashboard']],
    'pumper_dashboard_new' => ['name' => 'Pumper Dashboard New', 'aliases' => ['pumper_dashboard_new', 'pumper_dashboard_new_module', 'pumperdashboardnew']],
    'purchase' => ['name' => 'Purchase', 'aliases' => ['purchase', 'purchase_module', 'purchases']],
    'purchases' => ['name' => 'Purchases', 'aliases' => ['purchases', 'purchase']],
    'ran' => ['name' => 'Ran', 'aliases' => ['ran', 'ran_module']],
    'real_time_entries' => ['name' => 'Real Time Entries', 'aliases' => ['real_time_entries', 'real_time_entries_module', 'realtimeentries']],
    'repair' => ['name' => 'Repair', 'aliases' => ['repair', 'repair_module']],
    'reporting' => ['name' => 'Reporting', 'aliases' => ['reporting', 'reporting_module']],
    'reports' => ['name' => 'Reports', 'aliases' => ['reports']],
    'reports_customized' => ['name' => 'Reports Customized', 'aliases' => ['customized_report', 'customized_reports_module', 'reports_customized', 'reports_customized_module', 'reportscustomized']],
    'restaurant_new' => ['name' => 'Restaurant New', 'aliases' => ['kitchen', 'restaurant_new', 'restaurant_new_module', 'restaurantnew', 'service_staff', 'tables']],
    'sales_agent' => ['name' => 'Sales Agent', 'aliases' => ['enable_sale_cmsn_agent', 'sales_agent', 'sales_agent_module', 'salesagent']],
    'sales_discounts' => ['name' => 'Sales Discounts', 'aliases' => ['sales_discounts', 'sales_discounts_module', 'salesdiscounts']],
    'settlement_core' => ['name' => 'Settlement Core', 'aliases' => ['settlement_core', 'settlement_core_module', 'settlementcore']],
    'settlement_sw' => ['name' => 'Settlement SW', 'aliases' => ['settlement_sw', 'settlement_sw_module', 'settlementsw']],
    'shipping' => ['name' => 'Shipping', 'aliases' => ['shipping', 'shipping_module']],
    'sms' => ['name' => 'SMS', 'aliases' => ['enable_sms', 'sms', 'sms_module', 'smsmodule_module']],
    'spreadsheet' => ['name' => 'Spreadsheet', 'aliases' => ['spreadsheet', 'spreadsheet_module']],
    'stock_adjustment' => ['name' => 'Stock Adjustment', 'aliases' => ['stock_adjustment']],
    'stock_adjustment_new' => ['name' => 'Stock Adjustment New', 'aliases' => ['stock_adjustment', 'stock_adjustment_new', 'stock_adjustment_new_module', 'stockadjustmentnew']],
    'stock_reports' => ['name' => 'Stock Reports', 'aliases' => ['stock_report', 'stock_reports', 'stock_reports_module', 'stockreports']],
    'stock_taking_new' => ['name' => 'Stock Taking New', 'aliases' => ['stock_taking_new', 'stock_taking_new_module', 'stocktakingnew']],
    'stock_transfer_new' => ['name' => 'Stock Transfer New', 'aliases' => ['stock_transfer_new', 'stock_transfer_new_module', 'stock_transfers', 'stocktransfernew']],
    'stock_transfers' => ['name' => 'Stock Transfers', 'aliases' => ['stock_transfers']],
    'stocktaking' => ['name' => 'Stocktaking', 'aliases' => ['stock_taking_module', 'stock_taking_page', 'stocktaking', 'stocktaking_module']],
    'subscription' => ['name' => 'Subscription', 'aliases' => ['enable_subscription', 'subscription', 'subscription_module']],
    'superadmin' => ['name' => 'Superadmin', 'aliases' => ['superadmin', 'superadmin_module']],
    'suppliers' => ['name' => 'Suppliers', 'aliases' => ['supplier', 'suppliers', 'suppliers_module']],
    'suppliers_core' => ['name' => 'Suppliers', 'aliases' => ['suppliers', 'supplier']],
    'tailoring' => ['name' => 'Tailoring', 'aliases' => ['tailoring', 'tailoring_module']],
    'tasks_management' => ['name' => 'Tasks Management', 'aliases' => ['tasks_management', 'tasks_management_module', 'tasksmanagement']],
    'translation' => ['name' => 'Translation', 'aliases' => ['translation', 'translation_module']],
    'user_management_new' => ['name' => 'User Management New', 'aliases' => ['user_management_new', 'user_management_new_module', 'usermanagementnew']],
    'vat' => ['name' => 'Vat', 'aliases' => ['ns_vat_module', 'vat', 'vat_module', 'vat_module_main']],
    'vehicle_service' => ['name' => 'Vehicle Service', 'aliases' => ['vehicle_service', 'vehicle_service_module', 'vehicleservice']],
    'visitor' => ['name' => 'Visitor', 'aliases' => ['visitor', 'visitor_module', 'visitors_registration', 'visitors_registration_module']],
];
