<?php

/*
 | Permission ownership map - generated from resources/views/role/sections/.
 |
 | The driver uses this to protect a role when a section is NOT rendered, and
 | RolePermissionService uses it as the whitelist of application permissions a
 | Managed role may be granted. Regenerate whenever sections change.
 */

return [
    '01_common' => [
        'edit_customer_loan',
        'offline.access',
        'offline.sync.manage',
    ],
    '02_bakery_module' => [
        'bakery_login',
    ],
    '04_sales_agent_module' => [
        'sales_agent.add',
        'sales_agent.add_commission',
        'sales_agent.delete',
        'sales_agent.edit',
        'sales_agent.view',
    ],
    '05_list_sms' => [
        'sms_ledger',
    ],
    '06_bakery_module' => [
        'bakery.loading_edit',
    ],
    '07_smsmodule_module' => [
        'sms_quick_send',
    ],
    '08_common' => [
        'edit_customer_cheque_Return.edit',
        'list_customer_payments.delete',
        'list_customer_payments.edit',
    ],
    '09_vat_module' => [
        'edit.vat_statement',
        'list_vat_expense',
        'list_vat_purchase',
        'list_vat_sale',
        'vat.delete_customer_statement',
        'vat.delete_statement_payment',
        'vat_contacts',
        'vat_edit_invoice127',
        'vat_expense',
        'vat_products',
        'vat_purchase',
        'vat_sale',
    ],
    '10_pos_sale' => [
        'pos.edit_discount',
        'pos.edit_pos_tax',
        'pos.edit_shipping',
        'pos.edit_total_tax',
    ],
    '11_crm_module' => [
        'crm.access',
        'crm.access_all_campaigns',
        'crm.access_all_leads',
        'crm.access_all_schedule',
        'crm.access_contact_login',
        'crm.access_life_stage',
        'crm.access_own_campaigns',
        'crm.access_own_leads',
        'crm.access_own_schedule',
        'crm.access_proposal',
        'crm.access_resources',
        'crm.add_proposal_template',
        'crm.view_all_call_log',
        'crm.view_own_call_log',
        'crm.view_reports',
    ],
    '12_common' => [
        'deposit.access',
        'deposit.card_deposit',
        'deposit.cash_deposit',
        'deposit.cheque_deposit',
        'deposit.realize_cheque',
        'deposit.transfer',
    ],
    '13_hms_module' => [
        'hms.access',
        'hms.add_booking',
        'hms.edit_booking',
        'hms.manage_amenities',
        'hms.manage_coupon',
        'hms.manage_extra',
        'hms.manage_price',
        'hms.manage_rooms',
        'hms.manage_unavailable',
    ],
    '14_asset_module' => [
        'asset.create',
        'asset.delete',
        'asset.update',
        'asset.view',
        'asset.view_all_maintenance',
        'asset.view_own_maintenance',
    ],
    '15_shipping_module' => [
        'shipping.access',
        'shipping.helpers.delete',
        'shipping.helpers.edit',
        'shipping.shipper_tracking_no.add',
        'shipping.shipper_tracking_no.edit',
    ],
    '16_ezyinvoice_module' => [
        'ezyinvoice.access',
    ],
    '17_common' => [
        'DailyReviewAll',
        'DailyReviewOne',
        'airline.access',
        'airline.view_setting',
        'airline_edit_invoice',
        'bypass.review',
        'user.create',
        'user.delete',
        'user.update',
        'user.view',
    ],
    '18_spreadsheet' => [
        'access.spreadsheet',
        'create.folder',
        'create.spreadsheet',
        'delete.spreadsheet',
        'download.spreadsheet',
        'edit.folder',
        'edit.spreadsheet',
        'toggle.spreadsheet',
    ],
    '19_common' => [
        'roles.create',
        'roles.delete',
        'roles.update',
        'roles.view',
    ],
    '20_contact_supplier' => [
        'supplier.create',
        'supplier.delete',
        'supplier.update',
        'supplier.view',
        'supplier_pay_due',
    ],
    '21_contact_customer' => [
        'customer.create',
        'customer.delete',
        'customer.update',
        'customer.view',
        'customer_pay_due',
    ],
    '22_products' => [
        'product.create',
        'product.delete',
        'product.opening_stock',
        'product.price_section',
        'product.update',
        'product.view',
        'view_purchase_price',
    ],
    '23_purchase' => [
        'add.payments',
        'product.edit_sku',
        'purchase.create',
        'purchase.delete',
        'purchase.delete.payments',
        'purchase.edit.payments',
        'purchase.update',
        'purchase.update_status',
        'purchase.view',
        'purchase.zero',
    ],
    '24_common' => [
        'expense.add_payment',
        'expense.create',
        'expense.delete',
        'expense.update',
    ],
    '25_sale_module' => [
        'access_shipping',
        'direct_sell.access',
        'discount.access',
        'edit_product_discount_from_pos_screen',
        'edit_product_discount_from_sale_screen',
        'edit_product_price_below_purchase_price',
        'edit_product_price_from_pos_screen',
        'edit_product_price_from_sale_screen',
        'list_drafts',
        'list_quotations',
        'pos_page_return',
        'sell.create',
        'sell.delete',
        'sell.payments',
        'sell.update',
        'sell.view',
        'status_order',
        'view_own_sell_only',
    ],
    '26_brands' => [
        'brand.create',
        'brand.delete',
        'brand.update',
        'brand.view',
    ],
    '27_visitors_registration_module' => [
        'visitor.registration.create',
        'visitor.registration.delete',
        'visitor.registration.edit',
        'visitor.registration.view',
        'visitor.settings.edit',
        'visitor.settings.view',
    ],
    '28_common' => [
        'tax_rate.create',
        'tax_rate.delete',
        'tax_rate.update',
        'tax_rate.view',
    ],
    '29_products_units' => [
        'unit.create',
        'unit.delete',
        'unit.update',
        'unit.view',
    ],
    '30_products_categories' => [
        'category.create',
        'category.delete',
        'category.update',
        'category.view',
    ],
    '31_crm_module' => [
        'crm.create',
        'crm.delete',
        'crm.update',
        'crm.view',
    ],
    '32_common' => [
        'report.access',
    ],
    '33_product_report' => [
        'item_report.view',
        'product_purchase_report.view',
        'product_sell_report.view',
        'product_transaction_report.view',
        'stock_adjustment_report.view',
    ],
    '33a_stock_reports' => [
        'stock_report.view',
    ],
    '34_stock_adjustment' => [
        'stockAdjustment.add',
        'stockAdjustment.delete',
        'stockAdjustment.edit',
        'stockAdjustment.list',
    ],
    '35_payment_status_report' => [
        'aging_report.view',
        'delete_received_outstanding',
        'edit_received_outstanding',
        'outstanding_received_report.view',
        'purchase_payment_report.view',
        'sell_payment_report.view',
    ],
    '36_management_reports' => [
        'credit_status.view',
        'daily_report.view',
        'daily_summary_report.view',
        'profit_loss_report.view',
        'management_report.view',
        'management_report.generate',
        'management_report.view_saved',
        'management_report.view_delivery_history',
        'management_report.settings',
        'register_report.view',
    ],
    '37_verification_report' => [
        'comparison_report.view',
        'monthly_report.view',
    ],
    '38_activity_report' => [
        'expense_report.view',
        'purchase_and_slae_report.view',
        'sales_report.view',
        'sales_representative.view',
        'tax_report.view',
    ],
    '39_contact_report' => [
        'contact_report.view',
    ],
    '40_common' => [
        'backup',
        'backup.restore',
        'backup.upload',
        'barcode_settings.access',
        'business_settings.access',
        'expense.access',
        'invoice_settings.access',
        'payment_received.view',
        'trending_products.view',
        'user_activity.view',
    ],
    '41_unfinished_form' => [
        'unfinished_form.expense',
        'unfinished_form.pos',
        'unfinished_form.purchase',
        'unfinished_form.sale',
        'unfinished_form.stock_adjustment',
        'unfinished_form.stock_transfer',
    ],
    '42_common' => [
        'DashboardCurrentPastGraph',
        'DashboardCurrentPastPayments',
        'DashboardGlance',
        'DashboardPaymentMethods',
        'DashboardProductCategories',
        'DashboardSummaryCards',
        'dashboard.data',
    ],
    '43_payroll' => [
        'payday',
    ],
    '44_common' => [
        'account.access',
        'account.deposit_transfer.edit',
        'account.edit',
        'account.link_account',
        'account.realize_cheque',
        'account.reconcile',
        'account.settings',
        'account.settings.edit',
        'account.unreconcile',
        'delete.cheque_ob',
        'edit.cheque_ob',
    ],
    '45_deposits_module' => [
        'deposit.access',
        'deposit.card_deposit',
        'deposit.cash_deposit',
        'deposit.cheque_deposit',
        'deposit.realize_cheque',
        'deposit.transfer',
    ],
    '46_contact_module' => [
        'contact.delete_customer_statement',
        'contact.delete_statement_payment',
        'edit_customer_statement',
        'enable_separate_customer_statement_no',
    ],
    '47_edit_received_outstanding' => [
        'add_received_outstanding',
    ],
    '47_products_new' => [
        'products_new.access',
        'products_new.availability.view',
        'products_new.barcode.templates',
        'products_new.barcode_center',
        'products_new.batch.adjust',
        'products_new.batch.create',
        'products_new.batch.view',
        'products_new.command_center.actions',
        'products_new.command_center.snapshot',
        'products_new.command_center.view',
        'products_new.create',
        'products_new.dashboard',
        'products_new.dashboard.management',
        'products_new.data_cleanup.manage',
        'products_new.data_cleanup.view',
        'products_new.delete',
        'products_new.deployment_readiness',
        'products_new.duplicates.manage',
        'products_new.expiry.resolve',
        'products_new.expiry.view',
        'products_new.import_export',
        'products_new.import_export.export',
        'products_new.import_export.import',
        'products_new.import_export.view',
        'products_new.integration_bridge.api',
        'products_new.integration_bridge.view',
        'products_new.intelligence.view',
        'products_new.inventory.create',
        'products_new.inventory.view',
        'products_new.inventory_intelligence.abc_xyz',
        'products_new.inventory_intelligence.cost_analysis',
        'products_new.inventory_intelligence.executive',
        'products_new.inventory_intelligence.planning',
        'products_new.inventory_intelligence.reorder_proposals',
        'products_new.inventory_intelligence.stock_intelligence',
        'products_new.inventory_intelligence.view',
        'products_new.kpi.index',
        'products_new.kpi.snapshot',
        'products_new.legacy_comparison.view',
        'products_new.media.create',
        'products_new.media.view',
        'products_new.migration_readiness.view',
        'products_new.notes.manage',
        'products_new.opening_stock.create',
        'products_new.opening_stock.view',
        'products_new.ownership.view',
        'products_new.price_center.create',
        'products_new.price_center.view',
        'products_new.production_audit.view',
        'products_new.products.create',
        'products_new.products.disable',
        'products_new.products.update',
        'products_new.products.view',
        'products_new.purchase_price.view',
        'products_new.recall.close',
        'products_new.recall.create',
        'products_new.recall.view',
        'products_new.relationships.manage',
        'products_new.reports',
        'products_new.reports.abc_xyz',
        'products_new.reports.aging',
        'products_new.reports.batch',
        'products_new.reports.category_brand',
        'products_new.reports.expiry',
        'products_new.reports.fast_slow_dead',
        'products_new.reports.index',
        'products_new.reports.inventory_turnover',
        'products_new.reports.low_stock',
        'products_new.reports.movement',
        'products_new.reports.negative_overstock',
        'products_new.reports.price_changes',
        'products_new.reports.price_history',
        'products_new.reports.product_master',
        'products_new.reports.profitability',
        'products_new.reports.reorder_recommendation',
        'products_new.reports.serial',
        'products_new.reports.stock_valuation',
        'products_new.serial.create',
        'products_new.serial.view',
        'products_new.settings',
        'products_new.settings.brands.create',
        'products_new.settings.brands.view',
        'products_new.settings.categories.create',
        'products_new.settings.categories.delete',
        'products_new.settings.categories.update',
        'products_new.settings.categories.view',
        'products_new.settings.units.create',
        'products_new.settings.units.view',
        'products_new.settings.variations.create',
        'products_new.settings.variations.view',
        'products_new.stock_center',
        'products_new.stock_history',
        'products_new.testing_checklist.view',
        'products_new.update',
        'products_new.view',
        'products_new.warranty.manage',
        'products_new.warranty.view',
        'products_new.workflow.manage',
    ],
    '48_common' => [
        'customer_reference.edit',
    ],
    '48_customers_module' => [
        'customers.access',
        'customers.activity',
        'customers.advance_payment',
        'customers.approve',
        'customers.audit',
        'customers.balance',
        'customers.cheque_return',
        'customers.create',
        'customers.credit',
        'customers.dashboard',
        'customers.delete',
        'customers.deposit',
        'customers.documents',
        'customers.edit',
        'customers.export',
        'customers.notes',
        'customers.payment',
        'customers.portal',
        'customers.portal.login',
        'customers.refund',
        'customers.reports',
        'customers.settings',
        'customers.update',
        'customers.view',
        'customers.workflow',
    ],
    '49_mpcs_module' => [
        'edit_f17_form',
        'edit_f22_stock_Taking_form',
        'f10_form',
        'f10_form_cash_given_button',
        'f10_form_cash_received_button',
        'f14b_form',
        'f15a9abc_form',
        'f16a_form',
        'f17_form',
        'f20_form',
        'f21_form',
        'f21c_form',
        'f22_authorized_signature_form',
        'f22_stock_taking_form',
        'f9c_form',
        'list_opening_values',
        'mpcs.access',
        'mpcs_form_settings',
        'signature_approve',
        'stock_taking_approve',
    ],
    '49_suppliers_module' => [
        'suppliers.accounts.manage',
        'suppliers.contacts.manage',
        'suppliers.create',
        'suppliers.delete',
        'suppliers.documents.manage',
        'suppliers.edit',
        'suppliers.profile.view',
        'suppliers.purchase_history.view',
        'suppliers.reports.view',
        'suppliers.view',
    ],
    '50_price_changes_module' => [
        'pricechanges.access',
    ],
    '50_purchase_module' => [
        'purchase.entry.create',
        'purchase.entry.delete',
        'purchase.entry.edit',
        'purchase.entry.print',
        'purchase.entry.view',
        'purchase.return.create',
        'purchase.return.delete',
        'purchase.return.edit',
        'purchase.return.view',
    ],
    '51_fleet_module' => [
        'edit.fleet_opening_balance',
        'edit_fleet',
        'edit_fuel_type',
        'fleet.access',
        'fleet.add_actual_meter',
        'fleet.drivers.delete',
        'fleet.drivers.edit',
        'fleet.edit_trip_category',
        'fleet.helpers.delete',
        'fleet.helpers.edit',
        'fleet.routes.delete',
        'fleet.routes.edit',
        'fuel_management',
        'list_trip_operations',
    ],
    '52_ran_module' => [
        'ran.access',
    ],
    '53_catalogue_qr' => [
        'catalogue.access',
    ],
    '54_repair_module' => [
        'repair.access',
    ],
    '55_auto_services_and_repair_module' => [
        'auto_services_and_repair_module.access',
        'auto_services_and_repair_module.job_sheet.edit',
    ],
    '56_enable_petro_module' => [
        'add_day_end_settlement',
        'add_dip_resetting',
        'bulk_assign_pumps',
        'daily_card.edit',
        'daily_collection.delete',
        'daily_collection.edit',
        'daily_pump_status.delete',
        'daily_pump_status.edit',
        'daily_shortage.edit',
        'dipmanagement.add_dip_chart',
        'dipmanagement.delete',
        'dipmanagement.delete_dip_chart',
        'dipmanagement.edit',
        'dipmanagement.edit_dip_chart',
        'edit_day_end_settlement',
        'edit_other_income_prices',
        'edit_pumper_opening_balance',
        'fuel_tank.edit',
        'manual_discount',
        'meter_resetting_tab',
        'petro.access',
        'petro_sms_notifications',
        'pum_operator.active_inactive',
        'pump_operator.access_code',
        'pump_operator.dashboard',
        'pump_operator.main_system',
        'pumper_dashboard.close_pump',
        'pumper_dashboard.close_shift',
        'pumper_dashboard.current_meter',
        'pumper_dashboard.dashboard',
        'pumper_dashboard.day_entries',
        'pumper_dashboard.list_other_sales',
        'pumper_dashboard.meters_with_payments',
        'pumper_dashboard.other_sales',
        'pumper_dashboard.payment_summary',
        'pumper_dashboard.payments',
        'pumper_dashboard.receive_pump',
        'pumper_dashboard.unload_stock',
        'pumper_dashboard.unload_stock_details',
        'pumper_dashboard_settings',
        'reset_dip',
        'settlement.delete',
        'settlement.edit',
    ],
    '57_petro_pd_module' => [
        // S678: also grantable from the Petro PD section, so a PD business
        // can assign pumps without enable_petro_module being switched on.
        'bulk_assign_pumps',
        'petro_pd.access',
        'petro_pd.create_settlement',
        'petro_pd.customer_payment_tab',
        'petro_pd.delete_settlement',
        'petro_pd.edit_settlement',
        'petro_pd.list_settlement',
        'petro_pd.manual_entry',
        'petro_pd.meter_sale_tab',
        'petro_pd.other_income_tab',
        'petro_pd.other_sale_tab',
        'petro_pd.payment_tab',
        'petro_pd.view_operators',
        'petro_pd.view_report',
        'petro_pd_blocked_pump_operators.delete',
        'petro_pd_blocked_pump_operators.edit',
        'petro_pd_daily_collection.delete',
        'petro_pd_daily_collection.edit',
        'petro_pd_daily_collection_sw.delete',
        'petro_pd_daily_collection_sw.edit',
        'petro_pd_day_end_settlement.delete',
        'petro_pd_day_end_settlement.edit',
        'petro_pd_dip_management.delete',
        'petro_pd_dip_management.edit',
        'petro_pd_meter_reading.delete',
        'petro_pd_meter_reading.edit',
        'petro_pd_meter_resetting.delete',
        'petro_pd_meter_resetting.edit',
        'petro_pd_petro_activity_report.delete',
        'petro_pd_petro_activity_report.edit',
        'petro_pd_pump_management.delete',
        'petro_pd_pump_management.edit',
        'petro_pd_pumper_management.delete',
        'petro_pd_pumper_management.edit',
        'petro_pd_settlement.delete',
        'petro_pd_settlement.edit',
        'petro_pd_sms_notifications',
        'petro_pd_tank_transfer.delete',
        'petro_pd_tank_transfer.edit',
        'petro_pd_tanks_transaction_details.delete',
        'petro_pd_tanks_transaction_details.edit',
        'petro_pd_tanks_transaction_summary.delete',
        'petro_pd_tanks_transaction_summary.edit',
        'petro_pd_whatsapp',
    ],
    '59_finance_reports_module' => [
        'finance_reports.view',
    ],
    '60_chequer_module' => [
        'chequer.access',
    ],
    '61_issue_customer_bill' => [
        'issue_customer_bill.access',
        'issue_customer_bill.add',
        'issue_customer_bill.view',
    ],
    '62_customer_settings' => [
        'approve_sell_over_limit',
        'customer_settings.access',
    ],
    '63_tasks_management' => [
        'tasks_management.access',
        'tasks_management.reminder',
        'tasks_management.tasks',
    ],
    '64_member_registration' => [
        'add_remarks',
        'member_registration.access',
        'update_status_of_issue',
    ],
    '65_leads_module' => [
        'day_count',
        'leads.create',
        'leads.delete',
        'leads.edit',
        'leads.import',
        'leads.settings',
        'leads.view',
    ],
    '66_property_module' => [
        'dashboard.change',
        'list_easy_payments.access',
        'property.add_new_sale',
        'property.approve_commission',
        'property.current_sale.close.create',
        'property.current_sale.close.edit',
        'property.current_sale.edit',
        'property.current_sale.view',
        'property.customer.create',
        'property.customer.delete',
        'property.customer.edit',
        'property.customer.view',
        'property.list.create',
        'property.list.delete',
        'property.list.edit',
        'property.list.view',
        'property.project_dashboard.customer_payments',
        'property.project_dashboard.sell_land_blocks',
        'property.purchase.create',
        'property.purchase.delete',
        'property.purchase.edit',
        'property.purchase.view',
        'property.settings.access',
        'property.settings.tax',
        'property.settings.unit',
        'property.update_commission_status',
        'property.update_sale_commission',
        'property_account_settings.edit',
        'property_finalize.edit',
        'property_penalty.delete',
    ],
    '67_sms_module' => [
        'sms.access',
        'sms.list',
    ],
    '68_enable_cheque_writing' => [
        'enable_cheque_add_new_template',
        'enable_cheque_default_settings',
        'enable_cheque_delete_numbers',
        'enable_cheque_manage_payee',
        'enable_cheque_manage_stamps',
        'enable_cheque_number_list',
        'enable_cheque_printed_details',
        'enable_cheque_templates',
        'enable_cheque_writing',
    ],
    '69_service_staff' => [
        'crud_all_bookings',
        'crud_own_bookings',
    ],
    '70_access_selling_price' => [
        'access_default_selling_price',
    ],
    '71_set_minimum_price' => [
        'product.set_min_sell_price',
    ],
    '72_view_sales_commission' => [
        'sales-commission-agents.create',
    ],
    '73_essentials_module' => [
        'add_essentials_leave_type',
        'edit_essentials_settings',
        'essentials.access_sales_target',
        'essentials.add_allowance_and_deduction',
        'essentials.add_todos',
        'essentials.allow_users_for_attendance_from_web',
        'essentials.approve_leave',
        'essentials.assign_todos',
        'essentials.create_message',
        'essentials.create_payroll',
        'essentials.crud_all_attendance',
        'essentials.crud_all_leave',
        'essentials.crud_department',
        'essentials.crud_designation',
        'essentials.crud_leave_type',
        'essentials.crud_own_leave',
        'essentials.delete_payroll',
        'essentials.delete_todos',
        'essentials.edit_todos',
        'essentials.update_payroll',
        'essentials.view_all_payroll',
        'essentials.view_allowance_and_deduction',
        'essentials.view_message',
        'essentials.view_own_attendance',
    ],
    '74_day_end_module' => [
        'day_end.bypass',
        'day_end.view',
    ],
    '75_upload_images' => [
        'upload_images',
    ],
    '76_sms_enable' => [
        'sms.view',
    ],
    '77_enable_restaurant' => [
        'restaurant.access',
    ],
    '78_cache_clear' => [
        'cache_clear',
    ],
    '80_customized_reports_module' => [
        'cr.add_lioc_statement',
        'cr.edit_lioc_statement',
        'cr.list_lioc_statements',
        'cr.prefix_numbers',
    ],
];
