<?php
namespace Modules\Ran\Services;
use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Str;use Modules\Ran\Entities\{DocumentShare,DocumentTemplate,Purchase,ProductionOrder,Sale,Transfer};use Modules\Ran\Support\RanContext;use RuntimeException;
class DocumentService{
 private array $models=['sale'=>Sale::class,'purchase'=>Purchase::class,'production_order'=>ProductionOrder::class,'stock_transfer'=>Transfer::class];
 public function find(string $type,int $id):Model{$class=$this->models[$type]??null;if(!$class)throw new RuntimeException('Unsupported Ran document type.');$relations=match($type){'sale'=>['lines.item','lines.stockLot','payments','customer'],'purchase'=>['lines.item','payments','supplier'],'production_order'=>['lines.item','artisan','materialIssues.lines.item','receipts.lines.item'],'stock_transfer'=>['lines.item','lines.stockLot'],default=>[]};return $class::query()->with($relations)->findOrFail($id);}
 public function template(string $type,?int $templateId=null,?int $businessId=null):DocumentTemplate{$q=$businessId?DocumentTemplate::withoutGlobalScopes()->where('business_id',$businessId):DocumentTemplate::query();$q->with('sections')->where('document_type',$type)->where('is_active',1);return $templateId?$q->findOrFail($templateId):($q->where('is_default',1)->first()?:$q->firstOrFail());}
 public function allowedSections(DocumentTemplate $template,string $channel):array{$flag='allow_'.$channel;return $template->sections->filter(fn($s)=>(bool)$s->{$flag})->pluck('section_key')->all();}
 public function selectedSections(DocumentTemplate $template,string $channel,array $selected):array{$allowed=$this->allowedSections($template,$channel);$selected=$selected?:$template->sections->where('enabled_by_default',true)->pluck('section_key')->all();return array_values(array_intersect($allowed,$selected));}
 public function share(string $type,int $id,string $channel,array $sections):DocumentShare{$document=$this->find($type,$id);return DocumentShare::create(['business_id'=>RanContext::businessId(),'location_id'=>$document->location_id??RanContext::locationId(),'store_id'=>$document->store_id??RanContext::storeId(),'token'=>Str::random(64),'document_type'=>$type,'document_id'=>$id,'channel'=>$channel,'selected_sections'=>$sections,'expires_at'=>now()->addDays((int)config('ran.share_link_expiry_days',30)),'is_active'=>1]);}
 public function publicUrl(DocumentShare $share):string{return route('ran.public.share',$share->token);}
 public function title(string $type,Model $document):string{return match($type){'sale'=>'Ran Invoice '.$document->invoice_no,'purchase'=>'Ran Purchase '.$document->purchase_no,'production_order'=>'Ran Production Order '.$document->order_no,'stock_transfer'=>'Ran Stock Transfer '.$document->transfer_no,default=>'Ran Document'};}
 public function number(string $type,Model $document):string{return match($type){'sale'=>$document->invoice_no,'purchase'=>$document->purchase_no,'production_order'=>$document->order_no,'stock_transfer'=>$document->transfer_no,default=>(string)$document->id};}
 public function recipient(string $type,Model $document,string $channel):?string{return match($type){'sale'=>$channel==='email'?($document->customer_email?:$document->customer?->email):($document->customer_mobile?:$document->customer?->mobile),'purchase'=>$channel==='email'?$document->supplier?->email:$document->supplier?->mobile,'production_order'=>$channel==='email'?$document->artisan?->email:$document->artisan?->phone,default=>null};}
 public function indexDocuments():array{return ['sales'=>Sale::query()->latest('invoice_date')->limit(20)->get(),'purchases'=>Purchase::query()->latest('purchase_date')->limit(20)->get(),'production'=>ProductionOrder::query()->latest('order_date')->limit(20)->get(),'transfers'=>Transfer::query()->latest('transfer_date')->limit(20)->get()];}
}
