<?php
namespace Modules\Ran\Services;
use DomainException;
use Illuminate\Support\Facades\DB;
use Modules\Ran\Entities\StockLot;
use Modules\Ran\Entities\StockMovement;
use Modules\Ran\Support\RanContext;
class InventoryService {
 public function __construct(private NumberSequenceService $numbers,private AuditService $audit){}
 public function receive(array $data):StockLot{return DB::transaction(function()use($data){$quantity=(float)($data['quantity']??0);$net=(float)($data['net_weight']??0);if($quantity<=0&&$net<=0)throw new DomainException('Quantity or net weight must be greater than zero.');$unit=(float)($data['unit_cost']??0);$lot=StockLot::create(array_merge(RanContext::scope(['location_id'=>(int)$data['location_id'],'store_id'=>(int)$data['store_id']]),['lot_no'=>$data['lot_no']??$this->numbers->next('stock_lot',(int)$data['location_id']),'item_id'=>(int)$data['item_id'],'serial_no'=>$data['serial_no']??null,'rfid_tag'=>$data['rfid_tag']??null,'quantity'=>$quantity,'gross_weight'=>(float)($data['gross_weight']??$net),'net_weight'=>$net,'stone_weight'=>(float)($data['stone_weight']??0),'fine_weight'=>(float)($data['fine_weight']??0),'unit_cost'=>$unit,'total_cost'=>(float)($data['total_cost']??($unit*max($quantity,1))),'sale_price'=>(float)($data['sale_price']??0),'stock_status'=>'available','source_type'=>$data['source_type']??'manual_receipt','source_id'=>$data['source_id']??null,'received_on'=>$data['received_on']??now()->toDateString(),'bin_location'=>$data['bin_location']??null,'notes'=>$data['notes']??null]));$this->movement($lot,'receipt',$quantity,0,$net,0,$data);$this->audit->record('stock_received',$lot);return $lot;});}
 public function issue(StockLot $lot,float $quantity,float $weight,array $reference=[]):StockMovement{return DB::transaction(function()use($lot,$quantity,$weight,$reference){if($quantity<0||$weight<0)throw new DomainException('Issue values cannot be negative.');$locked=StockLot::query()->lockForUpdate()->findOrFail($lot->id);if(!config('ran.allow_negative_stock',false)){if((float)$locked->quantity+0.000001<$quantity)throw new DomainException("Insufficient quantity in lot {$locked->lot_no}.");if((float)$locked->net_weight+0.000001<$weight)throw new DomainException("Insufficient weight in lot {$locked->lot_no}.");}$openingQuantity=(float)$locked->quantity;$openingCost=(float)$locked->total_cost;$issuedCost=$openingQuantity>0?min($openingCost,$openingCost*($quantity/$openingQuantity)):0;$locked->quantity=$openingQuantity-$quantity;$locked->net_weight=(float)$locked->net_weight-$weight;$locked->gross_weight=max(0,(float)$locked->gross_weight-$weight);$locked->total_cost=max(0,$openingCost-$issuedCost);if((float)$locked->quantity<=0.000001&&(float)$locked->net_weight<=0.000001)$locked->stock_status='consumed';$locked->save();$movement=$this->movement($locked,'issue',0,$quantity,0,$weight,$reference);$this->audit->record('stock_issued',$locked);return $movement;});}
 public function adjust(StockLot $lot,float $quantityVariance,float $weightVariance,string $reason):StockMovement{return DB::transaction(function()use($lot,$quantityVariance,$weightVariance,$reason){$locked=StockLot::query()->lockForUpdate()->findOrFail($lot->id);$newQty=(float)$locked->quantity+$quantityVariance;$newWeight=(float)$locked->net_weight+$weightVariance;if(!config('ran.allow_negative_stock',false)&&($newQty<0||$newWeight<0))throw new DomainException('Adjustment would create negative stock.');$locked->quantity=$newQty;$locked->net_weight=$newWeight;$locked->gross_weight=max(0,(float)$locked->gross_weight+$weightVariance);$locked->stock_status=($newQty<=0.000001&&$newWeight<=0.000001)?'consumed':'available';$locked->save();$movement=$this->movement($locked,'adjustment',max(0,$quantityVariance),max(0,-$quantityVariance),max(0,$weightVariance),max(0,-$weightVariance),['reference_type'=>'adjustment','description'=>$reason]);$this->audit->record('stock_adjusted',$locked);return $movement;});}
 private function movement(StockLot $lot,string $type,float $qin,float $qout,float $win,float $wout,array $ref):StockMovement{return StockMovement::create(array_merge(RanContext::scope(['location_id'=>$lot->location_id,'store_id'=>$lot->store_id]),['movement_at'=>now(),'movement_type'=>$type,'item_id'=>$lot->item_id,'stock_lot_id'=>$lot->id,'quantity_in'=>$qin,'quantity_out'=>$qout,'weight_in'=>$win,'weight_out'=>$wout,'unit_cost'=>$lot->unit_cost,'reference_type'=>$ref['reference_type']??$ref['source_type']??null,'reference_id'=>$ref['reference_id']??$ref['source_id']??null,'reference_no'=>$ref['reference_no']??$lot->lot_no,'description'=>$ref['description']??null]));}
}
