<div class="pdn-section-title pdn-operator-heading"><div><h2><i class="fa fa-thermometer-half"></i> Current Meter</h2><small class="text-muted">Latest pump readings and controlled tank transfers.</small></div><div class="pdn-heading-actions"><button type="button" class="btn btn-primary" data-pdn-open-modal="pdn-meter-modal"><i class="fa fa-plus"></i> Record Current Meter</button><button type="button" class="btn btn-info" data-pdn-open-modal="pdn-transfer-modal"><i class="fa fa-exchange"></i> Tank Transfer</button></div></div>
<div class="pdn-card pdn-compact-card pdn-scroll"><table class="table table-bordered table-striped mb-0"><thead><tr><th>Pump No.</th><th>Pump</th><th class="text-right">Current Meter</th><th>Last Reading Type</th><th>Last Recorded</th><th>Status</th></tr></thead><tbody>@forelse($currentMeters as $row)<tr><td>{{ $row->pump_no }}</td><td>{{ $row->pump_name }}</td><td class="pdn-money">{{ number_format($row->current_meter,3) }}</td><td>{{ $row->last_reading_type ? ucwords($row->last_reading_type) : '—' }}</td><td>{{ $row->last_recorded_at ? \Carbon\Carbon::parse($row->last_recorded_at)->format('d/m/Y H:i') : '—' }}</td><td><span class="pdn-status">{{ $row->status }}</span></td></tr>@empty<tr><td colspan="6" class="pdn-table-empty">No pumps configured.</td></tr>@endforelse</tbody></table></div>
<div class="pdn-modal" id="pdn-meter-modal" aria-hidden="true"><div class="pdn-modal-backdrop" data-pdn-close-modal></div><div class="pdn-modal-dialog pdn-modal-lg"><div class="pdn-modal-header"><h3><i class="fa fa-thermometer-half"></i> Record Current Meter</h3><button type="button" class="pdn-modal-close" data-pdn-close-modal>&times;</button></div><form method="post" action="{{ route('petro-direct-new.pumper-management.meters.store') }}" data-pdn-ajax-form>@csrf<div class="pdn-modal-body"><div class="alert alert-danger pdn-form-errors" hidden></div><div class="pdn-form-grid">
<div><label>Location *</label><select class="form-control" name="location_id" required>@foreach($locations as $loc)<option value="{{ $loc->id }}" @selected((int)$locationId === (int)$loc->id)>{{ $loc->name ?? $loc->id }}</option>@endforeach</select></div>
<div><label>Pump *</label><select class="form-control select2" name="pump_id" required>@foreach($pumps as $pump)<option value="{{ $pump->id }}">{{ $pump->pump_no }} - {{ $pump->name }} ({{ number_format($pump->current_meter,3) }})</option>@endforeach</select></div>
<div><label>Shift</label><select class="form-control select2" name="shift_id"><option value="">None</option>@foreach($openShifts as $shift)<option value="{{ $shift->id }}">{{ $shift->shift_no }}</option>@endforeach</select></div>
<div><label>Operator</label><select class="form-control select2" name="operator_id"><option value="">None</option>@foreach($operators as $operator)<option value="{{ $operator->id }}">{{ $operator->operator_no }} - {{ $operator->name }}</option>@endforeach</select></div>
<div><label>Reading Type</label><select class="form-control" name="reading_type"><option value="current">Current</option><option value="testing">Testing</option><option value="closing">Closing</option></select></div><div><label>Meter Reading *</label><input type="number" step="0.001" min="0" class="form-control" name="reading" required></div><div><label>Testing Qty</label><input type="number" step="0.001" min="0" class="form-control" name="testing_qty" value="0"></div>
</div></div><div class="pdn-modal-footer"><button type="button" class="btn btn-default" data-pdn-close-modal>Close</button><button class="btn btn-primary" type="submit">Save Meter</button></div></form></div></div>
<div class="pdn-modal" id="pdn-transfer-modal" aria-hidden="true"><div class="pdn-modal-backdrop" data-pdn-close-modal></div><div class="pdn-modal-dialog"><div class="pdn-modal-header"><h3><i class="fa fa-exchange"></i> Tank Transfer</h3><button type="button" class="pdn-modal-close" data-pdn-close-modal>&times;</button></div><form method="post" action="{{ route('petro-direct-new.pumper-management.transfers.store') }}" data-pdn-ajax-form>@csrf<div class="pdn-modal-body"><div class="alert alert-danger pdn-form-errors" hidden></div><div class="pdn-form-grid pdn-form-grid-2">
<div><label>From Tank *</label><select class="form-control select2" name="from_tank_id" required>@foreach($tanks as $tank)<option value="{{ $tank->id }}">{{ $tank->tank_no }} - {{ $tank->name }} ({{ number_format($tank->current_stock,3) }})</option>@endforeach</select></div><div><label>To Tank *</label><select class="form-control select2" name="to_tank_id" required>@foreach($tanks as $tank)<option value="{{ $tank->id }}">{{ $tank->tank_no }} - {{ $tank->name }}</option>@endforeach</select></div><div><label>Quantity *</label><input type="number" step="0.001" min="0.001" class="form-control" name="quantity" required></div><div><label>Date *</label><input type="date" class="form-control" name="transfer_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="pdn-span-2"><label>Note</label><input class="form-control" name="note"></div>
</div></div><div class="pdn-modal-footer"><button type="button" class="btn btn-default" data-pdn-close-modal>Close</button><button class="btn btn-primary" type="submit">Transfer Stock</button></div></form></div></div>
