<div class="pdn-section-title pdn-operator-heading"><div><h2><i class="fa fa-calculator"></i> Pumper Day Entries</h2><small class="text-muted">Daily operational entries linked to the operator and shift.</small></div><button type="button" class="btn btn-primary" data-pdn-open-modal="pdn-day-entry-modal"><i class="fa fa-plus"></i> Add Pumper Day Entry</button></div>
<div class="pdn-card pdn-compact-card pdn-scroll"><table class="table table-bordered table-striped mb-0"><thead><tr><th>Date</th><th>Operator</th><th>Shift</th><th>Type</th><th>Reference</th><th class="text-right">Quantity</th><th class="text-right">Amount</th><th>Note</th></tr></thead><tbody>@forelse($pumperDayEntries as $row)<tr><td>{{ optional($row->entry_date)->format('d/m/Y') }}</td><td>{{ optional($row->operator)->name ?: '—' }}</td><td>{{ optional($row->shift)->shift_no ?: '—' }}</td><td>{{ ucwords(str_replace('_',' ',$row->entry_type)) }}</td><td>{{ $row->reference_no ?: '—' }}</td><td class="pdn-money">{{ number_format($row->quantity,3) }}</td><td class="pdn-money">{{ number_format($row->amount,4) }}</td><td>{{ $row->note }}</td></tr>@empty<tr><td colspan="8" class="pdn-table-empty">No pumper day entries.</td></tr>@endforelse</tbody></table></div>
<div class="pdn-modal" id="pdn-day-entry-modal" aria-hidden="true"><div class="pdn-modal-backdrop" data-pdn-close-modal></div><div class="pdn-modal-dialog pdn-modal-lg" role="dialog" aria-modal="true"><div class="pdn-modal-header"><h3><i class="fa fa-calculator"></i> Add Pumper Day Entry</h3><button type="button" class="pdn-modal-close" data-pdn-close-modal>&times;</button></div><form method="post" action="{{ route('petro-direct-new.pumper-management.day-entries.store') }}" data-pdn-ajax-form>@csrf<div class="pdn-modal-body"><div class="alert alert-danger pdn-form-errors" hidden></div><div class="pdn-form-grid">
<div><label>Location *</label><select class="form-control" name="location_id" required>@foreach($locations as $loc)<option value="{{ $loc->id }}" @selected((int)$locationId === (int)$loc->id)>{{ $loc->name ?? $loc->id }}</option>@endforeach</select></div>
<div><label>Operator *</label><select class="form-control select2" name="operator_id" required>@foreach($operators as $operator)<option value="{{ $operator->id }}">{{ $operator->operator_no }} - {{ $operator->name }}</option>@endforeach</select></div>
<div><label>Shift</label><select class="form-control select2" name="shift_id"><option value="">None</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->shift_no }}</option>@endforeach</select></div>
<div><label>Date *</label><input type="date" class="form-control" name="entry_date" value="{{ now()->format('Y-m-d') }}" required></div>
<div><label>Entry Type *</label><select class="form-control" name="entry_type"><option value="general">General</option><option value="expense">Expense</option><option value="loan">Loan</option><option value="drawing">Owner Drawing</option><option value="deposit">Cash Deposit</option></select></div>
<div><label>Reference No.</label><input class="form-control" name="reference_no"></div><div><label>Amount</label><input type="number" step="0.0001" min="0" class="form-control" name="amount"></div><div><label>Quantity</label><input type="number" step="0.001" min="0" class="form-control" name="quantity"></div><div class="pdn-span-4"><label>Note</label><textarea class="form-control" name="note"></textarea></div>
</div></div><div class="pdn-modal-footer"><button type="button" class="btn btn-default" data-pdn-close-modal>Close</button><button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save Day Entry</button></div></form></div></div>
