-- Petro PD-New 1.0.0
-- Standalone tenant schema. Safe to run repeatedly.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `pdnew_settlements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `business_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NULL,
  `source_import_id` BIGINT UNSIGNED NOT NULL,
  `pone_shift_id` BIGINT UNSIGNED NOT NULL,
  `pone_shift_number` VARCHAR(80) NOT NULL,
  `pone_operator_profile_id` BIGINT UNSIGNED NOT NULL,
  `pone_pd_operator_id` INT UNSIGNED NOT NULL,
  `operator_name` VARCHAR(191) NOT NULL,
  `settlement_number` VARCHAR(80) NOT NULL,
  `settlement_date` DATE NOT NULL,
  `source_closed_at` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'draft',
  `source_hash` CHAR(64) NOT NULL,
  `meter_sales_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `other_sales_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `source_payments_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `manual_payments_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `source_declared_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `source_shortage_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `source_excess_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `manual_shortage_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `manual_excess_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `shortage_recovery_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `excess_commission_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `adjustments_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `expected_adjustments_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `received_adjustments_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `expected_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `received_total` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `operational_variance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `variance_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `reconciliation_status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `notes` TEXT NULL,
  `submitted_at` TIMESTAMP NULL DEFAULT NULL,
  `submitted_by` INT UNSIGNED NULL,
  `reviewed_at` TIMESTAMP NULL DEFAULT NULL,
  `reviewed_by` INT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL DEFAULT NULL,
  `approved_by` INT UNSIGNED NULL,
  `finalized_at` TIMESTAMP NULL DEFAULT NULL,
  `finalized_by` INT UNSIGNED NULL,
  `cancelled_at` TIMESTAMP NULL DEFAULT NULL,
  `cancelled_by` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_settlement_uuid_uq` (`uuid`),
  UNIQUE KEY `pdnew_settlement_number_uq` (`business_id`,`settlement_number`),
  UNIQUE KEY `pdnew_settlement_shift_uq` (`business_id`,`pone_shift_id`),
  KEY `pdnew_settlement_status_idx` (`business_id`,`location_id`,`status`,`settlement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_sources` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_shift_id` BIGINT UNSIGNED NOT NULL,
  `pone_shift_number` VARCHAR(80) NOT NULL,
  `source_hash` CHAR(64) NOT NULL,
  `source_closed_at` TIMESTAMP NULL DEFAULT NULL,
  `source_totals` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_settlement_source_uq` (`settlement_id`,`pone_shift_id`),
  KEY `pdnew_source_business_idx` (`business_id`,`pone_shift_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_pumps` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_assignment_id` BIGINT UNSIGNED NOT NULL,
  `pump_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `opening_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `closing_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `testing_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `sold_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_settlement_assignment_uq` (`settlement_id`,`pone_assignment_id`),
  KEY `pdnew_settlement_pump_idx` (`business_id`,`pump_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_meter_sales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_assignment_id` BIGINT UNSIGNED NOT NULL,
  `pone_meter_reading_id` BIGINT UNSIGNED NULL,
  `pump_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `reading_at` TIMESTAMP NULL DEFAULT NULL,
  `opening_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `closing_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `testing_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `sold_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_meter_assignment_uq` (`settlement_id`,`pone_assignment_id`),
  KEY `pdnew_meter_business_idx` (`business_id`,`pump_id`,`reading_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_payment_id` BIGINT UNSIGNED NULL,
  `payment_number` VARCHAR(80) NOT NULL,
  `payment_type` VARCHAR(40) NOT NULL,
  `gross_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `customer_id` INT UNSIGNED NULL,
  `reference_no` VARCHAR(191) NULL,
  `transaction_at` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `is_source` TINYINT(1) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  `metadata` LONGTEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `voided_by` INT UNSIGNED NULL,
  `voided_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_payment_uuid_uq` (`uuid`),
  UNIQUE KEY `pdnew_source_payment_uq` (`settlement_id`,`pone_payment_id`),
  KEY `pdnew_payment_type_idx` (`business_id`,`settlement_id`,`payment_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_payment_details` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `payment_id` BIGINT UNSIGNED NOT NULL,
  `detail_type` VARCHAR(40) NOT NULL,
  `reference_no` VARCHAR(191) NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `detail` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pdnew_payment_detail_idx` (`payment_id`,`detail_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_credit_sales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_credit_sale_id` BIGINT UNSIGNED NOT NULL,
  `pone_payment_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NULL,
  `order_number` VARCHAR(191) NULL,
  `bill_number` VARCHAR(191) NULL,
  `vehicle_number` VARCHAR(191) NULL,
  `customer_reference` VARCHAR(191) NULL,
  `order_date` DATE NULL,
  `due_date` DATE NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `metadata` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_credit_source_uq` (`settlement_id`,`pone_credit_sale_id`),
  KEY `pdnew_credit_customer_idx` (`business_id`,`customer_id`,`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_credit_sale_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `credit_sale_id` BIGINT UNSIGNED NOT NULL,
  `pone_credit_sale_line_id` BIGINT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_credit_line_source_uq` (`credit_sale_id`,`pone_credit_sale_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_other_sales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_other_sale_id` BIGINT UNSIGNED NOT NULL,
  `sale_number` VARCHAR(80) NOT NULL,
  `store_id` INT UNSIGNED NULL,
  `sale_at` TIMESTAMP NULL DEFAULT NULL,
  `gross_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `net_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_other_sale_source_uq` (`settlement_id`,`pone_other_sale_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_other_sale_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `other_sale_id` BIGINT UNSIGNED NOT NULL,
  `pone_other_sale_line_id` BIGINT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_other_line_source_uq` (`other_sale_id`,`pone_other_sale_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_unload_stocks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_unload_stock_id` BIGINT UNSIGNED NOT NULL,
  `receipt_number` VARCHAR(80) NOT NULL,
  `bill_number` VARCHAR(191) NULL,
  `store_id` INT UNSIGNED NULL,
  `unloaded_at` TIMESTAMP NULL DEFAULT NULL,
  `total_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_unload_source_uq` (`settlement_id`,`pone_unload_stock_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_unload_stock_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `unload_stock_id` BIGINT UNSIGNED NOT NULL,
  `pone_unload_stock_line_id` BIGINT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `tank_id` INT UNSIGNED NULL,
  `quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `dip_reading` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `current_stock` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_unload_line_source_uq` (`unload_stock_id`,`pone_unload_stock_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_day_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_day_entry_id` BIGINT UNSIGNED NOT NULL,
  `entry_type` VARCHAR(50) NOT NULL,
  `reference_no` VARCHAR(191) NULL,
  `pump_id` INT UNSIGNED NULL,
  `assignment_id` BIGINT UNSIGNED NULL,
  `quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `starting_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `closing_meter` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `testing_quantity` DECIMAL(22,3) NOT NULL DEFAULT 0,
  `entry_at` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_day_entry_source_uq` (`settlement_id`,`pone_day_entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_collections` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_collection_id` BIGINT UNSIGNED NOT NULL,
  `collection_number` VARCHAR(80) NOT NULL,
  `collection_at` TIMESTAMP NULL DEFAULT NULL,
  `expected_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `cash_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `card_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `cheque_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `credit_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `other_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `declared_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `difference_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_collection_source_uq` (`settlement_id`,`pone_collection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_ledger_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_ledger_entry_id` BIGINT UNSIGNED NOT NULL,
  `entry_at` TIMESTAMP NULL DEFAULT NULL,
  `source_type` VARCHAR(50) NOT NULL,
  `source_id` BIGINT UNSIGNED NULL,
  `reference_no` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `debit` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `credit` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_ledger_source_uq` (`settlement_id`,`pone_ledger_entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_recoveries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_recovery_id` BIGINT UNSIGNED NOT NULL,
  `recovery_number` VARCHAR(80) NOT NULL,
  `recovery_date` DATE NULL,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `payment_method` VARCHAR(40) NULL,
  `reference_no` VARCHAR(191) NULL,
  `status` VARCHAR(30) NOT NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_recovery_source_uq` (`settlement_id`,`pone_recovery_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_commissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `pone_commission_id` BIGINT UNSIGNED NOT NULL,
  `commission_number` VARCHAR(80) NOT NULL,
  `commission_date` DATE NULL,
  `base_excess_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `commission_type` VARCHAR(30) NULL,
  `commission_rate` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `commission_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_commission_source_uq` (`settlement_id`,`pone_commission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pdnew_settlement_adjustments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `business_id` INT UNSIGNED NOT NULL,
  `settlement_id` BIGINT UNSIGNED NOT NULL,
  `adjustment_number` VARCHAR(80) NOT NULL,
  `adjustment_type` VARCHAR(40) NOT NULL,
  `field_name` VARCHAR(80) NOT NULL,
  `current_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `requested_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `approved_amount` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `reason` TEXT NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'requested',
  `requested_by` INT UNSIGNED NOT NULL,
  `requested_at` TIMESTAMP NOT NULL,
  `approved_by` INT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL DEFAULT NULL,
  `rejected_by` INT UNSIGNED NULL,
  `rejected_at` TIMESTAMP NULL DEFAULT NULL,
  `decision_note` TEXT NULL,
  `metadata` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pdnew_adjustment_uuid_uq` (`uuid`),
  UNIQUE KEY `pdnew_adjustment_number_uq` (`business_id`,`adjustment_number`),
  KEY `pdnew_adjustment_status_idx` (`business_id`,`settlement_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
