<?php

return [
    'title' => 'Communication Hub',
    'icon' => 'fa fa-comments',
    'route' => 'communicationhub.dashboard',
    'permission' => 'communicationhub.dashboard.view',
    'items' => [
        ['title' => 'Dashboard', 'route' => 'communicationhub.dashboard', 'icon' => 'fa fa-dashboard'],
        ['title' => '--- SMS Selling Platform ---', 'header' => true],
        ['title' => 'SMS Dashboard', 'route' => 'communicationhub.commercial.sms_dashboard', 'icon' => 'fa fa-line-chart'],
        ['title' => 'Send SMS', 'route' => 'communicationhub.commercial.send_sms', 'icon' => 'fa fa-paper-plane'],
        ['title' => 'Bulk SMS', 'route' => 'communicationhub.commercial.bulk_sms', 'icon' => 'fa fa-users'],
        ['title' => 'Scheduled SMS', 'route' => 'communicationhub.commercial.scheduled_sms', 'icon' => 'fa fa-clock-o'],
        ['title' => 'SMS Packages', 'route' => 'communicationhub.commercial.sms_packages', 'icon' => 'fa fa-archive'],
        ['title' => 'Business Wallets', 'route' => 'communicationhub.commercial.business_wallets', 'icon' => 'fa fa-credit-card'],
        ['title' => 'Credit Refills', 'route' => 'communicationhub.commercial.credit_refills', 'icon' => 'fa fa-plus-circle'],
        ['title' => 'Credit Transactions', 'route' => 'communicationhub.commercial.credit_transactions', 'icon' => 'fa fa-exchange'],
        ['title' => 'SMS Clients', 'route' => 'communicationhub.commercial.sms_clients', 'icon' => 'fa fa-building'],
        ['title' => 'Reseller Dashboard', 'route' => 'communicationhub.commercial.reseller_dashboard', 'icon' => 'fa fa-sitemap'],
        ['title' => 'API Tokens', 'route' => 'communicationhub.commercial.api_tokens', 'icon' => 'fa fa-key'],
        ['title' => 'API Logs', 'route' => 'communicationhub.commercial.api_logs', 'icon' => 'fa fa-list-alt'],
        ['title' => 'API Documentation', 'route' => 'communicationhub.commercial.api_documentation', 'icon' => 'fa fa-book'],
        ['title' => 'Delivery Reports', 'route' => 'communicationhub.commercial.delivery_reports', 'icon' => 'fa fa-truck'],
        ['title' => 'SMS Profit Reports', 'route' => 'communicationhub.commercial.profit_reports', 'icon' => 'fa fa-money'],
        ['title' => '--- Email Business Platform ---', 'header' => true],
        ['title' => 'Email Dashboard', 'route' => 'communicationhub.email.dashboard', 'icon' => 'fa fa-envelope'],
        ['title' => 'Compose Email', 'route' => 'communicationhub.email.compose', 'icon' => 'fa fa-pencil'],
        ['title' => 'Bulk Email', 'route' => 'communicationhub.email.bulk', 'icon' => 'fa fa-users'],
        ['title' => 'Email Queue', 'route' => 'communicationhub.email.queue', 'icon' => 'fa fa-list'],
        ['title' => '--- WhatsApp Business Platform ---', 'header' => true],
        ['title' => 'WhatsApp Dashboard', 'route' => 'communicationhub.commercial.whatsapp_dashboard', 'icon' => 'fa fa-whatsapp'],
        ['title' => 'Send WhatsApp', 'route' => 'communicationhub.commercial.send_whatsapp', 'icon' => 'fa fa-paper-plane'],
        ['title' => 'Bulk WhatsApp', 'route' => 'communicationhub.commercial.bulk_whatsapp', 'icon' => 'fa fa-users'],
        ['title' => 'Scheduled WhatsApp', 'route' => 'communicationhub.commercial.scheduled_whatsapp', 'icon' => 'fa fa-clock-o'],
        ['title' => 'WhatsApp Templates', 'route' => 'communicationhub.commercial.whatsapp_templates', 'icon' => 'fa fa-file-text-o'],
        ['title' => 'WhatsApp Profiles', 'route' => 'communicationhub.commercial.whatsapp_profiles', 'icon' => 'fa fa-cogs'],
        ['title' => '--- Push Notification Platform ---', 'header' => true],
        ['title' => 'Push Dashboard', 'route' => 'communicationhub.commercial.push_dashboard', 'icon' => 'fa fa-bell'],
        ['title' => 'Send Push', 'route' => 'communicationhub.commercial.send_push', 'icon' => 'fa fa-paper-plane'],
        ['title' => 'Bulk Push', 'route' => 'communicationhub.commercial.bulk_push', 'icon' => 'fa fa-bullhorn'],
        ['title' => 'Scheduled Push', 'route' => 'communicationhub.commercial.scheduled_push', 'icon' => 'fa fa-clock-o'],
        ['title' => 'Push Devices', 'route' => 'communicationhub.commercial.push_devices', 'icon' => 'fa fa-mobile'],
        ['title' => 'Push Templates', 'route' => 'communicationhub.commercial.push_templates', 'icon' => 'fa fa-file-text-o'],
        ['title' => '--- In-App Notification Centre ---', 'header' => true],
        ['title' => 'In-App Dashboard', 'route' => 'communicationhub.commercial.in_app_dashboard', 'icon' => 'fa fa-bell-o'],
        ['title' => 'Send In-App Alert', 'route' => 'communicationhub.commercial.send_in_app', 'icon' => 'fa fa-paper-plane'],
        ['title' => 'In-App Inbox', 'route' => 'communicationhub.commercial.in_app_inbox', 'icon' => 'fa fa-inbox'],
        ['title' => 'In-App Templates', 'route' => 'communicationhub.commercial.in_app_templates', 'icon' => 'fa fa-file-text-o'],
        ['title' => '--- Live Chat / Internal Messaging ---', 'header' => true],
        ['title' => 'Chat Dashboard', 'route' => 'communicationhub.commercial.chat_dashboard', 'icon' => 'fa fa-comments-o'],
        ['title' => 'Live Chat', 'route' => 'communicationhub.commercial.live_chat', 'icon' => 'fa fa-commenting'],
        ['title' => 'Internal Messaging', 'route' => 'communicationhub.commercial.internal_messaging', 'icon' => 'fa fa-envelope-o'],
        ['title' => 'Chat Templates', 'route' => 'communicationhub.commercial.chat_templates', 'icon' => 'fa fa-file-text-o'],
        ['title' => '--- Automation / Workflow Engine ---', 'header' => true],
        ['title' => 'Automation Dashboard', 'route' => 'communicationhub.commercial.automation_dashboard', 'icon' => 'fa fa-magic'],
        ['title' => 'Automation Rules', 'route' => 'communicationhub.commercial.automation_rules', 'icon' => 'fa fa-random'],
        ['title' => 'Automation Events', 'route' => 'communicationhub.commercial.automation_events', 'icon' => 'fa fa-bolt'],
        ['title' => 'Workflow Dashboard', 'route' => 'communicationhub.commercial.workflow_dashboard', 'icon' => 'fa fa-sitemap'],
        ['title' => 'Workflow Events', 'route' => 'communicationhub.commercial.workflow_events', 'icon' => 'fa fa-calendar-check-o'],
        ['title' => 'Workflow Rules', 'route' => 'communicationhub.commercial.workflow_rules', 'icon' => 'fa fa-code-fork'],
        ['title' => 'Workflow Event Log', 'route' => 'communicationhub.commercial.workflow_event_log', 'icon' => 'fa fa-history'],
        ['title' => '--- Analytics / API / Audit ---', 'header' => true],
        ['title' => 'Communication Analytics', 'route' => 'communicationhub.commercial.analytics_dashboard', 'icon' => 'fa fa-line-chart'],
        ['title' => 'Message History Report', 'route' => 'communicationhub.commercial.message_history_report', 'icon' => 'fa fa-list-alt'],
        ['title' => 'Provider Performance', 'route' => 'communicationhub.commercial.provider_performance_report', 'icon' => 'fa fa-plug'],
        ['title' => 'Campaign Performance', 'route' => 'communicationhub.commercial.campaign_performance_report', 'icon' => 'fa fa-bullhorn'],
        ['title' => 'API Gateway', 'route' => 'communicationhub.commercial.api_gateway_dashboard', 'icon' => 'fa fa-exchange'],
        ['title' => 'Communication Audit Centre', 'route' => 'communicationhub.commercial.communication_audit_centre', 'icon' => 'fa fa-check-square-o'],
        ['title' => 'Readiness Check', 'route' => 'communicationhub.readiness.index', 'icon' => 'fa fa-check-circle'],
        ['title' => 'Diagnostics Centre', 'route' => 'communicationhub.diagnostics.index', 'icon' => 'fa fa-stethoscope'],
        ['title' => '--- Enterprise Excellence ---', 'header' => true],
        ['title' => 'Executive Communication Centre', 'route' => 'communicationhub.excellence.executive_centre', 'icon' => 'fa fa-desktop'],
        ['title' => 'Global Notification Centre', 'route' => 'communicationhub.excellence.notifications.index', 'icon' => 'fa fa-bell'],
        ['title' => 'ERP Event Registry', 'route' => 'communicationhub.excellence.events.index', 'icon' => 'fa fa-calendar-check-o'],
        ['title' => 'Provider Health Monitor', 'route' => 'communicationhub.excellence.provider_health.index', 'icon' => 'fa fa-heartbeat'],
        ['title' => 'Communication Cost Centre', 'route' => 'communicationhub.excellence.cost_centre', 'icon' => 'fa fa-calculator'],
        ['title' => 'Advanced Scheduler', 'route' => 'communicationhub.excellence.advanced_scheduler', 'icon' => 'fa fa-calendar'],
        ['title' => 'Public API Platform', 'route' => 'communicationhub.excellence.public_api_platform', 'icon' => 'fa fa-code'],
        ['title' => 'Mobile Integration Hooks', 'route' => 'communicationhub.excellence.mobile_hooks', 'icon' => 'fa fa-mobile'],
        ['title' => 'Provider Marketplace Architecture', 'route' => 'communicationhub.excellence.marketplace_architecture', 'icon' => 'fa fa-puzzle-piece'],
        ['title' => 'Final Enterprise Audit', 'route' => 'communicationhub.excellence.final_audit', 'icon' => 'fa fa-check-square'],
        ['title' => '--- Core Communication Hub ---', 'header' => true],
        ['title' => 'Providers', 'route' => 'communicationhub.providers.index', 'icon' => 'fa fa-plug'],
        ['title' => 'Templates', 'route' => 'communicationhub.templates.index', 'icon' => 'fa fa-file-text-o'],
        ['title' => 'Campaigns', 'route' => 'communicationhub.campaigns.index', 'icon' => 'fa fa-bullhorn'],
        ['title' => 'Message Queue', 'route' => 'communicationhub.queue.index', 'icon' => 'fa fa-list'],
        ['title' => 'OTP Center', 'route' => 'communicationhub.otp.index', 'icon' => 'fa fa-key'],
        ['title' => 'Reports', 'route' => 'communicationhub.reports.index', 'icon' => 'fa fa-bar-chart'],
        ['title' => 'Settings', 'route' => 'communicationhub.settings.index', 'icon' => 'fa fa-cog'],
        ['title' => 'Standalone Audit', 'route' => 'communicationhub.audit.index', 'icon' => 'fa fa-check-square-o'],
        ['title' => 'Production Hardening', 'route' => 'communicationhub.production.index', 'icon' => 'fa fa-shield'],
        ['title' => 'Operations Support', 'route' => 'communicationhub.operations.index', 'icon' => 'fa fa-life-ring'],
        ['title' => 'Marketplace', 'route' => 'communicationhub.marketplace.index', 'icon' => 'fa fa-puzzle-piece'],
        ['title' => 'Enterprise Certification', 'route' => 'communicationhub.certification.index', 'icon' => 'fa fa-certificate'],
    ],
];
