@extends('ezylaw::layouts.module')
@section('ezylaw_title','Retainer Agreements')
@section('ezylaw_content')
<div class="row"><div class="col-md-4"><div class="box box-primary"><div class="box-header"><h3 class="box-title">New Retainer</h3></div><form method="post" action="{{ route('ezylaw.retainers.store') }}"><div class="box-body">@csrf
<label>Client</label><select class="form-control" name="client_id" required><option value="">Please Select</option>@foreach($clients as $c)<option value="{{ $c->id }}">{{ $c->client_no }} - {{ $c->name }}</option>@endforeach</select>
<label>Matter</label><select class="form-control" name="matter_id"><option value="">General Retainer</option>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select>
<label>Retainer No</label><input class="form-control" name="retainer_no" placeholder="Auto if blank"><label>Agreement Date</label><input class="form-control" type="date" name="agreement_date" value="{{ now()->toDateString() }}" required>
<label>Type</label><select class="form-control" name="retainer_type"><option value="general">General</option><option value="specific">Matter Specific</option><option value="security">Security</option><option value="costs">Costs</option><option value="other">Other</option></select>
<label>Agreed Amount</label><input class="form-control text-right" type="number" step="0.0001" min="0" name="agreed_amount" value="0" required><label>Replenishment Threshold</label><input class="form-control text-right" type="number" step="0.0001" min="0" name="replenishment_threshold" value="0"><input type="hidden" name="status" value="active"><label>Notes</label><textarea class="form-control" name="notes" rows="3"></textarea>
</div><div class="box-footer"><button class="btn btn-primary">Save Retainer</button></div></form></div></div>
<div class="col-md-8"><div class="box"><div class="box-header"><h3 class="box-title">Retainer Register</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Retainer No</th><th>Client / Matter</th><th>Date</th><th>Type</th><th class="text-right">Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($retainers as $r)<tr><td>{{ $r->retainer_no }}</td><td>{{ optional($r->client)->name }}<br><small>{{ optional($r->matter)->matter_no }}</small></td><td>{{ optional($r->agreement_date)->format('Y-m-d') }}</td><td>{{ ucfirst($r->retainer_type) }}</td><td class="text-right">{{ number_format((float)$r->agreed_amount,2) }}</td><td>{{ ucfirst($r->status) }}</td><td>@if($r->status!=='closed')<form method="post" action="{{ route('ezylaw.retainers.close',$r) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-warning">Close</button></form>@endif</td></tr>@empty<tr><td colspan="7">No retainers recorded.</td></tr>@endforelse</tbody></table>{{ $retainers->links() }}</div></div></div></div>
@endsection
