@extends('ezylaw::layouts.module')
@section('ezylaw_title','Court Filings')
@section('ezylaw_content')
<div class="row"><div class="col-md-4"><div class="box box-primary"><div class="box-header"><h3 class="box-title">New Filing</h3></div><div class="box-body">
<form method="POST" action="{{ route('ezylaw.court_filings.store') }}">@csrf
<label>Matter</label><select name="matter_id" class="form-control" required><option value="">Select</option>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select>
<label>Court</label><select name="court_id" class="form-control"><option value="">Select</option>@foreach($courts as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select>
<label>Filing No</label><input name="filing_no" class="form-control" required><label>Filing Type</label><input name="filing_type" class="form-control" required><label>Title</label><input name="title" class="form-control" required>
<label>Filed On</label><input type="date" name="filed_on" class="form-control"><label>Reference No</label><input name="reference_no" class="form-control"><label>Fee Amount</label><input type="number" step="0.0001" min="0" name="fee_amount" class="form-control" value="0">
<label>Status</label><select name="status" class="form-control"><option>draft</option><option>filed</option><option>accepted</option><option>rejected</option><option>returned</option></select><label>Response Due</label><input type="datetime-local" name="response_due_at" class="form-control"><label>Notes</label><textarea name="notes" class="form-control"></textarea>
<br><button class="btn btn-primary">Save Filing</button></form></div></div></div>
<div class="col-md-8"><div class="box"><div class="box-body table-responsive"><table class="table table-bordered table-striped law-table-compact"><thead><tr><th>Filing No</th><th>Matter</th><th>Court</th><th>Type</th><th>Filed</th><th>Status</th><th>Response Due</th><th class="text-right">Fee</th></tr></thead><tbody>@forelse($filings as $f)<tr><td>{{ $f->filing_no }}</td><td>{{ optional($f->matter)->matter_no }}</td><td>{{ optional($f->court)->name }}</td><td>{{ $f->filing_type }}</td><td>{{ optional($f->filed_on)->format('Y-m-d') }}</td><td><form method="POST" action="{{ route('ezylaw.court_filings.update',$f) }}">@csrf @method('PATCH')<select name="status" class="form-control input-sm" onchange="this.form.submit()">@foreach(['draft','filed','accepted','rejected','returned'] as $s)<option value="{{ $s }}" @selected($f->status===$s)>{{ ucfirst($s) }}</option>@endforeach</select></form></td><td>{{ optional($f->response_due_at)->format('Y-m-d H:i') }}</td><td class="text-right">{{ number_format((float)$f->fee_amount,2) }}</td></tr>@empty<tr><td colspan="8">No court filings.</td></tr>@endforelse</tbody></table>{{ $filings->links() }}</div></div></div></div>
@endsection
