<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if(!Schema::hasTable('restnew_payments')) Schema::create('restnew_payments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('order_id')->index();$t->unsignedBigInteger('shift_id')->nullable()->index();$t->string('payment_no',80);$t->string('payment_method',40)->index();$t->decimal('amount',22,4);$t->decimal('tendered_amount',22,4)->default(0);$t->decimal('change_amount',22,4)->default(0);$t->string('reference_no',160)->nullable();$t->string('status',30)->default('completed')->index();$t->json('metadata')->nullable();$t->unsignedBigInteger('received_by')->nullable()->index();$t->dateTime('paid_at');$t->timestamps();$t->unique(['business_id','payment_no'],'restnew_payment_business_no_uq');$t->index(['business_id','location_id','payment_method','paid_at'],'restnew_payment_scope_method_date_idx');});
  if(!Schema::hasTable('restnew_daily_closures')) Schema::create('restnew_daily_closures',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->date('business_date')->index();$t->decimal('gross_sales',22,4)->default(0);$t->decimal('discount_total',22,4)->default(0);$t->decimal('tax_total',22,4)->default(0);$t->decimal('service_charge_total',22,4)->default(0);$t->decimal('net_sales',22,4)->default(0);$t->decimal('cash_total',22,4)->default(0);$t->decimal('card_total',22,4)->default(0);$t->decimal('other_total',22,4)->default(0);$t->decimal('refund_total',22,4)->default(0);$t->unsignedInteger('order_count')->default(0);$t->json('summary_json')->nullable();$t->dateTime('closed_at');$t->unsignedBigInteger('closed_by')->nullable();$t->timestamps();$t->unique(['business_id','location_id','business_date'],'restnew_daily_closure_scope_date_uq');});
  if(!Schema::hasTable('restnew_audit_logs')) Schema::create('restnew_audit_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->nullable()->index();$t->string('entity_type',100);$t->unsignedBigInteger('entity_id')->nullable();$t->string('event',120)->index();$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->json('metadata')->nullable();$t->string('ip_address',64)->nullable();$t->string('user_agent',500)->nullable();$t->unsignedBigInteger('created_by')->nullable()->index();$t->timestamps();$t->index(['business_id','entity_type','entity_id','created_at'],'restnew_audit_entity_date_idx');});
 }
 public function down(): void { foreach(['restnew_audit_logs','restnew_daily_closures','restnew_payments'] as $table) Schema::dropIfExists($table); }
};
