<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if(!Schema::hasTable('restnew_settings')) Schema::create('restnew_settings',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('setting_key',120);$t->longText('setting_value')->nullable();$t->json('value_json')->nullable();$t->boolean('is_encrypted')->default(false);$t->unsignedBigInteger('updated_by')->nullable();$t->timestamps();$t->unique(['business_id','setting_key'],'restnew_setting_business_key_uq');});
  if(!Schema::hasTable('restnew_number_sequences')) Schema::create('restnew_number_sequences',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('sequence_key',80);$t->unsignedBigInteger('last_number')->default(0);$t->timestamps();$t->unique(['business_id','sequence_key'],'restnew_sequence_business_key_uq');});
  if(!Schema::hasTable('restnew_floors')) Schema::create('restnew_floors',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('name',120);$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','location_id','name'],'restnew_floor_scope_name_uq');});
  if(!Schema::hasTable('restnew_tables')) Schema::create('restnew_tables',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('floor_id')->nullable()->index();$t->string('table_code',50);$t->string('name',120);$t->unsignedInteger('capacity')->default(4);$t->string('shape',30)->default('square');$t->string('status',30)->default('available')->index();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','location_id','table_code'],'restnew_table_scope_code_uq');});
  if(!Schema::hasTable('restnew_kitchen_stations')) Schema::create('restnew_kitchen_stations',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('station_code',50);$t->string('name',120);$t->string('screen_colour',30)->default('blue');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','location_id','station_code'],'restnew_station_scope_code_uq');});
  if(!Schema::hasTable('restnew_printers')) Schema::create('restnew_printers',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('station_id')->nullable()->index();$t->string('name',120);$t->string('printer_type',30)->default('browser');$t->string('paper_size',20)->default('80mm');$t->string('connection_type',30)->default('browser');$t->string('connection_value',255)->nullable();$t->json('settings_json')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['business_id','location_id','is_active'],'restnew_printer_scope_active_idx');});
  if(!Schema::hasTable('restnew_user_screen_assignments')) Schema::create('restnew_user_screen_assignments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('user_id')->index();$t->string('screen_role',40)->index();$t->unsignedBigInteger('station_id')->nullable()->index();$t->boolean('is_active')->default(true);$t->json('settings_json')->nullable();$t->timestamps();$t->unique(['business_id','location_id','user_id','screen_role'],'restnew_user_screen_scope_uq');});
 }
 public function down(): void { foreach(['restnew_user_screen_assignments','restnew_printers','restnew_kitchen_stations','restnew_tables','restnew_floors','restnew_number_sequences','restnew_settings'] as $table) Schema::dropIfExists($table); }
};
