<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if(!Schema::hasTable('restnew_shifts')) Schema::create('restnew_shifts',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('shift_no',80);$t->unsignedBigInteger('user_id')->index();$t->string('status',30)->default('open')->index();$t->decimal('opening_cash',22,4)->default(0);$t->decimal('expected_cash',22,4)->default(0);$t->decimal('closing_cash',22,4)->nullable();$t->decimal('cash_variance',22,4)->default(0);$t->text('opening_note')->nullable();$t->text('closing_note')->nullable();$t->dateTime('opened_at');$t->dateTime('closed_at')->nullable();$t->unsignedBigInteger('closed_by')->nullable();$t->timestamps();$t->unique(['business_id','shift_no'],'restnew_shift_business_no_uq');$t->index(['business_id','location_id','user_id','status'],'restnew_shift_scope_status_idx');});
  if(!Schema::hasTable('restnew_orders')) Schema::create('restnew_orders',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('shift_id')->nullable()->index();$t->unsignedBigInteger('table_id')->nullable()->index();$t->unsignedBigInteger('waiter_id')->nullable()->index();$t->unsignedBigInteger('cashier_id')->nullable()->index();$t->string('order_no',80);$t->string('bill_no',80)->nullable();$t->string('receipt_no',80)->nullable();$t->string('order_type',30)->default('dine_in')->index();$t->string('source',30)->default('waiter');$t->string('customer_name',160)->nullable();$t->string('customer_phone',60)->nullable()->index();$t->string('customer_email',160)->nullable();$t->unsignedInteger('guest_count')->default(1);$t->text('notes')->nullable();$t->string('status',40)->default('draft')->index();$t->string('payment_status',30)->default('unpaid')->index();$t->string('kitchen_status',30)->default('not_sent')->index();$t->decimal('subtotal',22,4)->default(0);$t->decimal('discount_total',22,4)->default(0);$t->decimal('tax_total',22,4)->default(0);$t->decimal('service_charge_total',22,4)->default(0);$t->decimal('rounding_amount',22,4)->default(0);$t->decimal('total_amount',22,4)->default(0);$t->decimal('paid_amount',22,4)->default(0);$t->decimal('balance_amount',22,4)->default(0);$t->dateTime('opened_at')->nullable();$t->dateTime('sent_at')->nullable();$t->dateTime('ready_at')->nullable();$t->dateTime('paid_at')->nullable();$t->dateTime('cancelled_at')->nullable();$t->dateTime('completed_at')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','order_no'],'restnew_order_business_no_uq');$t->index(['business_id','location_id','order_type','status','created_at'],'restnew_order_scope_status_date_idx');});
  if(!Schema::hasTable('restnew_order_items')) Schema::create('restnew_order_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('order_id')->index();$t->unsignedBigInteger('menu_item_id')->index();$t->unsignedBigInteger('station_id')->nullable()->index();$t->string('item_code',60)->nullable();$t->string('item_name',180);$t->decimal('quantity',22,4);$t->decimal('unit_price',22,4);$t->decimal('modifier_total',22,4)->default(0);$t->decimal('discount_amount',22,4)->default(0);$t->decimal('tax_amount',22,4)->default(0);$t->decimal('service_charge_amount',22,4)->default(0);$t->decimal('line_total',22,4);$t->text('notes')->nullable();$t->string('status',30)->default('pending')->index();$t->dateTime('sent_at')->nullable();$t->dateTime('started_at')->nullable();$t->dateTime('ready_at')->nullable();$t->dateTime('stock_posted_at')->nullable();$t->unsignedBigInteger('voided_by')->nullable();$t->dateTime('voided_at')->nullable();$t->text('void_reason')->nullable();$t->timestamps();$t->index(['order_id','status'],'restnew_order_item_order_status_idx');});
  if(!Schema::hasTable('restnew_order_item_modifiers')) Schema::create('restnew_order_item_modifiers',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('order_item_id')->index();$t->unsignedBigInteger('modifier_id')->nullable()->index();$t->string('modifier_name',120);$t->decimal('quantity',22,4)->default(1);$t->decimal('price_delta',22,4)->default(0);$t->decimal('line_total',22,4)->default(0);$t->timestamps();});
  if(!Schema::hasTable('restnew_kitchen_tickets')) Schema::create('restnew_kitchen_tickets',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('order_id')->index();$t->unsignedBigInteger('station_id')->nullable()->index();$t->string('ticket_no',80);$t->string('ticket_type',30)->default('dine_in');$t->string('status',30)->default('new')->index();$t->unsignedInteger('priority')->default(0);$t->dateTime('printed_at')->nullable();$t->dateTime('accepted_at')->nullable();$t->dateTime('started_at')->nullable();$t->dateTime('ready_at')->nullable();$t->unsignedBigInteger('accepted_by')->nullable();$t->unsignedBigInteger('ready_by')->nullable();$t->timestamps();$t->unique(['business_id','ticket_no'],'restnew_ticket_business_no_uq');$t->index(['business_id','location_id','station_id','status','created_at'],'restnew_ticket_queue_idx');});
  if(!Schema::hasTable('restnew_kitchen_ticket_items')) Schema::create('restnew_kitchen_ticket_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('ticket_id')->index();$t->unsignedBigInteger('order_item_id')->index();$t->string('item_name',180);$t->decimal('quantity',22,4);$t->text('notes')->nullable();$t->string('status',30)->default('new')->index();$t->dateTime('started_at')->nullable();$t->dateTime('ready_at')->nullable();$t->timestamps();$t->unique(['ticket_id','order_item_id'],'restnew_ticket_order_item_uq');});
  if(!Schema::hasTable('restnew_order_status_logs')) Schema::create('restnew_order_status_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('order_id')->index();$t->string('from_status',40)->nullable();$t->string('to_status',40);$t->text('remarks')->nullable();$t->json('metadata')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->index(['order_id','created_at'],'restnew_order_status_date_idx');});
  if(!Schema::hasTable('restnew_collection_tokens')) Schema::create('restnew_collection_tokens',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('order_id')->unique();$t->string('token_no',40);$t->string('status',30)->default('queued')->index();$t->unsignedInteger('call_count')->default(0);$t->dateTime('called_at')->nullable();$t->dateTime('ready_at')->nullable();$t->dateTime('collected_at')->nullable();$t->unsignedBigInteger('collected_by')->nullable();$t->timestamps();$t->unique(['business_id','location_id','token_no'],'restnew_collection_scope_token_uq');});
  if(!Schema::hasTable('restnew_reservations')) Schema::create('restnew_reservations',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('table_id')->nullable()->index();$t->string('reservation_no',80);$t->string('customer_name',160);$t->string('customer_phone',60);$t->unsignedInteger('guest_count')->default(1);$t->dateTime('reserved_at')->index();$t->string('status',30)->default('booked')->index();$t->text('notes')->nullable();$t->json('metadata')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->unique(['business_id','reservation_no'],'restnew_reservation_business_no_uq');});
  if(!Schema::hasTable('restnew_print_jobs')) Schema::create('restnew_print_jobs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('printer_id')->nullable()->index();$t->unsignedBigInteger('order_id')->nullable()->index();$t->unsignedBigInteger('ticket_id')->nullable()->index();$t->string('document_type',40)->index();$t->string('status',30)->default('pending')->index();$t->unsignedInteger('attempt_count')->default(0);$t->json('payload')->nullable();$t->text('error_message')->nullable();$t->dateTime('printed_at')->nullable();$t->dateTime('failed_at')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();});
 }
 public function down(): void { foreach(['restnew_print_jobs','restnew_reservations','restnew_collection_tokens','restnew_order_status_logs','restnew_kitchen_ticket_items','restnew_kitchen_tickets','restnew_order_item_modifiers','restnew_order_items','restnew_orders','restnew_shifts'] as $table) Schema::dropIfExists($table); }
};
