<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if(!Schema::hasTable('restnew_categories')) Schema::create('restnew_categories',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->string('name',120);$t->string('colour',30)->default('blue');$t->string('icon',80)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','location_id','name'],'restnew_category_scope_name_uq');});
  if(!Schema::hasTable('restnew_menu_items')) Schema::create('restnew_menu_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('category_id')->nullable()->index();$t->unsignedBigInteger('station_id')->nullable()->index();$t->string('item_code',60);$t->string('name',180);$t->text('description')->nullable();$t->decimal('selling_price',22,4)->default(0);$t->decimal('takeaway_price',22,4)->nullable();$t->decimal('cost_price',22,4)->default(0);$t->decimal('tax_rate',8,4)->default(0);$t->decimal('service_charge_rate',8,4)->default(0);$t->string('unit',40)->default('Item');$t->string('image_path',255)->nullable();$t->boolean('is_dine_in')->default(true);$t->boolean('is_takeaway')->default(true);$t->boolean('is_available')->default(true)->index();$t->boolean('is_active')->default(true)->index();$t->unsignedInteger('preparation_minutes')->default(10);$t->json('metadata')->nullable();$t->timestamps();$t->unique(['business_id','location_id','item_code'],'restnew_menu_scope_code_uq');$t->index(['business_id','location_id','category_id','is_active','is_available'],'restnew_menu_filter_idx');});
  if(!Schema::hasTable('restnew_modifier_groups')) Schema::create('restnew_modifier_groups',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('name',120);$t->boolean('is_required')->default(false);$t->unsignedInteger('min_select')->default(0);$t->unsignedInteger('max_select')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','name'],'restnew_modifier_group_name_uq');});
  if(!Schema::hasTable('restnew_modifiers')) Schema::create('restnew_modifiers',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('modifier_group_id')->index();$t->string('name',120);$t->decimal('price_delta',22,4)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['modifier_group_id','name'],'restnew_modifier_group_name_uq');});
  if(!Schema::hasTable('restnew_menu_item_modifier_groups')) Schema::create('restnew_menu_item_modifier_groups',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('menu_item_id')->index();$t->unsignedBigInteger('modifier_group_id')->index();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();$t->unique(['menu_item_id','modifier_group_id'],'restnew_item_modifier_group_uq');});
  if(!Schema::hasTable('restnew_ingredients')) Schema::create('restnew_ingredients',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->string('ingredient_code',60);$t->string('name',160);$t->string('unit',40)->default('Nos');$t->decimal('unit_cost',22,4)->default(0);$t->decimal('reorder_level',22,4)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','ingredient_code'],'restnew_ingredient_business_code_uq');});
  if(!Schema::hasTable('restnew_recipes')) Schema::create('restnew_recipes',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('menu_item_id')->index();$t->string('name',160);$t->decimal('yield_qty',22,4)->default(1);$t->string('yield_unit',40)->default('Item');$t->boolean('is_active')->default(true);$t->text('instructions')->nullable();$t->timestamps();$t->unique(['business_id','menu_item_id'],'restnew_recipe_menu_item_uq');});
  if(!Schema::hasTable('restnew_recipe_lines')) Schema::create('restnew_recipe_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('recipe_id')->index();$t->unsignedBigInteger('ingredient_id')->index();$t->decimal('quantity',22,4);$t->decimal('waste_percent',8,4)->default(0);$t->timestamps();$t->unique(['recipe_id','ingredient_id'],'restnew_recipe_ingredient_uq');});
  if(!Schema::hasTable('restnew_inventory_balances')) Schema::create('restnew_inventory_balances',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('ingredient_id')->index();$t->decimal('quantity',22,4)->default(0);$t->decimal('average_cost',22,4)->default(0);$t->timestamps();$t->unique(['business_id','location_id','ingredient_id'],'restnew_inventory_scope_ingredient_uq');});
  if(!Schema::hasTable('restnew_stock_movements')) Schema::create('restnew_stock_movements',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id')->index();$t->unsignedBigInteger('location_id')->nullable()->index();$t->unsignedBigInteger('ingredient_id')->index();$t->string('movement_type',40)->index();$t->decimal('quantity',22,4);$t->decimal('unit_cost',22,4)->default(0);$t->decimal('value',22,4)->default(0);$t->string('source_type',80)->nullable();$t->unsignedBigInteger('source_id')->nullable();$t->string('reference_no',100)->nullable();$t->text('notes')->nullable();$t->json('metadata')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->index(['business_id','location_id','ingredient_id','created_at'],'restnew_stock_scope_date_idx');$t->unique(['source_type','source_id','ingredient_id'],'restnew_stock_source_ingredient_uq');});
 }
 public function down(): void { foreach(['restnew_stock_movements','restnew_inventory_balances','restnew_recipe_lines','restnew_recipes','restnew_ingredients','restnew_menu_item_modifier_groups','restnew_modifiers','restnew_modifier_groups','restnew_menu_items','restnew_categories'] as $table) Schema::dropIfExists($table); }
};
