@extends('pumperdashboardnew::layouts.admin')
@section('title','Pumper Dashboard-New')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Pumper Dashboard Operations</div><h1>Pumper Dashboard-New</h1><p>Pump operations, operator controls and Petro PD-New settlement integration within the current system.</p></div></div>
<div class="pone-grid pone-grid-4"><div class="pone-stat"><div class="pone-stat-label">Active Operators</div><div class="pone-stat-value">{{ $metrics['operators'] }}</div></div><div class="pone-stat"><div class="pone-stat-label">Open Shifts</div><div class="pone-stat-value">{{ $metrics['open_shifts'] }}</div></div><div class="pone-stat"><div class="pone-stat-label">Closed Today</div><div class="pone-stat-value">{{ $metrics['closed_today'] }}</div></div><div class="pone-stat"><div class="pone-stat-label">Integration Issues</div><div class="pone-stat-value">{{ $metrics['integration_issues'] }}</div></div></div>
<div class="pone-tile-grid" style="margin-top:18px">
@can('pumper_dashboard_new.operators.view')<a class="pone-tile pone-blue" href="{{ route('pumper-dashboard-new.admin.operators.index') }}"><span class="pone-tile-icon">OP</span><span><span class="pone-tile-title">PONE Operator Profiles</span><span class="pone-tile-desc">Manage Pumper Dashboard-New operator profiles</span></span></a>@endcan
@can('pumper_dashboard_new.shifts.manage')<a class="pone-tile pone-green" href="{{ route('pumper-dashboard-new.admin.shifts.create') }}"><span class="pone-tile-icon">+</span><span><span class="pone-tile-title">Assign New Shift</span><span class="pone-tile-desc">Create a PONE shift and publish pump assignments</span></span></a>@endcan
@can('pumper_dashboard_new.shifts.view')<a class="pone-tile pone-cyan" href="{{ route('pumper-dashboard-new.admin.shifts.index') }}"><span class="pone-tile-icon">SH</span><span><span class="pone-tile-title">Shift Register</span><span class="pone-tile-desc">Full operator and transaction history</span></span></a>@endcan
@can('pumper_dashboard_new.reconciliation.view')<a class="pone-tile pone-red" href="{{ route('pumper-dashboard-new.admin.reconciliation.index') }}"><span class="pone-tile-icon">±</span><span><span class="pone-tile-title">Reconciliation</span><span class="pone-tile-desc">Shortage recoveries and excess commissions</span></span></a>@endcan
@can('pumper_dashboard_new.ledger.view')<a class="pone-tile pone-purple" href="{{ route('pumper-dashboard-new.admin.ledger.index') }}"><span class="pone-tile-icon">L</span><span><span class="pone-tile-title">Operator Ledger</span><span class="pone-tile-desc">Debit, collection and running-balance view</span></span></a>@endcan
@can('pumper_dashboard_new.documents.view')<a class="pone-tile pone-orange" href="{{ route('pumper-dashboard-new.admin.documents.index') }}"><span class="pone-tile-icon">D</span><span><span class="pone-tile-title">Notes & Documents</span><span class="pone-tile-desc">Operator incidents, handovers and attachments</span></span></a>@endcan
@can('pumper_dashboard_new.reports.view')<a class="pone-tile pone-purple" href="{{ route('pumper-dashboard-new.admin.reports.index') }}"><span class="pone-tile-icon">Σ</span><span><span class="pone-tile-title">Reports</span><span class="pone-tile-desc">Operational and audit reports</span></span></a>@endcan
@can('pumper_dashboard_new.integration.view')<a class="pone-tile pone-orange" href="{{ route('pumper-dashboard-new.admin.integration.index') }}"><span class="pone-tile-icon">↔</span><span><span class="pone-tile-title">Petro PD-New Pairing</span><span class="pone-tile-desc">Review source-ready events and settlement writebacks</span></span></a>@endcan
@can('pumper_dashboard_new.login_attempts.view')<a class="pone-tile pone-red" href="{{ route('pumper-dashboard-new.admin.login-attempts.index') }}"><span class="pone-tile-icon">🔒</span><span><span class="pone-tile-title">Blocked Logins</span><span class="pone-tile-desc">Review and unblock operator login attempts</span></span></a>@endcan
@can('pumper_dashboard_new.print_logs.view')<a class="pone-tile pone-gray" href="{{ route('pumper-dashboard-new.admin.print-logs.index') }}"><span class="pone-tile-icon">P</span><span><span class="pone-tile-title">Print History</span><span class="pone-tile-desc">Original and reprint audit trail</span></span></a>@endcan
@can('pumper_dashboard_new.settings.manage')<a class="pone-tile pone-gray" href="{{ route('pumper-dashboard-new.admin.settings.edit') }}"><span class="pone-tile-icon">⚙</span><span><span class="pone-tile-title">Module Settings</span><span class="pone-tile-desc">Operations, security, printing and bridge rules</span></span></a>@endcan
</div>
<div class="pone-panel" style="margin-top:18px"><div class="pone-panel-head"><h2>Recent Shifts</h2>@can('pumper_dashboard_new.shifts.view')<a class="pone-btn pone-btn-light pone-btn-sm" href="{{ route('pumper-dashboard-new.admin.shifts.index') }}">All Shifts</a>@endcan</div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table"><thead><tr><th>Shift</th><th>Operator</th><th>Opened</th><th>Closed</th><th class="pone-text-right">Expected</th><th class="pone-text-right">Payments</th><th>Result</th><th>Status</th><th>Sync</th><th>Action</th></tr></thead><tbody>@forelse($recentShifts as $shift)<tr><td><strong>{{ $shift->shift_number }}</strong></td><td>{{ $shift->operatorProfile->display_name ?? ('Operator '.$shift->pd_operator_id) }}</td><td>{{ optional($shift->opened_at)->format('Y-m-d H:i') }}</td><td>{{ optional($shift->closed_at)->format('Y-m-d H:i') ?: '-' }}</td><td class="pone-text-right">{{ number_format((float)$shift->expected_total,4) }}</td><td class="pone-text-right">{{ number_format((float)$shift->payments_total,4) }}</td><td><span class="pone-badge pone-badge-{{ $shift->reconciliation_status }}">{{ $shift->reconciliation_status }}</span></td><td><span class="pone-badge pone-badge-{{ $shift->status }}">{{ $shift->status }}</span></td><td><span class="pone-badge pone-badge-{{ $shift->integration_status }}">{{ $shift->integration_status }}</span></td><td>@can('pumper_dashboard_new.shifts.view')<a class="pone-btn pone-btn-light pone-btn-sm" href="{{ route('pumper-dashboard-new.admin.shifts.show',$shift) }}">View</a>@endcan</td></tr>@empty<tr><td colspan="10" class="pone-empty">No shifts available.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
