@extends('pumperdashboardnew::layouts.operator')
@section('title','Shortage & Excess')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Reconciliation</div><h1>Shortage Recovery & Excess Commission</h1><p>Shift {{ $shift->shift_number }}</p></div><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.dashboard') }}">Dashboard</a></div>
<div class="pone-grid pone-grid-4" style="margin-bottom:16px"><div class="pone-stat"><div class="pone-stat-label">Recorded Shortage</div><div class="pone-stat-value">{{ number_format((float)$shift->shortage_amount,4) }}</div></div><div class="pone-stat"><div class="pone-stat-label">Available to Recover</div><div class="pone-stat-value">{{ number_format((float)$availableShortage,4) }}</div></div><div class="pone-stat"><div class="pone-stat-label">Recorded Excess</div><div class="pone-stat-value">{{ number_format((float)$shift->excess_amount,4) }}</div></div><div class="pone-stat"><div class="pone-stat-label">Available for Commission</div><div class="pone-stat-value">{{ number_format((float)$availableExcess,4) }}</div></div></div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Recover Shortage</h2></div><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.reconciliation.recover') }}" data-confirm-message="Confirm this shortage recovery?">@csrf<div class="pone-form-grid"><div class="pone-field pone-col-4"><label class="pone-required">Amount</label><input name="amount" type="number" min="0.0001" max="{{ $availableShortage }}" step="0.0001" required></div><div class="pone-field pone-col-4"><label class="pone-required">Payment Method</label><select name="payment_method" required>@foreach(['cash','card','cheque','bank','other'] as $method)<option value="{{ $method }}">{{ ucfirst($method) }}</option>@endforeach</select></div><div class="pone-field pone-col-4"><label>Date</label><input name="recovery_date" type="date" value="{{ now()->toDateString() }}"></div><div class="pone-field pone-col-6"><label>Reference No.</label><input name="reference_no"></div><div class="pone-field pone-col-6"><label>Note</label><input name="note"></div></div><div class="pone-actions pone-actions-end" style="margin-top:14px"><button class="pone-btn pone-btn-danger" {{ $availableShortage<=0?'disabled':'' }}>Save Recovery</button></div></form></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Excess Commission</h2></div><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.reconciliation.commission') }}" data-confirm-message="Confirm this excess commission?">@csrf<div class="pone-form-grid"><div class="pone-field pone-col-4"><label class="pone-required">Type</label><select name="commission_type" required><option value="percentage">Percentage</option><option value="fixed">Fixed Amount</option></select></div><div class="pone-field pone-col-4"><label class="pone-required">Rate / Amount</label><input name="commission_rate" type="number" min="0.000001" step="0.000001" required></div><div class="pone-field pone-col-4"><label>Date</label><input name="commission_date" type="date" value="{{ now()->toDateString() }}"></div><div class="pone-field pone-col-12"><label>Note</label><input name="note"></div></div><div class="pone-actions pone-actions-end" style="margin-top:14px"><button class="pone-btn pone-btn-success" {{ $availableExcess<=0?'disabled':'' }}>Save Commission</button></div></form></div></div>
</div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Recovery History</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>No.</th><th>Date</th><th>Method</th><th class="pone-text-right">Amount</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recoveries as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->recovery_number }}</td><td>{{ optional($row->recovery_date)->format('Y-m-d') }}</td><td>{{ ucfirst($row->payment_method) }}</td><td class="pone-text-right">{{ number_format((float)$row->amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td>@if($row->status==='confirmed')<form method="post" action="{{ route('pumper-dashboard-new.operator.reconciliation.recoveries.destroy',$row) }}" data-confirm-message="Void this recovery?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="pone-empty">No shortage recoveries.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Commission History</h2></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-table-compact"><thead><tr><th>No.</th><th>Date</th><th>Type / Rate</th><th class="pone-text-right">Amount</th><th>Status</th><th></th></tr></thead><tbody>@forelse($commissions as $row)<tr class="{{ $row->status==='void'?'is-void':'' }}"><td>{{ $row->commission_number }}</td><td>{{ optional($row->commission_date)->format('Y-m-d') }}</td><td>{{ ucfirst($row->commission_type) }} / {{ number_format((float)$row->commission_rate,4) }}</td><td class="pone-text-right">{{ number_format((float)$row->commission_amount,4) }}</td><td><span class="pone-badge pone-badge-{{ $row->status }}">{{ $row->status }}</span></td><td>@if($row->status==='confirmed')<form method="post" action="{{ route('pumper-dashboard-new.operator.reconciliation.commissions.destroy',$row) }}" data-confirm-message="Void this commission?" data-void-form>@csrf @method('DELETE')<input type="hidden" name="reason"><button class="pone-btn pone-btn-danger pone-btn-sm">Void</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="pone-empty">No excess commissions.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
