@extends('ezylaw::layouts.module')
@section('ezylaw_title','Settlements & Mediation')
@section('ezylaw_content')
<div class="row"><div class="col-md-5"><div class="box box-primary"><div class="box-header"><h3 class="box-title">New Settlement</h3></div><div class="box-body"><form method="POST" action="{{ route('ezylaw.settlements.store') }}">@csrf
<label>Matter</label><select name="matter_id" class="form-control" required><option value="">Select</option>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select>
<label>Type</label><select name="settlement_type" class="form-control">@foreach(['negotiation','mediation','consent','arbitration','other'] as $x)<option>{{ $x }}</option>@endforeach</select><label>Offer Amount</label><input name="offer_amount" type="number" step="0.0001" min="0" class="form-control"><label>Agreed Amount</label><input name="agreed_amount" type="number" step="0.0001" min="0" class="form-control"><label>Status</label><select name="status" class="form-control">@foreach(['draft','offered','accepted','rejected','completed'] as $x)<option>{{ $x }}</option>@endforeach</select><label>Terms</label><textarea name="terms" class="form-control" rows="4"></textarea><label><input type="checkbox" name="confidential" value="1"> Confidential</label><br><button class="btn btn-primary">Create Settlement</button></form></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Add Mediation Session</h3></div><div class="box-body"><form method="POST" action="{{ route('ezylaw.settlements.mediation') }}">@csrf<label>Matter</label><select name="matter_id" class="form-control" required>@foreach($matters as $m)<option value="{{ $m->id }}">{{ $m->matter_no }}</option>@endforeach</select><label>Settlement ID (optional)</label><input name="settlement_id" type="number" class="form-control"><label>Mediator</label><input name="mediator" class="form-control"><label>Venue</label><input name="venue" class="form-control"><label>Session</label><input type="datetime-local" name="session_at" class="form-control" required><label>Status</label><select name="status" class="form-control">@foreach(['scheduled','completed','cancelled','adjourned'] as $x)<option>{{ $x }}</option>@endforeach</select><label>Outcome</label><textarea name="outcome" class="form-control"></textarea><br><button class="btn btn-default">Save Session</button></form></div></div></div>
<div class="col-md-7"><div class="box"><div class="box-body table-responsive"><table class="table table-bordered table-striped law-table-compact"><thead><tr><th>No</th><th>Matter</th><th>Type</th><th>Status</th><th class="text-right">Offer</th><th class="text-right">Agreed</th><th>Sessions</th><th>Action</th></tr></thead><tbody>@forelse($settlements as $s)<tr><td>{{ $s->settlement_no }}</td><td>{{ optional($s->matter)->matter_no }}</td><td>{{ ucfirst($s->settlement_type) }}</td><td>{{ ucfirst($s->status) }}</td><td class="text-right">{{ number_format((float)$s->offer_amount,2) }}</td><td class="text-right">{{ number_format((float)$s->agreed_amount,2) }}</td><td>{{ $s->sessions->count() }}</td><td><form method="POST" action="{{ route('ezylaw.settlements.status',$s) }}">@csrf @method('PATCH')<select name="status" class="form-control input-sm" onchange="this.form.submit()">@foreach(['draft','offered','accepted','rejected','completed'] as $x)<option @selected($s->status===$x)>{{ $x }}</option>@endforeach</select></form></td></tr>@empty<tr><td colspan="8">No settlements.</td></tr>@endforelse</tbody></table>{{ $settlements->links() }}</div></div></div></div>
@endsection
