<?php
return [
    ['key' => 'tea_estate.access', 'label' => 'Tea Estate Management Access', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.dashboard.view', 'label' => 'Tea Estate Dashboard', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.plantation.view', 'label' => 'Plantation - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.plantation.manage', 'label' => 'Plantation - Manage', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.harvests.view', 'label' => 'Harvests - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.harvests.create', 'label' => 'Harvests - Create', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.parties.view', 'label' => 'Tea Parties - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.parties.manage', 'label' => 'Tea Parties - Manage', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.buying.view', 'label' => 'Green Leaf Buying - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.buying.create', 'label' => 'Green Leaf Buying - Create', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.buying.pay', 'label' => 'Green Leaf Buying - Payments', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.processing.view', 'label' => 'Processing - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.processing.create', 'label' => 'Processing - Create Batch', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.processing.update', 'label' => 'Processing - Update Stages', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.processing.finalize', 'label' => 'Processing - Finalize Batch', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.inventory.view', 'label' => 'Tea Inventory - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.sales.view', 'label' => 'Tea Sales - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.sales.create', 'label' => 'Tea Sales - Create', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.sales.receive', 'label' => 'Tea Sales - Receive Payment', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.finance.view', 'label' => 'Tea Finance Integration - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.finance.manage', 'label' => 'Tea Finance Integration - Manage', 'type' => 'action', 'source' => 'module_pages'],
    ['key' => 'tea_estate.reports.view', 'label' => 'Tea Reports - View', 'type' => 'page', 'source' => 'module_pages'],
    ['key' => 'tea_estate.settings.manage', 'label' => 'Tea Settings - Manage', 'type' => 'page', 'source' => 'module_pages'],
];
