@extends('hotelmanagement::layouts.app')
@section('hotel_content')
<section class="content-header"><h1>Billing & Guest Folios <small>Charges, payments and balances</small></h1></section>
<section class="content">
@include('hotelmanagement::partials.nav')
@if(session('status'))<div class="alert alert-success hm-alert">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger hm-alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="box hm-card"><div class="box-header"><h3 class="box-title">Create Folio</h3></div><div class="box-body"><form method="POST" action="{{ route('hotel-management.billing.store') }}">@csrf<div class="hm-form-grid">
<div class="form-group"><label>Folio No</label><input name="folio_no" type="text" class="form-control" placeholder="Auto if blank"></div>
<div class="form-group"><label>Guest</label><select name="guest_id" class="form-control"><option value="">Please Select</option>@foreach($guests as $g)<option value="{{ $g->id }}">{{ $g->guest_name }}</option>@endforeach</select></div>
<div class="form-group"><label>Reservation</label><select name="reservation_id" class="form-control"><option value="">Please Select</option>@foreach($reservations as $r)<option value="{{ $r->id }}">{{ $r->reservation_no }}</option>@endforeach</select></div>
<div class="form-group"><label>Folio Type</label><select name="folio_type" class="form-control"><option value="guest">Guest</option><option value="company">Company</option><option value="house">House</option></select></div>
<div class="form-group"><label>Folio Date</label><input name="folio_date" type="date" class="form-control" value="{{ date('Y-m-d') }}" required></div>
<div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="open">Open</option><option value="closed">Closed</option></select></div>
</div><br><button class="btn hm-btn-add">Save Folio</button></form></div></div>
<div class="box hm-card"><div class="box-header"><h3 class="box-title">Open Folios</h3></div><div class="box-body">@include('hotelmanagement::partials.toolbar')<div class="table-responsive"><table class="table hm-table table-striped"><thead><tr><th>Folio No</th><th>Guest</th><th>Reservation</th><th>Date</th><th>Type</th><th>Charges</th><th>Payments</th><th>Balance</th><th>Status</th><th>Quick Post</th></tr></thead><tbody>@forelse($folios as $row)<tr><td>{{ $row->folio_no ?? '' }}</td><td>{{ $row->guest_name ?? '-' }}</td><td>{{ $row->reservation_no ?? '-' }}</td><td>{{ $row->folio_date ?? '' }}</td><td>{{ ucfirst($row->folio_type ?? '') }}</td><td>{{ number_format((float)($row->total_charges ?? 0), 4) }}</td><td>{{ number_format((float)($row->total_payments ?? 0), 4) }}</td><td>{{ number_format((float)($row->balance ?? 0), 4) }}</td><td><span class="hm-badge {{ $row->status ?? '' }}">{{ ucfirst($row->status ?? '-') }}</span></td><td>
<form method="POST" action="{{ route('hotel-management.billing.payment', $row->id) }}" class="hm-inline-form">@csrf<input type="hidden" name="payment_date" value="{{ date('Y-m-d') }}"><input type="hidden" name="payment_method" value="cash"><input name="amount" type="number" step="0.0001" class="form-control hm-mini-input" placeholder="Payment"><button class="btn hm-btn-action">Pay</button></form>
</td></tr>@empty<tr><td colspan="10"><div class="hm-empty">No records found.</div></td></tr>@endforelse</tbody></table></div></div></div>
<div class="box hm-card"><div class="box-header"><h3 class="box-title">Post Charge</h3></div><div class="box-body"><form method="POST" action="{{ count($folios) ? route('hotel-management.billing.charge', $folios->first()->id) : '#' }}">@csrf<div class="hm-form-grid"><div class="form-group"><label>Folio</label><select class="form-control" onchange="this.form.action=this.value"><option value="">Please Select</option>@foreach($folios as $f)<option value="{{ route('hotel-management.billing.charge', $f->id) }}">{{ $f->folio_no }}</option>@endforeach</select></div><div class="form-group"><label>Room</label><select name="room_id" class="form-control"><option value="">Please Select</option>@foreach($rooms as $r)<option value="{{ $r->id }}">{{ $r->room_no }}</option>@endforeach</select></div><div class="form-group"><label>Charge Type</label><input name="charge_type" class="form-control" value="room"></div><div class="form-group"><label>Description</label><input name="description" class="form-control" required></div><div class="form-group"><label>Qty</label><input name="quantity" type="number" step="0.0001" class="form-control" value="1"></div><div class="form-group"><label>Unit Price</label><input name="unit_price" type="number" step="0.0001" class="form-control" value="0.0000"></div><div class="form-group"><label>Tax</label><input name="tax" type="number" step="0.0001" class="form-control" value="0.0000"></div><div class="form-group"><label>Discount</label><input name="discount" type="number" step="0.0001" class="form-control" value="0.0000"></div><div class="form-group"><label>Charge Date</label><input name="charge_date" type="date" class="form-control" value="{{ date('Y-m-d') }}" required></div></div><br><button class="btn hm-btn-add">Post Charge</button></form></div></div>
</section>
@endsection
