@extends('pumperdashboardnew::layouts.admin')
@section('title','Pumper Dashboard-New Settings')
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Module Configuration</div><h1>Pumper Dashboard-New Settings</h1><p>Business-wide defaults may be overridden for one location without depending on legacy Petro PD settings.</p></div></div>
<div class="pone-panel pone-no-print"><div class="pone-panel-body"><form method="get" action="{{ route('pumper-dashboard-new.admin.settings.edit') }}"><div class="pone-form-grid"><div class="pone-field pone-col-5"><label>Settings Scope</label><select name="location_id" data-search-select><option value="">All Locations / Business Default</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((int)$locationId===(int)$location->id)>{{ $location->name }}</option>@endforeach</select></div><div class="pone-field pone-col-2" style="align-self:end"><button class="pone-btn pone-btn-light pone-btn-block">Load Scope</button></div></div></form></div></div>
<form method="post" action="{{ route('pumper-dashboard-new.admin.settings.update') }}" data-processing-text="Saving Pumper Dashboard-New settings…">@csrf @method('PUT')<input type="hidden" name="location_id" value="{{ $locationId }}">
@php
$booleanGroups=[
 'Petro PD-New Pairing'=>[
  'integration_enabled'=>'Enable Petro PD-New source publication','sync_during_operation'=>'Mark each operation source-ready','require_clean_sync_before_close'=>'Require clean source state before closing a shift'],
 'Shift & Collection Controls'=>[
  'allow_operator_open_shift'=>'Allow operator-created local shifts','allow_close_with_open_pumps'=>'Allow close with open pumps','allow_close_with_pending_sync'=>'Allow close with pending/failed synchronization','require_collection_before_close'=>'Require a confirmed collection before close'],
 'Payment Controls'=>[
  'cash_denomination_enabled'=>'Enable cash denomination counting','multi_card_enabled'=>'Enable multiple card slips','cheque_enabled'=>'Enable cheque collections','credit_sale_enabled'=>'Enable credit sales','require_credit_dual_confirmation'=>'Require two credit-sale confirmations','allow_payment_edit'=>'Allow controlled payment editing']
];
@endphp
<div class="pone-grid pone-grid-3">@foreach($booleanGroups as $heading=>$options)<div class="pone-panel"><div class="pone-panel-head"><h2>{{ $heading }}</h2></div><div class="pone-panel-body">@foreach($options as $name=>$label)<div class="pone-field" style="margin-bottom:13px"><input type="hidden" name="{{ $name }}" value="0"><label class="pone-checkbox"><input type="checkbox" name="{{ $name }}" value="1" @checked((bool)($settings[$name]??false))><span>{{ $label }}</span></label></div>@endforeach</div></div>@endforeach</div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Operational Defaults</h2></div><div class="pone-panel-body"><div class="pone-form-grid"><div class="pone-field pone-col-6"><label>Integration Mode</label><input type="hidden" name="integration_mode" value="petro_pd_new"><input value="Petro PD-New (exclusive)" readonly></div><div class="pone-field pone-col-6"><label>Default Receipt Size</label><select name="receipt_paper_size" required>@foreach(['58mm','80mm','A4'] as $size)<option value="{{ $size }}" @selected(($settings['receipt_paper_size']??'80mm')===$size)>{{ $size }}</option>@endforeach</select></div><div class="pone-field pone-col-6"><label>Payment Edit Lock (minutes)</label><input name="payment_edit_lock_minutes" type="number" min="0" max="10080" value="{{ $settings['payment_edit_lock_minutes']??1440 }}" required><div class="pone-help">0 means no time limit while editing is enabled.</div></div><div class="pone-field pone-col-6"><label>Operator Auto Logout (minutes)</label><input name="auto_logout_minutes" type="number" min="0" max="1440" value="{{ $settings['auto_logout_minutes']??0 }}" required><div class="pone-help">0 disables inactivity logout.</div></div><div class="pone-field pone-col-12"><label>Default Store</label><select name="default_store_id" data-search-select><option value="">No Default</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected((int)($settings['default_store_id']??0)===(int)$store->id)>{{ $store->name }}</option>@endforeach</select></div></div></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Number Formats</h2></div><div class="pone-panel-body"><div class="pone-form-grid"><div class="pone-field pone-col-4"><label>Amount Decimals</label><input name="amount_decimals" type="number" min="0" max="6" value="{{ $settings['amount_decimals']??4 }}" required></div><div class="pone-field pone-col-4"><label>Quantity Decimals</label><input name="quantity_decimals" type="number" min="0" max="6" value="{{ $settings['quantity_decimals']??3 }}" required></div><div class="pone-field pone-col-4"><label>Meter Decimals</label><input name="meter_decimals" type="number" min="0" max="6" value="{{ $settings['meter_decimals']??3 }}" required></div></div><div class="pone-alert pone-alert-info" style="margin-top:14px">Calculations always retain full precision. These values control display and print formatting only.</div></div></div>
</div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Document Number Prefixes</h2></div><div class="pone-panel-body"><div class="pone-form-grid">@foreach(['shift_prefix'=>'Shift','payment_prefix'=>'Payment','other_sale_prefix'=>'Other Sale','unload_prefix'=>'Unload Stock','settlement_prefix'=>'Settlement','collection_prefix'=>'Collection','recovery_prefix'=>'Shortage Recovery','commission_prefix'=>'Excess Commission'] as $name=>$label)<div class="pone-field pone-col-3"><label>{{ $label }}</label><input name="{{ $name }}" maxlength="30" value="{{ $settings[$name]??config('pumperdashboardnew.defaults.'.$name) }}" required></div>@endforeach</div></div></div>
<div class="pone-actions pone-actions-end"><button class="pone-btn pone-btn-success">Save Settings</button></div></form>
@endsection
