@extends('hrmanager::layouts.master')
@section('hr_content')
<div class="hr-page">
@include('hrmanager::dashboard.partials.header',['title'=>'Payroll','subtitle'=>'Payroll periods, salary structures, payroll runs and payslips connected to the Employee Central Record.','section'=>'Payroll'])
<div class="hr-card-grid"><div class="hr-kpi purple"><i class="fa fa-users"></i><span>Employees</span><strong>{{ number_format($stats['employees'] ?? 0) }}</strong></div><div class="hr-kpi blue"><i class="fa fa-calendar"></i><span>Payroll Periods</span><strong>{{ number_format($stats['periods'] ?? 0) }}</strong></div><div class="hr-kpi orange"><i class="fa fa-cogs"></i><span>Payroll Runs</span><strong>{{ number_format($stats['runs'] ?? 0) }}</strong></div><div class="hr-kpi green"><i class="fa fa-money"></i><span>Net Payroll</span><strong>{{ number_format($stats['net_total'] ?? 0, 2) }}</strong></div></div>
<div class="payroll-grid"><div class="hr-panel"><h3>Create Payroll Run</h3><form method="POST" action="{{ route('hrmanager.payroll.runs.store') }}" class="payroll-form">@csrf<label>Payroll Period</label><select name="payroll_period_id" required><option value="">Select Period</option>@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->period_name ?? $period->period_code ?? ('Period #' . $period->id) }}</option>@endforeach</select><label>Remarks</label><textarea name="remarks"></textarea><button class="hr-primary-btn">Create Draft Run</button></form><div class="payroll-side-stats"><div><span>Components</span><strong>{{ number_format($stats['components'] ?? 0) }}</strong></div><div><span>Payslips</span><strong>{{ number_format($stats['payslips'] ?? 0) }}</strong></div></div></div>
<div class="hr-panel wide"><h3>Payroll Runs</h3>@include('hrmanager::components.list-toolbar',['searchPlaceholder'=>'Search payroll run no, status'])<table class="hr-table"><thead><tr><th>Run No</th><th>Run Date</th><th>Employees</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th>Process</th></tr></thead><tbody>@forelse($runs as $row)<tr><td>{{ $row->run_no }}</td><td>{{ $row->run_date }}</td><td>{{ $row->employee_count ?? 0 }}</td><td>{{ number_format($row->gross_total ?? 0, 2) }}</td><td>{{ number_format($row->deduction_total ?? 0, 2) }}</td><td>{{ number_format($row->net_total ?? 0, 2) }}</td><td><em class="status-pill">{{ ucfirst($row->status ?? 'Draft') }}</em></td><td>@if(($row->status ?? '') === 'draft')<form method="POST" action="{{ route('hrmanager.payroll.runs.process', $row->id) }}">@csrf<button class="mini-btn process">Process</button></form>@else<span class="muted">Processed</span>@endif</td></tr>@empty<tr><td colspan="8" class="empty-row">No payroll runs found.</td></tr>@endforelse</tbody></table>@if(method_exists($runs,'links')){{ $runs->links() }}@endif</div></div>
<div class="payroll-grid"><div class="hr-panel"><h3>Run Employees</h3><table class="hr-table compact-table"><thead><tr><th>Employee</th><th>Basic</th><th>Net</th><th>Status</th></tr></thead><tbody>@forelse($runEmployees as $row)<tr><td>#{{ $row->employee_id }}</td><td>{{ number_format($row->basic_salary ?? 0, 2) }}</td><td>{{ number_format($row->net_salary ?? 0, 2) }}</td><td><em class="status-pill">{{ $row->processing_status }}</em></td></tr>@empty<tr><td colspan="4" class="empty-row">No processed employee payroll records found.</td></tr>@endforelse</tbody></table></div><div class="hr-panel wide"><h3>Payslips</h3><table class="hr-table compact-table"><thead><tr><th>Payslip No</th><th>Employee</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th></tr></thead><tbody>@forelse($payslips as $row)<tr><td>{{ $row->payslip_no }}</td><td>#{{ $row->employee_id }}</td><td>{{ number_format($row->gross_salary ?? 0, 2) }}</td><td>{{ number_format($row->deduction_total ?? 0, 2) }}</td><td>{{ number_format($row->net_salary ?? 0, 2) }}</td><td><em class="status-pill">{{ $row->payment_status }}</em></td></tr>@empty<tr><td colspan="6" class="empty-row">No payslips found.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
