@extends('ezylaw::layouts.module')
@section('ezylaw_title','Case Stages / Workflow')
@section('ezylaw_content')
<div class="row"><div class="col-md-5"><div class="box box-primary"><div class="box-header"><h3 class="box-title">Workflow Template</h3></div><form method="post" action="{{ route('ezylaw.workflow.templates.store') }}"><div class="box-body">@csrf<label>Name</label><input class="form-control" name="name" required><label>Practice Area</label><select class="form-control" name="practice_area_id"><option value="">All</option>@foreach($areas as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select><label>Description</label><textarea class="form-control" name="description"></textarea></div><div class="box-footer"><button class="btn btn-primary">Add Template</button></div></form></div></div>
<div class="col-md-7"><div class="box"><div class="box-header"><h3 class="box-title">Add Stage</h3></div><form method="post" action="{{ route('ezylaw.workflow.stages.store') }}"><div class="box-body law-form-grid">@csrf<label>Template<select class="form-control" name="workflow_template_id" required>@foreach($templates as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><label>Stage Name<input class="form-control" name="name" required></label><label>Sequence<input type="number" min="1" class="form-control" name="sequence_no" value="1" required></label><label>Default Days<input type="number" min="0" class="form-control" name="default_days"></label><label><input type="checkbox" name="required" value="1"> Required stage</label></div><div class="box-footer"><button class="btn btn-primary">Add Stage</button></div></form></div></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Matter Workflow</h3></div><div class="box-body"><form class="form-inline" method="get"><select class="form-control" name="matter_id" onchange="this.form.submit()"><option value="">Select Matter</option>@foreach($matters as $m)<option value="{{ $m->id }}" {{ optional($selectedMatter)->id==$m->id?'selected':'' }}>{{ $m->matter_no }} - {{ $m->title }}</option>@endforeach</select></form>
@if($selectedMatter)<hr><form class="form-inline" method="post" action="{{ route('ezylaw.workflow.start',$selectedMatter) }}">@csrf<select class="form-control" name="workflow_stage_id" required>@foreach($templates as $t)<optgroup label="{{ $t->name }}">@foreach($t->stages as $s)<option value="{{ $s->id }}">{{ $s->sequence_no }}. {{ $s->name }}</option>@endforeach</optgroup>@endforeach</select><input type="datetime-local" class="form-control" name="due_at"><input class="form-control" name="notes" placeholder="Notes"><button class="btn btn-success">Start Stage</button></form>
<table class="table table-bordered table-striped law-table-compact"><thead><tr><th>Stage</th><th>Started</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($history as $h)<tr><td>{{ $h->stage_name }}</td><td>{{ optional($h->started_at)->format('Y-m-d H:i') }}</td><td>{{ optional($h->due_at)->format('Y-m-d H:i') }}</td><td>{{ ucfirst($h->status) }}</td><td>@if($h->status==='active')<form method="post" action="{{ route('ezylaw.workflow.complete',$h) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-success">Complete</button></form>@endif</td></tr>@empty<tr><td colspan="5">No workflow history.</td></tr>@endforelse</tbody></table>@endif</div></div>
@endsection
