@extends('stocktakingnew::layouts.app')
@section('stk_title','Stock Taking Command Center')
@section('stk_subtitle','Plan, count, recount, approve and reconcile physical stock across every business location and store.')
@section('stk_content')
<div class="stk-metric-grid">
 @php($cards=[['draft','Draft Sessions','fa-file-o','blue'],['counting','In Progress','fa-tasks','cyan'],['awaiting_approval','Awaiting Approval','fa-hourglass-half','purple'],['approved','Approved','fa-check','green'],['posted','Posted','fa-lock','green'],['variance_value','Variance Value','fa-balance-scale','orange']])
 @foreach($cards as $c)<a class="stk-metric-card {{ $c[3] }}" href="{{ route('stock-taking-new.sessions.index',['status'=>$c[0]==='awaiting_approval'?'submitted':$c[0]]) }}"><div class="stk-metric-icon"><i class="fa {{ $c[2] }}"></i></div><div><span>{{ $c[1] }}</span><strong>{{ $c[0]==='variance_value'?number_format((float)$stats[$c[0]],4):number_format((int)$stats[$c[0]]) }}</strong></div><i class="fa fa-angle-right stk-card-arrow"></i></a>@endforeach
</div>
<div class="stk-two-column">
 <section class="stk-card"><div class="stk-card-header"><div><h3><i class="fa fa-history"></i> Latest Sessions</h3><p>Most recent stock taking activity.</p></div><a href="{{ route('stock-taking-new.sessions.index') }}">View all</a></div><div class="table-responsive"><table class="stk-table"><thead><tr><th>No</th><th>Date</th><th>Location / Store</th><th>Progress</th><th>Variance</th><th>Status</th><th></th></tr></thead><tbody>@forelse($latest as $row)<tr><td><strong>{{ $row->stock_take_no }}</strong><small>{{ $row->title }}</small></td><td>{{ optional($row->count_date)->format('d M Y') }}</td><td>#{{ $row->location_id }} @if($row->store_id)/ #{{ $row->store_id }}@endif</td><td><div class="stk-progress"><span style="width:{{ $row->line_count?round($row->counted_line_count/$row->line_count*100):0 }}%"></span></div><small>{{ $row->counted_line_count }}/{{ $row->line_count }}</small></td><td class="text-right">{{ number_format((float)$row->variance_value_total,4) }}</td><td>@include('stocktakingnew::partials.status',['status'=>$row->status])</td><td><a class="stk-icon-btn" href="{{ route('stock-taking-new.sessions.show',$row) }}"><i class="fa fa-eye"></i></a></td></tr>@empty<tr><td colspan="7" class="stk-empty">No sessions created yet.</td></tr>@endforelse</tbody></table></div></section>
 <section class="stk-card"><div class="stk-card-header"><div><h3><i class="fa fa-bell"></i> Needs Attention</h3><p>Sessions requiring action.</p></div></div><div class="stk-action-list">@forelse($attention as $row)<a href="{{ route('stock-taking-new.sessions.show',$row) }}"><span class="stk-action-icon"><i class="fa {{ $row->status==='submitted'?'fa-check-circle':'fa-list-ol' }}"></i></span><span><strong>{{ $row->stock_take_no }}</strong><small>{{ $row->status==='submitted'?'Approval required':'Counting is incomplete' }}</small></span><i class="fa fa-angle-right"></i></a>@empty<div class="stk-empty">Nothing needs attention.</div>@endforelse</div></section>
</div>
<div class="stk-card"><div class="stk-card-header"><div><h3><i class="fa fa-bolt"></i> Quick Operations</h3><p>Open the most frequently used actions.</p></div></div><div class="stk-quick-grid"><a href="{{ route('stock-taking-new.sessions.create') }}"><i class="fa fa-plus"></i><strong>New Session</strong><small>Start a physical count</small></a><a href="{{ route('stock-taking-new.sessions.index',['status'=>'counting']) }}"><i class="fa fa-calculator"></i><strong>Continue Count</strong><small>Resume open counts</small></a><a href="{{ route('stock-taking-new.approvals.index') }}"><i class="fa fa-check"></i><strong>Approvals</strong><small>Review variances</small></a><a href="{{ route('stock-taking-new.reports.variance') }}"><i class="fa fa-line-chart"></i><strong>Variance Report</strong><small>Analyse differences</small></a><a href="{{ route('stock-taking-new.templates.index') }}"><i class="fa fa-copy"></i><strong>Templates</strong><small>Reusable count scopes</small></a><a href="{{ route('stock-taking-new.settings.index') }}"><i class="fa fa-cogs"></i><strong>Settings</strong><small>Rules and gateways</small></a></div></div>
@endsection
