@extends('pumperdashboardnew::layouts.operator')
@section('title',$payment->payment_number)
@section('pone_content')
<div class="pone-page-head"><div><div class="pone-page-kicker">Payment Record</div><h1>{{ $payment->payment_number }}</h1><p>{{ optional($payment->transaction_at)->format('Y-m-d H:i:s') }} · Shift {{ $shift->shift_number }}</p></div><div class="pone-actions"><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.payments.index') }}">Back</a>@if($payment->status==='confirmed'&&$payment->payment_type!=='credit')<a class="pone-btn pone-btn-warning" href="{{ route('pumper-dashboard-new.operator.payments.edit',$payment) }}">Edit</a>@endif<a class="pone-btn pone-btn-primary" href="{{ route('pumper-dashboard-new.operator.payments.print',$payment) }}">{{ $payment->printed_count?'Reprint':'Print' }}</a></div></div>
<div class="pone-grid pone-grid-2">
<div class="pone-panel"><div class="pone-panel-head"><h2>Payment Details</h2><span class="pone-badge pone-badge-{{ $payment->status }}">{{ $payment->status }}</span></div><div class="pone-panel-body"><dl class="pone-key-value"><dt>Type</dt><dd>{{ ucfirst($payment->payment_type) }}</dd><dt>Gross Amount</dt><dd class="pone-number">{{ number_format((float)$payment->gross_amount,4) }}</dd><dt>Discount</dt><dd class="pone-number">{{ number_format((float)$payment->discount_amount,4) }}</dd><dt>Net Amount</dt><dd class="pone-number"><strong>{{ number_format((float)$payment->amount,4) }}</strong></dd><dt>Reference</dt><dd>{{ $payment->reference_no ?: '-' }}</dd><dt>Collection Form</dt><dd>{{ $payment->collection_form_no ?: '-' }}</dd><dt>Integration</dt><dd><span class="pone-badge pone-badge-{{ $payment->integration_status }}">{{ $payment->integration_status }}</span> {{ $payment->integration_error }}</dd><dt>Note</dt><dd>{{ $payment->note ?: '-' }}</dd></dl></div></div>
<div class="pone-panel"><div class="pone-panel-head"><h2>Method Details</h2></div><div class="pone-panel-body">
@if($payment->payment_type==='cash')<div class="pone-table-wrap"><table class="pone-table pone-table-compact"><thead><tr><th>Denomination</th><th class="pone-text-right">Qty</th><th class="pone-text-right">Amount</th></tr></thead><tbody>@forelse($payment->cashDenominations as $row)<tr><td>{{ number_format((float)$row->denomination,2) }}</td><td class="pone-text-right">{{ $row->quantity }}</td><td class="pone-text-right pone-number">{{ number_format((float)$row->amount,4) }}</td></tr>@empty<tr><td colspan="3" class="pone-empty">Cash amount entered without denomination detail.</td></tr>@endforelse</tbody></table></div>
@elseif($payment->payment_type==='card')<div class="pone-table-wrap"><table class="pone-table pone-table-compact"><thead><tr><th>Card</th><th>Last 4</th><th>Slip</th><th>Reference</th><th class="pone-text-right">Amount</th></tr></thead><tbody>@forelse($payment->cardLines as $row)<tr><td>{{ $row->card_type ?: '-' }}</td><td>{{ $row->last_four ?: '-' }}</td><td>{{ $row->slip_no ?: '-' }}</td><td>{{ $row->reference_no ?: '-' }}</td><td class="pone-text-right pone-number">{{ number_format((float)$row->amount,4) }}</td></tr>@empty<tr><td colspan="5" class="pone-empty">No card lines.</td></tr>@endforelse</tbody></table></div>
@elseif($payment->payment_type==='cheque')<dl class="pone-key-value"><dt>Cheque No.</dt><dd>{{ $payment->cheque_no }}</dd><dt>Cheque Date</dt><dd>{{ optional($payment->cheque_date)->format('Y-m-d') }}</dd><dt>Bank</dt><dd>{{ $payment->bank_name ?: '-' }}</dd></dl>
@elseif($payment->payment_type==='credit' && $payment->creditSale)@php($c=$payment->creditSale)<dl class="pone-key-value"><dt>Customer</dt><dd>{{ $customers->get($payment->customer_id)->name ?? $payment->customer_id }}</dd><dt>Order No.</dt><dd>{{ $c->order_number }}</dd><dt>Vehicle</dt><dd>{{ $c->vehicle_number }}</dd><dt>Bill No.</dt><dd>{{ $c->bill_number ?: '-' }}</dd><dt>Confirmations</dt><dd>{{ $c->confirmation_rounds }} · Locked {{ optional($c->locked_at)->format('Y-m-d H:i') }}</dd></dl>@else<p class="pone-muted">No additional method details.</p>@endif
</div></div></div>
@if($payment->payment_type==='credit' && $payment->creditSale)<div class="pone-panel"><div class="pone-panel-head"><h2>Credit Sale Products</h2><span class="pone-badge pone-badge-credit">Locked</span></div><div class="pone-panel-body-compact"><div class="pone-table-wrap" style="border:0"><table class="pone-table"><thead><tr><th>Product</th><th class="pone-text-right">Qty</th><th class="pone-text-right">Unit Price</th><th class="pone-text-right">Discount</th><th class="pone-text-right">Amount</th></tr></thead><tbody>@foreach($payment->creditSale->lines as $line)<tr><td>{{ $products->get($line->product_id)->name ?? ('Product '.$line->product_id) }}</td><td class="pone-text-right">{{ number_format((float)$line->quantity,3) }}</td><td class="pone-text-right">{{ number_format((float)$line->unit_price,4) }}</td><td class="pone-text-right">{{ number_format((float)$line->discount_amount,4) }}</td><td class="pone-text-right"><strong>{{ number_format((float)$line->amount,4) }}</strong></td></tr>@endforeach</tbody></table></div></div></div>@endif
@if($payment->editHistories->isNotEmpty())<div class="pone-panel"><div class="pone-panel-head"><h2>Edit History</h2></div><div class="pone-panel-body-compact"><div class="pone-table-wrap" style="border:0"><table class="pone-table"><thead><tr><th>Version</th><th>Edited At</th><th>Edited By</th><th>Reason</th></tr></thead><tbody>@foreach($payment->editHistories as $history)<tr><td>v{{ $history->version_no }}</td><td>{{ optional($history->edited_at)->format('Y-m-d H:i:s') }}</td><td>{{ $history->edited_by ?: '-' }}</td><td class="pone-wrap">{{ $history->reason }}</td></tr>@endforeach</tbody></table></div></div></div>@endif
@if($payment->status==='confirmed')<div class="pone-panel pone-no-print"><div class="pone-panel-head"><h2>Void Payment</h2></div><div class="pone-panel-body"><form method="post" action="{{ route('pumper-dashboard-new.operator.payments.destroy',$payment) }}" data-confirm-message="Void this payment? This action is logged and becomes part of the Petro PD-New source snapshot." data-void-form>@csrf @method('DELETE')<div class="pone-form-grid"><div class="pone-field pone-col-9"><label class="pone-required">Reason</label><input name="reason" required></div><div class="pone-field pone-col-3" style="align-self:end"><button class="pone-btn pone-btn-danger pone-btn-block">Void Payment</button></div></div></form></div></div>@endif
@endsection
