<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    protected function schema(){return Schema::connection(config('egg.connection') ?: config('database.default'));}
    public function up(){
        $s=$this->schema();
        $s->create('egg_sequences',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->string('sequence_key',50);$t->unsignedBigInteger('current_value')->default(0);$t->timestamps();$t->unique(['business_id','sequence_key']);});
        $s->create('egg_grades',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->string('code',30);$t->string('name',100);$t->decimal('min_weight_g',10,2)->nullable();$t->decimal('max_weight_g',10,2)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('active')->default(1);$t->timestamps();$t->softDeletes();$t->unique(['business_id','code']);$t->index(['business_id','active']);});
        $s->create('egg_flocks',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('flock_code',50);$t->string('name',100);$t->string('breed',100)->nullable();$t->date('started_on')->nullable();$t->date('ended_on')->nullable();$t->unsignedInteger('bird_count')->nullable();$t->boolean('active')->default(1);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','flock_code']);$t->index(['business_id','location_id','active']);});
        $s->create('egg_collections',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('collection_no',50);$t->date('collection_date');$t->unsignedBigInteger('flock_id')->nullable();$t->string('shift',30)->nullable();$t->integer('total_pieces');$t->integer('good_pieces');$t->integer('broken_pieces')->default(0);$t->integer('dirty_pieces')->default(0);$t->integer('rejected_pieces')->default(0);$t->string('status',30)->default('open');$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','collection_no']);$t->index(['business_id','collection_date']);$t->index(['business_id','flock_id']);});
        $s->create('egg_collection_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('collection_id');$t->string('quality_type',30);$t->integer('pieces');$t->timestamps();$t->softDeletes();$t->index(['business_id','collection_id']);});
        $s->create('egg_grading_runs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('grading_no',50);$t->unsignedBigInteger('collection_id');$t->date('graded_on');$t->integer('input_pieces');$t->integer('output_pieces');$t->string('status',30);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','grading_no']);$t->index(['business_id','graded_on']);});
        $s->create('egg_grading_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('grading_run_id');$t->unsignedBigInteger('grade_id');$t->integer('pieces');$t->decimal('unit_cost',18,4)->default(0);$t->timestamps();$t->softDeletes();$t->index(['business_id','grading_run_id']);$t->index(['business_id','grade_id']);});
        $s->create('egg_stock_lots',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->unsignedBigInteger('grade_id');$t->string('lot_no',60);$t->date('collection_date')->nullable();$t->date('best_before')->nullable();$t->integer('received_pieces');$t->integer('available_pieces');$t->decimal('unit_cost',18,4)->default(0);$t->string('source_type',50);$t->unsignedBigInteger('source_id')->nullable();$t->string('status',30)->default('available');$t->timestamps();$t->softDeletes();$t->unique(['business_id','lot_no']);$t->index(['business_id','location_id','store_id','grade_id','status'],'egg_stock_scope_idx');});
        $s->create('egg_stock_movements',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->dateTime('movement_date');$t->string('direction',10);$t->unsignedBigInteger('grade_id');$t->integer('pieces');$t->decimal('unit_cost',18,4)->default(0);$t->unsignedBigInteger('stock_lot_id')->nullable();$t->string('source_type',50);$t->unsignedBigInteger('source_id')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->index(['business_id','movement_date']);$t->index(['business_id','grade_id','location_id','store_id'],'egg_move_scope_idx');});
        $s->create('egg_sales',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('sale_no',50);$t->date('sale_date');$t->unsignedBigInteger('customer_id')->nullable();$t->decimal('subtotal',18,4)->default(0);$t->decimal('discount',18,4)->default(0);$t->decimal('total',18,4)->default(0);$t->string('status',30);$t->string('payment_status',30);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','sale_no']);$t->index(['business_id','sale_date']);});
        $s->create('egg_sale_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('sale_id');$t->unsignedBigInteger('grade_id');$t->unsignedBigInteger('product_id')->nullable();$t->integer('pieces');$t->decimal('unit_price',18,4);$t->decimal('amount',18,4);$t->timestamps();$t->softDeletes();$t->index(['business_id','sale_id']);});
        $s->create('egg_purchases',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('purchase_no',50);$t->date('purchase_date');$t->unsignedBigInteger('supplier_id')->nullable();$t->string('supplier_reference',100)->nullable();$t->decimal('subtotal',18,4)->default(0);$t->decimal('discount',18,4)->default(0);$t->decimal('total',18,4)->default(0);$t->string('status',30);$t->string('payment_status',30);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','purchase_no']);$t->index(['business_id','purchase_date']);});
        $s->create('egg_purchase_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('purchase_id');$t->unsignedBigInteger('grade_id');$t->unsignedBigInteger('product_id')->nullable();$t->integer('pieces');$t->decimal('unit_cost',18,4);$t->decimal('amount',18,4);$t->date('best_before')->nullable();$t->timestamps();$t->softDeletes();$t->index(['business_id','purchase_id']);});
        $s->create('egg_transfers',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->string('transfer_no',50);$t->date('transfer_date');$t->unsignedBigInteger('from_location_id')->nullable();$t->unsignedBigInteger('from_store_id')->nullable();$t->unsignedBigInteger('to_location_id')->nullable();$t->unsignedBigInteger('to_store_id')->nullable();$t->string('status',30);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','transfer_no']);$t->index(['business_id','transfer_date']);});
        $s->create('egg_transfer_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('transfer_id');$t->unsignedBigInteger('grade_id');$t->integer('pieces');$t->timestamps();$t->softDeletes();$t->index(['business_id','transfer_id']);});
        $s->create('egg_adjustments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('location_id')->nullable();$t->unsignedBigInteger('store_id')->nullable();$t->string('adjustment_no',50);$t->date('adjustment_date');$t->string('reason',150);$t->string('status',30);$t->text('note')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['business_id','adjustment_no']);$t->index(['business_id','adjustment_date']);});
        $s->create('egg_adjustment_lines',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('adjustment_id');$t->unsignedBigInteger('grade_id');$t->integer('pieces');$t->decimal('unit_cost',18,4)->default(0);$t->timestamps();$t->softDeletes();$t->index(['business_id','adjustment_id']);});
        $s->create('egg_product_mappings',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('grade_id');$t->unsignedBigInteger('product_id');$t->unsignedInteger('pieces_per_unit')->default(1);$t->timestamps();$t->softDeletes();$t->unique(['business_id','grade_id','product_id'],'egg_product_mapping_unique');});
        $s->create('egg_integration_outbox',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->string('event_type',100);$t->string('aggregate_type',50)->nullable();$t->unsignedBigInteger('aggregate_id')->nullable();$t->json('payload');$t->string('status',30)->default('pending');$t->unsignedInteger('attempts')->default(0);$t->text('last_error')->nullable();$t->dateTime('processed_at')->nullable();$t->timestamps();$t->softDeletes();$t->index(['business_id','status','event_type'],'egg_outbox_idx');});
        $s->create('egg_share_links',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->string('token_hash',64)->unique();$t->string('resource_type',50);$t->unsignedBigInteger('resource_id')->nullable();$t->string('format',20)->default('html');$t->json('parameters')->nullable();$t->dateTime('expires_at');$t->dateTime('used_at')->nullable();$t->unsignedBigInteger('created_by')->nullable();$t->timestamps();$t->softDeletes();$t->index(['business_id','resource_type']);});
        $s->create('egg_audit_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('user_id')->nullable();$t->string('action',50);$t->string('auditable_type',80);$t->unsignedBigInteger('auditable_id')->nullable();$t->json('before_data')->nullable();$t->json('after_data')->nullable();$t->string('ip_address',64)->nullable();$t->string('user_agent',500)->nullable();$t->timestamps();$t->softDeletes();$t->index(['business_id','created_at']);});
        $s->create('egg_access_grants',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('business_id');$t->unsignedBigInteger('user_id');$t->string('permission',120);$t->boolean('allowed')->default(1);$t->timestamps();$t->softDeletes();$t->unique(['business_id','user_id','permission'],'egg_access_unique');});
    }
    public function down(){foreach(['egg_access_grants','egg_audit_logs','egg_share_links','egg_integration_outbox','egg_product_mappings','egg_adjustment_lines','egg_adjustments','egg_transfer_lines','egg_transfers','egg_purchase_lines','egg_purchases','egg_sale_lines','egg_sales','egg_stock_movements','egg_stock_lots','egg_grading_lines','egg_grading_runs','egg_collection_lines','egg_collections','egg_flocks','egg_grades','egg_sequences'] as $table){$this->schema()->dropIfExists($table);}}
};
