<?php
namespace Modules\EzyLaw\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Routing\Controller;
use Modules\EzyLaw\Entities\{LawDocument,LawDocumentApproval,LawEsignRequest,LawClient}; use Modules\EzyLaw\Services\DocumentApprovalService;
class DocumentApprovalController extends Controller {
 public function index(){return view('ezylaw::approvals.index',['documents'=>LawDocument::orderByDesc('id')->limit(200)->get(),'approvals'=>LawDocumentApproval::with(['document','matter'])->orderByDesc('id')->paginate(25),'esign'=>LawEsignRequest::with(['document','client','matter'])->orderByDesc('id')->limit(100)->get(),'clients'=>LawClient::where('status','active')->orderBy('name')->get()]);}
 public function requestApproval(Request $r,DocumentApprovalService $s){$d=$r->validate(['document_id'=>'required|integer','approver_user_id'=>'required|integer','version_no'=>'nullable|integer|min:1','comments'=>'nullable|string']);$s->requestApproval(LawDocument::findOrFail($d['document_id']),(int)$d['approver_user_id'],$d['version_no']??null,$d['comments']??null);return back()->with('success','Document approval requested.');}
 public function respond(Request $r,LawDocumentApproval $approval,DocumentApprovalService $s){$allowed=(int)$approval->approver_user_id===(int)auth()->id();if(!$allowed){$u=auth()->user();$allowed=method_exists($u,'roleAllowsPermission')?$u->roleAllowsPermission('ezylaw_document_approvals_respond_any'):$u->can('ezylaw_document_approvals_respond_any');}if(!$allowed)abort(403,'Only the assigned approver or an authorized supervisor can respond.');$d=$r->validate(['status'=>'required|in:approved,rejected,changes_requested','comments'=>'nullable|string']);$s->respond($approval,$d['status'],$d['comments']??null);return back()->with('success','Approval response saved.');}
 public function requestEsign(Request $r,DocumentApprovalService $s){$d=$r->validate(['document_id'=>'required|integer','client_id'=>'nullable|integer','recipient_name'=>'required|string|max:191','recipient_email'=>'required|email|max:191','version_no'=>'nullable|integer|min:1','expires_at'=>'nullable|date|after:now']);$result=$s->requestEsign(LawDocument::findOrFail($d['document_id']),$d);return back()->with('success','E-sign request created. It will appear in the matching client portal access for '.$d['recipient_email'].'.');}
}
