<?php
namespace Modules\EzyLaw\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Routing\Controller;
use Modules\EzyLaw\Entities\{LawFeeEstimate,LawClient,LawMatter}; use Modules\EzyLaw\Services\FeeEstimateService;
class EstimateController extends Controller {
 public function index(){return view('ezylaw::estimates.index',['estimates'=>LawFeeEstimate::with(['client','matter'])->orderByDesc('estimate_date')->paginate(25),'clients'=>LawClient::where('status','active')->orderBy('name')->get(),'matters'=>LawMatter::whereIn('status',['open','pending'])->orderBy('matter_no')->get()]);}
 public function store(Request $r,FeeEstimateService $s){$d=$r->validate(['client_id'=>'required|integer','matter_id'=>'nullable|integer','estimate_date'=>'required|date','valid_until'=>'nullable|date|after_or_equal:estimate_date','tax_amount'=>'nullable|numeric|min:0','discount_amount'=>'nullable|numeric|min:0','notes'=>'nullable|string','description'=>'required|array|min:1','description.*'=>'nullable|string|max:1000','qty'=>'required|array','qty.*'=>'nullable|numeric|min:0','unit_price'=>'required|array','unit_price.*'=>'nullable|numeric|min:0']);$lines=[];foreach($d['description'] as $i=>$desc){if(trim((string)$desc)==='')continue;$lines[]=['description'=>$desc,'qty'=>(float)($d['qty'][$i]??1),'unit_price'=>(float)($d['unit_price'][$i]??0)];}$s->create(['client_id'=>$d['client_id'],'matter_id'=>$d['matter_id']??null,'estimate_date'=>$d['estimate_date'],'valid_until'=>$d['valid_until']??null,'tax_amount'=>$d['tax_amount']??0,'discount_amount'=>$d['discount_amount']??0,'notes'=>$d['notes']??null],$lines);return back()->with('success','Fee estimate created.');}
 public function show(LawFeeEstimate $estimate){$estimate->load(['client','matter','lines','invoice']);return view('ezylaw::estimates.show',compact('estimate'));}
 public function status(Request $r,LawFeeEstimate $estimate,FeeEstimateService $s){$d=$r->validate(['status'=>'required|in:draft,sent,accepted,rejected']);$s->setStatus($estimate,$d['status']);return back()->with('success','Estimate status updated.');}
 public function convert(Request $r,LawFeeEstimate $estimate,FeeEstimateService $s){$d=$r->validate(['invoice_date'=>'nullable|date','due_date'=>'nullable|date']);$invoice=$s->convertToInvoice($estimate,$d);return redirect()->route('ezylaw.billing.show',$invoice)->with('success','Estimate converted to invoice.');}
}
