<?php
namespace Modules\EzyLaw\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Routing\Controller;
use Modules\EzyLaw\Entities\{LawPortalMessage,LawEsignRequest}; use Modules\EzyLaw\Services\PortalPublicService;
class PublicPortalController extends Controller {
 public function show(Request $r,string $token,PortalPublicService $s){$access=$s->resolve($token);$access->update(['last_login_at'=>now()]);$s->audit($access,'portal_view',$r);return view('ezylaw::portal.public',['token'=>$token,'access'=>$access]+$s->dashboard($access));}
 public function message(Request $r,string $token,PortalPublicService $s){$access=$s->resolve($token);$d=$r->validate(['matter_id'=>'nullable|integer','subject'=>'nullable|string|max:191','body'=>'required|string|max:10000']);$matterId=$s->validateMatter($access,isset($d['matter_id'])?(int)$d['matter_id']:null);LawPortalMessage::withoutGlobalScopes()->create(['business_id'=>$access->business_id,'client_id'=>$access->client_id,'matter_id'=>$matterId,'direction'=>'inbound','subject'=>$d['subject']??null,'body'=>$d['body'],'status'=>'logged','sent_at'=>now(),'created_by'=>null]);$s->audit($access,'message_sent',$r,$matterId);return back()->with('success','Your message has been sent.');}
 public function esign(Request $r,string $token,LawEsignRequest $esign,PortalPublicService $s){$access=$s->resolve($token);$esign=LawEsignRequest::withoutGlobalScopes()->where('business_id',$access->business_id)->where('client_id',$access->client_id)->where('recipient_email',$access->email)->whereKey($esign->id)->firstOrFail();if($esign->expires_at&&$esign->expires_at->isPast())abort(403,'This signing request has expired.');if(!in_array($esign->status,['pending','viewed'],true))abort(422,'This signing request is already completed.');$d=$r->validate(['action'=>'required|in:sign,decline','signature_name'=>'nullable|string|max:191']);if($d['action']==='sign'&&trim((string)($d['signature_name']??''))==='')return back()->withErrors(['signature_name'=>'Signature name is required.']);if($d['action']==='sign')$esign->update(['status'=>'signed','signed_at'=>now(),'signature_name'=>$d['signature_name'],'signature_ip'=>$r->ip(),'signature_user_agent'=>substr((string)$r->userAgent(),0,2000)]);else $esign->update(['status'=>'declined','declined_at'=>now(),'signature_ip'=>$r->ip(),'signature_user_agent'=>substr((string)$r->userAgent(),0,2000)]);$s->audit($access,'esign_'.$d['action'],$r,$esign->matter_id,['esign_request_id'=>$esign->id]);return back()->with('success',$d['action']==='sign'?'Document signed.':'Signing request declined.');}
}
