@extends('hrmanager::layouts.master')
@section('hr_content')
<div class="hr-page">
@include('hrmanager::dashboard.partials.header',['title'=>'Face Attendance','subtitle'=>'Face enrollment, device management, verification logs and attendance capture connected to Employee Central Record.','section'=>'Face Attendance'])
<div class="hr-card-grid">
<div class="hr-kpi purple"><i class="fa fa-users"></i><span>Employees</span><strong>{{ number_format($stats['employees'] ?? 0) }}</strong></div>
<div class="hr-kpi green"><i class="fa fa-user-circle"></i><span>Face Profiles</span><strong>{{ number_format($stats['profiles'] ?? 0) }}</strong></div>
<div class="hr-kpi blue"><i class="fa fa-camera"></i><span>Devices</span><strong>{{ number_format($stats['devices'] ?? 0) }}</strong></div>
<div class="hr-kpi orange"><i class="fa fa-wifi"></i><span>Online Devices</span><strong>{{ number_format($stats['online_devices'] ?? 0) }}</strong></div>
<div class="hr-kpi green"><i class="fa fa-check"></i><span>Success Today</span><strong>{{ number_format($stats['success_today'] ?? 0) }}</strong></div>
<div class="hr-kpi red"><i class="fa fa-warning"></i><span>Failed Today</span><strong>{{ number_format($stats['failed_today'] ?? 0) }}</strong></div>
<div class="hr-kpi orange"><i class="fa fa-question"></i><span>Unknown Today</span><strong>{{ number_format($stats['unknown_today'] ?? 0) }}</strong></div>
<div class="hr-kpi red"><i class="fa fa-ban"></i><span>Blacklist</span><strong>{{ number_format($stats['blacklist'] ?? 0) }}</strong></div>
</div>
<div class="face-grid">
<div class="hr-panel"><h3>Face Enrollment</h3><div class="camera-box"><i class="fa fa-camera"></i><span>Camera Preview</span><small>Ready for camera integration</small></div><form method="POST" action="{{ route('hrmanager.face.enroll') }}" class="face-form">@csrf<label>Employee</label><select name="employee_id" required><option value="">Select Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no ?? $employee->id }} - {{ $employee->full_name ?? '' }}</option>@endforeach</select><label>Quality Score</label><input type="number" step="0.01" name="quality_score" value="95.00"><label>Remarks</label><textarea name="remarks"></textarea><button class="hr-primary-btn">Enroll Face</button></form></div>
<div class="hr-panel"><h3>Add Face Device</h3><form method="POST" action="{{ route('hrmanager.face.devices.store') }}" class="face-form">@csrf<label>Device Name</label><input name="device_name" required><label>Device Type</label><select name="device_type"><option value="generic_rest">Generic REST API</option><option value="zkteco">ZKTeco</option><option value="hikvision">Hikvision</option><option value="suprema">Suprema</option><option value="anviz">Anviz</option><option value="essl">eSSL</option></select><label>Brand / Model</label><div class="two-cols"><input name="brand" placeholder="Brand"><input name="model" placeholder="Model"></div><label>IP / Port</label><div class="two-cols"><input name="ip_address" placeholder="IP Address"><input name="port" placeholder="Port"></div><label>API Base URL</label><input name="api_base_url"><button class="hr-primary-btn">Save Device</button></form></div>
<div class="hr-panel"><h3>Simulate Attendance Log</h3><form method="POST" action="{{ route('hrmanager.face.simulate_log') }}" class="face-form">@csrf<label>Employee</label><select name="employee_id" required><option value="">Select Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no ?? $employee->id }} - {{ $employee->full_name ?? '' }}</option>@endforeach</select><label>Device</label><select name="device_id"><option value="">Web Camera</option>@foreach($devices as $device)<option value="{{ $device->id }}">{{ $device->device_name }}</option>@endforeach</select><label>Log Type</label><select name="log_type"><option value="sign_in">Sign In</option><option value="sign_out">Sign Out</option></select><label>Confidence Score</label><input type="number" step="0.01" name="confidence_score" value="98.50"><button class="hr-primary-btn">Record Face Attendance</button></form></div>
</div>
<div class="hr-panel"><h3>Face Attendance Logs</h3>@include('hrmanager::components.list-toolbar',['searchPlaceholder'=>'Search log no, employee, status'])<table class="hr-table"><thead><tr><th>Log No</th><th>Time</th><th>Employee</th><th>Device</th><th>Type</th><th>Status</th><th>Confidence</th><th>Recognition Time</th></tr></thead><tbody>@forelse($logs as $row)<tr><td>{{ $row->log_no }}</td><td>{{ $row->log_time }}</td><td>#{{ $row->employee_id }}</td><td>{{ $row->device_id }}</td><td>{{ $row->log_type }}</td><td><em class="status-pill">{{ ucfirst($row->recognition_status) }}</em></td><td>{{ number_format($row->confidence_score, 2) }}%</td><td>{{ $row->recognition_time_ms }} ms</td></tr>@empty<tr><td colspan="8" class="empty-row">No face attendance logs found.</td></tr>@endforelse</tbody></table>@if(method_exists($logs,'links')){{ $logs->links() }}@endif</div>
<div class="face-grid bottom"><div class="hr-panel"><h3>Face Profiles</h3><table class="hr-table compact-table"><thead><tr><th>Employee</th><th>Quality</th><th>Status</th></tr></thead><tbody>@forelse($profiles as $row)<tr><td>#{{ $row->employee_id }}</td><td>{{ number_format($row->quality_score, 2) }}%</td><td><em class="status-pill">{{ $row->enrollment_status }}</em></td></tr>@empty<tr><td colspan="3" class="empty-row">No profiles enrolled.</td></tr>@endforelse</tbody></table></div><div class="hr-panel"><h3>Devices</h3><table class="hr-table compact-table"><thead><tr><th>Device</th><th>Type</th><th>Online</th></tr></thead><tbody>@forelse($devices as $row)<tr><td>{{ $row->device_name }}</td><td>{{ $row->device_type }}</td><td><em class="status-pill">{{ $row->online_status }}</em></td></tr>@empty<tr><td colspan="3" class="empty-row">No devices configured.</td></tr>@endforelse</tbody></table></div><div class="hr-panel"><h3>Verification Logs</h3><table class="hr-table compact-table"><thead><tr><th>Employee</th><th>Status</th><th>Score</th></tr></thead><tbody>@forelse($verificationLogs as $row)<tr><td>#{{ $row->employee_id }}</td><td><em class="status-pill">{{ $row->verification_status }}</em></td><td>{{ number_format($row->confidence_score, 2) }}%</td></tr>@empty<tr><td colspan="3" class="empty-row">No verification logs.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
