<div class="ran-document"><header><h2>{{ $template->name }}</h2><div>{{ strtoupper(str_replace('_',' ',$type)) }}: <strong>{{ app(\Modules\Ran\Services\DocumentService::class)->number($type,$document) }}</strong></div></header>
@foreach($template->sections->whereIn('section_key',$sections)->sortBy('sort_order') as $section)<section class="ran-doc-section ran-section-{{ $section->section_key }}"><h4>{{ $section->title }}</h4>
@if($section->section_key==='header')<p><strong>{{ session('business.name','Business') }}</strong><br>{{ session('business.address') }}</p>
@elseif(in_array($section->section_key,['customer','supplier','artisan']))<p>@if($type==='sale'){{ $document->customer_name }}<br>{{ $document->customer_mobile }}<br>{{ $document->customer_email }}@elseif($type==='purchase'){{ $document->supplier?->supplier_business_name ?: $document->supplier?->name }}<br>{{ $document->supplier?->mobile }}@elseif($type==='production_order'){{ $document->artisan?->name }}<br>{{ $document->artisan?->phone }}@endif</p>
@elseif(in_array($section->section_key,['items','materials','design']))<table class="table table-bordered"><thead><tr><th>Description</th><th class="text-right">Qty</th><th class="text-right">Net Weight</th><th class="text-right">Amount/Cost</th></tr></thead><tbody>@foreach($document->lines??[] as $line)<tr><td>{{ $line->item?->name ?: $line->description }}</td><td class="text-right">{{ $line->quantity ?? $line->planned_quantity }}</td><td class="text-right">{{ $line->net_weight ?? $line->planned_net_weight }}</td><td class="text-right">{{ number_format((float)($line->line_total ?? $line->estimated_cost ?? 0),4) }}</td></tr>@endforeach</tbody></table>
@elseif(in_array($section->section_key,['charges','totals']))<table class="table"><tr><th>Subtotal</th><td class="text-right">{{ number_format((float)($document->subtotal??0),4) }}</td></tr><tr><th>Discount</th><td class="text-right">{{ number_format((float)($document->discount_amount??0),4) }}</td></tr><tr><th>Tax</th><td class="text-right">{{ number_format((float)($document->tax_amount??0),4) }}</td></tr><tr><th>Total</th><td class="text-right"><strong>{{ number_format((float)($document->total_amount??$document->estimated_cost??0),4) }}</strong></td></tr></table>
@elseif($section->section_key==='payments')<p>Paid: {{ number_format((float)$document->paid_amount,4) }} &nbsp; Balance: {{ number_format((float)$document->balance_amount,4) }}</p>
@elseif(in_array($section->section_key,['terms','instructions']))<p>{!! nl2br(e($document->terms??$document->notes??'')) !!}</p>
@elseif($section->section_key==='weights')<p>Gross: {{ $document->lines?->sum('gross_weight') }} &nbsp; Net: {{ $document->lines?->sum('net_weight') }} &nbsp; Stone: {{ $document->lines?->sum('stone_weight') }}</p>
@elseif($section->section_key==='route')<p>From: {{ $document->from_location_id }}/{{ $document->from_store_id }} &nbsp; To: {{ $document->to_location_id }}/{{ $document->to_store_id }}</p>
@elseif(in_array($section->section_key,['signature','approval','dispatch','receipt']))<div style="height:70px"></div><div>______________________________</div>
@else<p>{{ $document->notes ?? '' }}</p>@endif</section>@endforeach</div>
