@extends('stocktakingnew::layouts.app')
@section('stk_title','Create Stock Taking Session')
@section('stk_subtitle','Define the count scope, location, store, counting mode and responsible team.')
@section('stk_content')
<form method="post" action="{{ route('stock-taking-new.sessions.store') }}" class="stk-form">@csrf
<div class="stk-form-grid">
 <section class="stk-card stk-card-accent blue"><div class="stk-card-header"><div><h3><span class="stk-square-icon"><i class="fa fa-info"></i></span> Session Details</h3><p>Basic identification and count date.</p></div></div><div class="stk-card-body stk-fields"><div class="wide"><label>Session Title *</label><input name="title" value="{{ old('title') }}" class="form-control" required placeholder="Example: July Main Store Full Count"></div><div><label>Count Date *</label><input type="date" name="count_date" value="{{ old('count_date',now()->toDateString()) }}" class="form-control" required></div><div><label>Reusable Template</label><select name="template_id" class="form-control"><option value="">No template</option>@foreach($templates as $id=>$name)<option value="{{ $id }}" @selected((string)old('template_id')===(string)$id)>{{ $name }}</option>@endforeach</select></div><div class="wide"><label>Notes</label><textarea name="notes" class="form-control" rows="3">{{ old('notes') }}</textarea></div></div></section>
 <section class="stk-card stk-card-accent green"><div class="stk-card-header"><div><h3><span class="stk-square-icon green"><i class="fa fa-map-marker"></i></span> Inventory Scope</h3><p>Select the exact business location and store.</p></div></div><div class="stk-card-body stk-fields"><div><label>Location *</label><select name="location_id" class="form-control stk-location-select" required><option value="">Select location</option>@foreach($locations as $id=>$name)<option value="{{ $id }}" @selected((string)old('location_id')===(string)$id)>{{ $name }}</option>@endforeach</select></div><div><label>Store</label><select name="store_id" class="form-control stk-store-select" data-selected="{{ old('store_id') }}"><option value="">Location-level stock</option></select></div><div><label>Category</label><select name="scope[category_id]" class="form-control"><option value="">All Categories</option>@foreach($categories as $id=>$name)<option value="{{ $id }}" @selected((string)old('scope.category_id')===(string)$id)>{{ $name }}</option>@endforeach</select></div><div><label>Brand</label><select name="scope[brand_id]" class="form-control"><option value="">All Brands</option>@foreach($brands as $id=>$name)<option value="{{ $id }}" @selected((string)old('scope.brand_id')===(string)$id)>{{ $name }}</option>@endforeach</select></div><div class="wide"><label>Specific Products</label><div class="stk-product-picker" data-url="{{ route('stock-taking-new.lookup.products') }}"><div class="stk-product-search-row"><input type="search" class="form-control stk-product-search-input" placeholder="Type product name, SKU or scan barcode"><button type="button" class="stk-btn stk-btn-light stk-product-search-button"><i class="fa fa-search"></i> Find</button></div><div class="stk-product-results"></div><div class="stk-selected-products">@foreach((array)old('scope.product_ids',[]) as $productId)<span data-product-id="{{ $productId }}">Product #{{ $productId }} <button type="button" aria-label="Remove">×</button><input type="hidden" name="scope[product_ids][]" value="{{ $productId }}"></span>@endforeach</div></div></div><div class="wide stk-hint"><i class="fa fa-lightbulb-o"></i> Leave all scope filters empty for a full location/store count. Selecting specific products limits the snapshot to those products.</div></div></section>
 <section class="stk-card stk-card-accent orange"><div class="stk-card-header"><div><h3><span class="stk-square-icon orange"><i class="fa fa-sliders"></i></span> Counting Rules</h3><p>Control visibility and variance recount rules.</p></div></div><div class="stk-card-body stk-fields"><div><label>Count Method *</label><select name="count_method" class="form-control"><option value="full">Full Count</option><option value="cycle">Cycle Count</option><option value="spot">Spot Count</option></select></div><div><label>Count Mode *</label><select name="count_mode" class="form-control"><option value="blind" @selected(old('count_mode',$moduleSettings['default_count_mode']??'blind')==='blind')>Blind – hide system quantity</option><option value="open" @selected(old('count_mode')==='open')>Open – show system quantity</option></select></div><div><label>Variance Qty Threshold</label><input type="number" step="0.0001" name="variance_qty_threshold" value="{{ old('variance_qty_threshold',0) }}" class="form-control"></div><div><label>Variance Value Threshold</label><input type="number" step="0.0001" name="variance_value_threshold" value="{{ old('variance_value_threshold',0) }}" class="form-control"></div><label class="stk-switch-row"><input type="checkbox" name="freeze_stock" value="1" @checked(old('freeze_stock'))><span>Mark snapshot as frozen during the count</span></label><label class="stk-switch-row"><input type="checkbox" name="require_recount" value="1" @checked(old('require_recount',true))><span>Require recount when threshold is exceeded</span></label></div></section>
 <section class="stk-card stk-card-accent purple"><div class="stk-card-header"><div><h3><span class="stk-square-icon purple"><i class="fa fa-users"></i></span> Counting Team</h3><p>Assign one or more users to enter counts.</p></div></div><div class="stk-card-body"><label>Assigned Users</label><select name="assigned_users[]" class="form-control" multiple size="9">@foreach($users as $id=>$name)<option value="{{ $id }}" @selected(in_array($id,(array)old('assigned_users',[])))>{{ $name }}</option>@endforeach</select><div class="stk-hint"><i class="fa fa-info-circle"></i> Hold Ctrl to select multiple users.</div></div></section>
</div><div class="stk-sticky-actions"><a href="{{ route('stock-taking-new.sessions.index') }}" class="stk-btn stk-btn-light">Cancel</a><button class="stk-btn stk-btn-primary"><i class="fa fa-save"></i> Create Session</button></div></form>
@endsection
