@extends('autoservice::layouts.master')
@section('title','Auto Service Invoices')
@section('autoservice_content')
<div class="box"><div class="box-header with-border"><h3 class="box-title">{{ $invoice->id ? 'Edit' : 'Add' }} Invoice</h3></div>
<form method="post" action="{{ $invoice->id ? route('autoservice.invoices.update',$invoice->id) : route('autoservice.invoices.store') }}">
@csrf @if($invoice->id) @method('PUT') @endif
<div class="box-body">
<div class="row">
<div class="col-md-3"><label>Invoice Date</label><input type="date" name="invoice_date" class="form-control" value="{{ old('invoice_date',$invoice->invoice_date ?: date('Y-m-d')) }}"></div>
<div class="col-md-3"><label>Status</label><select name="status" class="form-control"><option value="draft" @selected($invoice->status=='draft')>Draft</option><option value="issued" @selected($invoice->status=='issued')>Issued</option><option value="partial" @selected($invoice->status=='partial')>Partial</option><option value="paid" @selected($invoice->status=='paid')>Paid</option><option value="cancelled" @selected($invoice->status=='cancelled')>Cancelled</option></select></div>
<div class="col-md-3"><label>Customer</label><select name="contact_id" class="form-control"><option value="">Please Select</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string) $invoice->contact_id === (string) $customer->id)>{{ $customer->name }}{{ !empty($customer->mobile) ? ' - '.$customer->mobile : '' }}</option>@endforeach</select></div>
<div class="col-md-3"><label>Vehicle</label><select name="vehicle_id" class="form-control"><option value="">Please Select</option>@foreach($vehicles as $v)<option value="{{ $v->id }}" @selected($invoice->vehicle_id==$v->id)>{{ $v->registration_no }} - {{ $v->make }} {{ $v->model }}</option>@endforeach</select></div>
</div>
<div class="row" style="margin-top:10px"><div class="col-md-3"><label>Job Card</label><select name="job_id" class="form-control"><option value="">Please Select</option>@foreach($jobs as $j)<option value="{{ $j->id }}" @selected($invoice->job_id==$j->id)>{{ $j->job_no }}</option>@endforeach</select></div><div class="col-md-3"><label>Discount</label><input name="discount_amount" class="form-control input_number" value="{{ old('discount_amount',$invoice->discount_amount ?? 0) }}"></div><div class="col-md-3"><label>Tax</label><input name="tax_amount" class="form-control input_number" value="{{ old('tax_amount',$invoice->tax_amount ?? 0) }}"></div><div class="col-md-3"><label>Paid Amount</label><input name="paid_amount" class="form-control input_number" value="{{ old('paid_amount',$invoice->paid_amount ?? 0) }}"></div></div>
<hr><h4>Invoice Lines</h4><table class="table table-bordered" id="invoice-lines"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Unit Price</th><th></th></tr></thead><tbody>
@php($lines = old('lines', $invoice->lines && count($invoice->lines) ? $invoice->lines->toArray() : [['line_type'=>'service','description'=>'','quantity'=>1,'unit_price'=>0]]))
@foreach($lines as $i=>$line)<tr><td><select name="lines[{{ $i }}][line_type]" class="form-control"><option value="service" @selected(($line['line_type']??'')=='service')>Service/Labour</option><option value="part" @selected(($line['line_type']??'')=='part')>Part</option></select></td><td><input name="lines[{{ $i }}][description]" class="form-control" value="{{ $line['description'] ?? '' }}"></td><td><input name="lines[{{ $i }}][quantity]" class="form-control input_number" value="{{ $line['quantity'] ?? 1 }}"></td><td><input name="lines[{{ $i }}][unit_price]" class="form-control input_number" value="{{ $line['unit_price'] ?? 0 }}"></td><td><button type="button" class="btn btn-danger btn-xs remove-line">X</button></td></tr>@endforeach
</tbody></table><button type="button" class="btn btn-default btn-sm" id="add-invoice-line">Add Line</button>
<div class="row" style="margin-top:10px"><div class="col-md-6"><label>Terms</label><textarea name="terms" class="form-control">{{ old('terms',$invoice->terms) }}</textarea></div><div class="col-md-6"><label>Internal Note</label><textarea name="internal_note" class="form-control">{{ old('internal_note',$invoice->internal_note) }}</textarea></div></div>
</div><div class="box-footer"><button class="btn btn-primary">Save Invoice</button><a href="{{ route('autoservice.invoices.index') }}" class="btn btn-default">Cancel</a></div></form></div>
<script>document.addEventListener('click',function(e){if(e.target.id==='add-invoice-line'){var tb=document.querySelector('#invoice-lines tbody'),i=tb.children.length;tb.insertAdjacentHTML('beforeend','<tr><td><select name="lines['+i+'][line_type]" class="form-control"><option value="service">Service/Labour</option><option value="part">Part</option></select></td><td><input name="lines['+i+'][description]" class="form-control"></td><td><input name="lines['+i+'][quantity]" class="form-control input_number" value="1"></td><td><input name="lines['+i+'][unit_price]" class="form-control input_number" value="0"></td><td><button type="button" class="btn btn-danger btn-xs remove-line">X</button></td></tr>')}if(e.target.classList.contains('remove-line')){e.target.closest('tr').remove();}});</script>
@endsection
