-- Stock Adjustment New - idempotent tenant table creation
CREATE TABLE IF NOT EXISTS `san_stock_adjustment_reasons` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(191) NOT NULL,
  `code` VARCHAR(50) NULL,
  `effect` VARCHAR(20) NOT NULL DEFAULT 'both',
  `requires_approval` TINYINT(1) NOT NULL DEFAULT 1,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `san_reason_business_idx` (`business_id`),
  KEY `san_reason_code_idx` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `adjustment_no` VARCHAR(191) NOT NULL,
  `adjustment_date` DATE NOT NULL,
  `adjustment_type` VARCHAR(50) NOT NULL DEFAULT 'quantity',
  `stock_adjustment_type` VARCHAR(20) NOT NULL DEFAULT 'increase',
  `reason_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'draft',
  `total_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `total_cost_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `approved_by` BIGINT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL,
  `approval_remarks` TEXT NULL,
  `posted_by` BIGINT UNSIGNED NULL,
  `posted_at` TIMESTAMP NULL,
  `host_transaction_id` BIGINT UNSIGNED NULL,
  `posting_summary` JSON NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `san_adj_business_no_unique` (`business_id`,`adjustment_no`),
  KEY `san_adj_scope_idx` (`business_id`,`location_id`,`store_id`),
  KEY `san_adj_status_idx` (`status`),
  KEY `san_adj_date_idx` (`adjustment_date`),
  KEY `san_adj_stock_type_idx` (`stock_adjustment_type`),
  KEY `san_adj_host_transaction_idx` (`host_transaction_id`),
  KEY `san_adj_business_status_date_idx` (`business_id`,`status`,`adjustment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustment_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adjustment_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `product_name` VARCHAR(191) NULL,
  `sku` VARCHAR(191) NULL,
  `batch_no` VARCHAR(191) NULL,
  `expiry_date` DATE NULL,
  `system_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `counted_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `adjustment_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `stock_adjustment_type` VARCHAR(20) NOT NULL DEFAULT 'increase',
  `unit_cost` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `cost_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `line_notes` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `san_line_adjustment_idx` (`adjustment_id`),
  KEY `san_line_product_idx` (`product_id`,`variation_id`),
  KEY `san_line_batch_idx` (`batch_no`),
  KEY `san_line_stock_type_idx` (`stock_adjustment_type`),
  KEY `san_line_product_batch_expiry_idx` (`product_id`,`batch_no`,`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustment_movements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `adjustment_id` BIGINT UNSIGNED NOT NULL,
  `adjustment_line_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `batch_no` VARCHAR(191) NULL,
  `movement_type` VARCHAR(30) NOT NULL,
  `qty_change` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `cost_change` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `movement_date` TIMESTAMP NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `san_mov_scope_idx` (`business_id`,`location_id`,`store_id`),
  KEY `san_mov_product_idx` (`product_id`,`variation_id`),
  KEY `san_mov_adjustment_idx` (`adjustment_id`),
  KEY `san_mov_scope_date_idx` (`business_id`,`location_id`,`store_id`,`movement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustment_audits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NULL,
  `adjustment_id` BIGINT UNSIGNED NOT NULL,
  `event` VARCHAR(80) NOT NULL,
  `payload` JSON NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `san_audit_business_idx` (`business_id`),
  KEY `san_audit_adjustment_idx` (`adjustment_id`),
  KEY `san_audit_event_idx` (`event`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustment_settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `number_prefix` VARCHAR(30) NOT NULL DEFAULT 'SAN-',
  `number_padding` TINYINT UNSIGNED NOT NULL DEFAULT 5,
  `default_adjustment_type` VARCHAR(30) NOT NULL DEFAULT 'quantity',
  `default_page_size` SMALLINT UNSIGNED NOT NULL DEFAULT 25,
  `quantity_decimals` TINYINT UNSIGNED NOT NULL DEFAULT 4,
  `amount_decimals` TINYINT UNSIGNED NOT NULL DEFAULT 4,
  `require_reason` TINYINT(1) NOT NULL DEFAULT 0,
  `require_location` TINYINT(1) NOT NULL DEFAULT 1,
  `require_store` TINYINT(1) NOT NULL DEFAULT 0,
  `require_approval` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_submit` TINYINT(1) NOT NULL DEFAULT 0,
  `auto_post_after_approval` TINYINT(1) NOT NULL DEFAULT 0,
  `require_batch_when_available` TINYINT(1) NOT NULL DEFAULT 1,
  `hide_zero_stock_products` TINYINT(1) NOT NULL DEFAULT 0,
  `allow_negative_stock` TINYINT(1) NOT NULL DEFAULT 0,
  `allow_zero_unit_cost` TINYINT(1) NOT NULL DEFAULT 1,
  `allow_backdated_adjustments` TINYINT(1) NOT NULL DEFAULT 1,
  `max_backdate_days` INT UNSIGNED NULL,
  `allow_future_dated_adjustments` TINYINT(1) NOT NULL DEFAULT 1,
  `batch_selection_method` VARCHAR(20) NOT NULL DEFAULT 'fefo',
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `san_settings_business_unique` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `san_stock_adjustment_account_mappings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `effective_from` TIMESTAMP NULL,
  `adjustment_type` VARCHAR(30) NOT NULL DEFAULT 'quantity',
  `category_id` BIGINT UNSIGNED NULL,
  `sub_category_id` BIGINT UNSIGNED NULL,
  `account_to_link_id` BIGINT UNSIGNED NULL,
  `increase_account_id` BIGINT UNSIGNED NULL,
  `decrease_account_id` BIGINT UNSIGNED NULL,
  `stock_account_group_id` BIGINT UNSIGNED NULL,
  `stock_account_id` BIGINT UNSIGNED NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `san_mapping_business_idx` (`business_id`),
  KEY `san_mapping_effective_idx` (`effective_from`),
  KEY `san_mapping_type_idx` (`adjustment_type`),
  KEY `san_mapping_category_idx` (`category_id`),
  KEY `san_mapping_sub_category_idx` (`sub_category_id`),
  KEY `san_mapping_account_link_idx` (`account_to_link_id`),
  KEY `san_mapping_increase_account_idx` (`increase_account_id`),
  KEY `san_mapping_decrease_account_idx` (`decrease_account_id`),
  KEY `san_mapping_stock_group_idx` (`stock_account_group_id`),
  KEY `san_mapping_stock_account_idx` (`stock_account_id`),
  KEY `san_mapping_active_idx` (`is_active`),
  KEY `san_mapping_lookup_idx` (`business_id`,`adjustment_type`,`category_id`,`sub_category_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
