@extends('ezylaw::layouts.module')
@section('ezylaw_title','Parties / Counsel - '.$matter->matter_no)
@section('ezylaw_content')
<div class="law-subnav"><a class="btn btn-default" href="{{ route('ezylaw.matters.show',$matter) }}">Back to Matter</a><a class="btn btn-default" href="{{ route('ezylaw.chronology.index',$matter) }}">Chronology</a></div>
<div class="row"><div class="col-md-4"><div class="box box-primary"><div class="box-header"><h3 class="box-title">Add Party / Counsel</h3></div><form method="post" action="{{ route('ezylaw.parties.store',$matter) }}"><div class="box-body">@csrf
<label>Type</label><select class="form-control" name="party_type" required><option value="client">Client / Applicant</option><option value="opponent">Opponent / Respondent</option><option value="witness">Witness</option><option value="counsel">Counsel / Attorney</option><option value="expert">Expert</option><option value="court_officer">Court Officer</option><option value="other">Other</option></select>
<label>Name</label><input class="form-control" name="name" required><label>Role</label><input class="form-control" name="role"><label>Phone</label><input class="form-control" name="phone"><label>Email</label><input class="form-control" type="email" name="email"><label>Address</label><textarea class="form-control" name="address" rows="3"></textarea>
</div><div class="box-footer"><button class="btn btn-primary">Add Party</button></div></form></div></div>
<div class="col-md-8"><div class="box"><div class="box-header"><h3 class="box-title">Matter Parties</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Type</th><th>Name / Role</th><th>Contact</th><th>Address</th><th>Action</th></tr></thead><tbody>@forelse($parties as $p)<tr><td>{{ ucfirst(str_replace('_',' ',$p->party_type)) }}</td><td><b>{{ $p->name }}</b><br><small>{{ $p->role }}</small></td><td>{{ $p->phone }}<br>{{ $p->email }}</td><td>{{ $p->address }}</td><td><form method="post" action="{{ route('ezylaw.parties.destroy',[$matter,$p]) }}">@csrf @method('DELETE')<button class="btn btn-xs btn-danger" onclick="return confirm('Remove this party?')">Delete</button></form></td></tr>@empty<tr><td colspan="5">No parties added.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
