CREATE TABLE IF NOT EXISTS `stn_carrier_invoices` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `transfer_id` BIGINT UNSIGNED NULL,
  `vehicle_id` BIGINT UNSIGNED NULL,
  `driver_name` VARCHAR(191) NULL,
  `carrier_name` VARCHAR(191) NULL,
  `invoice_no` VARCHAR(191) NOT NULL,
  `invoice_date` DATE NULL,
  `freight_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `loading_charge` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `unloading_charge` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `other_charge` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `total_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` VARCHAR(50) NOT NULL DEFAULT 'draft',
  `remarks` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `approved_by` BIGINT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL,
  `cancelled_by` BIGINT UNSIGNED NULL,
  `cancelled_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stn_carrier_inv_unique` (`business_id`, `invoice_no`),
  KEY `stn_carrier_inv_business_status` (`business_id`, `status`),
  KEY `stn_carrier_inv_transfer` (`transfer_id`),
  KEY `stn_carrier_inv_date` (`invoice_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stn_carrier_invoice_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `carrier_invoice_id` BIGINT UNSIGNED NOT NULL,
  `charge_type` VARCHAR(50) NOT NULL DEFAULT 'other',
  `description` VARCHAR(191) NULL,
  `qty` DECIMAL(22,4) NOT NULL DEFAULT 1.0000,
  `rate` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `remarks` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `stn_carrier_line_business` (`business_id`),
  KEY `stn_carrier_line_invoice` (`carrier_invoice_id`),
  KEY `stn_carrier_line_charge` (`charge_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
