-- Ran Module - idempotent tenant database SQL
-- Table prefix: ran_
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `ran_settings` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  `key` VARCHAR(120) NOT NULL,
  `value` JSON NULL,
  value_type VARCHAR(30) NOT NULL DEFAULT 'string',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_settings_business_key_unique(business_id,
  `key`),
  KEY(business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_number_sequences` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  document_type VARCHAR(60) NOT NULL,
  prefix VARCHAR(20) NULL,
  next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
  padding INT UNSIGNED NOT NULL DEFAULT 5,
  reset_period VARCHAR(20) NOT NULL DEFAULT 'never',
  last_reset_on DATE NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_sequence_scope_unique(business_id,
  location_id,
  document_type),
  KEY(business_id),
  KEY(location_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_metals` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  symbol VARCHAR(20) NULL,
  default_density DECIMAL(14,
  6) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_metals_code_unique(business_id,
  code),
  KEY(business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_purities` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  metal_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  fineness DECIMAL(10,
  6) NOT NULL,
  karat DECIMAL(8,
  3) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_purities_code_unique(business_id,
  metal_id,
  code),
  KEY(business_id),
  KEY(metal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_gemstones` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(60) NULL,
  colour VARCHAR(60) NULL,
  unit VARCHAR(20) NOT NULL DEFAULT 'carat',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_gemstones_code_unique(business_id,
  code),
  KEY(business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_artisans` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  artisan_code VARCHAR(30) NOT NULL,
  name VARCHAR(150) NOT NULL,
  supplier_contact_id BIGINT UNSIGNED NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(255) NULL,
  address TEXT NULL,
  speciality VARCHAR(120) NULL,
  opening_balance DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_artisans_code_unique(business_id,
  artisan_code),
  KEY(business_id),
  KEY(supplier_contact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_designs` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  design_code VARCHAR(40) NOT NULL,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NULL,
  description TEXT NULL,
  image_path VARCHAR(255) NULL,
  specifications JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_designs_code_unique(business_id,
  design_code),
  KEY(business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_items` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(60) NOT NULL,
  barcode VARCHAR(80) NULL,
  name VARCHAR(180) NOT NULL,
  item_type VARCHAR(40) NOT NULL DEFAULT 'finished',
  category VARCHAR(100) NULL,
  design_id BIGINT UNSIGNED NULL,
  metal_id BIGINT UNSIGNED NULL,
  purity_id BIGINT UNSIGNED NULL,
  stock_unit VARCHAR(20) NOT NULL DEFAULT 'piece',
  standard_gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  standard_net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  standard_stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  making_charge DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  making_charge_type VARCHAR(30) NOT NULL DEFAULT 'fixed',
  default_sale_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  minimum_sale_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  image_path VARCHAR(255) NULL,
  description TEXT NULL,
  serialized TINYINT(1) NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_items_sku_unique(business_id,
  sku),
  UNIQUE KEY ran_items_barcode_unique(business_id,
  barcode),
  KEY(business_id),
  KEY(design_id),
  KEY(metal_id),
  KEY(purity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_item_components` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  component_type VARCHAR(30) NOT NULL,
  metal_id BIGINT UNSIGNED NULL,
  purity_id BIGINT UNSIGNED NULL,
  gemstone_id BIGINT UNSIGNED NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  wastage_percent DECIMAL(10,
  4) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(business_id),
  KEY(item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_rate_cards` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  effective_date DATE NOT NULL,
  metal_id BIGINT UNSIGNED NOT NULL,
  purity_id BIGINT UNSIGNED NULL,
  purchase_rate DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  sale_rate DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  rate_unit VARCHAR(20) NOT NULL DEFAULT 'gram',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY ran_rate_cards_date_idx(business_id,
  location_id,
  effective_date),
  KEY(metal_id),
  KEY(purity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_stock_lots` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  lot_no VARCHAR(60) NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  serial_no VARCHAR(100) NULL,
  rfid_tag VARCHAR(100) NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  fine_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  total_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  sale_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  stock_status VARCHAR(30) NOT NULL DEFAULT 'available',
  source_type VARCHAR(60) NULL,
  source_id BIGINT UNSIGNED NULL,
  received_on DATE NULL,
  bin_location VARCHAR(100) NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_stock_lots_no_unique(business_id,
  lot_no),
  KEY ran_stock_lots_scope_idx(business_id,
  location_id,
  store_id,
  item_id,
  stock_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_stock_movements` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  movement_at DATETIME NOT NULL,
  movement_type VARCHAR(50) NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NULL,
  quantity_in DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  quantity_out DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  weight_in DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  weight_out DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  reference_type VARCHAR(60) NULL,
  reference_id BIGINT UNSIGNED NULL,
  reference_no VARCHAR(80) NULL,
  description TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY ran_stock_movements_date_idx(business_id,
  movement_at,
  item_id),
  KEY(stock_lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_transfers` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  transfer_no VARCHAR(60) NOT NULL,
  transfer_date DATE NOT NULL,
  from_location_id BIGINT UNSIGNED NOT NULL,
  from_store_id BIGINT UNSIGNED NOT NULL,
  to_location_id BIGINT UNSIGNED NOT NULL,
  to_store_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  notes TEXT NULL,
  dispatched_by BIGINT UNSIGNED NULL,
  dispatched_at DATETIME NULL,
  received_by BIGINT UNSIGNED NULL,
  received_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_transfers_no_unique(business_id,
  transfer_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_transfer_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  transfer_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  received_quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  received_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(transfer_id),
  KEY(stock_lot_id),
  KEY(item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_stocktakes` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  stocktake_no VARCHAR(60) NOT NULL,
  stocktake_date DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  notes TEXT NULL,
  posted_by BIGINT UNSIGNED NULL,
  posted_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_stocktakes_no_unique(business_id,
  stocktake_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_stocktake_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  stocktake_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  system_quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  counted_quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  quantity_variance DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  system_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  counted_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  weight_variance DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(stocktake_id),
  KEY(stock_lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_purchases` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  purchase_no VARCHAR(60) NOT NULL,
  supplier_invoice_no VARCHAR(100) NULL,
  purchase_date DATE NOT NULL,
  supplier_contact_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  total_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  balance_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  posted_by BIGINT UNSIGNED NULL,
  posted_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_purchases_no_unique(business_id,
  purchase_no),
  KEY(supplier_contact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_purchase_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  purchase_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(255) NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  line_total DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  lot_no VARCHAR(60) NULL,
  serial_no VARCHAR(100) NULL,
  sale_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(purchase_id),
  KEY(item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_supplier_payments` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  payment_no VARCHAR(60) NOT NULL,
  payment_date DATE NOT NULL,
  purchase_id BIGINT UNSIGNED NULL,
  supplier_contact_id BIGINT UNSIGNED NOT NULL,
  finance_account_id BIGINT UNSIGNED NULL,
  amount DECIMAL(22,
  4) NOT NULL,
  payment_method VARCHAR(40) NOT NULL,
  reference_no VARCHAR(100) NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_supplier_payments_no_unique(business_id,
  payment_no),
  KEY(purchase_id),
  KEY(supplier_contact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_production_orders` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  order_no VARCHAR(60) NOT NULL,
  order_date DATE NOT NULL,
  due_date DATE NULL,
  artisan_id BIGINT UNSIGNED NULL,
  supplier_contact_id BIGINT UNSIGNED NULL,
  customer_contact_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  instructions TEXT NULL,
  estimated_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  actual_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_production_orders_no_unique(business_id,
  order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_production_order_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  production_order_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NULL,
  design_id BIGINT UNSIGNED NULL,
  description VARCHAR(255) NULL,
  planned_quantity DECIMAL(20,
  4) NOT NULL DEFAULT 1,
  planned_gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  planned_net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  planned_stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  wastage_percent DECIMAL(10,
  4) NOT NULL DEFAULT 0,
  making_charge DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  specifications JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(production_order_id),
  KEY(item_id),
  KEY(design_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_material_issues` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  issue_no VARCHAR(60) NOT NULL,
  issue_date DATE NOT NULL,
  production_order_id BIGINT UNSIGNED NOT NULL,
  artisan_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_material_issues_no_unique(business_id,
  issue_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_material_issue_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  material_issue_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  fine_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  total_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(material_issue_id),
  KEY(stock_lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_production_receipts` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  receipt_no VARCHAR(60) NOT NULL,
  receipt_date DATE NOT NULL,
  production_order_id BIGINT UNSIGNED NOT NULL,
  artisan_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  labour_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  other_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_production_receipts_no_unique(business_id,
  receipt_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_production_receipt_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  production_receipt_id BIGINT UNSIGNED NOT NULL,
  production_order_line_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  lot_no VARCHAR(60) NOT NULL,
  serial_no VARCHAR(100) NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 1,
  gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  fine_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  material_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  labour_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  other_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  total_cost DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  sale_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(production_receipt_id),
  KEY(item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_wastage_entries` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  entry_date DATE NOT NULL,
  production_order_id BIGINT UNSIGNED NOT NULL,
  material_issue_line_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NULL,
  entry_type VARCHAR(30) NOT NULL DEFAULT 'wastage',
  weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  fine_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  value DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  reason TEXT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(production_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_sales` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  invoice_no VARCHAR(60) NOT NULL,
  invoice_date DATE NOT NULL,
  customer_contact_id BIGINT UNSIGNED NULL,
  customer_name VARCHAR(255) NULL,
  customer_mobile VARCHAR(40) NULL,
  customer_email VARCHAR(255) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  making_charge_total DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  rounding_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  total_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  balance_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  terms TEXT NULL,
  posted_by BIGINT UNSIGNED NULL,
  posted_at DATETIME NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_sales_invoice_unique(business_id,
  invoice_no),
  KEY ran_sales_date_idx(business_id,
  location_id,
  invoice_date,
  status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_sale_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  sale_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NULL,
  description VARCHAR(255) NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 1,
  gross_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  net_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  stone_weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  metal_rate DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  metal_value DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  stone_value DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  making_charge DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  other_charge DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  unit_price DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  line_total DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  cost_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(sale_id),
  KEY(item_id),
  KEY(stock_lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_payments` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  payment_no VARCHAR(60) NOT NULL,
  payment_date DATE NOT NULL,
  sale_id BIGINT UNSIGNED NULL,
  customer_contact_id BIGINT UNSIGNED NULL,
  finance_account_id BIGINT UNSIGNED NULL,
  payment_method VARCHAR(40) NOT NULL,
  amount DECIMAL(22,
  4) NOT NULL,
  reference_no VARCHAR(100) NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_payments_no_unique(business_id,
  payment_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_sale_returns` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  return_no VARCHAR(60) NOT NULL,
  return_date DATE NOT NULL,
  sale_id BIGINT UNSIGNED NULL,
  customer_contact_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  total_amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  reason TEXT NULL,
  posted_by BIGINT UNSIGNED NULL,
  posted_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_sale_returns_no_unique(business_id,
  return_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_sale_return_lines` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  sale_return_id BIGINT UNSIGNED NOT NULL,
  sale_line_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  stock_lot_id BIGINT UNSIGNED NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  weight DECIMAL(20,
  3) NOT NULL DEFAULT 0,
  amount DECIMAL(22,
  4) NOT NULL DEFAULT 0,
  `condition` VARCHAR(40) NOT NULL DEFAULT 'good',
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY(sale_return_id),
  KEY(sale_line_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_finance_postings` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  source_type VARCHAR(60) NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  posting_type VARCHAR(60) NOT NULL,
  debit_account_id BIGINT UNSIGNED NULL,
  credit_account_id BIGINT UNSIGNED NULL,
  amount DECIMAL(22,
  4) NOT NULL,
  debit_account_transaction_id BIGINT UNSIGNED NULL,
  credit_account_transaction_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  message TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_finance_postings_unique(business_id,
  source_type,
  source_id,
  posting_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_document_templates` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  document_type VARCHAR(60) NOT NULL,
  name VARCHAR(120) NOT NULL,
  paper_size VARCHAR(30) NOT NULL DEFAULT 'A4',
  orientation VARCHAR(20) NOT NULL DEFAULT 'portrait',
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  style_options JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY ran_doc_templates_type_idx(business_id,
  document_type,
  is_default)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_document_template_sections` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  section_key VARCHAR(80) NOT NULL,
  title VARCHAR(120) NOT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  enabled_by_default TINYINT(1) NOT NULL DEFAULT 1,
  allow_print TINYINT(1) NOT NULL DEFAULT 1,
  allow_sms TINYINT(1) NOT NULL DEFAULT 1,
  allow_email TINYINT(1) NOT NULL DEFAULT 1,
  allow_whatsapp TINYINT(1) NOT NULL DEFAULT 1,
  settings JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY ran_doc_sections_unique(template_id,
  section_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_document_shares` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  token VARCHAR(100) NOT NULL,
  document_type VARCHAR(60) NOT NULL,
  document_id BIGINT UNSIGNED NOT NULL,
  channel VARCHAR(30) NOT NULL,
  selected_sections JSON NOT NULL,
  expires_at DATETIME NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  download_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_viewed_at DATETIME NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY(token),
  KEY ran_document_shares_doc_idx(business_id,
  document_type,
  document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_communication_logs` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  channel VARCHAR(30) NOT NULL,
  document_type VARCHAR(60) NOT NULL,
  document_id BIGINT UNSIGNED NOT NULL,
  recipient VARCHAR(255) NULL,
  subject TEXT NULL,
  message LONGTEXT NULL,
  share_url VARCHAR(500) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'queued',
  provider_reference VARCHAR(150) NULL,
  provider_response LONGTEXT NULL,
  sent_at DATETIME NULL,
  failed_at DATETIME NULL,
  failure_reason TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  KEY ran_comms_doc_idx(business_id,
  document_type,
  document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ran_audit_logs` (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(120) NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  old_values JSON NULL,
  new_values JSON NULL,
  ip_address VARCHAR(64) NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ran_audit_entity_idx(business_id,
  entity_type,
  entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
