-- LOAN-19 Loan Products tables / columns
-- Run in each tenant database where Loan Module is enabled.

CREATE TABLE IF NOT EXISTS `loan_categories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(191) NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `risk_level` varchar(30) DEFAULT NULL,
  `priority_level` varchar(30) DEFAULT NULL,
  `recovery_strategy` text DEFAULT NULL,
  `auto_assign_collectors` tinyint(1) NOT NULL DEFAULT 0,
  `enable_escalations` tinyint(1) NOT NULL DEFAULT 0,
  `allow_settlements` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` int unsigned DEFAULT NULL,
  `updated_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_categories_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_fees` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(191) NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `fee_type` varchar(30) DEFAULT NULL,
  `calculation_method` varchar(50) DEFAULT NULL,
  `apply_when` varchar(50) DEFAULT NULL,
  `default_value` decimal(22,4) DEFAULT NULL,
  `minimum_value` decimal(22,4) DEFAULT NULL,
  `maximum_value` decimal(22,4) DEFAULT NULL,
  `is_mandatory` tinyint(1) NOT NULL DEFAULT 0,
  `is_editable` tinyint(1) NOT NULL DEFAULT 1,
  `is_taxable` tinyint(1) NOT NULL DEFAULT 0,
  `priority_order` int DEFAULT NULL,
  `recovery_applicable` tinyint(1) NOT NULL DEFAULT 0,
  `allow_fee_waiver` tinyint(1) NOT NULL DEFAULT 1,
  `auto_apply` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `created_by` int unsigned DEFAULT NULL,
  `updated_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_fees_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_penalties` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(191) NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `penalty_type` varchar(30) DEFAULT NULL,
  `calculation_method` varchar(50) DEFAULT NULL,
  `default_value` decimal(22,4) DEFAULT NULL,
  `minimum_value` decimal(22,4) DEFAULT NULL,
  `maximum_value` decimal(22,4) DEFAULT NULL,
  `grace_period_days` int DEFAULT NULL,
  `apply_after_days` int DEFAULT NULL,
  `maximum_penalty_limit` decimal(22,4) DEFAULT NULL,
  `daily_accrual` tinyint(1) NOT NULL DEFAULT 0,
  `compound_penalty` tinyint(1) NOT NULL DEFAULT 0,
  `is_waivable` tinyint(1) NOT NULL DEFAULT 1,
  `requires_approval` tinyint(1) NOT NULL DEFAULT 0,
  `auto_apply` tinyint(1) NOT NULL DEFAULT 0,
  `priority_level` varchar(30) DEFAULT NULL,
  `recovery_stage` varchar(50) DEFAULT NULL,
  `escalation_trigger` varchar(100) DEFAULT NULL,
  `legal_recovery_applicable` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `created_by` int unsigned DEFAULT NULL,
  `updated_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_penalties_business_id_index` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_products` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(191) NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `minimum_amount` decimal(22,4) DEFAULT NULL,
  `maximum_amount` decimal(22,4) DEFAULT NULL,
  `minimum_loan_term` int DEFAULT NULL,
  `maximum_loan_term` int DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `duration_type` varchar(30) DEFAULT NULL,
  `interest_rate` decimal(10,4) DEFAULT NULL,
  `minimum_interest_rate` decimal(10,4) DEFAULT NULL,
  `maximum_interest_rate` decimal(10,4) DEFAULT NULL,
  `default_interest_rate` decimal(10,4) DEFAULT NULL,
  `interest_method` varchar(50) DEFAULT NULL,
  `interest_frequency` varchar(50) DEFAULT NULL,
  `calculation_method` varchar(50) DEFAULT NULL,
  `compounding_period` varchar(50) DEFAULT NULL,
  `grace_period` int DEFAULT NULL,
  `grace_period_cycle` varchar(30) DEFAULT NULL,
  `repayment_frequency` varchar(50) DEFAULT NULL,
  `number_of_installments` int DEFAULT NULL,
  `allow_partial_payments` tinyint(1) NOT NULL DEFAULT 1,
  `allow_early_settlement` tinyint(1) NOT NULL DEFAULT 1,
  `auto_generate_schedule` tinyint(1) NOT NULL DEFAULT 1,
  `category_id` bigint unsigned DEFAULT NULL,
  `currency_id` int unsigned DEFAULT NULL,
  `location_id` int unsigned DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_products_business_id_index` (`business_id`),
  KEY `loan_products_code_index` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_product_locations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `loan_product_id` bigint unsigned NOT NULL,
  `location_id` int unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `loan_product_location_unique` (`loan_product_id`, `location_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_product_fees` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `loan_product_id` bigint unsigned NOT NULL,
  `loan_fee_id` bigint unsigned NOT NULL,
  `fee_type` varchar(30) DEFAULT NULL,
  `fee_value` decimal(22,4) DEFAULT NULL,
  `calculation_based_on` varchar(100) DEFAULT NULL,
  `applied_when` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_product_fees_product_index` (`loan_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loan_product_penalties` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `loan_product_id` bigint unsigned NOT NULL,
  `loan_penalty_id` bigint unsigned NOT NULL,
  `penalty_type` varchar(30) DEFAULT NULL,
  `penalty_value` decimal(22,4) DEFAULT NULL,
  `grace_period` int DEFAULT NULL,
  `grace_period_cycle` varchar(30) DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loan_product_penalties_product_index` (`loan_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
