<?php
namespace Modules\DealerManagement\Http\Controllers\Portal;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Modules\DealerManagement\Services\{HubContext,HubDatabaseManager,HubProductService,HubOrderService};
class HubOrderController extends Controller
{
 public function index(){ $u=app(HubContext::class)->user();$rows=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_orders')->where('hub_dealer_id',$u->hub_dealer_id)->orderByDesc('id')->simplePaginate(50));return view('dealermanagement::hub.orders.index',compact('rows')); }
 public function create(){ $ctx=app(HubContext::class);$u=$ctx->user();$rows=app(HubProductService::class)->consolidatedStock($u->hub_dealer_id,$ctx->outletIds());$outlets=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_outlets')->whereIn('id',$ctx->outletIds()?:[0])->get());$sources=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_product_sources as s')->join('dlr_hub_distributors as d','d.id','=','s.distributor_id')->where('s.hub_dealer_id',$u->hub_dealer_id)->where('s.is_active',1)->select('s.product_key','s.distributor_id','d.name')->get()->groupBy('product_key'));return view('dealermanagement::hub.orders.create',compact('rows','outlets','sources')); }
 public function store(Request $r){$ctx=app(HubContext::class);$u=$ctx->user();$d=$r->validate(['hub_outlet_id'=>'required|integer','requested_delivery_date'=>'nullable|date','notes'=>'nullable|string','lines'=>'required|array','lines.*.product_key'=>'required|string','lines.*.product_name'=>'required|string','lines.*.current_qty'=>'nullable|numeric','lines.*.suggested_qty'=>'nullable|numeric','lines.*.requested_qty'=>'required|numeric|min:0','lines.*.preferred_distributor_id'=>'nullable|integer']);abort_unless(in_array((int)$d['hub_outlet_id'],$ctx->outletIds(),true),403);app(HubOrderService::class)->createAndSplit($u->hub_dealer_id,(int)$d['hub_outlet_id'],$u->id,$d['lines'],$d['requested_delivery_date']??null,$d['notes']??null);return redirect()->route('dealermanagement.hub.orders.index')->with('status','Combined order saved and split to the selected distributors.');}
}
