<?php
namespace Modules\DealerManagement\Http\Controllers\Portal;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Modules\DealerManagement\Services\{HubContext,HubDatabaseManager,HubProductService,HubSalesService};
class HubSalesController extends Controller
{
 public function index(){ $ctx=app(HubContext::class);$u=$ctx->user();$rows=app(HubProductService::class)->consolidatedStock($u->hub_dealer_id,$ctx->outletIds());$outlets=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_outlets')->whereIn('id',$ctx->outletIds()?:[0])->where('is_active',1)->get());$sources=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_product_sources as s')->join('dlr_hub_distributors as d','d.id','=','s.distributor_id')->where('s.hub_dealer_id',$u->hub_dealer_id)->where('s.is_active',1)->select('s.product_key','s.distributor_id','d.name')->orderBy('d.name')->get()->groupBy('product_key'));return view('dealermanagement::hub.sales.create',compact('rows','outlets','sources')); }
 public function store(Request $r){$ctx=app(HubContext::class);$u=$ctx->user();$d=$r->validate(['hub_outlet_id'=>'required|integer','sale_date'=>'required|date','notes'=>'nullable|string','lines'=>'required|array','lines.*.product_key'=>'required|string','lines.*.product_name'=>'required|string','lines.*.sold_qty'=>'nullable|numeric|min:0','lines.*.return_qty'=>'nullable|numeric|min:0','lines.*.damaged_qty'=>'nullable|numeric|min:0','lines.*.received_qty'=>'nullable|numeric|min:0','lines.*.allocation_method'=>'nullable|in:fifo,proportional,manual','lines.*.distributor_id'=>'nullable|integer']);abort_unless(in_array((int)$d['hub_outlet_id'],$ctx->outletIds(),true),403);app(HubSalesService::class)->post($u->hub_dealer_id,(int)$d['hub_outlet_id'],$u->id,$d['sale_date'],$d['lines'],$d['notes']??null);return redirect()->route('dealermanagement.hub.sales.history')->with('status','Sales details saved once and allocated to the related distributors.');}
 public function history(){ $u=app(HubContext::class)->user();$rows=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_sales_entries')->where('hub_dealer_id',$u->hub_dealer_id)->orderByDesc('sale_date')->orderByDesc('id')->simplePaginate(50));return view('dealermanagement::hub.sales.history',compact('rows')); }
}
