@extends('restaurantnew::layouts.app')
@section('rest_title','Restaurant Control Centre')
@section('rest_subtitle','Live operational exceptions, approvals and management indicators.')
@section('rest_content')
<form method="get" class="rest-filter-card"><label>Business Location<select name="location_id"><option value="">All permitted locations</option>@foreach($locations as $l)<option value="{{ $l->id }}" @selected((string)$locationId===(string)$l->id)>{{ $l->name }}</option>@endforeach</select></label><button class="rest-btn rest-btn-primary">Apply</button></form>
<div class="rest-metric-grid rest-metric-grid-wide">
@foreach([['Sales Today',$metrics['sales'],'fa-money','blue'],['Paid Orders',$metrics['paid_orders'],'fa-check-circle','green'],['Average Bill',$metrics['average_bill'],'fa-calculator','purple'],['Late KOT',$metrics['late_tickets'],'fa-fire','red'],['Reservations',$metrics['upcoming_reservations'],'fa-calendar','orange'],['Active Deliveries',$metrics['active_deliveries'],'fa-motorcycle','cyan'],['Low Stock',$metrics['low_stock'],'fa-warning','red'],['Discounts',$metrics['discounts'],'fa-percent','orange'],['Wastage',$metrics['wastage'],'fa-trash','purple'],['Draft Receipts',$metrics['unposted_receipts'],'fa-truck','blue']] as [$label,$value,$icon,$colour])<div class="rest-metric rest-metric-{{ $colour }}"><span><i class="fa {{ $icon }}"></i></span><div><small>{{ $label }}</small><strong>{{ is_numeric($value)?number_format((float)$value,4):$value }}</strong></div></div>@endforeach
</div>
<div class="rest-grid-2"><section class="rest-card"><div class="rest-card-head"><h3><i class="fa fa-fire"></i> Late Kitchen Tickets</h3></div>@forelse($lateTickets as $t)<div class="rest-list-row"><span><strong>{{ $t->ticket_no }}</strong><small>Order #{{ $t->order_id }} · {{ $t->created_at?->diffForHumans() }}</small></span>@include('restaurantnew::partials.status',['status'=>$t->status])</div>@empty<div class="rest-empty">No late kitchen tickets.</div>@endforelse</section><section class="rest-card"><div class="rest-card-head"><h3><i class="fa fa-calendar"></i> Upcoming Reservations</h3></div>@forelse($reservations as $r)<div class="rest-list-row"><span><strong>{{ $r->customer_name }}</strong><small>{{ $r->reserved_at?->format('d M H:i') }} · {{ $r->guest_count }} guests · {{ $r->table?->name }}</small></span>@include('restaurantnew::partials.status',['status'=>$r->status])</div>@empty<div class="rest-empty">No reservations due soon.</div>@endforelse</section><section class="rest-card"><div class="rest-card-head"><h3><i class="fa fa-motorcycle"></i> Active Deliveries</h3></div>@forelse($deliveries as $d)<div class="rest-list-row"><span><strong>{{ $d->dispatch_no }}</strong><small>{{ $d->order?->order_no }} · {{ $d->delivery_address }}</small></span>@include('restaurantnew::partials.status',['status'=>$d->status])</div>@empty<div class="rest-empty">No active deliveries.</div>@endforelse</section><section class="rest-card"><div class="rest-card-head"><h3><i class="fa fa-warning"></i> Low Ingredient Stock</h3></div>@forelse($lowStock as $s)<div class="rest-list-row"><span><strong>{{ $s->name }}</strong><small>Reorder at {{ number_format((float)$s->reorder_level,4) }} {{ $s->unit }}</small></span><b class="rest-danger">{{ number_format((float)$s->quantity,4) }}</b></div>@empty<div class="rest-empty">No low-stock ingredients.</div>@endforelse</section></div>
<div class="rest-card"><div class="rest-card-head"><h3>Manager Approval History</h3></div><div class="table-responsive"><table class="rest-table"><thead><tr><th>Date</th><th>Type</th><th>Entity</th><th>Reason</th><th>Requested By</th><th>Approved By</th><th>Status</th></tr></thead><tbody>@forelse($approvals as $a)<tr><td>{{ $a->created_at?->format('d M Y H:i') }}</td><td>{{ ucwords(str_replace('_',' ',$a->approval_type)) }}</td><td>{{ $a->entity_type }} #{{ $a->entity_id }}</td><td>{{ $a->reason }}</td><td>#{{ $a->requested_by }}</td><td>#{{ $a->approved_by }}</td><td>@include('restaurantnew::partials.status',['status'=>$a->status])</td></tr>@empty<tr><td colspan="7" class="rest-empty">No approvals recorded.</td></tr>@endforelse</tbody></table></div></div>
@endsection
