@extends('layouts.app')
@section('title', 'Add Invoice')
@section('content')
<section class="content-header"><h1>Add Invoice</h1></section>
<section class="content"><form method="post" action="{{ route('myhealth.billing.invoices.store') }}">@csrf
<div class="row"><div class="col-md-5"><label>Member</label><select name="member_id" class="form-control" required><option value="">Select</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->myhealth_code }} - {{ $member->name }} - {{ $member->mobile }}</option>@endforeach</select></div><div class="col-md-3"><label>Invoice Date</label><input type="date" name="invoice_date" value="{{ date('Y-m-d') }}" class="form-control"></div><div class="col-md-2"><label>Discount</label><input name="discount_amount" value="0.0000" class="form-control text-right"></div><div class="col-md-2"><label>Insurance</label><input name="insurance_amount" value="0.0000" class="form-control text-right"></div></div><hr>
<h4>Invoice Items</h4><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Service</th><th>Type</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount</th></tr></thead><tbody>
@for($i=0;$i<5;$i++)<tr><td><select name="items[{{ $i }}][service_id]" class="form-control"><option value="">Manual</option>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->service_name }}</option>@endforeach</select></td><td><select name="items[{{ $i }}][item_type]" class="form-control"><option value="service">Service</option><option value="consultation">Consultation</option><option value="pharmacy">Pharmacy</option><option value="lab">Lab</option><option value="telemedicine">Telemedicine</option></select></td><td><input name="items[{{ $i }}][description]" class="form-control"></td><td><input name="items[{{ $i }}][qty]" value="1.0000" class="form-control text-right"></td><td><input name="items[{{ $i }}][unit_price]" value="0.0000" class="form-control text-right"></td><td><input name="items[{{ $i }}][discount_amount]" value="0.0000" class="form-control text-right"></td></tr>@endfor
</tbody></table></div><label>Remarks</label><textarea name="remarks" class="form-control"></textarea><br><button class="btn btn-primary">Save Invoice</button> <a href="{{ route('myhealth.billing.invoices.index') }}" class="btn btn-default">Cancel</a>
</form></section>
@endsection
