<?php
namespace Modules\TeaEstateManagement\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class SettingsController extends BaseTeaController
{
 public function index(){ $d=$this->common();$b=$this->businessId(); if($d['installed'] && DB::table('tea_processing_stages')->where('business_id',$b)->count()===0){ foreach(['WITHERING'=>'Withering','ROLLING'=>'Rolling','OXIDATION'=>'Oxidation / Fermentation','DRYING'=>'Drying / Firing','SORTING'=>'Sorting','GRADING'=>'Grading','PACKING'=>'Packing'] as $code=>$name){ DB::table('tea_processing_stages')->insert(['business_id'=>$b,'stage_code'=>$code,'name'=>$name,'sequence_no'=>DB::table('tea_processing_stages')->where('business_id',$b)->count()+1,'status'=>'active','created_at'=>now(),'updated_at'=>now()]); } } $d['factories']=$d['installed']?$this->scopeLocations(DB::table('tea_factories')->where('business_id',$b))->get():collect();$d['grades']=$d['installed']?DB::table('tea_grades')->where('business_id',$b)->get():collect();$d['stages']=$d['installed']?DB::table('tea_processing_stages')->where('business_id',$b)->orderBy('sequence_no')->get():collect();return view('teaestate::settings.index',$d);}
 public function factory(Request $r){$r->validate(['location_id'=>'nullable','name'=>'required|string|max:180']);$loc=$this->locations->resolveRequired($r->location_id);$b=$this->businessId();$code=$r->factory_code?:'FAC-'.str_pad((string)(DB::table('tea_factories')->where('business_id',$b)->count()+1),3,'0',STR_PAD_LEFT);DB::table('tea_factories')->insert(['business_id'=>$b,'location_id'=>$loc,'factory_code'=>$code,'name'=>$r->name,'address'=>$r->address,'daily_capacity_kg'=>(float)$r->daily_capacity_kg,'status'=>'active','notes'=>$r->notes,'created_at'=>now(),'updated_at'=>now()]);return back()->with('tea_success','Factory created.');}
 public function grade(Request $r){$r->validate(['grade_code'=>'required|string|max:50','name'=>'required|string|max:120']);DB::table('tea_grades')->insert(['business_id'=>$this->businessId(),'grade_code'=>$r->grade_code,'name'=>$r->name,'description'=>$r->description,'default_sale_price'=>(float)$r->default_sale_price,'status'=>'active','created_at'=>now(),'updated_at'=>now()]);return back()->with('tea_success','Tea grade created.');}
 public function stage(Request $r){$r->validate(['stage_code'=>'required|string|max:50','name'=>'required|string|max:120']);DB::table('tea_processing_stages')->insert(['business_id'=>$this->businessId(),'stage_code'=>$r->stage_code,'name'=>$r->name,'sequence_no'=>(int)($r->sequence_no??1),'status'=>'active','notes'=>$r->notes,'created_at'=>now(),'updated_at'=>now()]);return back()->with('tea_success','Processing stage created.');}
}
