<?php

return [
    'module' => 'HotelManagement',
    'slug' => 'hotel-management',
    'permission' => 'hotel.view',
    'route' => 'hotel-management.dashboard',
    'icon' => 'fa fa-hotel',
    'order' => 55,
    'sections' => [
        ['label' => 'Dashboard', 'route' => 'hotel-management.dashboard', 'permission' => 'hotel.dashboard.view'],
        ['label' => 'Setup', 'route' => 'hotel-management.hotels.index', 'permission' => 'hotel.setup.view'],
        ['label' => 'Rooms', 'route' => 'hotel-management.rooms.index', 'permission' => 'hotel.rooms.view'],
        ['label' => 'Rates', 'route' => 'hotel-management.rate-plans.index', 'permission' => 'hotel.rates.view'],
        ['label' => 'Reservations', 'route' => 'hotel-management.reservations.index', 'permission' => 'hotel.reservations.view'],
        ['label' => 'Front Office', 'route' => 'hotel-management.front-office.index', 'permission' => 'hotel.front_office.view'],
        ['label' => 'Housekeeping', 'route' => 'hotel-management.housekeeping.index', 'permission' => 'hotel.housekeeping.view'],
        ['label' => 'Maintenance', 'route' => 'hotel-management.maintenance.index', 'permission' => 'hotel.maintenance.view'],
        ['label' => 'Billing', 'route' => 'hotel-management.billing.index', 'permission' => 'hotel.billing.view'],
        ['label' => 'POS Charges', 'route' => 'hotel-management.pos.index', 'permission' => 'hotel.pos.view'],
        ['label' => 'Banquets', 'route' => 'hotel-management.banquets.index', 'permission' => 'hotel.banquets.view'],
        ['label' => 'Conference', 'route' => 'hotel-management.conference.index', 'permission' => 'hotel.conference.view'],
        ['label' => 'Room Service', 'route' => 'hotel-management.room-service.index', 'permission' => 'hotel.room_service.view'],
        ['label' => 'Night Audit', 'route' => 'hotel-management.night-audit.index', 'permission' => 'hotel.night_audit.view'],
        ['label' => 'Stores', 'route' => 'hotel-management.inventory.index', 'permission' => 'hotel.inventory.view'],
        ['label' => 'Guests', 'route' => 'hotel-management.crm.index', 'permission' => 'hotel.crm.view'],
        ['label' => 'Guest Feedback', 'route' => 'hotel-management.feedback.index', 'permission' => 'hotel.feedback.view'],
        ['label' => 'Loyalty', 'route' => 'hotel-management.loyalty.index', 'permission' => 'hotel.loyalty.view'],
        ['label' => 'Spa & Wellness', 'route' => 'hotel-management.spa.index', 'permission' => 'hotel.spa.view'],
        ['label' => 'Transport', 'route' => 'hotel-management.transport.index', 'permission' => 'hotel.transport.view'],
        ['label' => 'Mini Bar', 'route' => 'hotel-management.minibar.index', 'permission' => 'hotel.minibar.view'],
        ['label' => 'Procurement', 'route' => 'hotel-management.procurement.index', 'permission' => 'hotel.procurement.view'],
        ['label' => 'Assets & Equipment', 'route' => 'hotel-management.asset-equipment.index', 'permission' => 'hotel.asset_equipment.view'],
        ['label' => 'Preventive Maintenance', 'route' => 'hotel-management.preventive-maintenance.index', 'permission' => 'hotel.preventive_maintenance.view'],
        ['label' => 'Channel Manager', 'route' => 'hotel-management.channel-manager.index', 'permission' => 'hotel.channel_manager.view'],
        ['label' => 'Valet Parking', 'route' => 'hotel-management.valet.index', 'permission' => 'hotel.valet.view'],
        ['label' => 'Laundry', 'route' => 'hotel-management.laundry.index', 'permission' => 'hotel.laundry.view'],
        ['label' => 'Reports', 'route' => 'hotel-management.reports.index', 'permission' => 'hotel.reports.view'],
        ['label' => 'System Check', 'route' => 'hotel-management.system-check.index', 'permission' => 'hotel.settings'],
        ['label' => 'Production Hardening', 'route' => 'hotel-management.production-hardening.index', 'permission' => 'hotel.settings'],
    ],
];
