@extends('pos::layouts.app')
@section('pos_content')
<div class="ch-kpi-grid ch-standard-grid">
    <a class="ch-kpi-link" href="{{ route('pos.purchases.create') }}"><div class="ch-kpi"><div class="ch-kpi-top"><div class="ch-icon"><i class="fa fa-truck"></i></div><div class="label-text">Purchases</div></div><div class="value">{{ number_format($stats['purchases'] ?? 0) }}</div><div class="hint">Posted purchase entries <span class="ch-drill">Add <i class="fa fa-angle-right"></i></span></div><div class="spark"></div></div></a>
    <a class="ch-kpi-link" href="{{ route('pos.purchases.index') }}"><div class="ch-kpi success"><div class="ch-kpi-top"><div class="ch-icon"><i class="fa fa-money"></i></div><div class="label-text">Purchase Value</div></div><div class="value">{{ number_format($stats['purchase_value'] ?? 0, 2) }}</div><div class="hint">Stock purchase value</div><div class="spark"></div></div></a>
    <a class="ch-kpi-link" href="{{ route('pos.products.movements') }}"><div class="ch-kpi warning"><div class="ch-kpi-top"><div class="ch-icon"><i class="fa fa-cubes"></i></div><div class="label-text">Items Received</div></div><div class="value">{{ number_format($stats['items_received'] ?? 0, 3) }}</div><div class="hint">Total received quantity</div><div class="spark"></div></div></a>
    <a class="ch-kpi-link" href="{{ route('pos.products.index') }}"><div class="ch-kpi purple"><div class="ch-kpi-top"><div class="ch-icon"><i class="fa fa-tags"></i></div><div class="label-text">Products</div></div><div class="value">{{ number_format($stats['products'] ?? 0) }}</div><div class="hint">POS product master</div><div class="spark"></div></div></a>
</div>
<div class="ch-card"><div class="ch-card-header"><div><h3 class="ch-card-title"><i class="fa fa-truck text-primary"></i> Purchase Stock</h3><div class="ch-card-subtitle">Receive stock into POS inventory without using main system purchase files.</div></div><a class="btn btn-primary" href="{{ route('pos.purchases.create') }}"><i class="fa fa-plus"></i> Add Purchase</a></div>
<div class="ch-card-body">
<form class="ch-toolbar" method="get"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search reference or supplier"><input class="form-control" type="date" name="date_from" value="{{ request('date_from') }}"><input class="form-control" type="date" name="date_to" value="{{ request('date_to') }}"><button class="btn btn-primary">Search</button><a class="btn btn-default" href="{{ route('pos.purchases.index') }}">Reset</a></form>
<div class="table-responsive"><table class="table pos-standard-table"><thead><tr><th>Date</th><th>Reference</th><th>Supplier</th><th>Status</th><th class="text-right">Total</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($purchases as $row)<tr><td>{{ $row->purchase_date }}</td><td><strong>{{ $row->reference_no }}</strong></td><td>{{ $row->supplier_name ?: '-' }}</td><td><span class="ch-badge-soft {{ $row->status === 'void' ? 'danger' : 'info' }}">{{ ucfirst($row->status) }}</span></td><td class="text-right">{{ number_format($row->total_amount, 2) }}</td><td class="text-right"><a class="btn btn-primary" href="{{ route('pos.purchases.show', $row->id) }}">View</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No purchases found.</td></tr>@endforelse</tbody></table></div>{{ $purchases->links() }}</div></div>
@endsection
