@php
$isEdit = isset($sale);
$oldLines = old('lines', $isEdit ? $sale->lines->map(fn($line)=>['product_id'=>$line->product_id,'quantity'=>$line->quantity,'unit_price'=>$line->unit_price,'discount_amount'=>$line->discount_amount])->all() : [['product_id'=>'','quantity'=>1,'unit_price'=>0,'discount_amount'=>0]]);
@endphp
<div class="pone-panel"><div class="pone-panel-head"><div><h2>Sale Information</h2><div class="pone-panel-subtitle">Products and quantities are maintained only in PONE transaction tables.</div></div></div><div class="pone-panel-body"><div class="pone-form-grid">
<div class="pone-field pone-col-3"><label>Store</label><select name="store_id" data-search-select><option value="">Please Select</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected((string)old('store_id',$sale->store_id ?? '')===(string)$store->id)>{{ $store->name }}</option>@endforeach</select></div>
<div class="pone-field pone-col-3"><label>Customer</label><select name="customer_id" data-search-select><option value="">Walk-in / Other</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id',$sale->customer_id ?? '')===(string)$customer->id)>{{ $customer->name }} @if($customer->contact_id) ({{ $customer->contact_id }}) @endif</option>@endforeach</select></div>
<div class="pone-field pone-col-2"><label>Payment Method</label><select name="payment_method"><option value="cash" @selected(old('payment_method',$sale->payment_method ?? 'cash')==='cash')>Cash</option><option value="card" @selected(old('payment_method',$sale->payment_method ?? '')==='card')>Card</option><option value="cheque" @selected(old('payment_method',$sale->payment_method ?? '')==='cheque')>Cheque</option><option value="credit" @selected(old('payment_method',$sale->payment_method ?? '')==='credit')>Credit</option><option value="other" @selected(old('payment_method',$sale->payment_method ?? '')==='other')>Other</option></select></div>
<div class="pone-field pone-col-2"><label>Collection Form No.</label><input name="collection_form_no" maxlength="100" value="{{ old('collection_form_no',$sale->collection_form_no ?? '') }}"></div>
<div class="pone-field pone-col-2"><label>Date/Time</label><input name="sale_at" type="datetime-local" value="{{ old('sale_at',isset($sale)&&$sale->sale_at?$sale->sale_at->format('Y-m-d\TH:i'):now()->format('Y-m-d\TH:i')) }}"></div>
<div class="pone-field pone-col-12"><label>Note</label><textarea name="note">{{ old('note',$sale->note ?? '') }}</textarea></div>
@if($isEdit)<div class="pone-field pone-col-12"><label class="pone-required">Reason for Edit</label><textarea name="edit_reason" required>{{ old('edit_reason') }}</textarea><div class="pone-help">The previous and revised values are retained in the audit history.</div></div>@endif
</div></div></div>
<div class="pone-panel" data-line-table><div class="pone-panel-head"><div><h2>Sale Lines</h2><div class="pone-panel-subtitle">Unit price is inclusive of tax from the selected product where available.</div></div><button class="pone-btn pone-btn-primary pone-btn-sm" type="button" data-add-line data-target="#pone-other-sale-lines" data-template="#pone-other-sale-template">+ Add Product</button></div><div class="pone-panel-body pone-panel-body-compact"><div class="pone-table-wrap" style="border:0;border-radius:0"><table class="pone-table pone-line-table"><thead><tr><th>Product</th><th class="pone-text-right">Available</th><th>Quantity</th><th>Unit Price</th><th>Discount</th><th class="pone-text-right">Amount</th><th></th></tr></thead><tbody id="pone-other-sale-lines" data-next-index="{{ count($oldLines) }}">@foreach($oldLines as $i=>$line)<tr data-line-row><td><select name="lines[{{ $i }}][product_id]" data-product-select data-search-select required><option value="">Select Product</option>@foreach($products as $product)<option value="{{ $product->id }}" data-price="{{ $product->unit_price ?? 0 }}" @selected((string)($line['product_id']??'')===(string)$product->id)>{{ $product->name }} @if($product->sku) ({{ $product->sku }}) @endif</option>@endforeach</select></td><td class="pone-text-right pone-muted">@php($selected=$products->firstWhere('id',(int)($line['product_id']??0))){{ number_format((float)($selected->quantity_available??0),3) }}</td><td><input name="lines[{{ $i }}][quantity]" data-line-qty type="number" step="0.001" min="0.001" value="{{ $line['quantity']??1 }}" required></td><td><input name="lines[{{ $i }}][unit_price]" data-line-price type="number" step="0.0001" min="0" value="{{ $line['unit_price']??0 }}" required></td><td><input name="lines[{{ $i }}][discount_amount]" data-line-discount type="number" step="0.0001" min="0" value="{{ $line['discount_amount']??0 }}"></td><td class="pone-text-right pone-line-total" data-line-total>0.0000</td><td><button class="pone-btn pone-btn-danger pone-btn-sm" type="button" data-remove-line>×</button></td></tr>@endforeach</tbody><tfoot><tr><th colspan="5" class="pone-text-right">Net Total</th><th class="pone-text-right" data-grand-total>0.0000</th><th></th></tr></tfoot></table></div></div></div>
<template id="pone-other-sale-template"><tr data-line-row><td><select name="lines[__INDEX__][product_id]" data-product-select required><option value="">Select Product</option>@foreach($products as $product)<option value="{{ $product->id }}" data-price="{{ $product->unit_price ?? 0 }}">{{ $product->name }} @if($product->sku) ({{ $product->sku }}) @endif</option>@endforeach</select></td><td class="pone-text-right pone-muted">—</td><td><input name="lines[__INDEX__][quantity]" data-line-qty type="number" step="0.001" min="0.001" value="1" required></td><td><input name="lines[__INDEX__][unit_price]" data-line-price type="number" step="0.0001" min="0" value="0" required></td><td><input name="lines[__INDEX__][discount_amount]" data-line-discount type="number" step="0.0001" min="0" value="0"></td><td class="pone-text-right pone-line-total" data-line-total>0.0000</td><td><button class="pone-btn pone-btn-danger pone-btn-sm" type="button" data-remove-line>×</button></td></tr></template>
<div class="pone-actions pone-actions-end"><a class="pone-btn pone-btn-light" href="{{ route('pumper-dashboard-new.operator.other-sales.index') }}">Cancel</a><button class="pone-btn pone-btn-success" type="submit">{{ $isEdit ? 'Save Changes' : 'Save Other Sale' }}</button></div>
