@extends('pos::layouts.app', ['title' => __('pos::messages.cash_drawer')])
@section('pos_content')
@php($cp = session('business.currency_precision', 2))
<div class="row pos-kpi-row ch-kpi-row">
    <div class="col-md-3 col-sm-6"><div class="pos-kpi-card ch-card-accent ch-accent-green"><span>{{ __('pos::messages.cash_in') }}</span><strong>{{ number_format($dashboard['cash_in'] ?? 0, $cp) }}</strong><small>{{ __('pos::messages.today') }}</small></div></div>
    <div class="col-md-3 col-sm-6"><div class="pos-kpi-card ch-card-accent ch-accent-orange"><span>{{ __('pos::messages.cash_out') }}</span><strong>{{ number_format($dashboard['cash_out'] ?? 0, $cp) }}</strong><small>{{ __('pos::messages.today') }}</small></div></div>
    <div class="col-md-3 col-sm-6"><div class="pos-kpi-card ch-card-accent ch-accent-red"><span>{{ __('pos::messages.refunds') }}</span><strong>{{ number_format($dashboard['refunds'] ?? 0, $cp) }}</strong><small>{{ __('pos::messages.today') }}</small></div></div>
    <div class="col-md-3 col-sm-6"><div class="pos-kpi-card ch-card-accent ch-accent-blue"><span>{{ __('pos::messages.net_cash') }}</span><strong>{{ number_format($dashboard['net_cash'] ?? 0, $cp) }}</strong><small>{{ __('pos::messages.cash_drawer') }}</small></div></div>
</div>
<div class="pos-toolbar-card box box-solid"><div class="box-body pos-toolbar"><input type="text" class="form-control pos-instant-search" data-target="#pos-cash-table" placeholder="{{ __('pos::messages.search') }}"><div class="pos-toolbar-right"><a href="{{ route('pos.cash_drawer.cash_in_form') }}" class="btn btn-success"><i class="fa fa-plus"></i> {{ __('pos::messages.cash_in') }}</a><a href="{{ route('pos.cash_drawer.cash_out_form') }}" class="btn btn-warning"><i class="fa fa-minus"></i> {{ __('pos::messages.cash_out') }}</a><a href="{{ route('pos.cash_drawer.count_form') }}" class="btn btn-info"><i class="fa fa-calculator"></i> {{ __('pos::messages.cash_count') }}</a><button class="btn btn-default pos-print" data-table="#pos-cash-table"><i class="fa fa-print"></i> {{ __('pos::messages.print') }}</button></div></div></div>
<div class="box box-primary pos-table-card"><div class="box-body table-responsive"><table class="table table-bordered table-striped pos-standard-table" id="pos-cash-table"><thead><tr><th>{{ __('pos::messages.date') }}</th><th>{{ __('pos::messages.register') }}</th><th>{{ __('pos::messages.shift_no') }}</th><th>{{ __('pos::messages.type') }}</th><th>{{ __('pos::messages.reference_no') }}</th><th>{{ __('pos::messages.amount') }}</th><th>{{ __('pos::messages.approval') }}</th><th>{{ __('pos::messages.note') }}</th></tr></thead><tbody>
@forelse($movements as $movement)
<tr><td>{{ $movement->transaction_date ?? '-' }}</td><td>{{ $movement->register_name ?? '-' }}</td><td>{{ $movement->session_no ?? '-' }}</td><td>{{ __('pos::messages.'.($movement->movement_type ?? '')) }}</td><td>{{ $movement->reference_no ?? '-' }}</td><td class="text-right">{{ number_format((float)($movement->amount ?? 0), $cp) }}</td><td><span class="label label-{{ ($movement->approval_status ?? 'approved') === 'pending' ? 'warning' : 'success' }}">{{ ucfirst($movement->approval_status ?? 'approved') }}</span></td><td><button type="button" class="btn btn-xs btn-info pos-note-btn" data-note="{{ e($movement->note ?? '') }}">{{ __('pos::messages.note') }}</button></td></tr>
@empty<tr><td colspan="8" class="text-center text-muted">{{ __('pos::messages.no_records_found') }}</td></tr>@endforelse
</tbody></table>@if(method_exists($movements, 'links')) {{ $movements->links() }} @endif</div></div>
@endsection
