<?php

return [
    'myhealth.view',
    'myhealth.create',
    'myhealth.edit',
    'myhealth.delete',
    'myhealth.doctors.view',
    'myhealth.doctors.create',
    'myhealth.consultations.view',
    'myhealth.consultations.create',
    'myhealth.documents.view',
    'myhealth.documents.create',
    'myhealth.lab.view',
    'myhealth.lab.create',
    'myhealth.pharmacy.view',
    'myhealth.pharmacy.medicines.view',
    'myhealth.pharmacy.medicines.create',
    'myhealth.pharmacy.stock.view',
    'myhealth.pharmacy.stock.create',
    'myhealth.pharmacy.dispensing.view',
    'myhealth.pharmacy.dispensing.create',
    'myhealth.insurance.view',
    'myhealth.insurance.companies.view',
    'myhealth.insurance.policies.view',
    'myhealth.insurance.claims.view',
    'myhealth.telemedicine.view',
    'myhealth.telemedicine.schedules.view',
    'myhealth.telemedicine.appointments.view',
    'myhealth.billing.view',
    'myhealth.billing.services.view',
    'myhealth.billing.invoices.view',
    'myhealth.billing.claims.view',
    'myhealth.reports.view',
    'myhealth.settings.view',
    'myhealth.superadmin.permissions',

    'myhealth.hospital.view' => 'View My Health Hospital Dashboard',
    'myhealth.hospital.reception.view' => 'View My Health Reception',
    'myhealth.hospital.appointments.view' => 'View My Health Appointments',
    'myhealth.hospital.appointments.create' => 'Create My Health Appointments',
    'myhealth.hospital.queue.view' => 'View My Health Waiting Queue',
    'myhealth.hospital.schedules.view' => 'View Doctor Session Schedules',
    'myhealth.hospital.schedules.create' => 'Create Doctor Session Schedules',

    'myhealth.nursing.view' => 'View My Health Nursing Dashboard',
    'myhealth.nursing.station.view' => 'View Nursing Station',
    'myhealth.nursing.vitals.view' => 'View Vital Signs',
    'myhealth.nursing.vitals.create' => 'Create Vital Signs',
    'myhealth.nursing.notes.view' => 'View Nursing Notes',
    'myhealth.nursing.notes.create' => 'Create Nursing Notes',
    'myhealth.nursing.medications.view' => 'View Medication Administration',
    'myhealth.nursing.medications.create' => 'Create Medication Administration',
    'myhealth.nursing.care_plans.view' => 'View Nursing Care Plans',
    'myhealth.nursing.care_plans.create' => 'Create Nursing Care Plans',
    'myhealth.nursing.handovers.view' => 'View Shift Handovers',
    'myhealth.nursing.handovers.create' => 'Create Shift Handovers',
    'myhealth.laboratory.view' => 'View My Health Laboratory Dashboard',
    'myhealth.laboratory.catalogue.view' => 'View Lab Test Catalogue',
    'myhealth.laboratory.catalogue.create' => 'Create Lab Test Catalogue',
    'myhealth.laboratory.samples.view' => 'View Lab Samples',
    'myhealth.laboratory.samples.create' => 'Collect Lab Samples',
    'myhealth.laboratory.processing.view' => 'View Lab Processing',
    'myhealth.laboratory.processing.create' => 'Enter Lab Results',

    'myhealth.radiology.view' => 'View My Health Radiology Dashboard',
    'myhealth.radiology.requests.view' => 'View Radiology Requests',
    'myhealth.radiology.requests.create' => 'Create Radiology Requests',
    'myhealth.radiology.reports.view' => 'View Radiology Reports',
    'myhealth.radiology.reports.create' => 'Create Radiology Reports',


    'myhealth.operation_theatre.view' => 'View My Health Operation Theatre Dashboard',
    'myhealth.operation_theatre.schedules.view' => 'View Surgery Schedules',
    'myhealth.operation_theatre.schedules.create' => 'Create Surgery Schedules',
    'myhealth.operation_theatre.theatres.view' => 'View Theatre Rooms',
    'myhealth.operation_theatre.theatres.create' => 'Create Theatre Rooms',
    'myhealth.operation_theatre.checklists.view' => 'View Pre-Operative Checklists',
    'myhealth.operation_theatre.checklists.create' => 'Create Pre-Operative Checklists',
    'myhealth.operation_theatre.records.view' => 'View Operative Records',
    'myhealth.operation_theatre.records.create' => 'Create Operative Records',
    'myhealth.operation_theatre.post_op.view' => 'View Post-Operative Notes',
    'myhealth.operation_theatre.post_op.create' => 'Create Post-Operative Notes',
    'myhealth.operation_theatre.reports.view' => 'View Operation Theatre Reports',

    'myhealth.vaccination.view' => 'View vaccination module',
    'myhealth.vaccination.vaccines.view' => 'View vaccines',
    'myhealth.vaccination.vaccines.create' => 'Create vaccines',
    'myhealth.vaccination.records.view' => 'View vaccination records',
    'myhealth.vaccination.records.create' => 'Create vaccination records',
    'myhealth.vaccination.schedules.view' => 'View immunization schedules',
    'myhealth.vaccination.schedules.create' => 'Create immunization schedules',
    'myhealth.vaccination.reports.view' => 'View vaccination reports',

    'myhealth.analytics.view' => 'View My Health Analytics',
    'myhealth.analytics.clinical.view' => 'View Clinical Analytics',
    'myhealth.analytics.operational.view' => 'View Operational Analytics',
    'myhealth.analytics.financial.view' => 'View Financial Analytics',


    'myhealth.ai_clinical.view' => 'View AI Clinical Assistant',
    'myhealth.ai_clinical.alerts.view' => 'View AI Clinical Alerts',
    'myhealth.ai_clinical.alerts.acknowledge' => 'Acknowledge AI Clinical Alerts',
    'myhealth.ai_clinical.timeline.view' => 'View AI Clinical Timeline',
    'myhealth.ai_clinical.reports.view' => 'View AI Clinical Reports',


    'myhealth.disaster_recovery.view' => 'View Disaster Recovery dashboard',
    'myhealth.disaster_recovery.backups.view' => 'View My Health backups',
    'myhealth.disaster_recovery.backups.create' => 'Create My Health backup requests',
    'myhealth.disaster_recovery.restores.view' => 'View My Health restore centre',
    'myhealth.disaster_recovery.restores.create' => 'Create My Health restore requests',
    'myhealth.disaster_recovery.health.view' => 'View My Health system health',
    'myhealth.disaster_recovery.health.run' => 'Run My Health health checks',
    'myhealth.disaster_recovery.tests.view' => 'View My Health recovery tests',
    'myhealth.disaster_recovery.reports.view' => 'View My Health disaster recovery reports',


    'myhealth.disaster_recovery.view' => 'View My Health Disaster Recovery',
    'myhealth.disaster_recovery.backups.view' => 'View My Health Backups',
    'myhealth.disaster_recovery.backups.create' => 'Create My Health Backups',
    'myhealth.disaster_recovery.restores.view' => 'View My Health Restore Centre',
    'myhealth.disaster_recovery.health.view' => 'View My Health System Health',
    'myhealth.disaster_recovery.tests.view' => 'View My Health Recovery Tests',
    'myhealth.disaster_recovery.reports.view' => 'View My Health Disaster Recovery Reports',
    'myhealth.certification.view' => 'View My Health Production Certification',
    'myhealth.certification.security.view' => 'View My Health Security Review',
    'myhealth.certification.performance.view' => 'View My Health Performance Review',
    'myhealth.certification.workflow.view' => 'View My Health Workflow Certification',
];
