<?php
namespace Modules\DealerManagement\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Modules\DealerManagement\Services\{DistributionAvailabilityService,HubConnectionService,HubDatabaseManager,HubIdentityService};
class HubAdminController extends Controller
{
 private function businessId():int{$id=(int)(session('business.id')??session('business_id')??session('user.business_id')??0);abort_unless($id>0&&app(DistributionAvailabilityService::class)->enabledForBusiness($id),404);return $id;}
 public function index(){ $businessId=$this->businessId();$dist=app(HubConnectionService::class)->registerCurrentDistributor($businessId);$connections=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_connections as c')->join('dlr_hub_dealers as h','h.id','=','c.hub_dealer_id')->where('c.distributor_id',$dist->id)->select('c.*','h.hub_code','h.name as hub_dealer_name')->orderByDesc('c.id')->get());$hubDealers=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_dealers')->where('status','active')->orderBy('name')->get());$localDealers=DB::table('dlr_dealers')->where('business_id',$businessId)->orderBy('name')->get();$localOutlets=DB::table('dlr_outlets as o')->join('dlr_dealers as d','d.id','=','o.dealer_id')->where('o.business_id',$businessId)->select('o.*','d.name as dealer_name')->orderBy('d.name')->orderBy('o.name')->get();$hubOutlets=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_outlets as o')->join('dlr_hub_dealers as h','h.id','=','o.hub_dealer_id')->select('o.*','h.name as hub_dealer_name')->where('o.is_active',1)->orderBy('h.name')->orderBy('o.name')->get());return view('dealermanagement::admin.hub.index',compact('dist','connections','hubDealers','localDealers','localOutlets','hubOutlets')); }
 public function createHubDealer(Request $r){$this->businessId();$d=$r->validate(['name'=>'required|string|max:191','mobile'=>'nullable|string|max:50','email'=>'nullable|email|max:191','admin_name'=>'required|string|max:191','admin_mobile'=>'nullable|string|max:50','admin_email'=>'nullable|email|max:191','notes'=>'nullable|string']);$x=app(HubIdentityService::class)->createHubDealer($d);return back()->with('status','Dealer Hub created. Hub Code: '.$x['hub_code'].' Login Code: '.$x['login_code'].' Temporary Password: '.$x['temporary_password']);}
 public function invite(Request $r){$businessId=$this->businessId();$d=$r->validate(['hub_dealer_id'=>'required|integer','local_dealer_id'=>'required|integer']);$x=app(HubConnectionService::class)->invite((int)$d['hub_dealer_id'],$businessId,(int)$d['local_dealer_id']);DB::table('dlr_dealers')->where('business_id',$businessId)->where('id',$d['local_dealer_id'])->update(['hub_dealer_id'=>$d['hub_dealer_id'],'updated_at'=>now()]);return back()->with('status','Invitation created. Code: '.$x['invitation_code']);}
 public function approveRequest(Request $r,int $id){$businessId=$this->businessId();$d=$r->validate(['local_dealer_id'=>'required|integer']);$local=DB::table('dlr_dealers')->where('business_id',$businessId)->where('id',$d['local_dealer_id'])->first();abort_unless($local,422,'Local dealer not found.');$dist=app(HubConnectionService::class)->registerCurrentDistributor($businessId);$row=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_connections')->where('id',$id)->where('distributor_id',$dist->id)->first());abort_unless($row,404);app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_connections')->where('id',$id)->update(['local_dealer_id'=>$d['local_dealer_id'],'status'=>'active','approved_at'=>now(),'updated_at'=>now()]));DB::table('dlr_dealers')->where('id',$d['local_dealer_id'])->update(['hub_dealer_id'=>$row->hub_dealer_id,'updated_at'=>now()]);return back()->with('status','Dealer connection approved and linked to the local dealer.');}
 public function mapOutlet(Request $r){$businessId=$this->businessId();$d=$r->validate(['connection_id'=>'required|integer','local_outlet_id'=>'required|integer','hub_outlet_id'=>'required|integer']);$dist=app(HubConnectionService::class)->registerCurrentDistributor($businessId);$conn=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_connections')->where('id',$d['connection_id'])->where('distributor_id',$dist->id)->where('status','active')->first());abort_unless($conn,404);$local=DB::table('dlr_outlets')->where('business_id',$businessId)->where('dealer_id',$conn->local_dealer_id)->where('id',$d['local_outlet_id'])->first();abort_unless($local,422,'Local outlet does not belong to this dealer.');$hubOk=app(HubDatabaseManager::class)->central(fn()=>DB::table('dlr_hub_outlets')->where('hub_dealer_id',$conn->hub_dealer_id)->where('id',$d['hub_outlet_id'])->exists());abort_unless($hubOk,422,'Hub outlet does not belong to this dealer.');DB::table('dlr_outlets')->where('id',$local->id)->update(['hub_outlet_id'=>$d['hub_outlet_id'],'updated_at'=>now()]);return back()->with('status','Dealer outlet mapped to Dealer Hub outlet.');}

}
