<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('disnew_credit_controls', function (Blueprint $table) {
            $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable();
            $table->unsignedBigInteger('customer_id'); $table->decimal('credit_limit',22,4)->default(0); $table->integer('credit_days')->default(0);
            $table->boolean('block_on_over_limit')->default(true); $table->boolean('block_on_overdue')->default(true); $table->decimal('warning_percentage',8,3)->default(80);
            $table->decimal('temporary_limit',22,4)->default(0); $table->date('temporary_limit_expiry')->nullable(); $table->enum('status',['active','inactive','blocked'])->default('active');
            $table->text('note')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps();
            $table->unique(['business_id','customer_id'],'disnew_credit_customer_unique'); $table->index(['business_id','business_location_id','status'],'disnew_credit_business_status_idx');
        });
        Schema::create('disnew_price_lists', function (Blueprint $table) {
            $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->string('price_list_code',60)->nullable(); $table->string('name',150);
            $table->enum('scope_type',['general','customer','route','territory','sales_rep'])->default('general'); $table->unsignedBigInteger('customer_id')->nullable(); $table->unsignedBigInteger('route_id')->nullable(); $table->unsignedBigInteger('territory_id')->nullable(); $table->unsignedBigInteger('sales_rep_id')->nullable();
            $table->date('valid_from')->nullable(); $table->date('valid_to')->nullable(); $table->integer('priority')->default(0); $table->enum('status',['active','inactive'])->default('active'); $table->text('note')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps();
            $table->index(['business_id','scope_type','status','priority'],'disnew_price_scope_idx');
        });
        Schema::create('disnew_price_list_lines', function (Blueprint $table) {
            $table->id(); $table->unsignedInteger('business_id'); $table->unsignedBigInteger('price_list_id'); $table->unsignedBigInteger('product_id'); $table->unsignedBigInteger('variation_id')->nullable(); $table->unsignedBigInteger('unit_id')->nullable(); $table->decimal('unit_price',22,4)->default(0); $table->decimal('minimum_qty',22,4)->default(0); $table->decimal('maximum_qty',22,4)->nullable(); $table->timestamps();
            $table->index(['business_id','product_id','variation_id'],'disnew_price_lines_product_idx'); $table->index(['price_list_id'],'disnew_price_lines_list_idx');
        });
        Schema::create('disnew_discount_rules', function (Blueprint $table) {
            $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->string('rule_code',60)->nullable(); $table->string('name',150); $table->enum('scope_type',['general','customer','route','territory','product','category','sales_rep'])->default('general'); $table->enum('discount_type',['percentage','fixed'])->default('percentage'); $table->decimal('discount_value',22,4)->default(0); $table->decimal('minimum_order_amount',22,4)->default(0); $table->decimal('minimum_qty',22,4)->default(0); $table->date('valid_from')->nullable(); $table->date('valid_to')->nullable(); $table->integer('priority')->default(0); $table->boolean('requires_approval')->default(false); $table->enum('status',['active','inactive'])->default('active'); $table->json('condition_json')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps();
            $table->index(['business_id','scope_type','status','priority'],'disnew_discount_rules_idx');
        });
        Schema::create('disnew_promotions', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->string('promotion_code',60)->nullable(); $table->string('name',150); $table->enum('promotion_type',['bundle','seasonal','free_issue','discount','campaign'])->default('discount'); $table->date('valid_from')->nullable(); $table->date('valid_to')->nullable(); $table->decimal('budget_amount',22,4)->default(0); $table->decimal('used_amount',22,4)->default(0); $table->enum('status',['draft','active','paused','closed'])->default('draft'); $table->text('note')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps(); $table->index(['business_id','business_location_id','status','valid_from','valid_to'],'disnew_promotions_business_idx'); });
        Schema::create('disnew_promotion_lines', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedBigInteger('promotion_id'); $table->unsignedBigInteger('buy_product_id')->nullable(); $table->unsignedBigInteger('buy_variation_id')->nullable(); $table->decimal('buy_qty',22,4)->default(0); $table->unsignedBigInteger('free_product_id')->nullable(); $table->unsignedBigInteger('free_variation_id')->nullable(); $table->decimal('free_qty',22,4)->default(0); $table->enum('discount_type',['none','percentage','fixed'])->default('none'); $table->decimal('discount_value',22,4)->default(0); $table->timestamps(); $table->index(['business_id','promotion_id'],'disnew_promotion_lines_idx'); });
        Schema::create('disnew_free_issue_rules', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->string('name',150); $table->unsignedBigInteger('buy_product_id'); $table->unsignedBigInteger('buy_variation_id')->nullable(); $table->decimal('buy_qty',22,4)->default(0); $table->unsignedBigInteger('free_product_id'); $table->unsignedBigInteger('free_variation_id')->nullable(); $table->decimal('free_qty',22,4)->default(0); $table->date('valid_from')->nullable(); $table->date('valid_to')->nullable(); $table->enum('status',['active','inactive'])->default('active'); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps(); $table->index(['business_id','buy_product_id','status'],'disnew_free_issue_idx'); });
        Schema::create('disnew_sales_targets', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->enum('target_type',['sales_rep','territory','route','customer','product'])->default('sales_rep'); $table->unsignedBigInteger('sales_rep_id')->nullable(); $table->unsignedBigInteger('territory_id')->nullable(); $table->unsignedBigInteger('route_id')->nullable(); $table->unsignedBigInteger('customer_id')->nullable(); $table->unsignedBigInteger('product_id')->nullable(); $table->enum('period_type',['daily','weekly','monthly','quarterly','yearly'])->default('monthly'); $table->date('period_start'); $table->date('period_end'); $table->decimal('target_amount',22,4)->default(0); $table->decimal('target_qty',22,4)->default(0); $table->decimal('achieved_amount',22,4)->default(0); $table->decimal('achieved_qty',22,4)->default(0); $table->enum('status',['active','closed','cancelled'])->default('active'); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('updated_by')->nullable(); $table->timestamps(); $table->index(['business_id','target_type','period_start','period_end','status'],'disnew_targets_idx'); });
        Schema::create('disnew_sales_commissions', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->unsignedBigInteger('sales_rep_id')->nullable(); $table->unsignedBigInteger('customer_id')->nullable(); $table->unsignedBigInteger('sales_order_id')->nullable(); $table->unsignedBigInteger('sales_invoice_id')->nullable(); $table->date('commission_date'); $table->decimal('base_amount',22,4)->default(0); $table->enum('commission_type',['percentage','fixed'])->default('percentage'); $table->decimal('commission_value',22,4)->default(0); $table->decimal('commission_amount',22,4)->default(0); $table->enum('status',['pending','approved','paid','cancelled'])->default('pending'); $table->text('note')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->unsignedBigInteger('approved_by')->nullable(); $table->timestamp('approved_at')->nullable(); $table->timestamps(); $table->index(['business_id','sales_rep_id','commission_date','status'],'disnew_commissions_idx'); });
        Schema::create('disnew_sales_kpi_snapshots', function (Blueprint $table) { $table->id(); $table->unsignedInteger('business_id'); $table->unsignedInteger('business_location_id')->nullable(); $table->date('snapshot_date'); $table->unsignedBigInteger('sales_rep_id')->nullable(); $table->unsignedBigInteger('territory_id')->nullable(); $table->unsignedBigInteger('route_id')->nullable(); $table->integer('orders_count')->default(0); $table->integer('invoices_count')->default(0); $table->decimal('gross_sales',22,4)->default(0); $table->decimal('discount_amount',22,4)->default(0); $table->decimal('net_sales',22,4)->default(0); $table->decimal('collections_amount',22,4)->default(0); $table->decimal('returns_amount',22,4)->default(0); $table->decimal('target_amount',22,4)->default(0); $table->decimal('achievement_percentage',8,3)->default(0); $table->timestamps(); $table->index(['business_id','snapshot_date','sales_rep_id','territory_id','route_id'],'disnew_kpi_snapshot_idx'); });
    }
    public function down(): void
    {
        Schema::dropIfExists('disnew_sales_kpi_snapshots'); Schema::dropIfExists('disnew_sales_commissions'); Schema::dropIfExists('disnew_sales_targets'); Schema::dropIfExists('disnew_free_issue_rules'); Schema::dropIfExists('disnew_promotion_lines'); Schema::dropIfExists('disnew_promotions'); Schema::dropIfExists('disnew_discount_rules'); Schema::dropIfExists('disnew_price_list_lines'); Schema::dropIfExists('disnew_price_lists'); Schema::dropIfExists('disnew_credit_controls');
    }
};
