<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('disnew_barcode_profiles', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->string('name'); $table->enum('profile_type',['barcode','qr','both'])->default('both'); $table->string('prefix',50)->nullable(); $table->boolean('is_default')->default(false); $table->boolean('is_active')->default(true); $table->unsignedBigInteger('created_by')->nullable(); $table->timestamps(); $table->index('business_id'); });
        Schema::create('disnew_barcode_labels', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->unsignedBigInteger('business_location_id')->nullable(); $table->unsignedBigInteger('product_id'); $table->unsignedBigInteger('variation_id')->nullable(); $table->string('batch_no',100)->nullable(); $table->string('barcode_value')->unique(); $table->text('qr_value')->nullable(); $table->enum('label_status',['active','void','used'])->default('active'); $table->unsignedBigInteger('created_by')->nullable(); $table->timestamps(); $table->index(['business_id','product_id','batch_no']); });
        Schema::create('disnew_scanner_sessions', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->unsignedBigInteger('business_location_id')->nullable(); $table->enum('session_type',['loading','unloading','bin','verification','dispatch','delivery']); $table->string('reference_type',80)->nullable(); $table->unsignedBigInteger('reference_id')->nullable(); $table->unsignedBigInteger('vehicle_id')->nullable(); $table->unsignedBigInteger('warehouse_id')->nullable(); $table->enum('status',['open','closed','cancelled'])->default('open'); $table->unsignedBigInteger('started_by')->nullable(); $table->dateTime('started_at')->nullable(); $table->dateTime('closed_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->index(['business_id','session_type','reference_id']); });
        Schema::create('disnew_scanner_scans', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id')->nullable(); $table->unsignedBigInteger('scanner_session_id')->nullable(); $table->unsignedBigInteger('resolved_label_id')->nullable(); $table->string('barcode_value'); $table->unsignedBigInteger('product_id')->nullable(); $table->unsignedBigInteger('variation_id')->nullable(); $table->string('batch_no',100)->nullable(); $table->decimal('qty',22,4)->default(1); $table->enum('scan_status',['accepted','duplicate','exception','reversed'])->default('accepted'); $table->string('exception_reason')->nullable(); $table->unsignedBigInteger('scanned_by')->nullable(); $table->dateTime('scanned_at')->nullable(); $table->timestamps(); $table->index('scanner_session_id'); $table->index('barcode_value'); });
        Schema::create('disnew_bin_locations', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->unsignedBigInteger('business_location_id')->nullable(); $table->unsignedBigInteger('warehouse_id')->nullable(); $table->string('code',80); $table->string('name'); $table->string('aisle',80)->nullable(); $table->string('rack',80)->nullable(); $table->string('shelf',80)->nullable(); $table->decimal('capacity_qty',22,4)->nullable(); $table->boolean('is_active')->default(true); $table->unsignedBigInteger('created_by')->nullable(); $table->timestamps(); $table->unique(['business_id','warehouse_id','code'],'disnew_bin_locations_code_unique'); });
        Schema::create('disnew_bin_stock_movements', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->unsignedBigInteger('business_location_id')->nullable(); $table->unsignedBigInteger('warehouse_id')->nullable(); $table->unsignedBigInteger('bin_location_id'); $table->unsignedBigInteger('product_id'); $table->unsignedBigInteger('variation_id')->nullable(); $table->string('batch_no',100)->nullable(); $table->decimal('qty',22,4); $table->enum('movement_type',['in','out','return','adjustment']); $table->string('reference_type',80)->nullable(); $table->unsignedBigInteger('reference_id')->nullable(); $table->unsignedBigInteger('created_by')->nullable(); $table->timestamps(); $table->index(['business_id','bin_location_id','product_id'],'disnew_bin_stock_movements_bal_idx'); });
        Schema::create('disnew_stock_verifications', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('business_id'); $table->unsignedBigInteger('business_location_id')->nullable(); $table->unsignedBigInteger('warehouse_id')->nullable(); $table->unsignedBigInteger('vehicle_id')->nullable(); $table->string('verification_no',80)->nullable(); $table->enum('verification_type',['warehouse','vehicle','bin'])->default('warehouse'); $table->enum('status',['draft','counting','submitted','approved','cancelled'])->default('draft'); $table->unsignedBigInteger('counted_by')->nullable(); $table->unsignedBigInteger('approved_by')->nullable(); $table->dateTime('started_at')->nullable(); $table->dateTime('submitted_at')->nullable(); $table->dateTime('approved_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->index(['business_id','status']); });
        Schema::create('disnew_stock_verification_lines', function(Blueprint $table){ $table->id(); $table->unsignedBigInteger('stock_verification_id'); $table->unsignedBigInteger('product_id'); $table->unsignedBigInteger('variation_id')->nullable(); $table->string('batch_no',100)->nullable(); $table->decimal('system_qty',22,4)->default(0); $table->decimal('counted_qty',22,4)->default(0); $table->decimal('variance_qty',22,4)->default(0); $table->string('last_barcode_value')->nullable(); $table->text('remarks')->nullable(); $table->timestamps(); $table->index('stock_verification_id'); });
    }
    public function down(): void
    {
        Schema::dropIfExists('disnew_stock_verification_lines'); Schema::dropIfExists('disnew_stock_verifications'); Schema::dropIfExists('disnew_bin_stock_movements'); Schema::dropIfExists('disnew_bin_locations'); Schema::dropIfExists('disnew_scanner_scans'); Schema::dropIfExists('disnew_scanner_sessions'); Schema::dropIfExists('disnew_barcode_labels'); Schema::dropIfExists('disnew_barcode_profiles');
    }
};
