<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Dealer Hub')</title><link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}"><style>{!! file_exists(base_path('Modules/DealerManagement/Resources/css/dealer.css')) ? file_get_contents(base_path('Modules/DealerManagement/Resources/css/dealer.css')) : '' !!}</style></head><body data-quantity-precision="{{ (int) session('business.quantity_precision', config('constants.quantity_precision',2)) }}">
@php($ctx=app(\Modules\DealerManagement\Services\HubContext::class)) @php($me=$ctx->user()) @php($dealer=$ctx->dealer())
<div class="dlr-shell"><aside class="dlr-sidebar"><div class="dlr-logo">SYZYGY</div><div class="dlr-module-select">Dealer Hub <i class="fa fa-angle-down"></i></div><nav class="dlr-nav">
@foreach([
['dealermanagement.hub.dashboard','fa-home','Dashboard',null],['dealermanagement.hub.stock.index','fa-cubes','All Products / Stock','stock.view'],['dealermanagement.hub.products.sources','fa-random','Product Sources','settings.manage'],['dealermanagement.hub.reorder.index','fa-bell-o','Re-order Alerts','stock.view'],['dealermanagement.hub.sales.create','fa-line-chart','Daily Sales Entry','hub.sales.create'],['dealermanagement.hub.sales.history','fa-history','Sales History','hub.sales.create'],['dealermanagement.hub.distributors.index','fa-sitemap','My Distributors','hub.connections.manage'],['dealermanagement.hub.orders.index','fa-shopping-cart','Orders','orders.view'],['dealermanagement.hub.deliveries.index','fa-truck','Deliveries','deliveries.view'],['dealermanagement.hub.returns.index','fa-reply','Returns','returns.view'],['dealermanagement.hub.notifications.index','fa-bell','Notifications','notifications.view'],['dealermanagement.hub.reports.index','fa-bar-chart','Reports','reports.view'],['dealermanagement.hub.outlets.index','fa-building','Outlets','outlets.manage'],['dealermanagement.hub.users.index','fa-users','Staff Users','hub.users.manage']
] as $l)@if(empty($l[3]) || $ctx->can($l[3]))<a class="{{ request()->routeIs($l[0])?'active':'' }}" href="{{ route($l[0]) }}"><i class="fa {{ $l[1] }}"></i><span>{{ $l[2] }}</span></a>@endif @endforeach
</nav></aside><main class="dlr-main"><header class="dlr-topbar"><div><div class="dlr-module-caption">MULTI-DISTRIBUTOR DEALER HUB</div><div class="dlr-page-caption">@yield('title','Dashboard')</div></div><div class="dlr-top-actions"><form method="post" action="{{ route('dealermanagement.hub.refresh') }}">@csrf<button title="Refresh all distributor data"><i class="fa fa-refresh"></i></button></form><a href="{{ route('dealermanagement.hub.profile.login-code') }}"><i class="fa fa-key"></i></a><a href="{{ route('dealermanagement.hub.profile.password') }}"><i class="fa fa-lock"></i></a><form method="post" action="{{ route('dealermanagement.hub.logout') }}">@csrf<button><i class="fa fa-sign-out"></i></button></form></div></header><div class="dlr-wrap">
@if(session('status'))<div class="dlr-alert success"><i class="fa fa-check-circle"></i> {{ session('status') }}</div>@endif @if($errors->any())<div class="dlr-alert error"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
@yield('content')</div></main></div><script src="{{ asset('modules/dealermanagement/js/dealer.js') }}"></script>@yield('scripts')</body></html>
