-- ATN-003 CREATE SQL
CREATE TABLE IF NOT EXISTS `atn_corporate_customers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `customer_no` VARCHAR(40) NOT NULL,
  `company_name` VARCHAR(180) NOT NULL,
  `registration_no` VARCHAR(80) NULL,
  `tax_no` VARCHAR(80) NULL,
  `contact_person` VARCHAR(150) NULL,
  `email` VARCHAR(150) NULL,
  `phone` VARCHAR(40) NULL,
  `alternate_phone` VARCHAR(40) NULL,
  `billing_address` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `country_code` VARCHAR(2) NULL,
  `credit_limit` DECIMAL(22,4) NOT NULL DEFAULT 0,
  `payment_terms_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `currency_code` VARCHAR(3) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `atn_corp_customer_no_unique` (`business_id`,`customer_no`),
  KEY `atn_corp_customer_name_idx` (`business_id`,`company_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_passengers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `passenger_no` VARCHAR(40) NOT NULL,
  `title` VARCHAR(20) NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(20) NULL,
  `date_of_birth` DATE NULL,
  `nationality_code` VARCHAR(2) NULL,
  `email` VARCHAR(150) NULL,
  `phone` VARCHAR(40) NULL,
  `alternate_phone` VARCHAR(40) NULL,
  `address` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `country_code` VARCHAR(2) NULL,
  `corporate_customer_id` BIGINT UNSIGNED NULL,
  `is_vip` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `atn_passenger_no_unique` (`business_id`,`passenger_no`),
  KEY `atn_passenger_name_idx` (`business_id`,`last_name`,`first_name`),
  KEY `atn_passenger_contact_idx` (`business_id`,`phone`,`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_passenger_documents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `passenger_id` BIGINT UNSIGNED NOT NULL,
  `document_type` VARCHAR(40) NOT NULL,
  `document_number` VARCHAR(100) NOT NULL,
  `issuing_country_code` VARCHAR(2) NULL,
  `issued_date` DATE NULL,
  `expiry_date` DATE NULL,
  `place_of_issue` VARCHAR(150) NULL,
  `file_path` VARCHAR(255) NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `verified_by` BIGINT UNSIGNED NULL,
  `verified_at` TIMESTAMP NULL,
  `notes` TEXT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `atn_passenger_doc_unique` (`business_id`,`document_type`,`document_number`),
  KEY `atn_passenger_doc_expiry_idx` (`business_id`,`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_passenger_visas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `passenger_id` BIGINT UNSIGNED NOT NULL,
  `country_code` VARCHAR(2) NOT NULL,
  `visa_type` VARCHAR(80) NOT NULL,
  `visa_number` VARCHAR(100) NULL,
  `issued_date` DATE NULL,
  `expiry_date` DATE NULL,
  `entries_allowed` VARCHAR(40) NULL,
  `status` VARCHAR(40) NULL,
  `file_path` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `atn_passenger_visa_expiry_idx` (`business_id`,`expiry_date`),
  KEY `atn_passenger_visa_country_idx` (`business_id`,`country_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_passenger_loyalty_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `passenger_id` BIGINT UNSIGNED NOT NULL,
  `airline_id` BIGINT UNSIGNED NULL,
  `program_name` VARCHAR(120) NOT NULL,
  `membership_number` VARCHAR(100) NOT NULL,
  `tier_name` VARCHAR(80) NULL,
  `points_balance` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `expiry_date` DATE NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `atn_loyalty_member_unique` (`business_id`,`program_name`,`membership_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_passenger_emergency_contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `passenger_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `relationship` VARCHAR(80) NULL,
  `phone` VARCHAR(40) NOT NULL,
  `alternate_phone` VARCHAR(40) NULL,
  `email` VARCHAR(150) NULL,
  `country_code` VARCHAR(2) NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `atn_emergency_passenger_idx` (`business_id`,`passenger_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `atn_corporate_contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` BIGINT UNSIGNED NOT NULL,
  `business_location_id` BIGINT UNSIGNED NULL,
  `store_id` BIGINT UNSIGNED NULL,
  `corporate_customer_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `designation` VARCHAR(100) NULL,
  `department` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  `phone` VARCHAR(40) NULL,
  `alternate_phone` VARCHAR(40) NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `atn_corporate_contact_idx` (`business_id`,`corporate_customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
