-- DISNEW_014 Smart Sales Distribution Large Parcel
-- Run inside every tenant database. No database name is specified intentionally.

CREATE TABLE IF NOT EXISTS `disnew_credit_controls` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `credit_limit` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `credit_days` INT NOT NULL DEFAULT 0,
  `block_on_over_limit` TINYINT(1) NOT NULL DEFAULT 1,
  `block_on_overdue` TINYINT(1) NOT NULL DEFAULT 1,
  `warning_percentage` DECIMAL(8,3) NOT NULL DEFAULT 80.000,
  `temporary_limit` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `temporary_limit_expiry` DATE NULL,
  `status` ENUM('active','inactive','blocked') NOT NULL DEFAULT 'active',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `disnew_credit_customer_unique` (`business_id`,`customer_id`),
  KEY `disnew_credit_business_status_idx` (`business_id`,`business_location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_price_lists` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `price_list_code` VARCHAR(60) NULL,
  `name` VARCHAR(150) NOT NULL,
  `scope_type` ENUM('general','customer','route','territory','sales_rep') NOT NULL DEFAULT 'general',
  `customer_id` BIGINT UNSIGNED NULL,
  `route_id` BIGINT UNSIGNED NULL,
  `territory_id` BIGINT UNSIGNED NULL,
  `sales_rep_id` BIGINT UNSIGNED NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `priority` INT NOT NULL DEFAULT 0,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_price_scope_idx` (`business_id`,`scope_type`,`status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_price_list_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `price_list_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `variation_id` BIGINT UNSIGNED NULL,
  `unit_id` BIGINT UNSIGNED NULL,
  `unit_price` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `minimum_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `maximum_qty` DECIMAL(22,4) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_price_lines_product_idx` (`business_id`,`product_id`,`variation_id`),
  KEY `disnew_price_lines_list_idx` (`price_list_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_discount_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `rule_code` VARCHAR(60) NULL,
  `name` VARCHAR(150) NOT NULL,
  `scope_type` ENUM('general','customer','route','territory','product','category','sales_rep') NOT NULL DEFAULT 'general',
  `discount_type` ENUM('percentage','fixed') NOT NULL DEFAULT 'percentage',
  `discount_value` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `minimum_order_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `minimum_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `priority` INT NOT NULL DEFAULT 0,
  `requires_approval` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `condition_json` JSON NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_discount_rules_idx` (`business_id`,`scope_type`,`status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_promotions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `promotion_code` VARCHAR(60) NULL,
  `name` VARCHAR(150) NOT NULL,
  `promotion_type` ENUM('bundle','seasonal','free_issue','discount','campaign') NOT NULL DEFAULT 'discount',
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `budget_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `used_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` ENUM('draft','active','paused','closed') NOT NULL DEFAULT 'draft',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_promotions_business_idx` (`business_id`,`business_location_id`,`status`,`valid_from`,`valid_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_promotion_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `promotion_id` BIGINT UNSIGNED NOT NULL,
  `buy_product_id` BIGINT UNSIGNED NULL,
  `buy_variation_id` BIGINT UNSIGNED NULL,
  `buy_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `free_product_id` BIGINT UNSIGNED NULL,
  `free_variation_id` BIGINT UNSIGNED NULL,
  `free_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_type` ENUM('none','percentage','fixed') NOT NULL DEFAULT 'none',
  `discount_value` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_promotion_lines_idx` (`business_id`,`promotion_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_free_issue_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `name` VARCHAR(150) NOT NULL,
  `buy_product_id` BIGINT UNSIGNED NOT NULL,
  `buy_variation_id` BIGINT UNSIGNED NULL,
  `buy_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `free_product_id` BIGINT UNSIGNED NOT NULL,
  `free_variation_id` BIGINT UNSIGNED NULL,
  `free_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_free_issue_idx` (`business_id`,`buy_product_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_sales_targets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `target_type` ENUM('sales_rep','territory','route','customer','product') NOT NULL DEFAULT 'sales_rep',
  `sales_rep_id` BIGINT UNSIGNED NULL,
  `territory_id` BIGINT UNSIGNED NULL,
  `route_id` BIGINT UNSIGNED NULL,
  `customer_id` BIGINT UNSIGNED NULL,
  `product_id` BIGINT UNSIGNED NULL,
  `period_type` ENUM('daily','weekly','monthly','quarterly','yearly') NOT NULL DEFAULT 'monthly',
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `target_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `target_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `achieved_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `achieved_qty` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` ENUM('active','closed','cancelled') NOT NULL DEFAULT 'active',
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_targets_idx` (`business_id`,`target_type`,`period_start`,`period_end`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_sales_commissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `sales_rep_id` BIGINT UNSIGNED NULL,
  `customer_id` BIGINT UNSIGNED NULL,
  `sales_order_id` BIGINT UNSIGNED NULL,
  `sales_invoice_id` BIGINT UNSIGNED NULL,
  `commission_date` DATE NOT NULL,
  `base_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `commission_type` ENUM('percentage','fixed') NOT NULL DEFAULT 'percentage',
  `commission_value` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `commission_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `status` ENUM('pending','approved','paid','cancelled') NOT NULL DEFAULT 'pending',
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `approved_by` BIGINT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_commissions_idx` (`business_id`,`sales_rep_id`,`commission_date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `disnew_sales_kpi_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT UNSIGNED NOT NULL,
  `business_location_id` INT UNSIGNED NULL,
  `snapshot_date` DATE NOT NULL,
  `sales_rep_id` BIGINT UNSIGNED NULL,
  `territory_id` BIGINT UNSIGNED NULL,
  `route_id` BIGINT UNSIGNED NULL,
  `orders_count` INT NOT NULL DEFAULT 0,
  `invoices_count` INT NOT NULL DEFAULT 0,
  `gross_sales` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `discount_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `net_sales` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `collections_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `returns_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `target_amount` DECIMAL(22,4) NOT NULL DEFAULT 0.0000,
  `achievement_percentage` DECIMAL(8,3) NOT NULL DEFAULT 0.000,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `disnew_kpi_snapshot_idx` (`business_id`,`snapshot_date`,`sales_rep_id`,`territory_id`,`route_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
